// Generated by pooling_settings_flt.py using PyTorch version 2.10.0+cu128.
const float16_t avgpooling_f16_1_output_ref[3] = {(float16_t)0.245605469f,
                                                  (float16_t)-0.167724609f,
                                                  (float16_t)-0.413818359f};
