// Generated by conv_settings_flt.py using PyTorch version 2.10.0+cu128.
const float16_t conv_match_1xn_6_generic_f16_input_data[4] = {(float16_t)-0.189208984f,
                                                              (float16_t)-0.953125f,
                                                              (float16_t)0.709960938f,
                                                              (float16_t)0.130249023f};
