// Generated by pooling_settings_flt.py using PyTorch version 2.10.0+cu128.
const float16_t maxpooling_f16_1_output_ref[3] = {(float16_t)5.80859375f,
                                                  (float16_t)5.87890625f,
                                                  (float16_t)5.8046875f};
