// Generated by pooling_settings_flt.py using PyTorch version 2.10.0+cu128.
const float16_t avgpooling_match_4_f16_output_ref[42] = {
    (float16_t)1.0546875f,   (float16_t)1.32910156f,   (float16_t)2.19921875f,   (float16_t)1.36425781f,
    (float16_t)-1.98242188f, (float16_t)0.414794922f,  (float16_t)-0.760253906f, (float16_t)-0.26171875f,
    (float16_t)2.0546875f,   (float16_t)1.06152344f,   (float16_t)-0.61328125f,  (float16_t)4.03515625f,
    (float16_t)1.39453125f,  (float16_t)1.30371094f,   (float16_t)-2.77929688f,  (float16_t)0.794433594f,
    (float16_t)-3.1171875f,  (float16_t)0.576660156f,  (float16_t)-2.98632812f,  (float16_t)-2.17773438f,
    (float16_t)-1.62304688f, (float16_t)0.463867188f,  (float16_t)-3.36914062f,  (float16_t)1.77441406f,
    (float16_t)4.29296875f,  (float16_t)0.192260742f,  (float16_t)3.44335938f,   (float16_t)0.279785156f,
    (float16_t)0.354492188f, (float16_t)-0.597167969f, (float16_t)2.44726562f,   (float16_t)-2.33984375f,
    (float16_t)0.349365234f, (float16_t)2.85351562f,   (float16_t)-0.638671875f, (float16_t)-0.333496094f,
    (float16_t)-1.76757812f, (float16_t)-1.31835938f,  (float16_t)2.21289062f,   (float16_t)-1.67871094f,
    (float16_t)3.85546875f,  (float16_t)3.89453125f};
