// Generated by test_settings.py using tensorflow version 2.15.0-dev20231004 (Keras version 2.15.0.dev2023092207).
// Interpreter from tflite_micro version 0.dev20231002060915-gec477d5c and revision None.
#pragma once
#include <stdint.h>

const int32_t fully_connected_int4_3_biases[9] = {-86, 25, 2, -74, -70, -105, -56, -55, -12};
