// Generated by test_settings.py using tensorflow version 2.15.0-dev20231004 (Keras version 2.15.0.dev2023092207).
// Interpreter from tflite_micro version 0.dev20231002060915-gec477d5c and revision None.
#pragma once
#include <stdint.h>

const int8_t fully_connected_int4_3_weights[27] = {73, 35,  161, 50,  66, 208, 196, 81, 251, 237, 133, 99, 229, 214,
                                                   96, 251, 106, 232, 24, 28,  31,  28, 249, 97,  228, 9,  198};
