// Generated by conv_settings_flt.py using PyTorch version 2.10.0+cu128.
const float16_t conv_match_1xn_4_f16_biases_data[4] = {(float16_t)-0.257568359f,
                                                       (float16_t)0.485839844f,
                                                       (float16_t)0.165771484f,
                                                       (float16_t)0.314697266f};
