// Generated by conv_settings_flt.py using PyTorch version 2.10.0+cu128.
const float16_t conv_match_1xn_4_f16_input_data[64] = {
    (float16_t)0.314697266f,   (float16_t)-0.870117188f, (float16_t)0.801269531f,  (float16_t)0.0375976562f,
    (float16_t)-0.0430297852f, (float16_t)-0.665527344f, (float16_t)-0.180664062f, (float16_t)-0.467285156f,
    (float16_t)-0.666992188f,  (float16_t)0.349609375f,  (float16_t)-0.393310547f, (float16_t)-0.310791016f,
    (float16_t)-0.755859375f,  (float16_t)-0.940917969f, (float16_t)0.970214844f,  (float16_t)0.646972656f,
    (float16_t)-0.979980469f,  (float16_t)0.575683594f,  (float16_t)-0.871582031f, (float16_t)-0.693847656f,
    (float16_t)-0.0450744629f, (float16_t)-0.955078125f, (float16_t)0.259765625f,  (float16_t)0.338378906f,
    (float16_t)0.750976562f,   (float16_t)0.252685547f,  (float16_t)0.343261719f,  (float16_t)-0.898925781f,
    (float16_t)0.804199219f,   (float16_t)-0.364013672f, (float16_t)0.139892578f,  (float16_t)-0.7109375f,
    (float16_t)0.142700195f,   (float16_t)-0.10546875f,  (float16_t)-0.639160156f, (float16_t)-0.782714844f,
    (float16_t)-0.765136719f,  (float16_t)-0.764160156f, (float16_t)-0.209960938f, (float16_t)-0.135864258f,
    (float16_t)-0.225341797f,  (float16_t)-0.866210938f, (float16_t)0.640625f,     (float16_t)0.480712891f,
    (float16_t)0.480712891f,   (float16_t)0.525878906f,  (float16_t)-0.121948242f, (float16_t)-0.9375f,
    (float16_t)-0.437011719f,  (float16_t)-0.49609375f,  (float16_t)0.846191406f,  (float16_t)0.443359375f,
    (float16_t)-0.741210938f,  (float16_t)-0.234741211f, (float16_t)-0.901855469f, (float16_t)0.373779297f,
    (float16_t)-0.949707031f,  (float16_t)-0.577636719f, (float16_t)-0.208251953f, (float16_t)0.102783203f,
    (float16_t)-0.724121094f,  (float16_t)0.321044922f,  (float16_t)0.493652344f,  (float16_t)-0.037322998f};
