// Generated by conv_settings_flt.py using PyTorch version 2.10.0+cu128.
const float16_t conv_match_1xn_4_f16_output_ref_data[28] = {
    (float16_t)-1.02246094f,   (float16_t)-0.752441406f,  (float16_t)0.0682983398f, (float16_t)0.339355469f,
    (float16_t)0.134033203f,   (float16_t)0.469482422f,   (float16_t)-0.613769531f, (float16_t)2.09570312f,
    (float16_t)-0.0251464844f, (float16_t)1.65527344f,    (float16_t)1.12695312f,   (float16_t)-0.392822266f,
    (float16_t)-0.538085938f,  (float16_t)0.263183594f,   (float16_t)2.37304688f,   (float16_t)1.0546875f,
    (float16_t)-0.253173828f,  (float16_t)0.897460938f,   (float16_t)-0.338134766f, (float16_t)0.983398438f,
    (float16_t)-0.719726562f,  (float16_t)-0.0426940918f, (float16_t)-0.3984375f,   (float16_t)-0.985351562f,
    (float16_t)0.305175781f,   (float16_t)-0.384033203f,  (float16_t)-1.76660156f,  (float16_t)0.270263672f};
