// Generated by conv_settings_flt.py using PyTorch version 2.10.0+cu128.
const float16_t conv_match_1xn_4_f16_weights_data[48] = {
    (float16_t)-0.717773438f, (float16_t)0.682617188f,  (float16_t)0.404052734f,   (float16_t)0.181152344f,
    (float16_t)-0.214233398f, (float16_t)-0.208129883f, (float16_t)0.189208984f,   (float16_t)-0.0822143555f,
    (float16_t)0.447998047f,  (float16_t)-0.64453125f,  (float16_t)-0.722167969f,  (float16_t)0.602539062f,
    (float16_t)-0.101745605f, (float16_t)0.609863281f,  (float16_t)-0.735351562f,  (float16_t)-0.158203125f,
    (float16_t)-0.705078125f, (float16_t)0.72265625f,   (float16_t)-0.284667969f,  (float16_t)-0.552246094f,
    (float16_t)0.0755615234f, (float16_t)0.154418945f,  (float16_t)0.423339844f,   (float16_t)-0.719238281f,
    (float16_t)0.602050781f,  (float16_t)0.334472656f,  (float16_t)-0.0123977661f, (float16_t)-0.264892578f,
    (float16_t)0.514160156f,  (float16_t)-0.119567871f, (float16_t)0.141723633f,   (float16_t)-0.446533203f,
    (float16_t)0.657226562f,  (float16_t)0.0280456543f, (float16_t)0.0500793457f,  (float16_t)-0.745117188f,
    (float16_t)0.692871094f,  (float16_t)-0.12902832f,  (float16_t)-0.373779297f,  (float16_t)-0.736328125f,
    (float16_t)-0.5078125f,   (float16_t)0.501953125f,  (float16_t)0.575683594f,   (float16_t)0.429931641f,
    (float16_t)-0.646484375f, (float16_t)-0.348144531f, (float16_t)-0.681640625f,  (float16_t)-0.197998047f};
