// Generated by lstm_settings_flt.py using PyTorch version 2.10.0+cu128.
const float32_t lstm_match_2_f32_cell_bias[7] =
    {-0.226487935f, -0.140098155f, -0.121486284f, 0.0437849127f, 0.320686311f, 0.228260562f, -0.00593394041f};
