// Generated by lstm_settings_flt.py using PyTorch version 2.10.0+cu128.
const float32_t lstm_match_2_f32_forget_bias[7] =
    {-0.0367999412f, 0.239391655f, 0.241278708f, -0.230712608f, 0.0918967426f, 0.322369218f, 0.170202538f};
