// Generated by lstm_settings_flt.py using PyTorch version 2.10.0+cu128.
const float32_t lstm_match_2_f32_input_bias[7] =
    {0.140675694f, 0.195227027f, -0.0599374175f, -0.0801632181f, -0.104561523f, 0.258368373f, 0.293761671f};
