// Generated by lstm_settings_flt.py using PyTorch version 2.10.0+cu128.
const float32_t lstm_match_2_f32_output_bias[7] =
    {0.239603385f, -0.204275876f, 0.0466675311f, -0.393553823f, 0.173193783f, -0.213457257f, -0.172586948f};
