// Generated by depthwise_conv_settings_flt.py using PyTorch version 2.10.0+cu128.
const float32_t depthwise_match_dilation_f32_weights_data[9] = {0.314733684f,
                                                                0.372551739f,
                                                                -0.673268497f,
                                                                -0.624940336f,
                                                                -0.160970256f,
                                                                0.205443457f,
                                                                0.138224602f,
                                                                0.418738872f,
                                                                -0.558079779f};
