// Generated by fully_connected_settings_flt.py using PyTorch version 2.10.0+cu128.
const float16_t fully_connected_match_mve_0_f16_biases_data[9] = {(float16_t)0.411621094f,
                                                                  (float16_t)-0.288085938f,
                                                                  (float16_t)0.451171875f,
                                                                  (float16_t)-0.288574219f,
                                                                  (float16_t)0.328369141f,
                                                                  (float16_t)0.669921875f,
                                                                  (float16_t)-0.458007812f,
                                                                  (float16_t)-0.400146484f,
                                                                  (float16_t)-0.0784301758f};
