// Generated by fully_connected_settings_flt.py using PyTorch version 2.10.0+cu128.
const float16_t fully_connected_match_mve_0_f16_output_ref_data[9] = {(float16_t)-2.4140625f,
                                                                      (float16_t)-3.36132812f,
                                                                      (float16_t)4.11328125f,
                                                                      (float16_t)-5.00390625f,
                                                                      (float16_t)0.8125f,
                                                                      (float16_t)4.7890625f,
                                                                      (float16_t)-2.32421875f,
                                                                      (float16_t)-5.01171875f,
                                                                      (float16_t)6.89453125f};
