// Generated by generate_test_data.py using tensorflow version 2.16.1 (Keras version 2.16.0).
// Interpreter from tensorflow version 2.16.1 and revision v2.16.1-0-g5bc9d26649c.
#pragma once
#include <stdint.h>

const int64_t int16xint8_spill_bias[9] =
    {-884417, 3945708, 3406942, 2133137, 3248303, 3305055, -1536011, -3483503, -3626630};

const int64_t *const int16xint8_spill_biases = int16xint8_spill_bias;
