// Generated by test_settings.py using tensorflow version 2.14.0 (Keras version 2.14.0).
// Interpreter from tensorflow version 2.14.0 and revision v2.14.0-rc1-21-g4dacf3f368e.
#pragma once
#include <stdint.h>

const int32_t int16xint8_spill_output_mult[9] =
    {1100398998, 1100624659, 1100035049, 1099990516, 1100661379, 1100714636, 1100682734, 1100519706, 1100868940};
