// Generated by generate_test_data.py using tensorflow version 2.16.1 (Keras version 2.16.0).
// Interpreter from tensorflow version 2.16.1 and revision v2.16.1-0-g5bc9d26649c.
#pragma once
#include <stdint.h>

const int32_t int16xint8_spill_output_multiplier[9] =
    {1922224780, 1923367059, 1923068806, 1922819466, 1922873839, 1922641561, 1921336846, 1922926391, 1922270735};

const int32_t *const int16xint8_spill_output_mult = int16xint8_spill_output_multiplier;
