// Generated by depthwise_conv_settings_flt.py using PyTorch version 2.10.0+cu128.
const float16_t depthwise_k3_1d_opt_batch2_f16_weights_data[24] = {
    (float16_t)-0.390380859f, (float16_t)0.107971191f,  (float16_t)0.658691406f,  (float16_t)0.078125f,
    (float16_t)0.256835938f,  (float16_t)-0.680175781f, (float16_t)-0.176391602f, (float16_t)0.533203125f,
    (float16_t)-0.59375f,     (float16_t)0.204956055f,  (float16_t)-0.571289062f, (float16_t)-0.153808594f,
    (float16_t)-0.189575195f, (float16_t)-0.586914062f, (float16_t)0.0103988647f, (float16_t)-0.486328125f,
    (float16_t)-0.575195312f, (float16_t)0.587890625f,  (float16_t)0.12109375f,   (float16_t)0.197631836f,
    (float16_t)0.547851562f,  (float16_t)0.679199219f,  (float16_t)-0.12322998f,  (float16_t)0.225463867f};
