// Generated by RefactoredTestGen/test.py using flatc version 23.5.26
// Interpreter from tflite_micro runtime version 0.dev20240224054047-gcfa4c91.
#pragma once
#include <stdint.h>

const int8_t lstm_2_s16_cell_gate_input_weights[42] = {
    -62,  75, 47,   104, 59, 76,  48,  52,  13, 68,  -69, 93, 8,    8,   -95,  26,  -76, -49, 108, 81,  -92,
    -104, 80, -118, -87, 25, 112, -56, -14, 61, -10, -26, 43, -118, -86, -108, -27, 26,  -40, 77,  -63, -125};