// Generated by RefactoredTestGen/test.py using flatc version 23.5.26
// Interpreter from tflite_micro runtime version 0.dev20240224054047-gcfa4c91.
#pragma once
#include <stdint.h>

const int8_t lstm_2_s16_cell_gate_hidden_weights[49] = {
    103, -81,  -66, 119, 103, 58, -7,  -56, -41, -99, 2,    12,   -23, 77,  -79, -4,  56,
    113, -2,   -52, -77, 8,   -6, 68,  77,  125, 106, -66,  88,   27,  117, 12,  -44, 41,
    -6,  -119, 52,  -82, -7,  -5, -57, 71,  7,   -62, -115, -108, -1,  119, 94};