// Generated by RefactoredTestGen/test.py using flatc version 23.5.26
// Interpreter from tflite_micro runtime version 0.dev20240224054047-gcfa4c91.
#pragma once
#include <stdint.h>

const int64_t lstm_2_s16_cell_gate_bias[7] = {19513, 13891, 21356, 10099, 17079, 31695, 8446};