// Generated by RefactoredTestGen/test.py using flatc version 23.5.26
// Interpreter from tflite_micro runtime version 0.dev20240224054047-gcfa4c91.
#pragma once
#define lstm_2_s16_time_major false
#define lstm_2_s16_batch_size 1
#define lstm_2_s16_time_steps 9
#define lstm_2_s16_input_size 6
#define lstm_2_s16_hidden_size 7
#define lstm_2_s16_cell_scale_power -9
#define lstm_2_s16_output_zero_point 0
#define lstm_2_s16_input_zero_point 0
#define lstm_2_s16_cell_clip 32767
#define lstm_2_s16_forget_to_cell_multiplier 1073741824
#define lstm_2_s16_forget_to_cell_shift -14
#define lstm_2_s16_input_to_cell_multiplier 1316479598
#define lstm_2_s16_input_to_cell_shift -20
#define lstm_2_s16_output_multiplier 1956298507
#define lstm_2_s16_output_shift -17
#define lstm_2_s16_output_gate_hidden_multiplier 1549742675
#define lstm_2_s16_output_gate_hidden_shift -11
#define lstm_2_s16_cell_gate_hidden_multiplier 1564226251
#define lstm_2_s16_cell_gate_hidden_shift -12
#define lstm_2_s16_forget_gate_hidden_multiplier 1670439145
#define lstm_2_s16_forget_gate_hidden_shift -12
#define lstm_2_s16_input_gate_hidden_multiplier 1164720936
#define lstm_2_s16_input_gate_hidden_shift -10
#define lstm_2_s16_output_gate_input_multiplier 1924775430
#define lstm_2_s16_output_gate_input_shift -10
#define lstm_2_s16_cell_gate_input_multiplier 1582330722
#define lstm_2_s16_cell_gate_input_shift -11
#define lstm_2_s16_forget_gate_input_multiplier 1281215547
#define lstm_2_s16_forget_gate_input_shift -9
#define lstm_2_s16_input_gate_input_multiplier 1578394576
#define lstm_2_s16_input_gate_input_shift -9
