// Generated by RefactoredTestGen/test.py using flatc version 23.5.26
// Interpreter from tflite_micro runtime version 0.dev20240224054047-gcfa4c91.
#pragma once
#include <stdint.h>

const int8_t lstm_2_s16_forget_gate_hidden_weights[49] = {
    118, 14,  8,  -95, -3,  -65, 2,   -67,  41,   104, 18, 51,   21,  -4,   -86, 31,  56,
    -60, -75, 74, 73,  -12, 115, 1,   -109, -119, 96,  15, -31,  -37, 25,   0,   -22, -24,
    95,  30,  -6, 23,  -25, -59, 105, -84,  102,  -16, 19, -118, 42,  -124, -38};