// Generated by RefactoredTestGen/test.py using flatc version 23.5.26
// Interpreter from tflite_micro runtime version 0.dev20240224054047-gcfa4c91.
#pragma once
#include <stdint.h>

const int8_t lstm_2_s16_forget_gate_input_weights[42] = {
    -37, -21, 118, -39, 90,  -97,  -99, 73, 59, -12, 1,   -74, -39,  -125, -60, 101, 68,  -22, -65, 47, 55,
    114, 86,  48,  57,  -72, -103, 103, -3, 78, 123, -51, 78,  -100, -100, -54, -25, -40, -21, 33,  60, -107};