// Generated by RefactoredTestGen/test.py using flatc version 23.5.26
// Interpreter from tflite_micro runtime version 0.dev20240224054047-gcfa4c91.
#pragma once
#include <stdint.h>

const int64_t lstm_2_s16_forget_gate_bias[7] = {20964, 16982, 16930, 22508, 31250, 30498, 16337};