// Generated by RefactoredTestGen/test.py using flatc version 23.5.26
// Interpreter from tflite_micro runtime version 0.dev20240224054047-gcfa4c91.
#pragma once
#include <stdint.h>

const int64_t lstm_2_s16_input_gate_bias[7] = {28793, 9909, 4344, 1117, 3627, 30848, 32766};