// Generated by RefactoredTestGen/test.py using flatc version 23.5.26
// Interpreter from tflite_micro runtime version 0.dev20240224054047-gcfa4c91.
#pragma once
#include <stdint.h>

const int8_t lstm_2_s16_input_gate_hidden_weights[49] = {
    3,   53, -35, -6,  -43, -23, -98, 16,  -114, -96, 15,   40,  80,  -82,  109, -22, 13,
    117, 90, 87,  -52, 58,  -46, 106, 34,  -90,  -63, -121, 106, 122, -101, 55,  7,   51,
    -55, 7,  124, 53,  97,  -96, -9,  -61, -25,  123, -69,  -1,  -55, 69,   -104};