// Generated by RefactoredTestGen/test.py using flatc version 23.5.26
// Interpreter from tflite_micro runtime version 0.dev20240224054047-gcfa4c91.
#pragma once
#include <stdint.h>

const int64_t lstm_2_s16_output_gate_bias[7] = {5138, 5363, 14184, 3723, 23687, 28588, 26805};