// Generated by RefactoredTestGen/test.py using flatc version 23.5.26
// Interpreter from tflite_micro runtime version 0.dev20240224054047-gcfa4c91.
#pragma once
#include <stdint.h>

const int8_t lstm_2_s16_output_gate_input_weights[42] = {
    -83, -37, -5, -58, 37,  -85,  37,  121, 112, -12, -104, -55, 116, -43, 33,  -108, -15, 79,   8,  -34, -64,
    -12, -63, 20, 90,  -89, -126, -49, -43, -16, 81,  65,   78,  -7,  -63, -92, -91,  8,   -108, -8, 37,  -67};