// Generated by RefactoredTestGen/test.py using flatc version 23.5.26
// Interpreter from tflite_micro runtime version 0.dev20240224054047-gcfa4c91.
#pragma once
#include <stdint.h>

const int8_t lstm_2_s16_output_gate_hidden_weights[49] = {
    29,   -8,  -81,  -77, -33,  23,  74,  -78, 68, -77, 22, -74,  95, 112,  13, 97, -124,
    -106, -3,  -122, 110, -124, -74, 47,  97,  11, 44,  8,  -100, 91, -103, 85, 68, 13,
    28,   119, -94,  -74, -39,  -15, -45, 60,  23, 37,  52, 70,   83, 111,  -9};