// Generated by fully_connected_settings_flt.py using PyTorch version 2.10.0+cu128.
const float32_t fully_connected_2out_batch2_f32_output_ref_data[4] = {0.838216066f,
                                                                      3.60571194f,
                                                                      -4.30911446f,
                                                                      0.432630181f};
