// Generated by pooling_settings_flt.py using PyTorch version 2.10.0+cu128.
const float16_t maxpooling_match_4_f16_input_tensor[40] = {
    (float16_t)2.79101562f,   (float16_t)2.57617188f,  (float16_t)-0.80078125f,  (float16_t)1.80957031f,
    (float16_t)-0.485839844f, (float16_t)3.44335938f,  (float16_t)2.9296875f,    (float16_t)5.91796875f,
    (float16_t)-0.15625f,     (float16_t)5.90234375f,  (float16_t)-1.76660156f,  (float16_t)4.578125f,
    (float16_t)-5.37109375f,  (float16_t)-2.83007812f, (float16_t)3.5f,          (float16_t)-4.79296875f,
    (float16_t)-2.35546875f,  (float16_t)-3.02539062f, (float16_t)3.94335938f,   (float16_t)2.76757812f,
    (float16_t)0.059173584f,  (float16_t)5.140625f,    (float16_t)4.58203125f,   (float16_t)-1.02636719f,
    (float16_t)2.30664062f,   (float16_t)-3.3671875f,  (float16_t)2.65234375f,   (float16_t)-5.54296875f,
    (float16_t)0.638671875f,  (float16_t)-3.08203125f, (float16_t)-1.6796875f,   (float16_t)4.55078125f,
    (float16_t)0.888183594f,  (float16_t)-5.8828125f,  (float16_t)-0.966796875f, (float16_t)5.25f,
    (float16_t)0.505859375f,  (float16_t)5.3828125f,   (float16_t)0.8984375f,    (float16_t)-2.484375f};
