// Generated by generate_test_data.py using tensorflow version 2.10.0 (Keras version 2.10.0).
// Interpreter from tflite_runtime version 2.11.0 and revision 0.6.0-134012-g31cfa135ac4.
#pragma once
#include <stdint.h>

const int8_t lstm_one_time_step_input_to_input_w[66] = {
    127, 42,  67,   72,  -34, 103, 27, 64,  -65, -23,  -122, -105, -49, -63, 71,  30,  -9,  -5,   103, -16, 42, -85,
    40,  37,  -115, -19, 45,  -49, 72, -26, 37,  -122, 99,   16,   31,  -94, -97, 92,  -76, -111, -6,  -82, -9, 97,
    8,   -23, 42,   108, 13,  13,  98, 50,  40,  -52,  -124, 7,    17,  117, 66,  -84, -88, -97,  -70, -4,  22, 54};
