// Generated by generate_test_data.py using tensorflow version 2.9.1 (Keras version 2.9.0).
// Interpreter from tflite_runtime version 2.11.0 and revision 0.6.0-135805-g25bfb32e73a.
#pragma once
#include <stdint.h>

const int32_t lstm_one_time_step_input_to_cell_eff_bias[4] = {-6182, 11893, -32509, -2381};
