// Generated by generate_test_data.py using tensorflow version 2.9.1 (Keras version 2.9.0).
// Interpreter from tflite_runtime version 2.11.0 and revision 0.6.0-135805-g25bfb32e73a.
#pragma once
#include <stdint.h>

const int8_t lstm_one_time_step_input_to_output_w[16] =
    {104, -24, -27, 85, 0, 108, -127, -65, 60, 37, -98, 64, 74, -39, 49, 116};
