// Generated by generate_test_data.py using tensorflow version 2.10.0 (Keras version 2.10.0).
// Interpreter from tflite_runtime version 2.11.0 and revision 0.6.0-134012-g31cfa135ac4.
#pragma once
#include <stdint.h>

const int8_t lstm_one_time_step_input[66] = {
    -75, -122, 117, 85,  -108, -63,  57,  -6,  -128, -27, 51,  -48, 35,   -103, 6,   -66, -35, 64,  82,  24, 29,  -39,
    -53, 47,   -74, 87,  124,  102,  -93, -8,  -128, 54,  45,  -26, -107, -21,  -60, -40, -45, 96,  -50, 75, 36,  -73,
    -93, -88,  -21, -32, -112, -113, 73,  -88, -101, 93,  -70, 6,   -36,  67,   86,  42,  66,  -70, 10,  8,  -63, -38};
