// Generated by generate_test_data.py using tensorflow version 2.10.0 (Keras version 2.10.0).
// Interpreter from tflite_runtime version 2.11.0 and revision 0.6.0-134012-g31cfa135ac4.
#pragma once
#include <stdint.h>

const int8_t lstm_one_time_step_input_to_forget_w[66] = {
    -10, -66,  -18, 87,  -5,  -12, 23,   -75, -72, -13, 37,  18,  30,  -28, -63,  -20, 13, 117, 55,   -103, -16,  -97,
    -40, -124, 47,  -78, -55, 104, -115, 86,  -65, 39,  -49, 56,  97,  -62, -1,   -11, 94, 67,  -104, -110, -108, -113,
    6,   -71,  85,  -84, 9,   48,  39,   -65, -37, 9,   -47, 123, -84, 127, -114, 90,  69, -4,  -48,  0,    -21,  72};
