// Generated by generate_test_data.py using tensorflow version 2.9.1 (Keras version 2.9.0).
// Interpreter from tflite_runtime version 2.11.0 and revision 0.6.0-135805-g25bfb32e73a.
#pragma once
#include <stdint.h>

const int8_t lstm_one_time_step_input_to_input_w[16] =
    {38, -119, -127, -99, 102, 72, -1, -16, 10, 70, 44, 21, 112, 0, -74, -112};
