// Generated by generate_test_data.py using tensorflow version 2.9.1 (Keras version 2.9.0).
// Interpreter from tflite_runtime version 2.11.0 and revision 0.6.0-135805-g25bfb32e73a.
#pragma once
#include <stdint.h>

const int8_t lstm_one_time_step_input_to_forget_w[16] =
    {42, 10, 127, -102, -24, 24, -82, -8, 96, 79, 102, 12, 11, 69, 5, -98};
