// Generated by generate_test_data.py using tensorflow version 2.9.1 (Keras version 2.9.0).
// Interpreter from tflite_runtime version 2.11.0 and revision 0.6.0-135805-g25bfb32e73a.
#pragma once
#include <stdint.h>

const int8_t lstm_one_time_step_input_to_cell_w[16] =
    {-121, 16, -68, 79, 127, 88, 9, 105, -63, -87, -29, 58, -86, 88, -126, -127};
