// Generated by generate_test_data.py using tensorflow version 2.10.0 (Keras version 2.10.0).
// Interpreter from tflite_runtime version 2.11.0 and revision 0.6.0-134012-g31cfa135ac4.
#pragma once
#include <stdint.h>

int8_t lstm_one_time_step_output_state[9] = {106, 106, 106, 106, 106, 106, 106, 106, 106};
