// Generated by generate_test_data.py using tensorflow version 2.9.1 (Keras version 2.9.0).
// Interpreter from tflite_runtime version 2.11.0 and revision 0.6.0-135805-g25bfb32e73a.
#pragma once
#include <stdint.h>

const int8_t lstm_one_time_step_recurrent_input_to_input_w[16] =
    {-107, 83, 21, 34, 95, 120, -16, 69, 127, -103, -123, 41, -69, -29, -116, -93};
