// Generated by generate_test_data.py using tensorflow version 2.10.0 (Keras version 2.10.0).
// Interpreter from tflite_runtime version 2.11.0 and revision 0.6.0-134012-g31cfa135ac4.
#pragma once
#include <stdint.h>

const int8_t lstm_one_time_step_recurrent_input_to_input_w[9] = {107, 126, 64, 47, 16, -71, 123, -127, -118};
