// Generated by generate_test_data.py using tensorflow version 2.10.0 (Keras version 2.10.0).
// Interpreter from tflite_runtime version 2.11.0 and revision 0.6.0-134012-g31cfa135ac4.
#pragma once
#include <stdint.h>

const int8_t lstm_one_time_step_recurrent_input_to_cell_w[9] = {-42, -127, -4, -88, -56, 107, -109, -112, 11};
