// Generated by generate_test_data.py using tensorflow version 2.9.1 (Keras version 2.9.0).
// Interpreter from tflite_runtime version 2.11.0 and revision 0.6.0-135805-g25bfb32e73a.
#pragma once
#include <stdint.h>

const int8_t lstm_one_time_step_recurrent_input_to_forget_w[16] =
    {-54, -45, 73, 27, 125, 120, -97, 121, 74, -29, -53, 127, 123, 19, 4, -51};
