// Generated by depthwise_conv_settings_flt.py using PyTorch version 2.10.0+cu128.
const float16_t depthwise_kernel_3x3_null_bias_f16_weights_data[45] = {
    (float16_t)0.331054688f,    (float16_t)0.159667969f,  (float16_t)0.167480469f,  (float16_t)-0.577148438f,
    (float16_t)0.133911133f,    (float16_t)0.251464844f,  (float16_t)0.453857422f,  (float16_t)-0.529785156f,
    (float16_t)-0.00604248047f, (float16_t)-0.274169922f, (float16_t)-0.195922852f, (float16_t)-0.0503845215f,
    (float16_t)0.279052734f,    (float16_t)-0.666992188f, (float16_t)-0.577636719f, (float16_t)-0.616699219f,
    (float16_t)0.13684082f,     (float16_t)0.200439453f,  (float16_t)-0.596679688f, (float16_t)0.322265625f,
    (float16_t)-0.709472656f,   (float16_t)0.442382812f,  (float16_t)0.0196685791f, (float16_t)-0.286132812f,
    (float16_t)0.610839844f,    (float16_t)0.0857543945f, (float16_t)0.360351562f,  (float16_t)-0.323242188f,
    (float16_t)0.747558594f,    (float16_t)-0.713867188f, (float16_t)-0.123901367f, (float16_t)0.418945312f,
    (float16_t)0.403564453f,    (float16_t)-0.24230957f,  (float16_t)0.627929688f,  (float16_t)0.223266602f,
    (float16_t)0.20690918f,     (float16_t)-0.736328125f, (float16_t)0.484863281f,  (float16_t)-0.056427002f,
    (float16_t)0.460205078f,    (float16_t)-0.503417969f, (float16_t)-0.108947754f, (float16_t)0.300292969f,
    (float16_t)0.331298828f};
