// Generated by conv_settings_flt.py using PyTorch version 2.10.0+cu128.
const float16_t conv_kernel_3x3_pad1_f16_biases_data[4] = {(float16_t)-0.21862793f,
                                                           (float16_t)0.135620117f,
                                                           (float16_t)-0.454589844f,
                                                           (float16_t)-0.183227539f};
