// Generated by conv_settings_flt.py using PyTorch version 2.10.0+cu128.
const float16_t conv_kernel_3x3_pad1_f16_input_data[36] = {
    (float16_t)0.51953125f,   (float16_t)0.337402344f,   (float16_t)-0.0354003906f, (float16_t)-0.638671875f,
    (float16_t)-0.56640625f,  (float16_t)-0.259033203f,  (float16_t)0.320800781f,   (float16_t)0.600097656f,
    (float16_t)-0.416259766f, (float16_t)0.754882812f,   (float16_t)0.216796875f,   (float16_t)0.199951172f,
    (float16_t)0.436767578f,  (float16_t)0.556152344f,   (float16_t)-0.797851562f,  (float16_t)-0.515136719f,
    (float16_t)0.346435547f,  (float16_t)-0.433837891f,  (float16_t)-0.551269531f,  (float16_t)-0.884277344f,
    (float16_t)0.341064453f,  (float16_t)-0.260498047f,  (float16_t)-0.619628906f,  (float16_t)0.493164062f,
    (float16_t)0.844238281f,  (float16_t)-0.0481262207f, (float16_t)0.760742188f,   (float16_t)-0.795410156f,
    (float16_t)0.126953125f,  (float16_t)0.335449219f,   (float16_t)-0.438964844f,  (float16_t)-0.495849609f,
    (float16_t)0.521972656f,  (float16_t)-0.681640625f,  (float16_t)-0.222412109f,  (float16_t)0.0363769531f};
