// Generated by fully_connected_settings_flt.py using PyTorch version 2.10.0+cu128.
const float32_t fully_connected_2out_tail21_f32_output_ref_data[4] = {5.00465202f, 1.03846145f, 10.0f, -2.68611073f};
