// Generated by generate_test_data.py using tensorflow version 2.10.0 (Keras version 2.10.0).
// Interpreter from tensorflow version 2.10.0 and revision v2.10.0-rc3-6-g359c3cdfc5f.
#pragma once
#include <stdint.h>

const int8_t fully_connected_mve_1_input[20] = {32, 47,   -94, -91, -88, 29,  -126, -6, 69,  -97,
                                                71, -127, -91, 19,  -74, -50, -49,  86, -42, 110};
