// Generated by generate_test_data.py using tensorflow version 2.10.0 (Keras version 2.10.0).
// Interpreter from tensorflow version 2.10.0 and revision v2.10.0-rc3-6-g359c3cdfc5f.
#pragma once
#include <stdint.h>

const int8_t depthwise_out_activation_weights[36] = {127, -84, 104, -112, -127, 77,  -112, -48,  66,   -123, 71, -86,
                                                     -25, 114, -5,  -13,  -1,   -6,  -87,  -109, 75,   -62,  -7, -64,
                                                     95,  -8,  -57, -17,  -95,  -71, -76,  95,   -127, 63,   71, 43};
