// Generated by conv_settings_flt.py using PyTorch version 2.10.0+cu128.
const float32_t conv_basic_f32_biases_data[10] = {-0.412936568f,
                                                  -0.366484016f,
                                                  0.0196087081f,
                                                  -0.110348053f,
                                                  0.052388642f,
                                                  0.111013778f,
                                                  0.187041506f,
                                                  -0.484796196f,
                                                  0.0728422925f,
                                                  0.320306778f};
