// Generated by add_mul_settings_flt.py using PyTorch version 2.10.0+cu128.
#define ADD_F16_DST_SIZE 128
#define ADD_F16_OUT_ACTIVATION_MIN (float16_t) - 10.0f
#define ADD_F16_OUT_ACTIVATION_MAX (float16_t)10.0f
#define ADD_F16_INPUT1_OFFSET 0
#define ADD_F16_INPUT2_OFFSET 0
#define ADD_F16_OUTPUT_MULT 0
#define ADD_F16_OUTPUT_SHIFT 0
#define ADD_F16_OUTPUT_OFFSET 0
#define ADD_F16_LEFT_SHIFT 0
#define ADD_F16_INPUT1_SHIFT 0
#define ADD_F16_INPUT2_SHIFT 0
#define ADD_F16_INPUT1_MULT 0
#define ADD_F16_INPUT2_MULT 0
