// Generated by conv_settings_flt.py using PyTorch version 2.10.0+cu128.
const float32_t conv_match_1xn_8_f32_biases_data[10] = {-0.39919129f,
                                                        -0.357987851f,
                                                        0.098305136f,
                                                        -0.309873283f,
                                                        0.216796428f,
                                                        0.220862448f,
                                                        -0.415014416f,
                                                        0.0901012793f,
                                                        -0.283576518f,
                                                        0.209595889f};
