// Generated by pooling_settings_flt.py using PyTorch version 2.10.0+cu128.
const float16_t maxpooling_f16_3_input_tensor[8] = {(float16_t)-0.858398438f,
                                                    (float16_t)8.9453125f,
                                                    (float16_t)6.63671875f,
                                                    (float16_t)-3.48242188f,
                                                    (float16_t)7.71875f,
                                                    (float16_t)8.9921875f,
                                                    (float16_t)6.1953125f,
                                                    (float16_t)9.3828125f};
