// Generated by fully_connected_settings_flt.py using PyTorch version 2.10.0+cu128.
const float16_t fully_connected_large_f16_biases_data[64] = {
    (float16_t)0.0359802246f,  (float16_t)-0.288330078f,  (float16_t)-0.0761108398f, (float16_t)0.0844726562f,
    (float16_t)0.353027344f,   (float16_t)0.299072266f,   (float16_t)-0.342529297f,  (float16_t)0.0765991211f,
    (float16_t)-0.135131836f,  (float16_t)0.0894165039f,  (float16_t)-0.250732422f,  (float16_t)-0.328857422f,
    (float16_t)-0.0844116211f, (float16_t)0.0754394531f,  (float16_t)0.295166016f,   (float16_t)0.317871094f,
    (float16_t)-0.0661010742f, (float16_t)0.0252227783f,  (float16_t)-0.341064453f,  (float16_t)-0.306396484f,
    (float16_t)-0.121154785f,  (float16_t)0.0190887451f,  (float16_t)0.395263672f,   (float16_t)-0.199462891f,
    (float16_t)-0.372558594f,  (float16_t)-0.363525391f,  (float16_t)-0.354492188f,  (float16_t)0.094909668f,
    (float16_t)0.299804688f,   (float16_t)0.227783203f,   (float16_t)-0.0345458984f, (float16_t)-0.30859375f,
    (float16_t)-0.185058594f,  (float16_t)0.285644531f,   (float16_t)0.284423828f,   (float16_t)0.297119141f,
    (float16_t)0.00994873047f, (float16_t)-0.0927734375f, (float16_t)0.333251953f,   (float16_t)-0.398925781f,
    (float16_t)-0.0784912109f, (float16_t)0.126708984f,   (float16_t)-0.292236328f,  (float16_t)-0.260009766f,
    (float16_t)0.134277344f,   (float16_t)-0.0977172852f, (float16_t)0.383544922f,   (float16_t)-0.269287109f,
    (float16_t)-0.181640625f,  (float16_t)0.155029297f,   (float16_t)0.281738281f,   (float16_t)-0.197753906f,
    (float16_t)-0.185302734f,  (float16_t)-0.141479492f,  (float16_t)0.276367188f,   (float16_t)-0.278320312f,
    (float16_t)0.318603516f,   (float16_t)0.0202941895f,  (float16_t)-0.172973633f,  (float16_t)-0.0606079102f,
    (float16_t)0.185058594f,   (float16_t)-0.147216797f,  (float16_t)0.176391602f,   (float16_t)0.00656890869f};
