// Generated by depthwise_conv_settings_flt.py using PyTorch version 2.10.0+cu128.
const float32_t depthwise_2x5_opt_batch2_f32_biases_data[8] =
    {0.411314994f, 0.431407601f, -0.470623553f, 0.139696479f, 0.136402279f, -0.0207028277f, 0.123203002f, 0.304578096f};
