// Generated by depthwise_conv_settings_flt.py using PyTorch version 2.10.0+cu128.
const float16_t depthwise_match_basic_f16_input_data[40] = {
    (float16_t)0.432617188f,   (float16_t)0.796386719f,   (float16_t)0.514648438f,  (float16_t)0.48046875f,
    (float16_t)-0.0737915039f, (float16_t)0.173706055f,   (float16_t)-0.350341797f, (float16_t)-0.548828125f,
    (float16_t)0.202392578f,   (float16_t)-0.775390625f,  (float16_t)0.756835938f,  (float16_t)0.0152664185f,
    (float16_t)0.858398438f,   (float16_t)0.272460938f,   (float16_t)-0.341308594f, (float16_t)0.788085938f,
    (float16_t)-0.138671875f,  (float16_t)0.328613281f,   (float16_t)-0.637207031f, (float16_t)-0.7890625f,
    (float16_t)0.119506836f,   (float16_t)0.219970703f,   (float16_t)-0.290039062f, (float16_t)-0.601074219f,
    (float16_t)-0.750976562f,  (float16_t)-0.765625f,     (float16_t)-0.790527344f, (float16_t)0.383789062f,
    (float16_t)-0.686035156f,  (float16_t)-0.0629882812f, (float16_t)0.69921875f,   (float16_t)-0.424316406f,
    (float16_t)-0.396728516f,  (float16_t)-0.849609375f,  (float16_t)-0.447265625f, (float16_t)0.884765625f,
    (float16_t)-0.981933594f,  (float16_t)0.208984375f,   (float16_t)-0.566894531f, (float16_t)0.705078125f};
