// Generated by depthwise_conv_settings_flt.py using PyTorch version 2.10.0+cu128.
const float16_t depthwise_match_basic_f16_output_ref_data[20] = {
    (float16_t)-0.87109375f,  (float16_t)-0.883789062f,  (float16_t)-0.79296875f,   (float16_t)-0.0607910156f,
    (float16_t)0.288085938f,  (float16_t)-0.743164062f,  (float16_t)-0.373291016f,  (float16_t)0.131713867f,
    (float16_t)-0.663574219f, (float16_t)-0.0963745117f, (float16_t)-0.751464844f,  (float16_t)0.472900391f,
    (float16_t)-0.64453125f,  (float16_t)-1.38769531f,   (float16_t)0.516113281f,   (float16_t)-0.0415039062f,
    (float16_t)-0.571777344f, (float16_t)0.478759766f,   (float16_t)-0.0931396484f, (float16_t)0.597167969f};
