// Generated by depthwise_conv_settings_flt.py using PyTorch version 2.10.0+cu128.
const float16_t depthwise_match_basic_f16_weights_data[8] = {(float16_t)0.126098633f,
                                                             (float16_t)-0.6328125f,
                                                             (float16_t)-0.17578125f,
                                                             (float16_t)-0.0864257812f,
                                                             (float16_t)0.53515625f,
                                                             (float16_t)-0.702148438f,
                                                             (float16_t)-0.414550781f,
                                                             (float16_t)0.553710938f};
