// Generated by conv_settings_flt.py using PyTorch version 2.10.0+cu128.
const float16_t conv_kernel_2x2_f16_biases_data[5] = {(float16_t)-0.0123672485f,
                                                      (float16_t)-0.122680664f,
                                                      (float16_t)-0.391601562f,
                                                      (float16_t)0.495605469f,
                                                      (float16_t)-0.170288086f};
