// Generated by test_settings.py using tensorflow version 2.14.0 (Keras version 2.14.0).
// Interpreter from tensorflow version 2.14.0 and revision v2.14.0-rc1-21-g4dacf3f368e.
#pragma once
#include <stdint.h>

const int8_t conv_3x3_dilation_5x5_input_int4_weights[18] =
    {53, -80, -10, 0, -96, -90, 84, -14, -53, 12, 86, -49, 83, -82, -119, 80, -92, -62};
