// Generated by generate_test_data.py using tensorflow version 2.10.0 (Keras version 2.10.0).
// Interpreter from tensorflow version 2.10.0 and revision upstream/v2.10.0-0-g359c3cdfc5f.
#pragma once
#include <stdint.h>

const int8_t conv_1_x_n_4_input[64] = {
    -46, 28,  -68,  -79, -113, 6,   17,  -89, 11,  53, 37,   -88, -40, 111,  -63, -114, -30, -29, 37,  104, 10,   -117,
    -19, -17, -121, 3,   -18,  100, 124, 5,   -86, 71, 31,   -84, -39, 99,   69,  -72,  9,   57,  88,  -93, -100, -40,
    45,  -26, 80,   -20, -91,  -28, 30,  75,  98,  56, -121, 50,  113, -107, -76, -74,  -26, -50, -17, 103};
