// Generated by generate_test_data.py using tensorflow version 2.10.0 (Keras version 2.10.0).
// Interpreter from tensorflow version 2.10.0 and revision upstream/v2.10.0-0-g359c3cdfc5f.
#pragma once
#include <stdint.h>

const int8_t conv_1_x_n_4_output_ref[32] = {-40, -39, 3,   -83, -88, 25,  -6,  -88, -71, 57,  -2,
                                            -85, -88, 83,  -42, -77, -58, 26,  -18, -83, -23, 15,
                                            -21, -83, -88, 62,  -31, -88, -38, 28,  -31, -88};
