// Generated by generate_test_data.py using tensorflow version 2.10.0 (Keras version 2.10.0).
// Interpreter from tensorflow version 2.10.0 and revision upstream/v2.10.0-0-g359c3cdfc5f.
#pragma once
#include <stdint.h>

const int8_t conv_1_x_n_4_weights[48] = {127,  -119, -88,  20, -50,  -58, 80, -72, -8,   58,  69,  -75,
                                         -68,  -24,  116,  85, 80,   117, -7, 112, -127, -47, -52, 66,
                                         83,   13,   127,  68, -101, 16,  63, 5,   30,   127, 15,  -16,
                                         -107, -16,  -127, 43, 38,   20,  65, -37, -41,  47,  -98, -5};
