// Generated by svdf_settings_flt.py using PyTorch version 2.10.0+cu128.
const float32_t svdf_match_1_f32_bias[12] = {-0.192471355f,
                                             0.158799261f,
                                             0.0522863083f,
                                             0.178179339f,
                                             -0.102457002f,
                                             0.102572344f,
                                             0.0237188339f,
                                             -0.0561561435f,
                                             0.0885431245f,
                                             -0.209797069f,
                                             0.155939877f,
                                             0.196953952f};
