// Generated by svdf_settings_flt.py using PyTorch version 2.10.0+cu128.
const float32_t svdf_match_1_f32_output_ref[12] = {0.0227753669f,
                                                   -0.522919655f,
                                                   -0.152971879f,
                                                   0.239851058f,
                                                   0.353781283f,
                                                   -0.0310471728f,
                                                   0.0693816245f,
                                                   0.15106152f,
                                                   0.218208849f,
                                                   0.124543831f,
                                                   0.555289388f,
                                                   -0.437801898f};
