// Generated by conv_settings_flt.py using PyTorch version 2.10.0+cu128.
const float16_t conv_match_1x1_basic_f16_biases_data[7] = {(float16_t)-0.102294922f,
                                                           (float16_t)-0.425292969f,
                                                           (float16_t)0.0492248535f,
                                                           (float16_t)-0.12310791f,
                                                           (float16_t)0.0642089844f,
                                                           (float16_t)-0.0920410156f,
                                                           (float16_t)-0.278320312f};
