// Generated by generate_test_data.py using tensorflow version 2.10.0 (Keras version 2.10.0).
// Interpreter from tensorflow version 2.10.0 and revision v2.10.0-rc3-6-g359c3cdfc5f.
#pragma once
#include <stdint.h>

const int8_t conv_1_x_n_3_input[24] = {48, -99, 102, -110, -50, 84,  15,   31, 97,   114, -21, -114,
                                       59, -45, -64, -119, 90,  -34, -112, -9, -108, 105, -22, -52};
