// Generated by generate_test_data.py using tensorflow version 2.11.0 (Keras version 2.11.0).
// Interpreter from tensorflow version 2.11.0 and revision v2.11.0-rc2-17-gd5b57ca93e5.
#include "biases_data.h"
#include "config_data.h"
#include "input_data.h"
#include "output_mult_data.h"
#include "output_ref_data.h"
#include "output_shift_data.h"
#include "weights_data.h"
