// Generated by generate_test_data.py using tensorflow version 2.10.0 (Keras version 2.10.0).
// Interpreter from tensorflow version 2.10.0 and revision v2.10.0-rc3-6-g359c3cdfc5f.
#pragma once
#include <stdint.h>

const int8_t conv_1_x_n_3_weights[33] = {85,  -76,  -73, -105, -2,  100, -127, 122, -94, 18,  -84,
                                         -38, -103, -66, -127, -99, -4,  30,   -45, 57,  -58, 29,
                                         113, -117, 18,  115,  -86, 127, 71,   71,  2,   -88, -118};
