// Generated by test_settings.py using tensorflow version 2.14.0 (Keras version 2.14.0).
// Interpreter from tensorflow version 2.14.0 and revision v2.14.0-rc1-21-g4dacf3f368e.
#pragma once
#define CONV_4_INT4_OUT_CH 3
#define CONV_4_INT4_IN_CH 3
#define CONV_4_INT4_INPUT_W 5
#define CONV_4_INT4_INPUT_H 5
#define CONV_4_INT4_DST_SIZE 36
#define CONV_4_INT4_INPUT_SIZE 75
#define CONV_4_INT4_OUT_ACTIVATION_MIN -109
#define CONV_4_INT4_OUT_ACTIVATION_MAX 127
#define CONV_4_INT4_INPUT_BATCHES 3
#define CONV_4_INT4_FILTER_X 2
#define CONV_4_INT4_FILTER_Y 3
#define CONV_4_INT4_STRIDE_X 2
#define CONV_4_INT4_STRIDE_Y 2
#define CONV_4_INT4_PAD_X 0
#define CONV_4_INT4_PAD_Y 0
#define CONV_4_INT4_OUTPUT_W 2
#define CONV_4_INT4_OUTPUT_H 2
#define CONV_4_INT4_INPUT_OFFSET 0
#define CONV_4_INT4_OUTPUT_OFFSET 0
#define CONV_4_INT4_DILATION_X 1
#define CONV_4_INT4_DILATION_Y 1
