// Generated by batch_norm_settings_flt.py using PyTorch version 2.10.0+cu128.
const float16_t bn_op_f16_bias[7] = {(float16_t)0.0762939453f,
                                     (float16_t)0.0415344238f,
                                     (float16_t)0.018157959f,
                                     (float16_t)0.0f,
                                     (float16_t)-0.015838623f,
                                     (float16_t)-0.0308685303f,
                                     (float16_t)-0.0459594727f};
