// Generated by svdf_settings_flt.py using PyTorch version 2.10.0+cu128.
const float32_t svdf_small_f32_bias[6] =
    {-0.158127844f, 0.194616497f, -0.00951028336f, 0.0701505169f, -0.0914256722f, 0.153938577f};
