// Generated by svdf_settings_flt.py using PyTorch version 2.10.0+cu128.
const float32_t svdf_small_f32_output_ref[6] =
    {0.306442022f, -0.180808574f, 0.246582955f, 0.879285574f, -1.05671418f, -0.104684159f};
