// Generated by svdf_settings_flt.py using PyTorch version 2.10.0+cu128.
#include "bias_data.h"
#include "config_data.h"
#include "initial_state_data.h"
#include "input_sequence_data.h"
#include "output_ref_data.h"
#include "weights_feature_data.h"
#include "weights_time_data.h"
