// Generated by fully_connected_settings_flt.py using PyTorch version 2.10.0+cu128.
const float16_t fully_connected_null_bias_f16_biases_data[5] = {(float16_t)0.0f,
                                                                (float16_t)0.0f,
                                                                (float16_t)0.0f,
                                                                (float16_t)0.0f,
                                                                (float16_t)0.0f};
