// Generated by fully_connected_settings_flt.py using PyTorch version 2.10.0+cu128.
const float16_t fully_connected_null_bias_f16_input_data[66] = {
    (float16_t)0.376464844f,   (float16_t)-1.90625f,     (float16_t)-0.494873047f, (float16_t)1.99609375f,
    (float16_t)-1.22851562f,   (float16_t)1.31542969f,   (float16_t)1.68261719f,   (float16_t)1.20996094f,
    (float16_t)0.750976562f,   (float16_t)-1.61230469f,  (float16_t)-0.267089844f, (float16_t)0.433349609f,
    (float16_t)-1.27246094f,   (float16_t)-1.90625f,     (float16_t)-0.112182617f, (float16_t)-0.355712891f,
    (float16_t)-0.738769531f,  (float16_t)-0.393798828f, (float16_t)0.556640625f,  (float16_t)0.588378906f,
    (float16_t)0.00319671631f, (float16_t)1.86230469f,   (float16_t)1.4765625f,    (float16_t)-1.97167969f,
    (float16_t)-0.848144531f,  (float16_t)0.897460938f,  (float16_t)-1.06054688f,  (float16_t)-0.770507812f,
    (float16_t)1.38964844f,    (float16_t)-0.732910156f, (float16_t)-1.87792969f,  (float16_t)-1.44238281f,
    (float16_t)-0.5078125f,    (float16_t)-1.45703125f,  (float16_t)-1.99316406f,  (float16_t)1.90039062f,
    (float16_t)-1.35449219f,   (float16_t)0.788574219f,  (float16_t)-0.489990234f, (float16_t)-1.58007812f,
    (float16_t)-1.27929688f,   (float16_t)-1.61914062f,  (float16_t)-1.81542969f,  (float16_t)0.854003906f,
    (float16_t)1.70019531f,    (float16_t)-1.87988281f,  (float16_t)1.43945312f,   (float16_t)1.34667969f,
    (float16_t)1.54003906f,    (float16_t)-0.653320312f, (float16_t)1.72265625f,   (float16_t)-1.74121094f,
    (float16_t)-1.76367188f,   (float16_t)1.29785156f,   (float16_t)-1.6015625f,   (float16_t)-0.9609375f,
    (float16_t)-0.701171875f,  (float16_t)-0.265625f,    (float16_t)1.71484375f,   (float16_t)0.119140625f,
    (float16_t)-0.513671875f,  (float16_t)-1.53710938f,  (float16_t)-0.273925781f, (float16_t)0.462158203f,
    (float16_t)1.75f,          (float16_t)-0.148681641f};
