// Generated by fully_connected_settings_flt.py using PyTorch version 2.10.0+cu128.
const float16_t fully_connected_null_bias_f16_output_ref_data[10] = {(float16_t)-1.46777344f,
                                                                     (float16_t)-4.890625f,
                                                                     (float16_t)-2.38867188f,
                                                                     (float16_t)-2.09570312f,
                                                                     (float16_t)-0.685546875f,
                                                                     (float16_t)0.813964844f,
                                                                     (float16_t)-2.16992188f,
                                                                     (float16_t)-3.77929688f,
                                                                     (float16_t)5.3359375f,
                                                                     (float16_t)3.82421875f};
