// Generated by conv_settings_flt.py using PyTorch version 2.10.0+cu128.
const float16_t conv_match_2x3_dilation_f16_weights_data[36] = {
    (float16_t)-0.360839844f, (float16_t)0.174072266f,  (float16_t)-0.269287109f,  (float16_t)-0.704101562f,
    (float16_t)0.400878906f,  (float16_t)-0.310302734f, (float16_t)0.200561523f,   (float16_t)0.608886719f,
    (float16_t)-0.134521484f, (float16_t)0.666503906f,  (float16_t)0.033416748f,   (float16_t)-0.109680176f,
    (float16_t)0.205932617f,  (float16_t)0.546875f,     (float16_t)-0.0606689453f, (float16_t)-0.719238281f,
    (float16_t)0.565917969f,  (float16_t)-0.202514648f, (float16_t)-0.456542969f,  (float16_t)0.694335938f,
    (float16_t)-0.61328125f,  (float16_t)-0.302734375f, (float16_t)-0.532714844f,  (float16_t)-0.07421875f,
    (float16_t)-0.038482666f, (float16_t)0.488525391f,  (float16_t)0.0210723877f,  (float16_t)-0.232177734f,
    (float16_t)-0.109619141f, (float16_t)-0.590820312f, (float16_t)-0.399169922f,  (float16_t)-0.525878906f,
    (float16_t)0.510253906f,  (float16_t)-0.439941406f, (float16_t)0.303710938f,   (float16_t)0.0485534668f};
