// Generated by test_settings.py using tensorflow version 2.11.0 (Keras version 2.11.0).
// Interpreter from tflite_runtime version 2.16.0 and revision 0.6.0-154906-gb2493fdf794.
#pragma once
#define AVGPOOLING_OUT_CH 20
#define AVGPOOLING_IN_CH 20
#define AVGPOOLING_INPUT_W 22
#define AVGPOOLING_INPUT_H 12
#define AVGPOOLING_DST_SIZE 360
#define AVGPOOLING_INPUT_SIZE 5280
#define AVGPOOLING_OUT_ACTIVATION_MIN -128
#define AVGPOOLING_OUT_ACTIVATION_MAX 127
#define AVGPOOLING_INPUT_BATCHES 2
#define AVGPOOLING_FILTER_X 6
#define AVGPOOLING_FILTER_Y 5
#define AVGPOOLING_STRIDE_X 9
#define AVGPOOLING_STRIDE_Y 5
#define AVGPOOLING_PAD_X 1
#define AVGPOOLING_PAD_Y 1
#define AVGPOOLING_OUTPUT_W 3
#define AVGPOOLING_OUTPUT_H 3
