// Generated by test_settings.py using tensorflow version 2.11.0 (Keras version 2.11.0).
// Interpreter from tflite_runtime version 2.16.0 and revision 0.6.0-154906-gb2493fdf794.
#pragma once
#include <stdint.h>

const int16_t maxpool_int16_1_output_ref[40] = {16109, 30000, 9275,  27498, 26033, 30000, 19786, 27498, 29496, 30000,
                                                29496, 27498, 29837, 30000, 29496, 30000, 29837, 28629, 29496, 30000,
                                                27394, 21735, 28157, 27060, 27394, 21735, 28157, 27060, 27394, 25411,
                                                28157, 27060, 26684, 25411, 26684, 25411, 26684, 25411, 26684, 25411};
