// Generated by lstm_settings_flt.py using PyTorch version 2.10.0+cu128.
const float32_t lstm_small_f32_cell_bias[8] = {0.230191752f,
                                               0.220425799f,
                                               -0.189792126f,
                                               0.0313377231f,
                                               0.0875475705f,
                                               0.327914596f,
                                               -0.280258566f,
                                               -0.327337712f};
