// Generated by lstm_settings_flt.py using PyTorch version 2.10.0+cu128.
const float32_t lstm_small_f32_forget_bias[8] = {0.237394065f,
                                                 -0.113466352f,
                                                 0.267885447f,
                                                 0.281396568f,
                                                 0.0399351493f,
                                                 0.280820549f,
                                                 0.225407809f,
                                                 -0.0104173273f};
