// Generated by lstm_settings_flt.py using PyTorch version 2.10.0+cu128.
const float32_t lstm_small_f32_input_bias[8] = {-0.41971314f,
                                                -0.0608372092f,
                                                0.190660983f,
                                                0.21183449f,
                                                0.0506335385f,
                                                0.0598877072f,
                                                0.346913338f,
                                                -0.143105775f};
