// Generated by lstm_settings_flt.py using PyTorch version 2.10.0+cu128.
const float32_t lstm_small_f32_output_bias[8] = {0.0584857911f,
                                                 0.139860123f,
                                                 0.288155317f,
                                                 -0.357741117f,
                                                 -0.0796674937f,
                                                 -0.108601421f,
                                                 -0.0784846917f,
                                                 -0.19089067f};
