// Generated by conv_settings_flt.py using PyTorch version 2.10.0+cu128.
const float16_t conv_match_stride2pad1_f16_input_data[49] = {
    (float16_t)-0.708984375f, (float16_t)-0.942871094f,  (float16_t)0.685058594f,   (float16_t)0.419189453f,
    (float16_t)-0.311767578f, (float16_t)0.791503906f,   (float16_t)-0.693359375f,  (float16_t)0.481933594f,
    (float16_t)-0.120910645f, (float16_t)-0.205932617f,  (float16_t)0.303710938f,   (float16_t)0.478515625f,
    (float16_t)0.659667969f,  (float16_t)0.0454101562f,  (float16_t)0.106079102f,   (float16_t)-0.81640625f,
    (float16_t)0.758789062f,  (float16_t)0.0231323242f,  (float16_t)-0.723632812f,  (float16_t)-0.986328125f,
    (float16_t)0.532226562f,  (float16_t)-0.580566406f,  (float16_t)0.775390625f,   (float16_t)0.915039062f,
    (float16_t)-0.350830078f, (float16_t)-0.222412109f,  (float16_t)0.7578125f,     (float16_t)-0.896484375f,
    (float16_t)-0.454345703f, (float16_t)-0.899414062f,  (float16_t)0.568359375f,   (float16_t)0.611816406f,
    (float16_t)-0.338867188f, (float16_t)-0.0114517212f, (float16_t)0.386962891f,   (float16_t)-0.103759766f,
    (float16_t)-0.97265625f,  (float16_t)-0.422607422f,  (float16_t)-0.159423828f,  (float16_t)0.276855469f,
    (float16_t)-0.250244141f, (float16_t)-0.614746094f,  (float16_t)-0.756347656f,  (float16_t)-0.350097656f,
    (float16_t)0.309814453f,  (float16_t)-0.830566406f,  (float16_t)-0.0858154297f, (float16_t)-0.604980469f,
    (float16_t)-0.0198364258f};
