// Generated by conv_settings_flt.py using PyTorch version 2.10.0+cu128.
const float16_t conv_match_stride2pad1_f16_weights_data[9] = {(float16_t)0.180786133f,
                                                              (float16_t)-0.614746094f,
                                                              (float16_t)0.486572266f,
                                                              (float16_t)0.0512390137f,
                                                              (float16_t)0.495117188f,
                                                              (float16_t)0.0369873047f,
                                                              (float16_t)-0.684082031f,
                                                              (float16_t)0.475830078f,
                                                              (float16_t)-0.528320312f};
