// Generated by generate_test_data.py using tensorflow version 2.10.0 (Keras version 2.10.0).
// Interpreter from tensorflow version 2.10.0 and revision v2.10.0-rc3-6-g359c3cdfc5f.
#pragma once
#include <stdint.h>

const int32_t fully_connected_mve_0_biases[9] = {22875, 25959, 12080, -28787, -23646, 5655, 2056, -18506, 15421};
