// Generated by generate_test_data.py using tensorflow version 2.10.0 (Keras version 2.10.0).
// Interpreter from tensorflow version 2.10.0 and revision upstream/v2.10.0-0-g359c3cdfc5f.
#pragma once
#include <stdint.h>

const int32_t fully_connected_mve_0_biases[9] = {11295, -30752, -3196, 10489, -5120, 18598, 27393, 29746, 22967};
