// Generated by generate_test_data.py using tensorflow version 2.10.0 (Keras version 2.10.0).
// Interpreter from tensorflow version 2.10.0 and revision upstream/v2.10.0-0-g359c3cdfc5f.
#pragma once
#include <stdint.h>

const int8_t fully_connected_mve_0_input[16] =
    {-43, 68, 79, -12, -119, -56, -102, -46, 107, -65, -109, -7, 92, -99, -80, -29};
