// Generated by lstm_settings_flt.py using PyTorch version 2.10.0+cu128.
const float32_t lstm_match_one_time_step_f32_cell_hidden_weights[9] = {-0.337720931f,
                                                                       0.0425028093f,
                                                                       -0.013403669f,
                                                                       0.209608719f,
                                                                       0.107653074f,
                                                                       -0.276642174f,
                                                                       0.255400896f,
                                                                       0.107432522f,
                                                                       0.108269237f};
