// Generated by lstm_settings_flt.py using PyTorch version 2.10.0+cu128.
const float32_t lstm_match_one_time_step_f32_forget_hidden_weights[9] = {0.316829979f,
                                                                         0.303915113f,
                                                                         0.181365564f,
                                                                         0.279291242f,
                                                                         -0.226180315f,
                                                                         -0.30044207f,
                                                                         0.338946372f,
                                                                         0.314945489f,
                                                                         -0.125375122f};
