// Generated by lstm_settings_flt.py using PyTorch version 2.10.0+cu128.
const float32_t lstm_match_one_time_step_f32_input_hidden_weights[9] = {-0.256600767f,
                                                                        -0.342558533f,
                                                                        -0.185401276f,
                                                                        -0.342203498f,
                                                                        -0.167991668f,
                                                                        0.109992482f,
                                                                        0.066665858f,
                                                                        -0.146376982f,
                                                                        -0.015817361f};
