// Generated by lstm_settings_flt.py using PyTorch version 2.10.0+cu128.
const float32_t lstm_match_one_time_step_f32_output_hidden_weights[9] = {0.237836272f,
                                                                         -0.0540235378f,
                                                                         -0.0786147118f,
                                                                         -0.0217899308f,
                                                                         0.244526252f,
                                                                         0.109344885f,
                                                                         -0.286713481f,
                                                                         -0.0474839397f,
                                                                         -0.0513517521f};
