// Generated by lstm_settings_flt.py using PyTorch version 2.10.0+cu128.
const float32_t lstm_match_one_time_step_f32_output_ref[9] = {-0.161744192f,
                                                              -0.117305152f,
                                                              -0.0433944538f,
                                                              -0.102637619f,
                                                              0.0759491548f,
                                                              0.151019618f,
                                                              0.263569236f,
                                                              -0.0263598394f,
                                                              0.113580383f};
