// Generated by svdf_settings_flt.py using PyTorch version 2.10.0+cu128.
const float32_t svdf_match_2_f32_bias[13] = {0.188273147f,
                                             0.22707507f,
                                             -0.00121727295f,
                                             -0.0686713308f,
                                             0.162811309f,
                                             -0.0556286871f,
                                             0.0875384659f,
                                             0.161679357f,
                                             -0.0673902184f,
                                             0.0608956404f,
                                             -0.241361111f,
                                             0.161413401f,
                                             0.113105059f};
