// Generated by test_settings.py using tensorflow version 2.11.0 (Keras version 2.11.0).
// Interpreter from tflite_runtime version 2.16.0 and revision 0.6.0-154906-gb2493fdf794.
#pragma once
#include <stdint.h>

const int16_t maxpool_int16_output_ref[12] =
    {17250, 18326, 12941, 28591, -9833, 31587, 27852, 25972, 25456, 28770, 30811, 31839};
