// Generated by pad_settings_flt.py using PyTorch version 2.10.0+cu128.
const float16_t pad_int8_1_f16_output_ref[50] = {
    (float16_t)-3.0f, (float16_t)-3.0f,         (float16_t)-3.0f,         (float16_t)-3.0f, (float16_t)-3.0f,
    (float16_t)-3.0f, (float16_t)-1.875f,       (float16_t)3.82226562f,   (float16_t)-3.0f, (float16_t)-3.0f,
    (float16_t)-3.0f, (float16_t)0.394042969f,  (float16_t)2.51171875f,   (float16_t)-3.0f, (float16_t)-3.0f,
    (float16_t)-3.0f, (float16_t)-3.0f,         (float16_t)-3.0f,         (float16_t)-3.0f, (float16_t)-3.0f,
    (float16_t)-3.0f, (float16_t)-3.0f,         (float16_t)-3.0f,         (float16_t)-3.0f, (float16_t)-3.0f,
    (float16_t)-3.0f, (float16_t)-3.0f,         (float16_t)-3.0f,         (float16_t)-3.0f, (float16_t)-3.0f,
    (float16_t)-3.0f, (float16_t)-0.326660156f, (float16_t)0.556640625f,  (float16_t)-3.0f, (float16_t)-3.0f,
    (float16_t)-3.0f, (float16_t)3.71484375f,   (float16_t)-0.600585938f, (float16_t)-3.0f, (float16_t)-3.0f,
    (float16_t)-3.0f, (float16_t)-3.0f,         (float16_t)-3.0f,         (float16_t)-3.0f, (float16_t)-3.0f,
    (float16_t)-3.0f, (float16_t)-3.0f,         (float16_t)-3.0f,         (float16_t)-3.0f, (float16_t)-3.0f};
