// Generated by ds_cnn_s_body_settings_flt.py using PyTorch version 2.10.0+cu128.
const float16_t ds_cnn_s_body_f16_dwconv1_biases_data[64] = {
    (float16_t)-0.0403442383f,  (float16_t)-0.00492477417f, (float16_t)0.0486755371f,   (float16_t)-0.0479431152f,
    (float16_t)0.0307922363f,   (float16_t)0.0142593384f,   (float16_t)-0.0321044922f,  (float16_t)-0.00685119629f,
    (float16_t)0.0364379883f,   (float16_t)0.0364990234f,   (float16_t)-0.0316467285f,  (float16_t)-0.0260009766f,
    (float16_t)0.0194091797f,   (float16_t)-0.0442810059f,  (float16_t)-0.0406494141f,  (float16_t)-0.0174255371f,
    (float16_t)0.00061416626f,  (float16_t)-0.0478210449f,  (float16_t)0.0282592773f,   (float16_t)0.0395507812f,
    (float16_t)-0.0162963867f,  (float16_t)-0.0303955078f,  (float16_t)-0.0387573242f,  (float16_t)-0.0016412735f,
    (float16_t)-0.040222168f,   (float16_t)0.0325622559f,   (float16_t)0.0267791748f,   (float16_t)0.0334777832f,
    (float16_t)-0.004737854f,   (float16_t)-0.0256195068f,  (float16_t)-0.0405578613f,  (float16_t)-0.0439147949f,
    (float16_t)0.0392456055f,   (float16_t)-0.0426330566f,  (float16_t)-0.0418395996f,  (float16_t)-0.0321350098f,
    (float16_t)-0.00518798828f, (float16_t)-0.0274200439f,  (float16_t)0.0245513916f,   (float16_t)0.0214233398f,
    (float16_t)0.024597168f,    (float16_t)0.0305023193f,   (float16_t)0.0250854492f,   (float16_t)0.00100421906f,
    (float16_t)-0.00284576416f, (float16_t)-0.0137786865f,  (float16_t)-0.00552749634f, (float16_t)-0.0333557129f,
    (float16_t)-0.0494384766f,  (float16_t)0.0323486328f,   (float16_t)-0.0402832031f,  (float16_t)0.0394897461f,
    (float16_t)-0.0186920166f,  (float16_t)0.0270996094f,   (float16_t)0.0438842773f,   (float16_t)0.0288848877f,
    (float16_t)0.00520706177f,  (float16_t)-0.00571060181f, (float16_t)0.0401000977f,   (float16_t)0.039855957f,
    (float16_t)0.0366210938f,   (float16_t)0.0109176636f,   (float16_t)0.0476074219f,   (float16_t)0.0379638672f};
