// Generated by ds_cnn_s_body_settings_flt.py using PyTorch version 2.10.0+cu128.
const float16_t ds_cnn_s_body_f16_dwconv3_biases_data[64] = {
    (float16_t)0.0133514404f,  (float16_t)-0.0243530273f,  (float16_t)0.00271606445f,  (float16_t)0.00584030151f,
    (float16_t)0.0429382324f,  (float16_t)-0.00430297852f, (float16_t)-0.0199584961f,  (float16_t)0.0335388184f,
    (float16_t)0.0236053467f,  (float16_t)-0.00170993805f, (float16_t)-0.0299072266f,  (float16_t)-0.0353393555f,
    (float16_t)0.0391845703f,  (float16_t)-0.0148849487f,  (float16_t)0.0134811401f,   (float16_t)-0.0453491211f,
    (float16_t)-0.0202026367f, (float16_t)0.0457458496f,   (float16_t)-0.0335388184f,  (float16_t)0.049621582f,
    (float16_t)0.0447692871f,  (float16_t)-0.0461730957f,  (float16_t)-0.03125f,       (float16_t)-0.00560379028f,
    (float16_t)0.0426330566f,  (float16_t)-0.0244293213f,  (float16_t)-0.0215148926f,  (float16_t)-0.00766372681f,
    (float16_t)-0.022644043f,  (float16_t)0.0237426758f,   (float16_t)-0.0483093262f,  (float16_t)0.0340576172f,
    (float16_t)0.00310325623f, (float16_t)-0.0355834961f,  (float16_t)0.0318603516f,   (float16_t)-0.0381164551f,
    (float16_t)0.0406188965f,  (float16_t)-0.0411682129f,  (float16_t)0.0254058838f,   (float16_t)-0.0393371582f,
    (float16_t)-0.0327453613f, (float16_t)0.035369873f,    (float16_t)-0.00932312012f, (float16_t)0.0204772949f,
    (float16_t)0.0497741699f,  (float16_t)0.0159606934f,   (float16_t)-0.0331726074f,  (float16_t)-0.0441589355f,
    (float16_t)0.0192565918f,  (float16_t)0.0167694092f,   (float16_t)0.0418701172f,   (float16_t)0.00492095947f,
    (float16_t)0.0284423828f,  (float16_t)-0.0279083252f,  (float16_t)-0.0293884277f,  (float16_t)-0.00240516663f,
    (float16_t)0.0369567871f,  (float16_t)0.0459594727f,   (float16_t)-0.0048789978f,  (float16_t)0.0115356445f,
    (float16_t)0.0190429688f,  (float16_t)-0.0297698975f,  (float16_t)0.0258331299f,   (float16_t)0.0263519287f};
