// Generated by ds_cnn_s_body_settings_flt.py using PyTorch version 2.10.0+cu128.
const float16_t ds_cnn_s_body_f16_dwconv0_biases_data[64] = {
    (float16_t)0.0421142578f,   (float16_t)0.0346679688f,   (float16_t)-0.0225219727f,  (float16_t)0.0123519897f,
    (float16_t)-0.0083694458f,  (float16_t)0.021270752f,    (float16_t)0.00528335571f,  (float16_t)0.0358581543f,
    (float16_t)0.0156860352f,   (float16_t)0.0154800415f,   (float16_t)0.0228424072f,   (float16_t)-0.0187530518f,
    (float16_t)-0.0168151855f,  (float16_t)-0.0133895874f,  (float16_t)-0.0356750488f,  (float16_t)-0.0144958496f,
    (float16_t)-0.016998291f,   (float16_t)0.0254974365f,   (float16_t)0.047668457f,    (float16_t)-0.0268249512f,
    (float16_t)-0.025894165f,   (float16_t)-0.00775909424f, (float16_t)0.00547409058f,  (float16_t)-0.0453186035f,
    (float16_t)-0.0207061768f,  (float16_t)0.018081665f,    (float16_t)0.0221862793f,   (float16_t)0.0193481445f,
    (float16_t)-0.0258178711f,  (float16_t)-0.00661849976f, (float16_t)0.0209960938f,   (float16_t)-8.73804092e-05f,
    (float16_t)-0.0186920166f,  (float16_t)-0.0140228271f,  (float16_t)-0.00281333923f, (float16_t)-0.00187492371f,
    (float16_t)0.0153198242f,   (float16_t)0.0256500244f,   (float16_t)-0.0455627441f,  (float16_t)0.01902771f,
    (float16_t)0.0306243896f,   (float16_t)-0.0102081299f,  (float16_t)-0.0389099121f,  (float16_t)0.0358886719f,
    (float16_t)-0.0375671387f,  (float16_t)0.0440979004f,   (float16_t)-0.0372619629f,  (float16_t)-0.00388145447f,
    (float16_t)-0.0169219971f,  (float16_t)-0.0401306152f,  (float16_t)-0.0320129395f,  (float16_t)-0.00127601624f,
    (float16_t)-0.0400085449f,  (float16_t)-0.0470275879f,  (float16_t)-0.0262298584f,  (float16_t)-0.0421447754f,
    (float16_t)-0.0294036865f,  (float16_t)0.0445861816f,   (float16_t)-0.0121612549f,  (float16_t)-0.004737854f,
    (float16_t)-0.00889587402f, (float16_t)-0.0371398926f,  (float16_t)0.0141448975f,   (float16_t)-0.0390319824f};
