// Generated by ds_cnn_s_body_settings_flt.py using PyTorch version 2.10.0+cu128.
const float16_t ds_cnn_s_body_f16_dwconv2_biases_data[64] = {
    (float16_t)0.00397491455f,  (float16_t)-0.00168132782f,  (float16_t)-0.008644104f,   (float16_t)0.0483093262f,
    (float16_t)0.0135726929f,   (float16_t)-0.0173950195f,   (float16_t)0.021194458f,    (float16_t)-0.0317687988f,
    (float16_t)0.00262641907f,  (float16_t)0.015411377f,     (float16_t)0.0223083496f,   (float16_t)0.00270271301f,
    (float16_t)-0.0258331299f,  (float16_t)-0.0152359009f,   (float16_t)0.00456237793f,  (float16_t)-0.00443649292f,
    (float16_t)-0.00221633911f, (float16_t)0.0322265625f,    (float16_t)0.0242156982f,   (float16_t)0.0247955322f,
    (float16_t)0.0461425781f,   (float16_t)0.00839996338f,   (float16_t)-0.0186157227f,  (float16_t)0.0491943359f,
    (float16_t)0.0227813721f,   (float16_t)-0.0408935547f,   (float16_t)-0.00636672974f, (float16_t)-0.0350341797f,
    (float16_t)-0.0455932617f,  (float16_t)-0.0363769531f,   (float16_t)-0.036315918f,   (float16_t)-0.0317687988f,
    (float16_t)0.0300750732f,   (float16_t)-0.0192718506f,   (float16_t)-0.0193939209f,  (float16_t)-0.0431518555f,
    (float16_t)-0.00131320953f, (float16_t)0.0294494629f,    (float16_t)0.0222320557f,   (float16_t)-0.033782959f,
    (float16_t)-0.0466918945f,  (float16_t)-0.0466308594f,   (float16_t)0.0284729004f,   (float16_t)-0.0145492554f,
    (float16_t)0.0485839844f,   (float16_t)0.0149459839f,    (float16_t)0.0110244751f,   (float16_t)0.0292358398f,
    (float16_t)0.0462036133f,   (float16_t)-0.0264892578f,   (float16_t)0.0400085449f,   (float16_t)0.014503479f,
    (float16_t)-0.0031452179f,  (float16_t)0.0222167969f,    (float16_t)-0.0199584961f,  (float16_t)0.0117340088f,
    (float16_t)0.0262908936f,   (float16_t)-0.000274896622f, (float16_t)-0.0108032227f,  (float16_t)0.0192565918f,
    (float16_t)0.0422363281f,   (float16_t)0.0305328369f,    (float16_t)-0.0149612427f,  (float16_t)0.0464477539f};
