// Generated by ds_cnn_s_body_settings_flt.py using PyTorch version 2.10.0+cu128.
const float16_t ds_cnn_s_body_f16_fc_biases_data[12] = {(float16_t)-0.0290374756f,
                                                        (float16_t)-0.00316047668f,
                                                        (float16_t)0.0229492188f,
                                                        (float16_t)0.00551605225f,
                                                        (float16_t)0.0250091553f,
                                                        (float16_t)-0.0442810059f,
                                                        (float16_t)0.0367126465f,
                                                        (float16_t)0.0375671387f,
                                                        (float16_t)0.0320739746f,
                                                        (float16_t)0.0360107422f,
                                                        (float16_t)0.0263671875f,
                                                        (float16_t)0.00165367126f};
