// Generated by ds_cnn_s_body_settings_flt.py using PyTorch version 2.10.0+cu128.
const float16_t ds_cnn_s_body_f16_output_ref_data[12] = {(float16_t)0.0775146484f,
                                                         (float16_t)0.081237793f,
                                                         (float16_t)0.0840454102f,
                                                         (float16_t)0.0834960938f,
                                                         (float16_t)0.0865478516f,
                                                         (float16_t)0.0793457031f,
                                                         (float16_t)0.0885620117f,
                                                         (float16_t)0.0869750977f,
                                                         (float16_t)0.0872802734f,
                                                         (float16_t)0.0823974609f,
                                                         (float16_t)0.0816040039f,
                                                         (float16_t)0.0809936523f};
