// Generated by ds_cnn_s_body_settings_flt.py using PyTorch version 2.10.0+cu128.
const float16_t ds_cnn_s_body_f16_pwconv2_biases_data[64] = {
    (float16_t)-0.0430297852f, (float16_t)-0.00845336914f,  (float16_t)-0.0346374512f,  (float16_t)-0.0414733887f,
    (float16_t)0.0115661621f,  (float16_t)-0.0394897461f,   (float16_t)-0.0136795044f,  (float16_t)-0.036529541f,
    (float16_t)-0.0123825073f, (float16_t)-0.0364685059f,   (float16_t)-0.0430908203f,  (float16_t)-0.0388793945f,
    (float16_t)-0.0356140137f, (float16_t)0.00366592407f,   (float16_t)-0.0105438232f,  (float16_t)-0.0330200195f,
    (float16_t)0.0225372314f,  (float16_t)-0.00901794434f,  (float16_t)-0.0272064209f,  (float16_t)0.0463867188f,
    (float16_t)-0.0266265869f, (float16_t)0.0194549561f,    (float16_t)-0.0471496582f,  (float16_t)-0.021987915f,
    (float16_t)-0.0272827148f, (float16_t)-0.0436706543f,   (float16_t)0.00968933105f,  (float16_t)-0.0205688477f,
    (float16_t)-0.0492553711f, (float16_t)0.0497741699f,    (float16_t)0.00910186768f,  (float16_t)0.0283660889f,
    (float16_t)-0.0194549561f, (float16_t)0.0433959961f,    (float16_t)0.0044631958f,   (float16_t)-0.0287017822f,
    (float16_t)0.041809082f,   (float16_t)0.00562667847f,   (float16_t)0.0375671387f,   (float16_t)-0.0165252686f,
    (float16_t)-0.0438842773f, (float16_t)-0.014793396f,    (float16_t)-0.0445861816f,  (float16_t)-0.00212097168f,
    (float16_t)0.0326538086f,  (float16_t)-0.0307159424f,   (float16_t)0.044708252f,    (float16_t)0.00253105164f,
    (float16_t)-0.038269043f,  (float16_t)0.038848877f,     (float16_t)-0.0391845703f,  (float16_t)0.00288391113f,
    (float16_t)0.010925293f,   (float16_t)-0.000226855278f, (float16_t)0.0493164062f,   (float16_t)0.0387878418f,
    (float16_t)0.0454711914f,  (float16_t)0.0357971191f,    (float16_t)0.0480957031f,   (float16_t)-0.0429992676f,
    (float16_t)0.0497131348f,  (float16_t)0.032623291f,     (float16_t)-0.00807189941f, (float16_t)-0.0350036621f};
