// Generated by ds_cnn_s_body_settings_flt.py using PyTorch version 2.10.0+cu128.
const float16_t ds_cnn_s_body_f16_pwconv0_biases_data[64] = {
    (float16_t)0.0314941406f,    (float16_t)0.0272064209f,   (float16_t)0.0285949707f,  (float16_t)0.00788879395f,
    (float16_t)-0.0286254883f,   (float16_t)0.0269927979f,   (float16_t)0.0354919434f,  (float16_t)-0.0121231079f,
    (float16_t)-0.000853538513f, (float16_t)-0.0225982666f,  (float16_t)-0.0423278809f, (float16_t)-0.00415802002f,
    (float16_t)0.0209197998f,    (float16_t)-0.00294494629f, (float16_t)-0.0483093262f, (float16_t)-0.026260376f,
    (float16_t)0.0343933105f,    (float16_t)0.0064125061f,   (float16_t)-0.0351257324f, (float16_t)-0.0348815918f,
    (float16_t)0.00340461731f,   (float16_t)0.00402069092f,  (float16_t)0.0137863159f,  (float16_t)-0.0195922852f,
    (float16_t)0.0352783203f,    (float16_t)-0.0342712402f,  (float16_t)0.0420227051f,  (float16_t)-0.020401001f,
    (float16_t)0.0260314941f,    (float16_t)-0.0454406738f,  (float16_t)0.0411987305f,  (float16_t)-0.040435791f,
    (float16_t)0.0356445312f,    (float16_t)0.0411987305f,   (float16_t)0.00714111328f, (float16_t)0.0411682129f,
    (float16_t)0.0393981934f,    (float16_t)-0.022354126f,   (float16_t)-0.029296875f,  (float16_t)0.03515625f,
    (float16_t)0.0236816406f,    (float16_t)-0.0445556641f,  (float16_t)0.0259399414f,  (float16_t)0.0473022461f,
    (float16_t)0.0264129639f,    (float16_t)0.00407409668f,  (float16_t)-0.0294036865f, (float16_t)-0.0143661499f,
    (float16_t)0.0346984863f,    (float16_t)0.0161743164f,   (float16_t)0.042388916f,   (float16_t)-0.00215148926f,
    (float16_t)0.00261497498f,   (float16_t)-0.0159759521f,  (float16_t)-0.0420532227f, (float16_t)-0.0205078125f,
    (float16_t)0.0419006348f,    (float16_t)-0.0307312012f,  (float16_t)-0.0343933105f, (float16_t)0.0106887817f,
    (float16_t)0.0304260254f,    (float16_t)0.00632095337f,  (float16_t)0.0210723877f,  (float16_t)0.040802002f};
