// Generated by ds_cnn_s_body_settings_flt.py using PyTorch version 2.10.0+cu128.
const float16_t ds_cnn_s_body_f16_pwconv3_biases_data[64] = {
    (float16_t)0.0272979736f,   (float16_t)-0.0305938721f,  (float16_t)-0.0338745117f,  (float16_t)0.0445861816f,
    (float16_t)-0.0433959961f,  (float16_t)-0.0499267578f,  (float16_t)0.00705718994f,  (float16_t)-0.0483093262f,
    (float16_t)-0.0275421143f,  (float16_t)0.0361938477f,   (float16_t)0.0411682129f,   (float16_t)-0.0482177734f,
    (float16_t)0.0284118652f,   (float16_t)-0.00737380981f, (float16_t)0.0356445312f,   (float16_t)0.0477905273f,
    (float16_t)-0.0361328125f,  (float16_t)0.0172424316f,   (float16_t)-0.0438537598f,  (float16_t)0.0333251953f,
    (float16_t)-0.0390930176f,  (float16_t)0.00852966309f,  (float16_t)-0.0129318237f,  (float16_t)0.0449523926f,
    (float16_t)0.0151596069f,   (float16_t)-0.0336303711f,  (float16_t)0.0428161621f,   (float16_t)0.0125350952f,
    (float16_t)-0.0393371582f,  (float16_t)-0.00080871582f, (float16_t)0.0344848633f,   (float16_t)-0.0409545898f,
    (float16_t)0.0169219971f,   (float16_t)0.0480957031f,   (float16_t)0.0346374512f,   (float16_t)0.0157318115f,
    (float16_t)0.0390930176f,   (float16_t)0.012336731f,    (float16_t)0.0223693848f,   (float16_t)-0.00405502319f,
    (float16_t)-0.00408554077f, (float16_t)0.0242919922f,   (float16_t)-0.0262145996f,  (float16_t)-0.0443725586f,
    (float16_t)0.0374450684f,   (float16_t)0.0230407715f,   (float16_t)0.00875854492f,  (float16_t)0.0482177734f,
    (float16_t)0.0117416382f,   (float16_t)0.0416870117f,   (float16_t)-0.00574111938f, (float16_t)-0.0410461426f,
    (float16_t)0.0232696533f,   (float16_t)-0.035369873f,   (float16_t)-0.0107879639f,  (float16_t)-0.0382995605f,
    (float16_t)0.0397033691f,   (float16_t)-0.0261230469f,  (float16_t)0.00910949707f,  (float16_t)-0.0491027832f,
    (float16_t)0.0485839844f,   (float16_t)0.0226593018f,   (float16_t)-0.00535964966f, (float16_t)0.0376586914f};
