// Generated by ds_cnn_s_body_settings_flt.py using PyTorch version 2.10.0+cu128.
const float16_t ds_cnn_s_body_f16_pwconv1_biases_data[64] = {
    (float16_t)0.0108947754f,   (float16_t)0.0380249023f,  (float16_t)0.0389404297f,  (float16_t)-0.000238180161f,
    (float16_t)-0.0472106934f,  (float16_t)-0.0354003906f, (float16_t)-0.0316467285f, (float16_t)-0.0165557861f,
    (float16_t)0.0411376953f,   (float16_t)-0.033203125f,  (float16_t)-0.0274810791f, (float16_t)0.0473022461f,
    (float16_t)0.0272369385f,   (float16_t)-0.0433959961f, (float16_t)-0.0499572754f, (float16_t)-0.0218658447f,
    (float16_t)0.0131149292f,   (float16_t)0.049987793f,   (float16_t)0.0292816162f,  (float16_t)-0.0483093262f,
    (float16_t)-0.0375061035f,  (float16_t)0.020614624f,   (float16_t)-0.0436096191f, (float16_t)0.0262145996f,
    (float16_t)0.01121521f,     (float16_t)0.0411682129f,  (float16_t)-0.0355529785f, (float16_t)-0.00168609619f,
    (float16_t)0.0415039062f,   (float16_t)-0.0193328857f, (float16_t)-0.0188751221f, (float16_t)0.00734329224f,
    (float16_t)0.0331115723f,   (float16_t)0.0155334473f,  (float16_t)0.0305328369f,  (float16_t)-0.0496826172f,
    (float16_t)-0.0225524902f,  (float16_t)0.0434265137f,  (float16_t)-0.0431518555f, (float16_t)0.0129241943f,
    (float16_t)-0.0445556641f,  (float16_t)0.0425415039f,  (float16_t)0.0241546631f,  (float16_t)0.0224151611f,
    (float16_t)-0.0123062134f,  (float16_t)0.0412597656f,  (float16_t)0.00578689575f, (float16_t)-0.0340576172f,
    (float16_t)2.58088112e-05f, (float16_t)-0.0366210938f, (float16_t)0.0481262207f,  (float16_t)-0.0057220459f,
    (float16_t)-0.030670166f,   (float16_t)0.0447998047f,  (float16_t)-0.0352172852f, (float16_t)-0.0334777832f,
    (float16_t)0.00871276855f,  (float16_t)-0.0317077637f, (float16_t)0.025970459f,   (float16_t)0.0420227051f,
    (float16_t)0.0354309082f,   (float16_t)-0.0333862305f, (float16_t)0.0422363281f,  (float16_t)0.0161590576f};
