// Generated by depthwise_conv_settings_flt.py using PyTorch version 2.10.0+cu128.
const float32_t depthwise_match_basic_f32_weights_data[8] = {0.1261556f,
                                                             -0.632649183f,
                                                             -0.175735846f,
                                                             -0.0864114761f,
                                                             0.535107136f,
                                                             -0.702003777f,
                                                             -0.414459974f,
                                                             0.553470552f};
