// Generated by pooling_settings_flt.py using PyTorch version 2.10.0+cu128.
const float32_t avgpooling_match_3_f32_output_ref[10] = {-1.9569428f,
                                                         1.21028328f,
                                                         3.5972383f,
                                                         -1.97945809f,
                                                         2.09824729f,
                                                         -0.132652447f,
                                                         -5.00376797f,
                                                         -0.419882268f,
                                                         -1.21378183f,
                                                         4.64763975f};
