// Generated by minmax_settings_flt.py using PyTorch version 2.10.0+cu128.
const float16_t minimum_broadcast_width_f16_input_tensor_2[38] = {
    (float16_t)-4.578125f,   (float16_t)-1.17089844f,  (float16_t)1.56054688f,  (float16_t)1.10058594f,
    (float16_t)5.07421875f,  (float16_t)-0.922851562f, (float16_t)-3.35742188f, (float16_t)3.51757812f,
    (float16_t)5.91796875f,  (float16_t)0.639160156f,  (float16_t)-4.1171875f,  (float16_t)-4.72265625f,
    (float16_t)-4.59765625f, (float16_t)-3.87890625f,  (float16_t)3.62890625f,  (float16_t)2.4296875f,
    (float16_t)3.02929688f,  (float16_t)-0.222167969f, (float16_t)-2.21289062f, (float16_t)-2.80859375f,
    (float16_t)1.13574219f,  (float16_t)4.33203125f,   (float16_t)-2.10742188f, (float16_t)4.34765625f,
    (float16_t)-1.04882812f, (float16_t)2.89453125f,   (float16_t)-1.02148438f, (float16_t)4.3828125f,
    (float16_t)-1.35839844f, (float16_t)4.57421875f,   (float16_t)0.728027344f, (float16_t)-4.6875f,
    (float16_t)2.62109375f,  (float16_t)-5.41015625f,  (float16_t)5.078125f,    (float16_t)-4.66015625f,
    (float16_t)1.82226562f,  (float16_t)-5.30859375f};
