// Generated by svdf_settings_flt.py using PyTorch version 2.10.0+cu128.
const float16_t svdf_match_2_f16_bias[13] = {(float16_t)-0.0391235352f,
                                             (float16_t)0.0301513672f,
                                             (float16_t)-0.0329589844f,
                                             (float16_t)-0.0195770264f,
                                             (float16_t)0.013168335f,
                                             (float16_t)0.0825195312f,
                                             (float16_t)0.160522461f,
                                             (float16_t)0.130615234f,
                                             (float16_t)-0.0397644043f,
                                             (float16_t)-0.186157227f,
                                             (float16_t)-0.121582031f,
                                             (float16_t)0.163330078f,
                                             (float16_t)0.206787109f};
