// Generated by svdf_settings_flt.py using PyTorch version 2.10.0+cu128.
const float16_t svdf_match_2_f16_output_ref[26] = {
    (float16_t)0.593261719f,   (float16_t)-0.118713379f, (float16_t)-0.487548828f, (float16_t)-0.756347656f,
    (float16_t)-0.493652344f,  (float16_t)-0.152709961f, (float16_t)0.489990234f,  (float16_t)0.795898438f,
    (float16_t)-0.560546875f,  (float16_t)-0.833496094f, (float16_t)-0.571777344f, (float16_t)0.859863281f,
    (float16_t)0.708007812f,   (float16_t)0.478271484f,  (float16_t)0.380615234f,  (float16_t)-0.487792969f,
    (float16_t)-0.799804688f,  (float16_t)-0.769042969f, (float16_t)0.0900878906f, (float16_t)0.0455932617f,
    (float16_t)0.0462036133f,  (float16_t)-0.541992188f, (float16_t)-0.927246094f, (float16_t)-0.165161133f,
    (float16_t)-0.0802001953f, (float16_t)-0.187133789f};
