// Generated by conv_settings_flt.py using PyTorch version 2.10.0+cu128.
const float16_t conv_match_1x1_stride_x_f16_biases_data[5] = {(float16_t)0.303710938f,
                                                              (float16_t)-0.0841674805f,
                                                              (float16_t)-0.291992188f,
                                                              (float16_t)0.243164062f,
                                                              (float16_t)0.109802246f};
