// Generated by conv_settings_flt.py using PyTorch version 2.10.0+cu128.
const float16_t conv_match_1x1_stride_x_f16_weights_data[45] = {
    (float16_t)0.222045898f,   (float16_t)-0.327148438f,  (float16_t)-0.161499023f, (float16_t)0.247070312f,
    (float16_t)0.392822266f,   (float16_t)-0.412597656f,  (float16_t)0.187988281f,  (float16_t)-0.251464844f,
    (float16_t)-0.456787109f,  (float16_t)0.136962891f,   (float16_t)0.547851562f,  (float16_t)-0.626953125f,
    (float16_t)-0.329833984f,  (float16_t)-0.0602111816f, (float16_t)-0.264404297f, (float16_t)0.293457031f,
    (float16_t)-0.5234375f,    (float16_t)0.13671875f,    (float16_t)0.524414062f,  (float16_t)0.233154297f,
    (float16_t)0.349365234f,   (float16_t)0.0117263794f,  (float16_t)0.737304688f,  (float16_t)0.532226562f,
    (float16_t)0.137573242f,   (float16_t)-0.562011719f,  (float16_t)0.743652344f,  (float16_t)0.0249328613f,
    (float16_t)-0.665039062f,  (float16_t)0.144897461f,   (float16_t)0.313964844f,  (float16_t)-0.347167969f,
    (float16_t)-0.0253143311f, (float16_t)-0.162841797f,  (float16_t)-0.53515625f,  (float16_t)0.500488281f,
    (float16_t)0.395507812f,   (float16_t)0.553710938f,   (float16_t)0.319335938f,  (float16_t)0.735839844f,
    (float16_t)0.298583984f,   (float16_t)-0.489746094f,  (float16_t)0.135253906f,  (float16_t)0.0647583008f,
    (float16_t)-0.57421875f};
