// Generated by conv_settings_flt.py using PyTorch version 2.10.0+cu128.
const float16_t conv_match_conv_2_f16_biases_data[4] = {(float16_t)0.244262695f,
                                                        (float16_t)-0.163696289f,
                                                        (float16_t)0.0114822388f,
                                                        (float16_t)-0.374267578f};
