// Generated by conv_settings_flt.py using PyTorch version 2.10.0+cu128.
const float16_t conv_match_conv_2_f16_input_data[36] = {
    (float16_t)0.898925781f,   (float16_t)0.156616211f,  (float16_t)0.270263672f,  (float16_t)0.960449219f,
    (float16_t)-0.966796875f,  (float16_t)-0.124816895f, (float16_t)0.0723266602f, (float16_t)0.564453125f,
    (float16_t)-0.301513672f,  (float16_t)0.420898438f,  (float16_t)0.322265625f,  (float16_t)-0.176147461f,
    (float16_t)-0.428466797f,  (float16_t)0.891601562f,  (float16_t)-0.94140625f,  (float16_t)0.378417969f,
    (float16_t)0.696777344f,   (float16_t)-0.959472656f, (float16_t)-0.59765625f,  (float16_t)-0.697753906f,
    (float16_t)0.51171875f,    (float16_t)0.579589844f,  (float16_t)0.722167969f,  (float16_t)-0.569335938f,
    (float16_t)-0.0676269531f, (float16_t)0.892089844f,  (float16_t)0.579101562f,  (float16_t)0.896484375f,
    (float16_t)0.783203125f,   (float16_t)0.106140137f,  (float16_t)-0.431152344f, (float16_t)-0.415771484f,
    (float16_t)-0.716308594f,  (float16_t)0.263427734f,  (float16_t)0.989746094f,  (float16_t)-0.619140625f};
