// Generated by svdf_settings_flt.py using PyTorch version 2.10.0+cu128.
const float16_t svdf_batch2_f16_bias[8] = {(float16_t)-0.0536499023f,
                                           (float16_t)0.138305664f,
                                           (float16_t)-0.24621582f,
                                           (float16_t)0.00514602661f,
                                           (float16_t)0.207397461f,
                                           (float16_t)0.104675293f,
                                           (float16_t)0.0415039062f,
                                           (float16_t)0.0168457031f};
