// Generated by svdf_settings_flt.py using PyTorch version 2.10.0+cu128.
const float16_t svdf_batch2_f16_weights_time[48] = {
    (float16_t)0.382324219f,   (float16_t)-0.210571289f,  (float16_t)-0.23815918f,   (float16_t)-0.162109375f,
    (float16_t)0.153076172f,   (float16_t)0.196411133f,   (float16_t)0.401367188f,   (float16_t)-0.290527344f,
    (float16_t)0.245849609f,   (float16_t)0.472167969f,   (float16_t)0.428466797f,   (float16_t)0.336425781f,
    (float16_t)-0.114746094f,  (float16_t)-0.29296875f,   (float16_t)-0.0184936523f, (float16_t)-0.0629272461f,
    (float16_t)0.315429688f,   (float16_t)0.356933594f,   (float16_t)-0.37890625f,   (float16_t)-0.433837891f,
    (float16_t)-0.0223388672f, (float16_t)0.191650391f,   (float16_t)-0.126708984f,  (float16_t)-0.193969727f,
    (float16_t)0.355224609f,   (float16_t)-0.368896484f,  (float16_t)0.475097656f,   (float16_t)-0.306640625f,
    (float16_t)0.0493469238f,  (float16_t)-0.169677734f,  (float16_t)-0.229858398f,  (float16_t)0.429443359f,
    (float16_t)0.46875f,       (float16_t)0.388671875f,   (float16_t)-0.438720703f,  (float16_t)-0.237182617f,
    (float16_t)0.0935058594f,  (float16_t)-0.135009766f,  (float16_t)-0.143188477f,  (float16_t)0.0646362305f,
    (float16_t)0.305419922f,   (float16_t)-0.0527038574f, (float16_t)0.0687866211f,  (float16_t)-0.256835938f,
    (float16_t)-0.138183594f,  (float16_t)0.410888672f,   (float16_t)-0.0739135742f, (float16_t)0.0841064453f};
