// Generated by test_settings.py using tensorflow version 2.14.0 (Keras version 2.14.0).
// Interpreter from tflite_micro version 0.dev20230817002213-g3bd11ea3 and revision None.
#pragma once
#include <stdint.h>

const int32_t fully_connected_int4_biases[5] = {17, -88, -107, 94, -29};
