// Generated by test_settings.py using tensorflow version 2.14.0 (Keras version 2.14.0).
// Interpreter from tflite_micro version 0.dev20230817002213-g3bd11ea3 and revision None.
#include "biases_data.h"
#include "config_data.h"
#include "input_data.h"
#include "output_ref_data.h"
#include "weights_data.h"
