// Generated by batch_matmul_settings_flt.py using PyTorch version 2.10.0+cu128.
const float16_t batch_matmul_3_f16_lhs_input_tensor[40] = {
    (float16_t)0.5078125f,     (float16_t)0.149902344f,   (float16_t)1.07324219f,   (float16_t)-1.61132812f,
    (float16_t)-1.34179688f,   (float16_t)1.32617188f,    (float16_t)-0.630371094f, (float16_t)-0.0172576904f,
    (float16_t)1.93066406f,    (float16_t)-0.794433594f,  (float16_t)-0.771484375f, (float16_t)1.74804688f,
    (float16_t)-1.42285156f,   (float16_t)1.04882812f,    (float16_t)1.53320312f,   (float16_t)-0.604003906f,
    (float16_t)1.55957031f,    (float16_t)1.203125f,      (float16_t)0.394287109f,  (float16_t)0.369628906f,
    (float16_t)-1.40527344f,   (float16_t)-1.2890625f,    (float16_t)0.384033203f,  (float16_t)-1.44726562f,
    (float16_t)1.80371094f,    (float16_t)0.425048828f,   (float16_t)-1.70800781f,  (float16_t)1.61523438f,
    (float16_t)-0.565429688f,  (float16_t)-0.0974121094f, (float16_t)1.44726562f,   (float16_t)0.849609375f,
    (float16_t)0.240966797f,   (float16_t)0.735351562f,   (float16_t)1.85546875f,   (float16_t)1.36914062f,
    (float16_t)-0.0921020508f, (float16_t)-0.784179688f,  (float16_t)0.0403137207f, (float16_t)1.86621094f};
