// Generated by add_mul_settings_flt.py using PyTorch version 2.10.0+cu128.
#define MUL_F16_DST_SIZE 160
#define MUL_F16_OUT_ACTIVATION_MIN (float16_t) - 10.0f
#define MUL_F16_OUT_ACTIVATION_MAX (float16_t)10.0f
#define MUL_F16_INPUT1_OFFSET 0
#define MUL_F16_INPUT2_OFFSET 0
#define MUL_F16_OUTPUT_MULT 0
#define MUL_F16_OUTPUT_SHIFT 0
#define MUL_F16_OUTPUT_OFFSET 0
