// Generated by depthwise_conv_settings_flt.py using PyTorch version 2.10.0+cu128.
const float32_t depthwise_basic_smallc_nhwc_f32_biases_data[6] =
    {-0.0907983407f, -0.169143111f, 0.184338167f, 0.268792182f, 0.106893525f, 0.459879994f};
