// Generated by conv_settings_flt.py using PyTorch version 2.10.0+cu128.
const float16_t conv_match_1x1_stride_x_y_1_f16_biases_data[5] = {(float16_t)0.195556641f,
                                                                  (float16_t)-0.267578125f,
                                                                  (float16_t)-0.0159912109f,
                                                                  (float16_t)0.376953125f,
                                                                  (float16_t)-0.264404297f};
