// Generated by conv_settings_flt.py using PyTorch version 2.10.0+cu128.
const float16_t conv_match_1x1_stride_x_y_1_f16_output_ref_data[40] = {
    (float16_t)-0.058380127f, (float16_t)-0.142944336f, (float16_t)0.695800781f,   (float16_t)0.9140625f,
    (float16_t)-0.416259766f, (float16_t)0.262695312f,  (float16_t)-0.152587891f,  (float16_t)0.288818359f,
    (float16_t)0.533203125f,  (float16_t)0.0343017578f, (float16_t)0.185913086f,   (float16_t)-0.255859375f,
    (float16_t)-0.324462891f, (float16_t)0.663085938f,  (float16_t)-1.49316406f,   (float16_t)0.375732422f,
    (float16_t)-0.68359375f,  (float16_t)-0.129882812f, (float16_t)0.370117188f,   (float16_t)-0.693847656f,
    (float16_t)0.843261719f,  (float16_t)-0.555175781f, (float16_t)-0.433837891f,  (float16_t)0.206054688f,
    (float16_t)-0.228393555f, (float16_t)-0.182495117f, (float16_t)-0.251953125f,  (float16_t)-1.09570312f,
    (float16_t)-0.470947266f, (float16_t)-0.494873047f, (float16_t)0.208496094f,   (float16_t)-0.154174805f,
    (float16_t)0.342773438f,  (float16_t)1.00878906f,   (float16_t)-1.02734375f,   (float16_t)-0.122741699f,
    (float16_t)-0.402832031f, (float16_t)-0.622070312f, (float16_t)-0.0786132812f, (float16_t)-0.709960938f};
