// Generated by conv_settings_flt.py using PyTorch version 2.10.0+cu128.
const float16_t conv_match_1x1_stride_x_y_1_f16_weights_data[25] = {
    (float16_t)0.448242188f,  (float16_t)-0.421875f,    (float16_t)0.0200653076f, (float16_t)-0.205810547f,
    (float16_t)0.0718383789f, (float16_t)0.067565918f,  (float16_t)0.351318359f,  (float16_t)0.0458374023f,
    (float16_t)0.274169922f,  (float16_t)-0.139282227f, (float16_t)0.476806641f,  (float16_t)-0.30078125f,
    (float16_t)0.489990234f,  (float16_t)0.55859375f,   (float16_t)0.356933594f,  (float16_t)0.65625f,
    (float16_t)0.0199127197f, (float16_t)0.657226562f,  (float16_t)0.24987793f,   (float16_t)0.00491714478f,
    (float16_t)-0.200561523f, (float16_t)-0.659667969f, (float16_t)-0.643066406f, (float16_t)0.428466797f,
    (float16_t)0.592285156f};
