// Generated by fully_connected_settings_flt.py using PyTorch version 2.10.0+cu128.
const float32_t fully_connected_out_activation_f32_biases_data[4] = {-0.428294659f,
                                                                     0.598740995f,
                                                                     -0.413622707f,
                                                                     -0.693337917f};
