// Generated by fully_connected_settings_flt.py using PyTorch version 2.10.0+cu128.
const float32_t fully_connected_out_activation_f32_input_data[10] = {-2.56194592f,
                                                                     -1.48222888f,
                                                                     2.710572f,
                                                                     -0.896814466f,
                                                                     0.537100017f,
                                                                     2.06214929f,
                                                                     -2.60774136f,
                                                                     0.626392245f,
                                                                     -2.71927524f,
                                                                     -0.706908584f};
