// Generated by fully_connected_settings_flt.py using PyTorch version 2.10.0+cu128.
const float32_t fully_connected_out_activation_f32_output_ref_data[4] = {-0.699999988f,
                                                                         -0.699999988f,
                                                                         -0.699999988f,
                                                                         -0.699999988f};
