// Generated by generate_test_data.py using tensorflow version 2.10.0 (Keras version 2.10.0).
// Interpreter from tensorflow version 2.10.0 and revision v2.10.0-rc3-6-g359c3cdfc5f.
#pragma once
#include <stdint.h>

const int64_t dw_int16xint8_dilation_biases[8] =
    {3304891, 3902926, -72743, 2093896, 3110820, -3486535, 1440939, -3022670};
