// Generated by batch_matmul_settings_flt.py using PyTorch version 2.10.0+cu128.
const float32_t batch_matmul_et_small_f32_lhs_transposed_tensor[6] =
    {-1.19223011f, 0.657582879f, 0.727761507f, -1.87273502f, -1.27740252f, -1.64384687f};
