// Generated by batch_matmul_settings_flt.py using PyTorch version 2.10.0+cu128.
const float32_t batch_matmul_et_small_f32_output[8] =
    {0.580903649f, 2.43280125f, -2.44782233f, 1.7580483f, 2.54052758f, -0.338131189f, 3.21111798f, 3.0767405f};
