// Generated by batch_matmul_settings_flt.py using PyTorch version 2.10.0+cu128.
const float32_t batch_matmul_et_small_f32_rhs_transposed_tensor[12] = {1.3838129f,
                                                                       0.441429287f,
                                                                       -1.49480832f,
                                                                       -0.0879031345f,
                                                                       1.16619527f,
                                                                       -1.1580441f,
                                                                       1.24959612f,
                                                                       -1.28939128f,
                                                                       0.0153803807f,
                                                                       0.154308945f,
                                                                       -0.169492006f,
                                                                       -1.61685133f};
