// Generated by conv_settings_flt.py using PyTorch version 2.10.0+cu128.
const float16_t conv_match_dilation_golden_f16_biases_data[3] = {(float16_t)-0.3046875f,
                                                                 (float16_t)0.285888672f,
                                                                 (float16_t)0.0186767578f};
