// Generated by conv_settings_flt.py using PyTorch version 2.10.0+cu128.
const float16_t conv_match_dilation_golden_f16_input_data[48] = {
    (float16_t)-0.0835571289f, (float16_t)0.560546875f,    (float16_t)0.0511779785f,  (float16_t)0.366699219f,
    (float16_t)-0.666015625f,  (float16_t)-0.0409240723f,  (float16_t)-0.5078125f,    (float16_t)-0.674804688f,
    (float16_t)0.759277344f,   (float16_t)0.533203125f,    (float16_t)-0.661132812f,  (float16_t)0.993652344f,
    (float16_t)0.637207031f,   (float16_t)0.666503906f,    (float16_t)0.691894531f,   (float16_t)0.18347168f,
    (float16_t)-0.502441406f,  (float16_t)0.482177734f,    (float16_t)0.492675781f,   (float16_t)-0.67578125f,
    (float16_t)-0.133178711f,  (float16_t)-0.00125980377f, (float16_t)-0.973144531f,  (float16_t)0.751953125f,
    (float16_t)0.19128418f,    (float16_t)-0.205078125f,   (float16_t)0.84765625f,    (float16_t)-0.600585938f,
    (float16_t)-0.62109375f,   (float16_t)0.631835938f,    (float16_t)-0.490966797f,  (float16_t)0.112426758f,
    (float16_t)0.48046875f,    (float16_t)-0.338378906f,   (float16_t)0.966308594f,   (float16_t)-0.214477539f,
    (float16_t)-0.421630859f,  (float16_t)0.423095703f,    (float16_t)-0.0955200195f, (float16_t)-0.251464844f,
    (float16_t)0.680664062f,   (float16_t)-0.257324219f,   (float16_t)0.98828125f,    (float16_t)-0.63671875f,
    (float16_t)0.68359375f,    (float16_t)-0.576171875f,   (float16_t)-0.590820312f,  (float16_t)0.591308594f};
