// Generated by conv_settings_flt.py using PyTorch version 2.10.0+cu128.
const float16_t conv_match_dilation_golden_f16_weights_data[12] = {(float16_t)0.383056641f,
                                                                   (float16_t)-0.543457031f,
                                                                   (float16_t)-0.60546875f,
                                                                   (float16_t)0.354980469f,
                                                                   (float16_t)0.735351562f,
                                                                   (float16_t)-0.636230469f,
                                                                   (float16_t)0.556640625f,
                                                                   (float16_t)-0.215576172f,
                                                                   (float16_t)-0.098815918f,
                                                                   (float16_t)-0.659179688f,
                                                                   (float16_t)-0.304443359f,
                                                                   (float16_t)0.569824219f};
