// Generated by RefactoredTestGen/test.py using flatc version 23.5.26
// Interpreter from tflite_micro runtime version 0.dev20240224054047-gcfa4c91.
#pragma once
#include <stdint.h>

const int8_t lstm_one_time_step_s16_cell_gate_input_weights[66] = {
    87,  101, 93,  23,  -94, -70, -51, -59,  -76,  -21, -16, -37, 122, -91,  -112, -111, -46, -68, -38, 15,   -38, 74,
    -97, -9,  -61, -7,  -4,  94,  105, -112, -123, -18, -29, 49,  42,  -13,  34,   83,   106, 60,  -24, 96,   48,  -86,
    66,  97,  -90, -21, 101, -90, -6,  78,   -1,   41,  2,   8,   11,  -123, -79,  -12,  -36, -25, -37, -127, 73,  100};