// Generated by RefactoredTestGen/test.py using flatc version 23.5.26
// Interpreter from tflite_micro runtime version 0.dev20240224054047-gcfa4c91.
#pragma once
#include <stdint.h>

const int8_t lstm_one_time_step_s16_forget_gate_input_weights[66] = {
    25, -38, 56,   -13, 108, -21, 92,   -97, 118,  105, 101, -2, -44,  123, -17, -23, 3,   92,  118, -115, -18, 78,
    27, 103, -108, -41, -8,  37,  -115, 55,  59,   56,  15,  76, -119, 18,  -72, 124, 20,  -8,  -29, 75,   66,  28,
    51, -44, 42,   -13, 101, 41,  -102, 30,  -118, -55, -19, 13, -106, 19,  19,  118, 106, -79, -15, -125, 29,  -109};