// Generated by RefactoredTestGen/test.py using flatc version 23.5.26
// Interpreter from tflite_micro runtime version 0.dev20240224054047-gcfa4c91.
#pragma once
#include <stdint.h>

const int8_t lstm_one_time_step_s16_forget_gate_hidden_weights[9] = {43, 123, -49, -80, 18, -113, 97, 41, 74};