// Generated by RefactoredTestGen/test.py using flatc version 23.5.26
// Interpreter from tflite_micro runtime version 0.dev20240224054047-gcfa4c91.
#pragma once
#include <stdint.h>

const int8_t lstm_one_time_step_s16_input_gate_input_weights[66] = {
    18,   -27, 78,   115,  101, -86, 106,  102, 23,  30,   13,  -90, -89, -67, 51,  11,  -97, -34, -113, 87,  88, 15,
    55,   -55, -116, -11,  -72, 101, -107, 59,  -29, -119, 109, -4,  120, -22, 4,   57,  26,  -87, 79,   19,  81, 28,
    -126, 96,  115,  -100, 27,  34,  14,   78,  84,  28,   -56, -67, 75,  33,  -93, -70, 19,  76,  103,  -47, 35, 69};