// Generated by RefactoredTestGen/test.py using flatc version 23.5.26
// Interpreter from tflite_micro runtime version 0.dev20240224054047-gcfa4c91.
#pragma once
#include <stdint.h>

const int64_t lstm_one_time_step_s16_output_gate_bias[3] = {32739, 16303, 29216};