// Generated by RefactoredTestGen/test.py using flatc version 23.5.26
// Interpreter from tflite_micro runtime version 0.dev20240224054047-gcfa4c91.
#pragma once
#include <stdint.h>

const int8_t lstm_one_time_step_s16_output_gate_input_weights[66] = {
    107, 18,  61,  4,    27,  96,  76,   -43, -48, -63,  -25, 18, -58, -69, 101, -75,  -36, 68,  61,  126, 122, 78,
    90,  -88, -36, 115,  -6,  -28, 99,   96,  55,  -108, -34, 70, 102, 116, 98,  -103, -55, 76,  98,  -78, -53, 81,
    -47, 66,  98,  -128, 103, -98, -124, -25, -37, -19,  -60, 4,  46,  28,  90,  88,   -90, -71, 124, 52,  58,  83};