// Generated by RefactoredTestGen/test.py using flatc version 23.5.26
// Interpreter from tflite_micro runtime version 0.dev20240224054047-gcfa4c91.
#pragma once
#include <stdint.h>

const int16_t lstm_one_time_step_s16_output[9] = {2054, 0, 0, 1138, 129, 0, -61, -2801, 225};