// Generated by pooling_settings_flt.py using PyTorch version 2.10.0+cu128.
const float16_t avgpooling_f16_global_output_ref[64] = {
    (float16_t)0.431884766f,   (float16_t)-0.609375f,     (float16_t)0.20715332f,    (float16_t)0.437011719f,
    (float16_t)-0.0850830078f, (float16_t)0.368408203f,   (float16_t)-0.0322570801f, (float16_t)0.23059082f,
    (float16_t)0.0767211914f,  (float16_t)-0.0109710693f, (float16_t)0.160766602f,   (float16_t)-0.666015625f,
    (float16_t)0.256347656f,   (float16_t)0.0915527344f,  (float16_t)-0.0246429443f, (float16_t)0.299072266f,
    (float16_t)-0.120239258f,  (float16_t)0.421386719f,   (float16_t)0.533203125f,   (float16_t)-0.134887695f,
    (float16_t)-0.331787109f,  (float16_t)-0.0963745117f, (float16_t)-0.256103516f,  (float16_t)-0.159179688f,
    (float16_t)-0.418701172f,  (float16_t)-0.328857422f,  (float16_t)0.025604248f,   (float16_t)-0.223388672f,
    (float16_t)0.462158203f,   (float16_t)0.0320129395f,  (float16_t)0.225463867f,   (float16_t)-0.0393676758f,
    (float16_t)0.363769531f,   (float16_t)-0.18347168f,   (float16_t)-0.345703125f,  (float16_t)0.16027832f,
    (float16_t)0.0443115234f,  (float16_t)-0.101196289f,  (float16_t)-0.413818359f,  (float16_t)0.260986328f,
    (float16_t)0.252197266f,   (float16_t)0.216308594f,   (float16_t)0.3125f,        (float16_t)0.490234375f,
    (float16_t)-0.837402344f,  (float16_t)0.221923828f,   (float16_t)-0.0914306641f, (float16_t)-0.0165557861f,
    (float16_t)-0.280273438f,  (float16_t)-0.140014648f,  (float16_t)0.193847656f,   (float16_t)0.180786133f,
    (float16_t)-0.674316406f,  (float16_t)0.129760742f,   (float16_t)0.347412109f,   (float16_t)0.216064453f,
    (float16_t)0.131347656f,   (float16_t)-0.218139648f,  (float16_t)-0.0665893555f, (float16_t)-0.174194336f,
    (float16_t)0.23034668f,    (float16_t)0.220947266f,   (float16_t)-0.075012207f,  (float16_t)-0.413818359f};
