var annotated_dup =
[
    [ "arm_nn_double", "group__genPrivTypes.html#structarm__nn__double", "group__genPrivTypes_structarm__nn__double" ],
    [ "arm_nn_long_long", "group__genPrivTypes.html#unionarm__nn__long__long", "group__genPrivTypes_unionarm__nn__long__long" ],
    [ "arm_nnword", "group__genPrivTypes.html#unionarm__nnword", "group__genPrivTypes_unionarm__nnword" ],
    [ "cmsis_nn_activation", "group__genPubTypes.html#structcmsis__nn__activation", "group__genPubTypes_structcmsis__nn__activation" ],
    [ "cmsis_nn_bias_data", "group__genPubTypes.html#structcmsis__nn__bias__data", "group__genPubTypes_structcmsis__nn__bias__data" ],
    [ "cmsis_nn_context", "group__genPubTypes.html#structcmsis__nn__context", "group__genPubTypes_structcmsis__nn__context" ],
    [ "cmsis_nn_conv_params", "group__genPubTypes.html#structcmsis__nn__conv__params", "group__genPubTypes_structcmsis__nn__conv__params" ],
    [ "cmsis_nn_dims", "group__genPubTypes.html#structcmsis__nn__dims", "group__genPubTypes_structcmsis__nn__dims" ],
    [ "cmsis_nn_dw_conv_params", "group__genPubTypes.html#structcmsis__nn__dw__conv__params", "group__genPubTypes_structcmsis__nn__dw__conv__params" ],
    [ "cmsis_nn_fc_params", "group__genPubTypes.html#structcmsis__nn__fc__params", "group__genPubTypes_structcmsis__nn__fc__params" ],
    [ "cmsis_nn_lstm_context", "group__genPubTypes.html#structcmsis__nn__lstm__context", "group__genPubTypes_structcmsis__nn__lstm__context" ],
    [ "cmsis_nn_lstm_dims", "group__genPubTypes.html#structcmsis__nn__lstm__dims", "group__genPubTypes_structcmsis__nn__lstm__dims" ],
    [ "cmsis_nn_lstm_gate", "group__genPubTypes.html#structcmsis__nn__lstm__gate", "group__genPubTypes_structcmsis__nn__lstm__gate" ],
    [ "cmsis_nn_lstm_params", "group__genPubTypes.html#structcmsis__nn__lstm__params", "group__genPubTypes_structcmsis__nn__lstm__params" ],
    [ "cmsis_nn_per_channel_quant_params", "group__genPubTypes.html#structcmsis__nn__per__channel__quant__params", "group__genPubTypes_structcmsis__nn__per__channel__quant__params" ],
    [ "cmsis_nn_per_tensor_quant_params", "group__genPubTypes.html#structcmsis__nn__per__tensor__quant__params", "group__genPubTypes_structcmsis__nn__per__tensor__quant__params" ],
    [ "cmsis_nn_pool_params", "group__genPubTypes.html#structcmsis__nn__pool__params", "group__genPubTypes_structcmsis__nn__pool__params" ],
    [ "cmsis_nn_scaling", "group__genPubTypes.html#structcmsis__nn__scaling", "group__genPubTypes_structcmsis__nn__scaling" ],
    [ "cmsis_nn_softmax_lut_s16", "group__genPubTypes.html#structcmsis__nn__softmax__lut__s16", "group__genPubTypes_structcmsis__nn__softmax__lut__s16" ],
    [ "cmsis_nn_svdf_params", "group__genPubTypes.html#structcmsis__nn__svdf__params", "group__genPubTypes_structcmsis__nn__svdf__params" ],
    [ "cmsis_nn_tile", "group__genPubTypes.html#structcmsis__nn__tile", "group__genPubTypes_structcmsis__nn__tile" ],
    [ "cmsis_nn_transpose_conv_params", "group__genPubTypes.html#structcmsis__nn__transpose__conv__params", "group__genPubTypes_structcmsis__nn__transpose__conv__params" ]
];