// Generated by pooling_settings_flt.py using PyTorch version 2.10.0+cu128.
const float16_t avgpooling_f16_2_input_tensor[9] = {(float16_t)-0.257324219f,
                                                    (float16_t)5.93359375f,
                                                    (float16_t)3.98632812f,
                                                    (float16_t)-0.883300781f,
                                                    (float16_t)7.15234375f,
                                                    (float16_t)3.27734375f,
                                                    (float16_t)-2.1875f,
                                                    (float16_t)6.83984375f,
                                                    (float16_t)6.61328125f};
