// Generated by pooling_settings_flt.py using PyTorch version 2.10.0+cu128.
const float16_t avgpooling_f16_2_output_ref[9] = {(float16_t)0.0f,
                                                  (float16_t)6.0f,
                                                  (float16_t)3.63085938f,
                                                  (float16_t)0.0f,
                                                  (float16_t)6.0f,
                                                  (float16_t)4.625f,
                                                  (float16_t)0.0f,
                                                  (float16_t)6.0f,
                                                  (float16_t)4.9453125f};
