// Generated by generate_test_data.py using tensorflow version 2.10.0 (Keras version 2.10.0).
// Interpreter from tensorflow version 2.10.0 and revision v2.10.0-rc3-6-g359c3cdfc5f.
#pragma once
#include <stdint.h>

const int32_t int16xint8_dilation_2_output_mult[4] = {1566522842, 1222196941, 1511961819, 1495244605};
