// Generated by generate_test_data.py using tensorflow version 2.10.0 (Keras version 2.10.0).
// Interpreter from tensorflow version 2.10.0 and revision v2.10.0-rc3-6-g359c3cdfc5f.
#pragma once
#include <stdint.h>

const int16_t int16xint8_output_ref[48] = {
    -6939, -7913, -10478, 2083,  4909,   -7615, -12139, 56,   -2031,  -239,  -1461, 12852, -5087, -4686, -6984,  4797,
    -7156, -9860, 2349,   4743,  -10003, -1689, -4330,  159,  14093,  -5456, -8866, -1445, 2552,  3120,  -13335, -10211,
    -4546, -7367, 95,     -1593, -9522,  6399,  -8913,  3013, -10355, 13874, 8880,  8500,  -4208, 703,   -7717,  2509};
