// Generated by test_settings.py using tensorflow version 2.14.0 (Keras version 2.14.0).
// Interpreter from tensorflow version 2.14.0 and revision v2.14.0-rc1-21-g4dacf3f368e.
#pragma once
#include <stdint.h>

const int16_t int16xint8_output_ref[40] = {180,  471,  855,  475,   -60,  327,  298,  -198, 147,  108,
                                           535,  -101, -101, -235,  -535, -188, -547, -944, -548, -328,
                                           -895, -624, -496, -1029, -809, -671, -453, -410, -266, -563,
                                           -818, -799, -512, -485,  -639, -968, -102, -9,   -414, -314};
