// Generated by depthwise_conv_settings_flt.py using PyTorch version 2.10.0+cu128.
const float32_t depthwise_kernel_3x3_f32_biases_data[5] = {0.157603428f,
                                                           -0.476453811f,
                                                           -0.38180697f,
                                                           0.141017616f,
                                                           0.445060611f};
