// Generated by depthwise_conv_settings_flt.py using PyTorch version 2.10.0+cu128.
const float32_t depthwise_match_stride2pad1_f32_weights_data[9] = {-0.0761408731f,
                                                                   -0.250961989f,
                                                                   -0.653435647f,
                                                                   -0.371298999f,
                                                                   -0.310764402f,
                                                                   -0.326433122f,
                                                                   0.14162825f,
                                                                   0.579869986f,
                                                                   0.184552491f};
