// Generated by fully_connected_settings_flt.py using PyTorch version 2.10.0+cu128.
const float16_t fully_connected_match_basic_f16_biases_data[6] = {(float16_t)-0.428222656f,
                                                                  (float16_t)-0.732910156f,
                                                                  (float16_t)0.489257812f,
                                                                  (float16_t)-0.588378906f,
                                                                  (float16_t)-0.290771484f,
                                                                  (float16_t)0.502929688f};
