// Generated by fully_connected_settings_flt.py using PyTorch version 2.10.0+cu128.
const float16_t fully_connected_match_basic_f16_input_data[60] = {
    (float16_t)-0.166992188f, (float16_t)0.767089844f,  (float16_t)-1.11914062f,  (float16_t)-0.146362305f,
    (float16_t)-1.47558594f,  (float16_t)-0.241088867f, (float16_t)-1.47363281f,  (float16_t)0.875488281f,
    (float16_t)-1.68554688f,  (float16_t)0.403076172f,  (float16_t)-0.126831055f, (float16_t)1.58300781f,
    (float16_t)1.04785156f,   (float16_t)-0.204223633f, (float16_t)-1.04296875f,  (float16_t)1.53027344f,
    (float16_t)1.60839844f,   (float16_t)1.41113281f,   (float16_t)0.0642089844f, (float16_t)1.16894531f,
    (float16_t)1.27148438f,   (float16_t)0.610839844f,  (float16_t)-0.775878906f, (float16_t)1.82128906f,
    (float16_t)0.489257812f,  (float16_t)-0.93359375f,  (float16_t)-0.7734375f,   (float16_t)-0.287841797f,
    (float16_t)-1.85351562f,  (float16_t)1.22949219f,   (float16_t)1.21875f,      (float16_t)1.15332031f,
    (float16_t)-0.856933594f, (float16_t)1.77441406f,   (float16_t)-1.0859375f,   (float16_t)1.8046875f,
    (float16_t)1.05371094f,   (float16_t)-0.640625f,    (float16_t)-0.530273438f, (float16_t)-0.294433594f,
    (float16_t)-1.07617188f,  (float16_t)-1.33496094f,  (float16_t)1.3203125f,    (float16_t)-1.67578125f,
    (float16_t)1.640625f,     (float16_t)1.24023438f,   (float16_t)1.40332031f,   (float16_t)-1.95214844f,
    (float16_t)1.56054688f,   (float16_t)-1.27148438f,  (float16_t)-1.9296875f,   (float16_t)-0.79296875f,
    (float16_t)-0.449462891f, (float16_t)-1.80078125f,  (float16_t)1.87109375f,   (float16_t)0.863769531f,
    (float16_t)0.81640625f,   (float16_t)1.4140625f,    (float16_t)-1.72265625f,  (float16_t)-1.06445312f};
