// Generated by generate_test_data.py using tensorflow version 2.10.0 (Keras version 2.10.0).
// Interpreter from tensorflow version 2.10.0 and revision v2.10.0-rc3-6-g359c3cdfc5f.
#pragma once
#include <stdint.h>

const int8_t depthwise_dilation_input[90] = {
    72,  28,  -30, -110, 13,  -96, 34,   -95, 94,   95,   -98,  -91,  21,  10, -109, -69, 24,   105,
    -17, 59,  -30, -114, -81, 0,   104,  -8,  -30,  -58,  -40,  -71,  -63, 95, 53,   -9,  102,  -53,
    47,  59,  -79, -85,  124, -79, 44,   38,  -125, 59,   -29,  -104, -44, 25, -8,   -95, -121, 16,
    117, 13,  47,  -15,  -38, 47,  -112, 92,  68,   -23,  19,   22,   104, -5, -117, 82,  13,   -69,
    9,   -99, -85, 38,   -36, -8,  54,   88,  34,   -120, -123, 17,   21,  55, -115, 104, 66,   -11};
