// Generated by generate_test_data.py using tensorflow version 2.10.0 (Keras version 2.10.0).
// Interpreter from tensorflow version 2.10.0 and revision upstream/v2.10.0-0-g359c3cdfc5f.
#pragma once
#include <stdint.h>

const int8_t depthwise_dilation_input[90] = {
    26,   -12, -106, 44,   -120, -86,  -44, -65, 57,  81,  3,   14,   -36,  -57, 119, -107, -7,   -86,
    -113, 64,  6,    9,    105,  -67,  47,  -15, 118, 70,  -5,  -37,  94,   -16, -13, 76,   93,   -28,
    -51,  -61, -16,  26,   107,  -104, 33,  19,  25,  -32, -9,  -38,  49,   -52, -45, 77,   36,   115,
    32,   104, -47,  -61,  109,  -23,  59,  21,  -37, -95, -61, -119, -115, 50,  -64, -57,  -103, -102,
    48,   -84, 124,  -119, 103,  -67,  75,  75,  -67, -28, 114, 28,   67,   42,  43,  -74,  -39,  -74};
