// Generated by generate_test_data.py using tensorflow version 2.10.0 (Keras version 2.10.0).
// Interpreter from tensorflow version 2.10.0 and revision upstream/v2.10.0-0-g359c3cdfc5f.
#pragma once
#include <stdint.h>

const int8_t depthwise_dilation_output_ref[81] = {
    14,  -46, 46,  -26, -10, -18, -32, -35, 17,  -18, -39, 44,  20,  -34, 26, -54, -47, 24,  20, -32, 33,
    -20, -41, 0,   -64, -54, -35, -8,  -2,  19,  -16, 44,  -31, -40, -49, 19, -6,  -10, 40,  8,  25,  42,
    -58, -48, -20, -32, -36, 59,  0,   -14, 1,   -53, -18, -20, 10,  -59, 26, -35, -18, -14, -9, -36, 3,
    -9,  -64, 54,  -7,  3,   2,   -50, 5,   -18, -22, -42, 55,  1,   -4,  -7, -35, -14, 4};
