// Generated by generate_test_data.py using tensorflow version 2.10.0 (Keras version 2.10.0).
// Interpreter from tensorflow version 2.10.0 and revision upstream/v2.10.0-0-g359c3cdfc5f.
#pragma once
#include <stdint.h>

const int32_t depthwise_dilation_output_mult[9] =
    {1289240074, 1261132178, 1336459652, 1386272717, 1262565343, 1381060732, 1370789449, 1332290030, 1419854710};
