// Generated by generate_test_data.py using tensorflow version 2.10.0 (Keras version 2.10.0).
// Interpreter from tensorflow version 2.10.0 and revision v2.10.0-rc3-6-g359c3cdfc5f.
#pragma once
#include <stdint.h>

const int32_t depthwise_dilation_output_mult[9] =
    {1253719158, 1559745097, 1204360159, 1085898488, 1263590957, 1085898488, 1095770288, 1233975558, 1994104433};
