// Generated by conv_settings_flt.py using PyTorch version 2.10.0+cu128.
const float32_t conv_match_basic_f32_weights_data[8] = {-0.441934943f,
                                                        -0.39759472f,
                                                        0.734636545f,
                                                        0.155938148f,
                                                        -0.02113037f,
                                                        -0.0182458982f,
                                                        -0.618008554f,
                                                        -0.665666223f};
