// Generated by test_settings.py using tensorflow version 2.11.0 (Keras version 2.11.0).
// Interpreter from tflite_runtime version 2.16.0 and revision 0.6.0-154906-gb2493fdf794.
#pragma once
#define MAXPOOLING_OUT_CH 8
#define MAXPOOLING_IN_CH 8
#define MAXPOOLING_INPUT_W 22
#define MAXPOOLING_INPUT_H 12
#define MAXPOOLING_DST_SIZE 144
#define MAXPOOLING_INPUT_SIZE 2112
#define MAXPOOLING_OUT_ACTIVATION_MIN -128
#define MAXPOOLING_OUT_ACTIVATION_MAX 127
#define MAXPOOLING_INPUT_BATCHES 2
#define MAXPOOLING_FILTER_X 6
#define MAXPOOLING_FILTER_Y 5
#define MAXPOOLING_STRIDE_X 9
#define MAXPOOLING_STRIDE_Y 5
#define MAXPOOLING_PAD_X 1
#define MAXPOOLING_PAD_Y 1
#define MAXPOOLING_OUTPUT_W 3
#define MAXPOOLING_OUTPUT_H 3
