// Generated by generate_test_data.py using tensorflow version 2.10.0 (Keras version 2.10.0).
// Interpreter from tensorflow version 2.10.0 and revision v2.10.0-rc3-6-g359c3cdfc5f.
#pragma once
#include <stdint.h>

const int64_t dw_int16xint8_mult4_biases[8] =
    {223178, -4314998, 3439509, 1837855, -3006016, 2312206, -2798955, -2952197};
