// Generated by generate_test_data.py using tensorflow version 2.10.0 (Keras version 2.10.0).
// Interpreter from tensorflow version 2.10.0 and revision v2.10.0-rc3-6-g359c3cdfc5f.
#pragma once
#include <stdint.h>

const int16_t dw_int16xint8_mult4_input[40] = {
    -17485, 21819, -26312, -14446, 32326,  26482,  -4390, -18621, -32186, 15037,  -7461,  30312,  -18990, 15605,
    -20064, 3712,  -25567, -22216, -7666,  4861,   30918, -1954,  14950,  6892,   -21628, -10369, 10901,  31979,
    -24233, 14297, 15444,  -30175, -32061, -29227, 28826, -9789,  5445,   -32022, 19913,  9312};
