// Generated by generate_test_data.py using tensorflow version 2.10.0 (Keras version 2.10.0).
// Interpreter from tensorflow version 2.10.0 and revision v2.10.0-rc3-6-g359c3cdfc5f.
#pragma once
#include <stdint.h>

const int16_t dw_int16xint8_mult4_output_ref[8] = {14964, 113, 4445, -17539, -15735, 3848, -3806, 14080};
