// Generated by generate_test_data.py using tensorflow version 2.10.0 (Keras version 2.10.0).
// Interpreter from tensorflow version 2.10.0 and revision v2.10.0-rc3-6-g359c3cdfc5f.
#pragma once
#include <stdint.h>

const int64_t fully_connected_int16_biases[11] =
    {-1411210, 2069961, -3545380, -1414388, -4053207, -3264892, -938857, 583225, 761105, -3288542, 3302019};
