// Generated by generate_test_data.py using tensorflow version 2.10.0 (Keras version 2.10.0).
// Interpreter from tensorflow version 2.10.0 and revision v2.10.0-rc3-6-g359c3cdfc5f.
#pragma once
#include <stdint.h>

const int32_t depthwise_sub_block_biases[9] = {26347, 2944, -19652, 5051, 35483, -36527, 28607, 29176, -60420};
