// Generated by generate_test_data.py using tensorflow version 2.10.0 (Keras version 2.10.0).
// Interpreter from tensorflow version 2.10.0 and revision v2.10.0-rc3-6-g359c3cdfc5f.
#pragma once
#include <stdint.h>

const int32_t depthwise_sub_block_output_mult[9] =
    {1827537650, 1703636848, 1812050049, 1688149247, 1781074849, 1331934207, 1858512967, 1719124448, 2075339371};
