// Generated by generate_test_data.py using tensorflow version 2.10.0 (Keras version 2.10.0).
// Interpreter from tensorflow version 2.10.0 and revision v2.10.0-rc3-6-g359c3cdfc5f.
#pragma once
#include <stdint.h>

const int8_t depthwise_null_bias_0_input[40] = {
    -97,  -113, 118, 69, 39,   -32, -1,   -79, -30, -8, 46,   -13, 82,  -19, 15, 105, 94,  -56, 35, 55,
    -122, -105, 70,  33, -128, -87, -109, 50,  2,   78, -113, 113, -50, -33, 19, -6,  -38, 122, 18, -121};
