// Generated by generate_test_data.py using tensorflow version 2.10.0 (Keras version 2.10.0).
// Interpreter from tensorflow version 2.10.0 and revision v2.10.0-rc3-6-g359c3cdfc5f.
#pragma once
#include <stdint.h>

const int8_t depthwise_null_bias_0_output_ref[40] = {
    1,  -91,  52, -57, 65,  -99, 62, 59,   55, -110, 97, -2,  -15, -128, 85, 36,  38, -128, -13, -56,
    49, -107, 29, 62,  -26, -96, 29, -128, 3,  -16,  41, -13, 14,  -54,  22, -96, 17, -17,  13,  -15};
