// Generated by generate_test_data.py using tensorflow version 2.17.0 (Keras version 3.5.0).
// Interpreter from tensorflow version 2.17.0 and revision v2.17.0-rc1-2-gad6d8cc177d.
#pragma once
#include <stdint.h>

const int8_t transpose_default_input_tensor[72] = {
    -63, -125, -114, -125, 62,  -60,  -60, -61, 77,  -83, 61,   -59, -32, -110, 116, 27,  -32, -93,
    28,  -13,  -38,  64,   121, -121, 117, -37, 113, -86, 120,  64,  52,  105,  16,  -11, 117, 87,
    -51, -4,   34,   -76,  0,   -20,  38,  -57, -96, -50, -103, -74, -22, 118,  -59, 97,  106, -96,
    60,  -17,  -91,  -15,  -50, 103,  45,  -98, 77,  97,  -119, 123, 9,   61,   -43, -94, 32,  88};
