// Generated by generate_test_data.py using tensorflow version 2.17.0 (Keras version 3.5.0).
// Interpreter from tensorflow version 2.17.0 and revision v2.17.0-rc1-2-gad6d8cc177d.
#pragma once
#include <stdint.h>

const int8_t transpose_default_output[72] = {
    -63,  28,  -51, 60,  -60, 117, 38,  45,   -32,  52,  -22, 9,   -114, -38,  34,  -91, 77,  113,
    -96,  77,  116, 16,  -59, -43, 62,  121,  0,    -50, 61,  120, -103, -119, -32, 117, 106, 32,
    -125, -13, -4,  -17, -61, -37, -57, -98,  -110, 105, 118, 61,  -125, 64,   -76, -15, -83, -86,
    -50,  97,  27,  -11, 97,  -94, -60, -121, -20,  103, -59, 64,  -74,  123,  -93, 87,  -96, 88};
