// Generated by test_settings.py using tensorflow version 2.11.0 (Keras version 2.11.0).
// Interpreter from tflite_runtime version 2.16.0 and revision 0.6.0-154906-gb2493fdf794.
#pragma once
#include <stdint.h>

const int16_t avgpooling_int16_1_output_ref[30] = {
    27192, -2386, 23736, 6052, 20092, 12962, 5913, 1851,  16431,  8809, -1394,  12620,  23113, -15952, 14291,
    72,    1007,  32440, 1392, 4414,  19817, 2381, 23500, -28769, 434,  -19722, -31498, 10483, -19374, 18529};
