// Generated by conv_settings_flt.py using PyTorch version 2.10.0+cu128.
const float32_t conv_match_1x1_stride_x_y_1_f32_biases_data[5] = {0.195574954f,
                                                                  -0.267665327f,
                                                                  -0.0159980971f,
                                                                  0.376846254f,
                                                                  -0.264294446f};
