// Generated by fully_connected_settings_flt.py using PyTorch version 2.10.0+cu128.
const float32_t fully_connected_null_bias_f32_output_ref_data[10] = {1.21968091f,
                                                                     0.613622069f,
                                                                     -3.91991735f,
                                                                     3.82579422f,
                                                                     5.64623737f,
                                                                     -1.7434901f,
                                                                     3.51101136f,
                                                                     5.28429985f,
                                                                     2.36786151f,
                                                                     1.15221679f};
