// Generated by pooling_settings_flt.py using PyTorch version 2.10.0+cu128.
const float16_t avgpooling_match_3_f16_output_ref[10] = {(float16_t)3.40234375f,
                                                         (float16_t)4.84765625f,
                                                         (float16_t)1.21289062f,
                                                         (float16_t)5.6015625f,
                                                         (float16_t)5.32421875f,
                                                         (float16_t)2.921875f,
                                                         (float16_t)4.421875f,
                                                         (float16_t)-1.8203125f,
                                                         (float16_t)-2.93945312f,
                                                         (float16_t)-5.8671875f};
