// Generated by fully_connected_settings_flt.py using PyTorch version 2.10.0+cu128.
const float16_t fully_connected_out_activation_f16_biases_data[4] = {(float16_t)0.211791992f,
                                                                     (float16_t)0.455810547f,
                                                                     (float16_t)0.0715942383f,
                                                                     (float16_t)0.588378906f};
