// Generated by fully_connected_settings_flt.py using PyTorch version 2.10.0+cu128.
const float16_t fully_connected_out_activation_f16_input_data[10] = {(float16_t)1.76171875f,
                                                                     (float16_t)-0.470214844f,
                                                                     (float16_t)0.206298828f,
                                                                     (float16_t)2.09765625f,
                                                                     (float16_t)2.3671875f,
                                                                     (float16_t)-2.7421875f,
                                                                     (float16_t)-2.61132812f,
                                                                     (float16_t)0.199584961f,
                                                                     (float16_t)0.829589844f,
                                                                     (float16_t)2.86132812f};
