// Generated by fully_connected_settings_flt.py using PyTorch version 2.10.0+cu128.
const float16_t fully_connected_out_activation_f16_output_ref_data[4] = {(float16_t)-0.700195312f,
                                                                         (float16_t)-0.700195312f,
                                                                         (float16_t)-0.700195312f,
                                                                         (float16_t)-0.700195312f};
