// Generated by fully_connected_settings_flt.py using PyTorch version 2.10.0+cu128.
const float16_t fully_connected_out_activation_f16_weights_data[40] = {
    (float16_t)-1.57714844f,  (float16_t)-0.5078125f,    (float16_t)0.895507812f,  (float16_t)0.0718994141f,
    (float16_t)-0.301513672f, (float16_t)0.0595092773f,  (float16_t)-0.506347656f, (float16_t)-1.27636719f,
    (float16_t)-0.992675781f, (float16_t)-1.93847656f,   (float16_t)-1.68847656f,  (float16_t)-1.31152344f,
    (float16_t)-1.65527344f,  (float16_t)-1.265625f,     (float16_t)0.252929688f,  (float16_t)-0.570800781f,
    (float16_t)-1.68066406f,  (float16_t)-1.16992188f,   (float16_t)0.0457763672f, (float16_t)-1.50488281f,
    (float16_t)-1.8515625f,   (float16_t)0.4140625f,     (float16_t)-0.9921875f,   (float16_t)-1.53222656f,
    (float16_t)1.20214844f,   (float16_t)-1.83300781f,   (float16_t)-0.759765625f, (float16_t)-1.11328125f,
    (float16_t)0.0697021484f, (float16_t)-1.31640625f,   (float16_t)-1.29394531f,  (float16_t)0.139282227f,
    (float16_t)1.26074219f,   (float16_t)1.05761719f,    (float16_t)1.6953125f,    (float16_t)1.24316406f,
    (float16_t)1.65332031f,   (float16_t)-0.0662231445f, (float16_t)0.747558594f,  (float16_t)-1.74804688f};
