// Generated by generate_test_data.py using tensorflow version 2.10.0 (Keras version 2.10.0).
// Interpreter from tensorflow version 2.10.0 and revision v2.10.0-rc3-6-g359c3cdfc5f.
#pragma once
#include <stdint.h>

const int32_t depthwise_kernel_3x3_null_bias_output_mult[5] = {1864971143,
                                                               1710982645,
                                                               1086474004,
                                                               2104508734,
                                                               2070289096};
