// Generated by generate_test_data.py using tensorflow version 2.10.0 (Keras version 2.10.0).
// Interpreter from tensorflow version 2.10.0 and revision v2.10.0-rc3-6-g359c3cdfc5f.
#pragma once
#include <stdint.h>

const int8_t depthwise_kernel_3x3_null_bias_output_ref[30] = {39,  17, 67, 77, 116, 70, 25, 121, 104, 53,
                                                              -58, 33, 11, 26, 42,  20, 10, 42,  127, 103,
                                                              -14, 34, 39, 78, 93,  3,  48, -20, 71,  126};
