// Generated by generate_test_data.py using tensorflow version 2.10.0 (Keras version 2.10.0).
// Interpreter from tensorflow version 2.10.0 and revision v2.10.0-rc3-6-g359c3cdfc5f.
#pragma once
#include <stdint.h>

const int8_t depthwise_kernel_3x3_null_bias_weights[45] = {
    -117, -86,  -127, -127, -88, -103, -6,   -38, 83,  -80,  -127, -104, 118, 89,   29,
    29,   -94,  -38,  0,    113, -40,  -102, -91, -11, 59,   -33,  19,   10,  -114, -24,
    -5,   -127, 102,  46,   -2,  -36,  52,   44,  62,  -127, -50,  36,   -94, -51,  -8};
