// Generated by generate_test_data.py using tensorflow version 2.10.0 (Keras version 2.10.0).
// Interpreter from tensorflow version 2.10.0 and revision v2.10.0-rc3-6-g359c3cdfc5f.
#pragma once
#include <stdint.h>

const int32_t depthwise_x_stride_biases[9] = {-12312, 6920, -5304, 28067, 32672, 30586, -10532, -22380, 1825};
