// Generated by generate_test_data.py using tensorflow version 2.10.0 (Keras version 2.10.0).
// Interpreter from tensorflow version 2.10.0 and revision v2.10.0-rc3-6-g359c3cdfc5f.
#pragma once
#include <stdint.h>

const int32_t depthwise_x_stride_output_mult[9] =
    {1991570884, 1925733739, 1909274483, 1975111629, 1859896718, 1777600441, 2024489395, 2024489395, 1168607622};
