// Generated by generate_test_data.py using tensorflow version 2.10.0 (Keras version 2.10.0).
// Interpreter from tensorflow version 2.10.0 and revision v2.10.0-rc3-6-g359c3cdfc5f.
#pragma once
#include <stdint.h>

const int8_t depthwise_x_stride_weights[36] = {-44,  -127, -35,  49,  -93, -115, -127, -64, 127, 21,   61, -86,
                                               28,   127,  -127, -50, 127, -39,  -127, -9,  124, -127, 51, 76,
                                               -124, -38,  116,  40,  -79, 127,  -96,  -91, -76, -90,  50, -47};
