/*
 * SPDX-FileCopyrightText: Copyright 2022 Arm Limited and/or its affiliates <open-source-office@arm.com>
 *
 * SPDX-License-Identifier: Apache-2.0
 *
 * Licensed under the Apache License, Version 2.0 (the License); you may
 * not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an AS IS BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#include "../TestData/ds_cnn_l/ds_cnn_l_model.h"

#define CONV_0_OUT_CH (276)
#define CONV_0_IN_CH (1)
#define CONV_0_INPUT_W (10)
#define CONV_0_INPUT_H (49)
#define CONV_0_FILTER_W (4)
#define CONV_0_FILTER_H (10)
#define CONV_0_STRIDE_W (1)
#define CONV_0_STRIDE_H (2)
#define CONV_0_PAD_W (1)
#define CONV_0_PAD_H (4)
#define CONV_0_OUTPUT_W (10)
#define CONV_0_OUTPUT_H (25)
#define CONV_0_INPUT_OFFSET (-96)
#define CONV_0_INPUT_SIZE (NA)
#define CONV_0_OUT_ACTIVATION_MIN (-128)
#define CONV_0_OUT_ACTIVATION_MAX (127)
#define CONV_0_INPUT_BATCHES (1)
#define CONV_0_DILATION_W (1)
#define CONV_0_DILATION_H (1)
#define CONV_0_OUTPUT_OFFSET (-128)

#define DW_CONV_1_OUT_CH (276)
#define DW_CONV_1_IN_CH (276)
#define DW_CONV_1_INPUT_W (10)
#define DW_CONV_1_INPUT_H (25)
#define DW_CONV_1_FILTER_W (3)
#define DW_CONV_1_FILTER_H (3)
#define DW_CONV_1_STRIDE_W (2)
#define DW_CONV_1_STRIDE_H (2)
#define DW_CONV_1_PAD_W (0)
#define DW_CONV_1_PAD_H (1)
#define DW_CONV_1_OUTPUT_W (5)
#define DW_CONV_1_OUTPUT_H (13)
#define DW_CONV_1_INPUT_OFFSET (128)
#define DW_CONV_1_INPUT_SIZE (NA)
#define DW_CONV_1_OUT_ACTIVATION_MIN (-128)
#define DW_CONV_1_OUT_ACTIVATION_MAX (127)
#define DW_CONV_1_INPUT_BATCHES (1)
#define DW_CONV_1_DILATION_W (1)
#define DW_CONV_1_DILATION_H (1)
#define DW_CONV_1_OUTPUT_OFFSET (-128)

#define CONV_2_OUT_CH (276)
#define CONV_2_IN_CH (276)
#define CONV_2_INPUT_W (5)
#define CONV_2_INPUT_H (13)
#define CONV_2_FILTER_W (1)
#define CONV_2_FILTER_H (1)
#define CONV_2_STRIDE_W (1)
#define CONV_2_STRIDE_H (1)
#define CONV_2_PAD_W (0)
#define CONV_2_PAD_H (0)
#define CONV_2_OUTPUT_W (5)
#define CONV_2_OUTPUT_H (13)
#define CONV_2_INPUT_OFFSET (128)
#define CONV_2_INPUT_SIZE (NA)
#define CONV_2_OUT_ACTIVATION_MIN (-128)
#define CONV_2_OUT_ACTIVATION_MAX (127)
#define CONV_2_INPUT_BATCHES (1)
#define CONV_2_DILATION_W (1)
#define CONV_2_DILATION_H (1)
#define CONV_2_OUTPUT_OFFSET (-128)

#define DW_CONV_3_OUT_CH (276)
#define DW_CONV_3_IN_CH (276)
#define DW_CONV_3_INPUT_W (5)
#define DW_CONV_3_INPUT_H (13)
#define DW_CONV_3_FILTER_W (3)
#define DW_CONV_3_FILTER_H (3)
#define DW_CONV_3_STRIDE_W (1)
#define DW_CONV_3_STRIDE_H (1)
#define DW_CONV_3_PAD_W (1)
#define DW_CONV_3_PAD_H (1)
#define DW_CONV_3_OUTPUT_W (5)
#define DW_CONV_3_OUTPUT_H (13)
#define DW_CONV_3_INPUT_OFFSET (128)
#define DW_CONV_3_INPUT_SIZE (NA)
#define DW_CONV_3_OUT_ACTIVATION_MIN (-128)
#define DW_CONV_3_OUT_ACTIVATION_MAX (127)
#define DW_CONV_3_INPUT_BATCHES (1)
#define DW_CONV_3_DILATION_W (1)
#define DW_CONV_3_DILATION_H (1)
#define DW_CONV_3_OUTPUT_OFFSET (-128)

#define CONV_4_OUT_CH (276)
#define CONV_4_IN_CH (276)
#define CONV_4_INPUT_W (5)
#define CONV_4_INPUT_H (13)
#define CONV_4_FILTER_W (1)
#define CONV_4_FILTER_H (1)
#define CONV_4_STRIDE_W (1)
#define CONV_4_STRIDE_H (1)
#define CONV_4_PAD_W (0)
#define CONV_4_PAD_H (0)
#define CONV_4_OUTPUT_W (5)
#define CONV_4_OUTPUT_H (13)
#define CONV_4_INPUT_OFFSET (128)
#define CONV_4_INPUT_SIZE (NA)
#define CONV_4_OUT_ACTIVATION_MIN (-128)
#define CONV_4_OUT_ACTIVATION_MAX (127)
#define CONV_4_INPUT_BATCHES (1)
#define CONV_4_DILATION_W (1)
#define CONV_4_DILATION_H (1)
#define CONV_4_OUTPUT_OFFSET (-128)

#define DW_CONV_5_OUT_CH (276)
#define DW_CONV_5_IN_CH (276)
#define DW_CONV_5_INPUT_W (5)
#define DW_CONV_5_INPUT_H (13)
#define DW_CONV_5_FILTER_W (3)
#define DW_CONV_5_FILTER_H (3)
#define DW_CONV_5_STRIDE_W (1)
#define DW_CONV_5_STRIDE_H (1)
#define DW_CONV_5_PAD_W (1)
#define DW_CONV_5_PAD_H (1)
#define DW_CONV_5_OUTPUT_W (5)
#define DW_CONV_5_OUTPUT_H (13)
#define DW_CONV_5_INPUT_OFFSET (128)
#define DW_CONV_5_INPUT_SIZE (NA)
#define DW_CONV_5_OUT_ACTIVATION_MIN (-128)
#define DW_CONV_5_OUT_ACTIVATION_MAX (127)
#define DW_CONV_5_INPUT_BATCHES (1)
#define DW_CONV_5_DILATION_W (1)
#define DW_CONV_5_DILATION_H (1)
#define DW_CONV_5_OUTPUT_OFFSET (-128)

#define CONV_6_OUT_CH (276)
#define CONV_6_IN_CH (276)
#define CONV_6_INPUT_W (5)
#define CONV_6_INPUT_H (13)
#define CONV_6_FILTER_W (1)
#define CONV_6_FILTER_H (1)
#define CONV_6_STRIDE_W (1)
#define CONV_6_STRIDE_H (1)
#define CONV_6_PAD_W (0)
#define CONV_6_PAD_H (0)
#define CONV_6_OUTPUT_W (5)
#define CONV_6_OUTPUT_H (13)
#define CONV_6_INPUT_OFFSET (128)
#define CONV_6_INPUT_SIZE (NA)
#define CONV_6_OUT_ACTIVATION_MIN (-128)
#define CONV_6_OUT_ACTIVATION_MAX (127)
#define CONV_6_INPUT_BATCHES (1)
#define CONV_6_DILATION_W (1)
#define CONV_6_DILATION_H (1)
#define CONV_6_OUTPUT_OFFSET (-128)

#define DW_CONV_7_OUT_CH (276)
#define DW_CONV_7_IN_CH (276)
#define DW_CONV_7_INPUT_W (5)
#define DW_CONV_7_INPUT_H (13)
#define DW_CONV_7_FILTER_W (3)
#define DW_CONV_7_FILTER_H (3)
#define DW_CONV_7_STRIDE_W (1)
#define DW_CONV_7_STRIDE_H (1)
#define DW_CONV_7_PAD_W (1)
#define DW_CONV_7_PAD_H (1)
#define DW_CONV_7_OUTPUT_W (5)
#define DW_CONV_7_OUTPUT_H (13)
#define DW_CONV_7_INPUT_OFFSET (128)
#define DW_CONV_7_INPUT_SIZE (NA)
#define DW_CONV_7_OUT_ACTIVATION_MIN (-128)
#define DW_CONV_7_OUT_ACTIVATION_MAX (127)
#define DW_CONV_7_INPUT_BATCHES (1)
#define DW_CONV_7_DILATION_W (1)
#define DW_CONV_7_DILATION_H (1)
#define DW_CONV_7_OUTPUT_OFFSET (-128)

#define CONV_8_OUT_CH (276)
#define CONV_8_IN_CH (276)
#define CONV_8_INPUT_W (5)
#define CONV_8_INPUT_H (13)
#define CONV_8_FILTER_W (1)
#define CONV_8_FILTER_H (1)
#define CONV_8_STRIDE_W (1)
#define CONV_8_STRIDE_H (1)
#define CONV_8_PAD_W (0)
#define CONV_8_PAD_H (0)
#define CONV_8_OUTPUT_W (5)
#define CONV_8_OUTPUT_H (13)
#define CONV_8_INPUT_OFFSET (128)
#define CONV_8_INPUT_SIZE (NA)
#define CONV_8_OUT_ACTIVATION_MIN (-128)
#define CONV_8_OUT_ACTIVATION_MAX (127)
#define CONV_8_INPUT_BATCHES (1)
#define CONV_8_DILATION_W (1)
#define CONV_8_DILATION_H (1)
#define CONV_8_OUTPUT_OFFSET (-128)

#define DW_CONV_9_OUT_CH (276)
#define DW_CONV_9_IN_CH (276)
#define DW_CONV_9_INPUT_W (5)
#define DW_CONV_9_INPUT_H (13)
#define DW_CONV_9_FILTER_W (3)
#define DW_CONV_9_FILTER_H (3)
#define DW_CONV_9_STRIDE_W (1)
#define DW_CONV_9_STRIDE_H (1)
#define DW_CONV_9_PAD_W (1)
#define DW_CONV_9_PAD_H (1)
#define DW_CONV_9_OUTPUT_W (5)
#define DW_CONV_9_OUTPUT_H (13)
#define DW_CONV_9_INPUT_OFFSET (128)
#define DW_CONV_9_INPUT_SIZE (NA)
#define DW_CONV_9_OUT_ACTIVATION_MIN (-128)
#define DW_CONV_9_OUT_ACTIVATION_MAX (127)
#define DW_CONV_9_INPUT_BATCHES (1)
#define DW_CONV_9_DILATION_W (1)
#define DW_CONV_9_DILATION_H (1)
#define DW_CONV_9_OUTPUT_OFFSET (-128)

#define CONV_10_OUT_CH (276)
#define CONV_10_IN_CH (276)
#define CONV_10_INPUT_W (5)
#define CONV_10_INPUT_H (13)
#define CONV_10_FILTER_W (1)
#define CONV_10_FILTER_H (1)
#define CONV_10_STRIDE_W (1)
#define CONV_10_STRIDE_H (1)
#define CONV_10_PAD_W (0)
#define CONV_10_PAD_H (0)
#define CONV_10_OUTPUT_W (5)
#define CONV_10_OUTPUT_H (13)
#define CONV_10_INPUT_OFFSET (128)
#define CONV_10_INPUT_SIZE (NA)
#define CONV_10_OUT_ACTIVATION_MIN (-128)
#define CONV_10_OUT_ACTIVATION_MAX (127)
#define CONV_10_INPUT_BATCHES (1)
#define CONV_10_DILATION_W (1)
#define CONV_10_DILATION_H (1)
#define CONV_10_OUTPUT_OFFSET (-128)

#define AVERAGE_POOL_11_OUT_CH (276)
#define AVERAGE_POOL_11_IN_CH (276)
#define AVERAGE_POOL_11_FILTER_W (5)
#define AVERAGE_POOL_11_FILTER_H (13)
#define AVERAGE_POOL_11_STRIDE_W (1)
#define AVERAGE_POOL_11_STRIDE_H (1)
#define AVERAGE_POOL_11_PAD_W (0)
#define AVERAGE_POOL_11_PAD_H (0)
#define AVERAGE_POOL_11_OUTPUT_W (1)
#define AVERAGE_POOL_11_OUTPUT_H (1)
#define AVERAGE_POOL_11_INPUT_OFFSET (128)
#define AVERAGE_POOL_11_OUT_ACTIVATION_MIN -(128)
#define AVERAGE_POOL_11_OUT_ACTIVATION_MAX (127)
#define AVERAGE_POOL_11_INPUT_BATCHES (1)

#define FULLY_CONNECTED_12_ACTIVATION_MIN (-128)
#define FULLY_CONNECTED_12_ACTIVATION_MAX (127)
#define FULLY_CONNECTED_12_OUTPUT_WIDTH (12)
#define FULLY_CONNECTED_12_INPUT_OFFSET (128)
#define FULLY_CONNECTED_12_OUTPUT_OFFSET (34)
#define FULLY_CONNECTED_12_MULT (1837785324)
#define FULLY_CONNECTED_12_SHIFT (-10)

#define SOFTMAX_13_NUM_ROWS (1)
#define SOFTMAX_13_ROW_SIZE (12)
#define SOFTMAX_13_MULT (1103896832)
#define SOFTMAX_13_SHIFT (25)
#define SOFTMAX_13_DIFF_MIN (-62)
