// Generated by pooling_settings_flt.py using PyTorch version 2.10.0+cu128.
const float32_t maxpooling_match_3_f32_output_ref[10] = {-3.89307833f,
                                                         4.61016512f,
                                                         -5.60490513f,
                                                         3.29377055f,
                                                         -2.76508212f,
                                                         4.99265099f,
                                                         0.341757447f,
                                                         0.936909616f,
                                                         3.62441826f,
                                                         -0.83713603f};
