// Generated by batch_norm_settings_flt.py using PyTorch version 2.10.0+cu128.
const float16_t bn_basic_nhwc_f16_bias[6] = {(float16_t)0.0762939453f,
                                             (float16_t)0.0362243652f,
                                             (float16_t)0.0104751587f,
                                             (float16_t)-0.00966644287f,
                                             (float16_t)-0.0278778076f,
                                             (float16_t)-0.0459594727f};
