// Generated by batch_norm_settings_flt.py using PyTorch version 2.10.0+cu128.
#define BN_BASIC_NHWC_F16_INPUT_N 1
#define BN_BASIC_NHWC_F16_INPUT_H 8
#define BN_BASIC_NHWC_F16_INPUT_W 8
#define BN_BASIC_NHWC_F16_INPUT_C 6
#define BN_BASIC_NHWC_F16_SIZE 384
#define BN_BASIC_NHWC_F16_LAYOUT ARM_NN_LAYOUT_NHWC
