// Generated by batch_norm_settings_flt.py using PyTorch version 2.10.0+cu128.
const float16_t bn_basic_nhwc_f16_scale[6] = {(float16_t)1.13183594f,
                                              (float16_t)1.05175781f,
                                              (float16_t)1.01171875f,
                                              (float16_t)0.991699219f,
                                              (float16_t)0.982421875f,
                                              (float16_t)0.979980469f};
