// Generated by generate_test_data.py using tensorflow version 2.10.0 (Keras version 2.10.0).
// Interpreter from tensorflow version 2.10.0 and revision v2.10.0-rc3-6-g359c3cdfc5f.
#pragma once
#include <stdint.h>

const int32_t dw_int16xint8_fast_multiple_batches_uneven_buffers_output_mult[8] =
    {1554034767, 1505895962, 1583401714, 1494720058, 1472755273, 1241592497, 1349384561, 1553647651};
