// Generated by pooling_settings_flt.py using PyTorch version 2.10.0+cu128.
const float32_t maxpooling_f32_3_input_tensor[8] =
    {5.5887661f, -1.79883885f, 7.83963394f, 2.05810666f, 8.88128853f, -0.263135225f, -2.66723323f, 9.48214912f};
