// Generated by lstm_settings_flt.py using PyTorch version 2.10.0+cu128.
const float32_t lstm_match_1_f32_cell_bias[11] = {0.367453396f,
                                                  0.334282398f,
                                                  0.0157604646f,
                                                  0.0513678938f,
                                                  -0.0226461887f,
                                                  -0.144018799f,
                                                  -0.197210193f,
                                                  -0.158578768f,
                                                  -0.161302894f,
                                                  0.177997932f,
                                                  -0.156867802f};
