// Generated by lstm_settings_flt.py using PyTorch version 2.10.0+cu128.
const float32_t lstm_match_1_f32_forget_bias[11] = {0.07326518f,
                                                    0.0773076341f,
                                                    -0.0194033831f,
                                                    -0.243045479f,
                                                    0.0540685728f,
                                                    -0.33674705f,
                                                    0.0171036087f,
                                                    -0.0666771978f,
                                                    -0.129992083f,
                                                    0.180498004f,
                                                    -0.219663337f};
