// Generated by lstm_settings_flt.py using PyTorch version 2.10.0+cu128.
const float32_t lstm_match_1_f32_input_bias[11] = {-0.0296523571f,
                                                   -0.0872102678f,
                                                   0.349362254f,
                                                   -0.0126139969f,
                                                   -0.198313937f,
                                                   -0.022658471f,
                                                   -0.227379307f,
                                                   0.021823585f,
                                                   -0.0399556644f,
                                                   -0.407198131f,
                                                   0.205341861f};
