// Generated by lstm_settings_flt.py using PyTorch version 2.10.0+cu128.
const float32_t lstm_match_1_f32_output_bias[11] = {0.21179682f,
                                                    0.0271224733f,
                                                    0.0610890239f,
                                                    -0.00270882621f,
                                                    0.0175702125f,
                                                    0.327572525f,
                                                    0.0448258594f,
                                                    0.00832810998f,
                                                    -0.412203401f,
                                                    0.0480898619f,
                                                    0.308657616f};
