// Generated by conv_settings_flt.py using PyTorch version 2.10.0+cu128.
const float32_t conv_k5_opt_f32_biases_data[12] = {0.370316595f,
                                                   -0.0276993774f,
                                                   -0.333786786f,
                                                   -0.143184528f,
                                                   -0.0529888347f,
                                                   0.00524023687f,
                                                   0.107681215f,
                                                   -0.155145317f,
                                                   0.0354041979f,
                                                   0.436348975f,
                                                   -0.195979178f,
                                                   0.226857617f};
