// Generated by depthwise_conv_settings_flt.py using PyTorch version 2.10.0+cu128.
const float32_t depthwise_match_sub_block_f32_biases_data[9] = {-0.375010908f,
                                                                0.357140869f,
                                                                -0.463421792f,
                                                                -0.04976511f,
                                                                0.0266925879f,
                                                                -0.145963833f,
                                                                0.466690183f,
                                                                -0.343103439f,
                                                                -0.412703067f};
