// Generated by generate_test_data.py using tensorflow version 2.18.0 (Keras version 3.14.1).
// Interpreter from tflite_micro runtime version 0.dev20260203175027-g88f8587.
#pragma once
#include <stdint.h>

const int8_t lstm_stateful_batch_major_multibatch_cell_gate_input_weights[42] = {
    92,  100, -29, 127, 76, -74, 115, -81, 63,  4,    69, -81, 8,  -25, 42,  99, 44, 101,  12,   -25, 99,
    -70, -88, -41, 107, 65, 67,  -31, 87,  -54, -104, 95, 35,  21, 125, -87, 27, 78, -113, -114, 61,  -101};
