// Generated by generate_test_data.py using tensorflow version 2.18.0 (Keras version 3.14.1).
// Interpreter from tflite_micro runtime version 0.dev20260203175027-g88f8587.
#pragma once
#include <stdint.h>

const int8_t lstm_stateful_batch_major_multibatch_cell_gate_hidden_weights[49] = {
    -20, -88, 87, 87,  109,  -54, -12,  21,  2,    -112, 44,  -79, -97, -15, 123, 105, -122,
    -29, -83, 36, 58,  33,   59,  -115, 127, -106, 101,  -57, -97, -64, -39, 71,  4,   -114,
    -94, 74,  34, -12, -118, -64, 104,  102, -36,  -114, 117, 95,  -1,  67,  81};
