// Generated by generate_test_data.py using tensorflow version 2.18.0 (Keras version 3.14.1).
// Interpreter from tflite_micro runtime version 0.dev20260203175027-g88f8587.
#pragma once
#include <stdint.h>

const int8_t lstm_stateful_batch_major_multibatch_forget_gate_input_weights[42] = {
    58,  -87, 92, 94,  -41, -61, 31,   -86, 72, 3,  116, 68, -81,  -55, -44, -122, -105, -87, -23, 94,  -113,
    -68, 23,  45, -96, 13,  103, -116, 87,  88, -2, 6,   58, -126, 33,  28,  -113, 68,   -30, -84, 127, -33};
