// Generated by generate_test_data.py using tensorflow version 2.18.0 (Keras version 3.14.1).
// Interpreter from tflite_micro runtime version 0.dev20260203175027-g88f8587.
#pragma once
#include <stdint.h>

const int8_t lstm_stateful_batch_major_multibatch_forget_gate_hidden_weights[49] = {
    8,   -96, 106, 66,  -101, 22,  -70,  86,   -37,  -1,  -127, 52,  9,  79,   111, -94, 126,
    -21, -25, -79, 42,  -57,  -42, -3,   126,  51,   -49, -28,  -10, 50, -104, -48, -11, -78,
    36,  121, 6,   -56, -24,  -75, -104, -103, -119, -63, -69,  -51, 11, -43,  19};
