// Generated by generate_test_data.py using tensorflow version 2.18.0 (Keras version 3.14.1).
// Interpreter from tflite_micro runtime version 0.dev20260203175027-g88f8587.
#pragma once
#include <stdint.h>

const int8_t lstm_stateful_batch_major_multibatch_input_gate_hidden_weights[49] = {
    -120, -121, -18, 3,  74,   27,  -107, 84, 43,  127, 91,   116, 77,  -17, -8,  32,  89,
    111,  85,   -8,  9,  -115, -36, 71,   70, -10, 70,  -106, -9,  -71, -83, -79, -73, -88,
    39,   -124, -1,  -2, 108,  117, -27,  61, -90, -32, -105, 97,  41,  -98, 57};
