// Generated by generate_test_data.py using tensorflow version 2.18.0 (Keras version 3.14.1).
// Interpreter from tflite_micro runtime version 0.dev20260203175027-g88f8587.
#pragma once
#include <stdint.h>

const int8_t lstm_stateful_batch_major_multibatch_input_gate_input_weights[42] = {
    -21, -53,  56,   127, -88, 66,  -111, 94, -19, 90, 124, -67, 15, 3,  85,  -34, 37,  65, 93, -86,  -72,
    -30, -121, -122, 5,   -54, -83, -111, -6, 49,  99, -67, 0,   45, 85, -16, 54,  120, 36, 79, -119, -4};
