// Generated by generate_test_data.py using tensorflow version 2.18.0 (Keras version 3.14.1).
// Interpreter from tflite_micro runtime version 0.dev20260203175027-g88f8587.
#pragma once
#include <stdint.h>

const int8_t lstm_stateful_batch_major_multibatch_output_gate_hidden_weights[49] = {
    29,  -109, 63, -104, -1, -60, 94,   -95, -65,  46, 52,  -10, 50,  -59,  -29, 30,  -106,
    108, 7,    88, -76,  5,  85,  -121, 127, 35,   63, -97, -12, 84,  -112, 109, -89, 19,
    -41, 74,   83, 56,   53, 93,  -127, -25, -104, 37, -75, 7,   -10, 72,   -111};
