// Generated by generate_test_data.py using tensorflow version 2.18.0 (Keras version 3.14.1).
// Interpreter from tflite_micro runtime version 0.dev20260203175027-g88f8587.
#pragma once
#include <stdint.h>

const int8_t lstm_stateful_batch_major_multibatch_output[28] = {72,  68, 89,  -16,  29,  94, -68, 7,  15, 102,
                                                                7,   2,  30,  -105, 39,  90, 65,  5,  52, 115,
                                                                -27, 54, 105, 98,   -48, 32, 78,  -23};
