// Generated by generate_test_data.py using tensorflow version 2.18.0 (Keras version 3.14.1).
// Interpreter from tflite_micro runtime version 0.dev20260203175027-g88f8587.
#pragma once
#include <stdint.h>

const int8_t lstm_stateful_batch_major_multibatch_output_gate_input_weights[42] = {
    -54, 67, -56, -37, -72, -6, -36, 1,   30, -117, -51, 94,  -11,  -95, -16,  52, -37, -99, -1,  66,  -31,
    73,  52, 11,  -93, 34,  9,  -84, -77, -1, 94,   -34, -61, -122, 115, -107, 2,  -35, 127, -76, -75, -79};
