// Generated by conv_settings_flt.py using PyTorch version 2.10.0+cu128.
const float32_t conv_match_1xn_1_f32_output_ref_data[12] = {0.58425808f,
                                                            -1.04209054f,
                                                            0.258911282f,
                                                            -1.3516531f,
                                                            -0.613562644f,
                                                            0.114563726f,
                                                            0.402786672f,
                                                            0.319794923f,
                                                            0.587856352f,
                                                            1.48796213f,
                                                            0.475916415f,
                                                            0.235712066f};
