// Generated by test_settings.py using tensorflow version 2.11.0 (Keras version 2.11.0).
// Interpreter from tflite_runtime version 2.16.0 and revision 0.6.0-154906-gb2493fdf794.
#pragma once
#include <stdint.h>

const int8_t maxpooling_3_input[54] = {7,   -57, 106,  28,   40,   106,  70,  36,  71,   -96, -69, -43, 75,   -96,
                                       -38, 38,  -117, -104, -108, -72,  -79, 57,  0,    72,  -31, 83,  109,  -3,
                                       -23, -59, -3,   -65,  -35,  -116, -56, -46, -120, 41,  117, 92,  -122, 4,
                                       30,  -16, -22,  118,  84,   67,   -44, -76, 92,   120, 48,  125};
