// Generated by test_settings.py using tensorflow version 2.11.0 (Keras version 2.11.0).
// Interpreter from tflite_runtime version 2.16.0 and revision 0.6.0-154906-gb2493fdf794.
#pragma once
#include <stdint.h>

const int8_t maxpooling_3_output_ref[30] = {7,    -57, 40,   106, 71,  -96, 75,  -96, -117, -104,
                                            -108, -72, 0,    72,  109, -3,  -3,  -65, -56,  -46,
                                            -120, 41,  -122, 4,   -22, 118, -44, -76, 48,   125};
