// Generated by test_settings.py using tensorflow version 2.15.0-dev20231004 (Keras version 2.15.0.dev2023092207).
// Interpreter from tflite_micro version 0.dev20231002060915-gec477d5c and revision None.
#pragma once
#include <stdint.h>

const int8_t fully_connected_int4_5_input[7] = {49, -95, -64, 48, 5, -123, -112};
