// Generated by test_settings.py using tensorflow version 2.15.0-dev20231004 (Keras version 2.15.0.dev2023092207).
// Interpreter from tflite_micro version 0.dev20231002060915-gec477d5c and revision None.
#include "biases_data.h"
#include "config_data.h"
#include "input_data.h"
#include "output_ref_data.h"
#include "weights_data.h"
