// Generated by test_settings.py using tensorflow version 2.15.0-dev20231004 (Keras version 2.15.0.dev2023092207).
// Interpreter from tflite_micro version 0.dev20231002060915-gec477d5c and revision None.
#pragma once
#include <stdint.h>

const int8_t fully_connected_int4_5_weights[14] = {12, 153, 180, 188, 191, 192, 50, 68, 109, 188, 133, 129, 227, 254};
