// Generated by test_settings.py using tensorflow version 2.14.0 (Keras version 2.14.0).
// Interpreter from tflite_runtime version 2.16.0dev20231108 and revision 0.6.0-155953-g2bcb825a248.
#pragma once
#define CONV_5_INT4_OUT_CH 1
#define CONV_5_INT4_IN_CH 128
#define CONV_5_INT4_INPUT_W 128
#define CONV_5_INT4_INPUT_H 1
#define CONV_5_INT4_DST_SIZE 32
#define CONV_5_INT4_INPUT_SIZE 16384
#define CONV_5_INT4_OUT_ACTIVATION_MIN -88
#define CONV_5_INT4_OUT_ACTIVATION_MAX 127
#define CONV_5_INT4_INPUT_BATCHES 1
#define CONV_5_INT4_FILTER_X 3
#define CONV_5_INT4_FILTER_Y 3
#define CONV_5_INT4_STRIDE_X 4
#define CONV_5_INT4_STRIDE_Y 4
#define CONV_5_INT4_PAD_X 0
#define CONV_5_INT4_PAD_Y 1
#define CONV_5_INT4_OUTPUT_W 32
#define CONV_5_INT4_OUTPUT_H 1
#define CONV_5_INT4_INPUT_OFFSET 128
#define CONV_5_INT4_OUTPUT_OFFSET 0
#define CONV_5_INT4_DILATION_X 1
#define CONV_5_INT4_DILATION_Y 1
