// Generated by svdf_settings_flt.py using PyTorch version 2.10.0+cu128.
const float32_t svdf_batch2_f32_bias[8] = {-0.0801542401f,
                                           0.102831051f,
                                           -0.209339321f,
                                           0.1675722f,
                                           -0.175365955f,
                                           -0.244661346f,
                                           -0.212981522f,
                                           -0.0593195707f};
