// Generated by depthwise_conv_settings_flt.py using PyTorch version 2.10.0+cu128.
const float16_t depthwise_k3_1d_opt_nhwc_f16_biases_data[8] = {(float16_t)-0.136474609f,
                                                               (float16_t)0.154541016f,
                                                               (float16_t)-0.068359375f,
                                                               (float16_t)0.0939331055f,
                                                               (float16_t)-0.0619506836f,
                                                               (float16_t)-0.444824219f,
                                                               (float16_t)0.348388672f,
                                                               (float16_t)-0.178222656f};
