// Generated by depthwise_conv_settings_flt.py using PyTorch version 2.10.0+cu128.
const float16_t depthwise_k3_1d_opt_nhwc_f16_weights_data[24] = {
    (float16_t)-0.190429688f, (float16_t)0.295654297f,   (float16_t)-0.606445312f, (float16_t)0.638183594f,
    (float16_t)-0.217773438f, (float16_t)0.00703811646f, (float16_t)0.162841797f,  (float16_t)0.323486328f,
    (float16_t)-0.419433594f, (float16_t)-0.118286133f,  (float16_t)-0.419433594f, (float16_t)0.0878295898f,
    (float16_t)0.329101562f,  (float16_t)-0.2265625f,    (float16_t)0.0169830322f, (float16_t)0.447998047f,
    (float16_t)-0.451171875f, (float16_t)0.201660156f,   (float16_t)0.274658203f,  (float16_t)-0.372314453f,
    (float16_t)0.447265625f,  (float16_t)0.449707031f,   (float16_t)0.308837891f,  (float16_t)0.483886719f};
