// Generated by transpose_conv_settings_flt.py using PyTorch version 2.10.0+cu128.
const float32_t transpose_conv_basic_f32_biases[6] =
    {0.337419599f, 0.0628587902f, -0.319512516f, -0.222603902f, 0.274047256f, -0.482694238f};
