// Generated by conv_settings_flt.py using PyTorch version 2.10.0+cu128.
const float32_t conv_match_dilation_golden_f32_weights_data[12] = {0.383066237f,
                                                                   -0.54359746f,
                                                                   -0.605349839f,
                                                                   0.354899645f,
                                                                   0.735494852f,
                                                                   -0.636392832f,
                                                                   0.556611359f,
                                                                   -0.215591922f,
                                                                   -0.0988261104f,
                                                                   -0.65936172f,
                                                                   -0.304476053f,
                                                                   0.569688559f};
