// Generated by depthwise_conv_settings_flt.py using PyTorch version 2.10.0+cu128.
const float32_t depthwise_k3_1d_opt_batch2_f32_biases_data[8] =
    {0.318682313f, -0.35397172f, 0.48092863f, -0.307419658f, -0.396993905f, -0.448122829f, -0.025135383f, 0.24585925f};
