// Generated by batch_matmul_settings_flt.py using PyTorch version 2.10.0+cu128.
const float16_t batch_matmul_et_small_f16_lhs_input_tensor[6] = {(float16_t)-0.821289062f,
                                                                 (float16_t)-0.650390625f,
                                                                 (float16_t)-0.815917969f,
                                                                 (float16_t)-1.21289062f,
                                                                 (float16_t)-1.0859375f,
                                                                 (float16_t)-0.4765625f};
