// Generated by batch_matmul_settings_flt.py using PyTorch version 2.10.0+cu128.
const float16_t batch_matmul_et_small_f16_output[8] = {(float16_t)-2.41992188f,
                                                       (float16_t)-0.548828125f,
                                                       (float16_t)0.373291016f,
                                                       (float16_t)1.4140625f,
                                                       (float16_t)-2.65234375f,
                                                       (float16_t)-2.24023438f,
                                                       (float16_t)-0.0537414551f,
                                                       (float16_t)1.71484375f};
