// Generated by batch_matmul_settings_flt.py using PyTorch version 2.10.0+cu128.
const float16_t batch_matmul_et_small_f16_rhs_transposed_tensor[12] = {(float16_t)0.845214844f,
                                                                       (float16_t)0.875976562f,
                                                                       (float16_t)1.41796875f,
                                                                       (float16_t)1.84765625f,
                                                                       (float16_t)0.798828125f,
                                                                       (float16_t)-1.82421875f,
                                                                       (float16_t)-0.435791016f,
                                                                       (float16_t)0.837402344f,
                                                                       (float16_t)-0.686523438f,
                                                                       (float16_t)-0.901855469f,
                                                                       (float16_t)-0.321777344f,
                                                                       (float16_t)-0.569335938f};
