// Generated by generate_test_data.py using tensorflow version 2.10.0 (Keras version 2.10.0).
// Interpreter from tensorflow version 2.10.0 and revision upstream/v2.10.0-0-g359c3cdfc5f.
#pragma once
#define KERNEL1X1_OUT_CH 2
#define KERNEL1X1_IN_CH 16
#define KERNEL1X1_INPUT_W 3
#define KERNEL1X1_INPUT_H 1
#define KERNEL1X1_DST_SIZE 6
#define KERNEL1X1_INPUT_SIZE 48
#define KERNEL1X1_OUT_ACTIVATION_MIN -126
#define KERNEL1X1_OUT_ACTIVATION_MAX 127
#define KERNEL1X1_INPUT_BATCHES 1
#define KERNEL1X1_FILTER_X 1
#define KERNEL1X1_FILTER_Y 1
#define KERNEL1X1_STRIDE_X 1
#define KERNEL1X1_STRIDE_Y 1
#define KERNEL1X1_PAD_X 0
#define KERNEL1X1_PAD_Y 0
#define KERNEL1X1_OUTPUT_W 3
#define KERNEL1X1_OUTPUT_H 1
#define KERNEL1X1_INPUT_OFFSET 128
#define KERNEL1X1_OUTPUT_OFFSET 71
#define KERNEL1X1_DILATION_X 1
#define KERNEL1X1_DILATION_Y 1
