// Generated by generate_test_data.py using tensorflow version 2.10.0 (Keras version 2.10.0).
// Interpreter from tensorflow version 2.10.0 and revision upstream/v2.10.0-0-g359c3cdfc5f.
#pragma once
#include <stdint.h>

const int8_t kernel1x1_input[48] = {96,  87, -2,  119, -83,  -111, 98,  73,  101,  -102, 80,  66, 56,  -10, 124, 8,
                                    -93, 88, 111, 68,  -105, 75,   -29, -66, -117, -68,  -36, 79, -17, -82, 32,  -15,
                                    61,  -6, 80,  59,  -39,  -124, 124, -52, -62,  26,   -78, 16, -27, 44,  3,   27};
