// Generated by generate_test_data.py using tensorflow version 2.10.0 (Keras version 2.10.0).
// Interpreter from tensorflow version 2.10.0 and revision v2.10.0-rc3-6-g359c3cdfc5f.
#pragma once
#include <stdint.h>

const int32_t kernel1x1_output_mult[7] =
    {1409372283, 1331073775, 1409372283, 1398186794, 1331073775, 1387001305, 1342259349};
