// Generated by generate_test_data.py using TFL version 2.9.1 as reference.
#pragma once
#include <stdint.h>

const int32_t kernel1x1_output_mult[9] =
    {1742180917, 2115505360, 1102196118, 1955509228, 2026618620, 2079950664, 1075530095, 1528852605, 1884399836};
