// Generated by generate_test_data.py using TFL version 2.9.1 as reference.
#pragma once
#include <stdint.h>

const int32_t kernel1x1_output_mult[7] =
    {1409372283, 1331073775, 1409372283, 1398186794, 1331073775, 1387001305, 1342259349};
