// Generated by generate_test_data.py using tensorflow version 2.10.0 (Keras version 2.10.0).
// Interpreter from tensorflow version 2.10.0 and revision upstream/v2.10.0-0-g359c3cdfc5f.
#pragma once
#include <stdint.h>

const int8_t kernel1x1_weights[32] = {127, -26, -69,  -66, -115, 12,  116, 114, 36,  51,  -12,  -44,  18, 94, -51, -116,
                                      -91, -16, -113, 47,  39,   -19, -99, -79, -19, -26, -127, -108, 62, 2,  -55, 10};
