// Generated by generate_test_data.py using TFL version 2.9.1 as reference.
#pragma once
#include <stdint.h>

const int8_t kernel1x1_weights[45] = {-127, 40, -127, -126, -44,  -46,  -47, 67,  127, 89,   51,  -53, -127, -109, 81,
                                      -127, 96, -35,  0,    -37,  43,   -2,  108, -26, -127, -86, 89,  -110, 27,   -127,
                                      -23,  39, -33,  76,   -127, -127, 18,  69,  -93, -12,  -34, 127, -30,  71,   -18};
