// Generated by batch_norm_settings_flt.py using PyTorch version 2.10.0+cu128.
const float32_t bn_op_f32_bias[7] =
    {0.0762719065f, 0.0415249765f, 0.0181606114f, 1.11758336e-08f, -0.0158358067f, -0.03086555f, -0.0459585339f};
