// Generated by conv_settings_flt.py using PyTorch version 2.10.0+cu128.
const float16_t conv_match_1xn_5_f16_input_data[68] = {
    (float16_t)-0.536132812f,   (float16_t)0.67578125f,    (float16_t)-0.851074219f,  (float16_t)-0.766601562f,
    (float16_t)0.568847656f,    (float16_t)0.700683594f,   (float16_t)0.792480469f,   (float16_t)-0.0495910645f,
    (float16_t)0.765136719f,    (float16_t)-0.0102081299f, (float16_t)0.907226562f,   (float16_t)0.487548828f,
    (float16_t)0.721679688f,    (float16_t)-0.569335938f,  (float16_t)0.801757812f,   (float16_t)-0.00796508789f,
    (float16_t)-0.109008789f,   (float16_t)0.814453125f,   (float16_t)0.668457031f,   (float16_t)-0.478027344f,
    (float16_t)0.244750977f,    (float16_t)-0.773925781f,  (float16_t)0.396240234f,   (float16_t)0.966796875f,
    (float16_t)0.674804688f,    (float16_t)0.444580078f,   (float16_t)0.181518555f,   (float16_t)-0.961914062f,
    (float16_t)0.57421875f,     (float16_t)-0.916503906f,  (float16_t)-0.724121094f,  (float16_t)-0.924804688f,
    (float16_t)0.264160156f,    (float16_t)-0.809570312f,  (float16_t)0.776367188f,   (float16_t)-0.495605469f,
    (float16_t)0.402832031f,    (float16_t)0.276611328f,   (float16_t)0.580078125f,   (float16_t)-0.901367188f,
    (float16_t)-0.0233306885f,  (float16_t)-0.604003906f,  (float16_t)0.901367188f,   (float16_t)-0.0601501465f,
    (float16_t)-0.0358276367f,  (float16_t)0.96484375f,    (float16_t)-0.028717041f,  (float16_t)0.181518555f,
    (float16_t)0.952636719f,    (float16_t)-0.177856445f,  (float16_t)0.856933594f,   (float16_t)0.0654907227f,
    (float16_t)0.298339844f,    (float16_t)0.324707031f,   (float16_t)0.447753906f,   (float16_t)-0.359130859f,
    (float16_t)-0.0861206055f,  (float16_t)0.697265625f,   (float16_t)-0.0390319824f, (float16_t)0.5390625f,
    (float16_t)-0.773925781f,   (float16_t)0.904785156f,   (float16_t)0.168579102f,   (float16_t)-0.690917969f,
    (float16_t)-0.00895690918f, (float16_t)-0.720703125f,  (float16_t)-0.291992188f,  (float16_t)0.0115432739f};
