// Generated by conv_settings_flt.py using PyTorch version 2.10.0+cu128.
const float16_t conv_match_1xn_5_f16_output_ref_data[5] = {(float16_t)1.24023438f,
                                                           (float16_t)0.444824219f,
                                                           (float16_t)0.380859375f,
                                                           (float16_t)-1.73242188f,
                                                           (float16_t)-0.606445312f};
