// Generated by conv_settings_flt.py using PyTorch version 2.10.0+cu128.
const float16_t conv_match_1xn_5_f16_weights_data[12] = {(float16_t)-0.118530273f,
                                                         (float16_t)-0.400146484f,
                                                         (float16_t)-0.725097656f,
                                                         (float16_t)0.0318908691f,
                                                         (float16_t)0.593261719f,
                                                         (float16_t)0.521484375f,
                                                         (float16_t)-0.467529297f,
                                                         (float16_t)-0.16796875f,
                                                         (float16_t)-0.258789062f,
                                                         (float16_t)-0.351074219f,
                                                         (float16_t)0.685546875f,
                                                         (float16_t)0.396728516f};
