// Generated by generate_test_data.py using tensorflow version 2.10.0 (Keras version 2.10.0).
// Interpreter from tensorflow version 2.10.0 and revision v2.10.0-rc3-6-g359c3cdfc5f.
#pragma once
#include <stdint.h>

const int8_t fully_connected_input[60] = {92,  -114, -71, 123, 9,   44,  -70,  -40, -87, -91, -127, -59, 49,  6,   88,
                                          -15, 10,   91,  38,  -83, 83,  -126, 92,  -32, -40, -27,  116, 120, 60,  104,
                                          77,  -41,  73,  90,  -99, -98, -71,  125, -4,  -31, 121,  55,  -57, -46, 48,
                                          66,  85,   114, -47, 29,  -65, 79,   -19, 85,  31,  37,   60,  -89, 31,  -23};
