// Generated by generate_test_data.py using tensorflow version 2.10.0 (Keras version 2.10.0).
// Interpreter from tensorflow version 2.10.0 and revision upstream/v2.10.0-0-g359c3cdfc5f.
#pragma once
#include <stdint.h>

const int8_t fully_connected_output_ref[18] =
    {-23, -128, -19, 63, 22, -71, 0, -125, -36, -10, -10, -56, 28, -128, 8, -31, 43, 6};
