// Generated by generate_test_data.py using tensorflow version 2.10.0 (Keras version 2.10.0).
// Interpreter from tensorflow version 2.10.0 and revision v2.10.0-rc3-6-g359c3cdfc5f.
#pragma once
#include <stdint.h>

const int8_t fully_connected_output_ref[18] =
    {5, -6, -20, -30, 103, 38, 21, 13, -72, -32, 85, 50, 15, 8, -40, -85, 87, 68};
