// Generated by fully_connected_settings_flt.py using PyTorch version 2.10.0+cu128.
const float16_t fully_connected_2out_tail21_f16_input_data[42] = {
    (float16_t)-1.25878906f,  (float16_t)-0.935058594f, (float16_t)-1.97460938f,  (float16_t)-0.487060547f,
    (float16_t)0.968261719f,  (float16_t)0.6015625f,    (float16_t)-0.583007812f, (float16_t)-0.688964844f,
    (float16_t)1.15039062f,   (float16_t)0.769042969f,  (float16_t)0.838867188f,  (float16_t)1.42871094f,
    (float16_t)1.65722656f,   (float16_t)1.734375f,     (float16_t)0.0180664062f, (float16_t)-1.27148438f,
    (float16_t)-0.304931641f, (float16_t)1.41503906f,   (float16_t)0.0697021484f, (float16_t)1.49707031f,
    (float16_t)-1.90234375f,  (float16_t)1.14355469f,   (float16_t)1.62695312f,   (float16_t)-1.98242188f,
    (float16_t)-0.202758789f, (float16_t)1.13964844f,   (float16_t)-1.80664062f,  (float16_t)-1.16308594f,
    (float16_t)-1.29296875f,  (float16_t)-0.927734375f, (float16_t)-0.222045898f, (float16_t)-0.00867462158f,
    (float16_t)-1.55175781f,  (float16_t)0.38671875f,   (float16_t)1.22753906f,   (float16_t)1.71777344f,
    (float16_t)0.639160156f,  (float16_t)-1.10742188f,  (float16_t)1.11132812f,   (float16_t)-1.58984375f,
    (float16_t)-1.31640625f,  (float16_t)0.243774414f};
