// Generated by fully_connected_settings_flt.py using PyTorch version 2.10.0+cu128.
const float16_t fully_connected_2out_tail21_f16_output_ref_data[4] = {(float16_t)-5.86328125f,
                                                                      (float16_t)-2.375f,
                                                                      (float16_t)-7.125f,
                                                                      (float16_t)4.81640625f};
