// Generated by fully_connected_settings_flt.py using PyTorch version 2.10.0+cu128.
const float16_t fully_connected_2out_tail21_f16_weights_data[42] = {
    (float16_t)-1.29492188f,  (float16_t)-1.20800781f,   (float16_t)-0.067565918f, (float16_t)0.766113281f,
    (float16_t)-0.858398438f, (float16_t)0.41015625f,    (float16_t)0.139404297f,  (float16_t)0.738769531f,
    (float16_t)-0.893554688f, (float16_t)-0.0297393799f, (float16_t)1.35449219f,   (float16_t)-0.166503906f,
    (float16_t)-1.45410156f,  (float16_t)-1.39550781f,   (float16_t)-1.32421875f,  (float16_t)0.853027344f,
    (float16_t)-0.454589844f, (float16_t)0.243164062f,   (float16_t)0.299072266f,  (float16_t)-1.30175781f,
    (float16_t)-0.111877441f, (float16_t)1.06445312f,    (float16_t)-0.624511719f, (float16_t)-0.803222656f,
    (float16_t)0.25f,         (float16_t)-0.408447266f,  (float16_t)-0.93359375f,  (float16_t)-0.829589844f,
    (float16_t)1.47070312f,   (float16_t)0.523925781f,   (float16_t)0.245361328f,  (float16_t)0.179443359f,
    (float16_t)-1.02636719f,  (float16_t)0.633300781f,   (float16_t)1.49023438f,   (float16_t)-0.944824219f,
    (float16_t)-0.783203125f, (float16_t)-0.178588867f,  (float16_t)-0.887695312f, (float16_t)-1.09179688f,
    (float16_t)-0.831054688f, (float16_t)1.35449219f};
