// Generated by conv_settings_flt.py using PyTorch version 2.10.0+cu128.
const float32_t conv_match_1xn_5_f32_output_ref_data[5] = {1.23991716f,
                                                           0.444789171f,
                                                           0.380858958f,
                                                           -1.73225701f,
                                                           -0.60636425f};
