// Generated by conv_settings_flt.py using PyTorch version 2.10.0+cu128.
const float32_t conv_match_1xn_5_f32_weights_data[12] = {-0.118545964f,
                                                         -0.400148779f,
                                                         -0.724927545f,
                                                         0.0318921469f,
                                                         0.593055844f,
                                                         0.521471143f,
                                                         -0.467611074f,
                                                         -0.168010309f,
                                                         -0.25878042f,
                                                         -0.351125062f,
                                                         0.685330093f,
                                                         0.396624357f};
