#!/usr/bin/env python3
#
# SPDX-FileCopyrightText: Copyright 2010-2026 Arm Limited and/or its affiliates <open-source-office@arm.com>
#
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the License); you may
# not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an AS IS BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

from __future__ import annotations

import os
import shlex
import shutil
import subprocess
import sys
from pathlib import Path

import numpy as np
import torch

TEST_DATA_ROOT = Path("TestCases/TestData")
PREGENERATED_DATA_ROOT = Path("PregeneratedData")


def format_generated_file(filepath: Path) -> None:
    formatter_cmd = os.getenv("CLANG_FORMAT")
    if formatter_cmd:
        command = shlex.split(formatter_cmd)
    else:
#Prefer the formatter shipped with the active Python environment so
#generation and CI checks see the same clang - format version.
        formatter = None
        python_bin_dir = Path(sys.executable).parent
        sibling_formatter = python_bin_dir / "clang-format"
        if sibling_formatter.is_file():
            formatter = str(sibling_formatter)
        else:
            virtual_env = os.getenv("VIRTUAL_ENV")
            if virtual_env:
                venv_formatter = Path(virtual_env) / "bin" / "clang-format"
                if venv_formatter.is_file():
                    formatter = str(venv_formatter)
        if formatter is None:
            formatter = shutil.which("clang-format")
        if formatter is None:
            raise RuntimeError(
                "clang-format not found. Set CLANG_FORMAT or add clang-format to PATH "
                "before generating unit-test headers."
            )
        command = [formatter]

    if "-i" not in command:
        command.append("-i")

    result = subprocess.run([*command, str(filepath)], check=False)
    if result.returncode != 0:
        raise RuntimeError(f"Failed to format generated file: {filepath}")


def as_c_float_literal(value: float) -> str:
    literal = f"{value:.9g}"
    if "." not in literal and "e" not in literal and "E" not in literal:
        literal += ".0"
    return literal


def format_float32(value: float) -> str:
    return f"{as_c_float_literal(float(np.float32(value)))}f"


def format_float16(value: float) -> str:
    return f"(float16_t){as_c_float_literal(float(np.float16(value).astype(np.float32)))}f"


def get_generator_comment(script_name: str) -> str:
    return f"// Generated by {script_name} using PyTorch version {torch.__version__}.\n"


def prepare_dataset_dirs(
    dataset: str,
    outdir: Path = TEST_DATA_ROOT,
    pregenerated_dir: Path = PREGENERATED_DATA_ROOT,
) -> tuple[Path, Path]:
    headers_dir = Path(outdir) / dataset
    pregenerated_data_dir = Path(pregenerated_dir) / dataset
    headers_dir.mkdir(parents=True, exist_ok=True)
    pregenerated_data_dir.mkdir(parents=True, exist_ok=True)
    return headers_dir, pregenerated_data_dir


def save_pregenerated_array(filepath: Path, values: np.ndarray) -> None:
    np.savetxt(filepath, np.asarray(values).reshape(-1), delimiter=",")


def load_pregenerated_array(
    filepath: Path,
    shape: tuple[int, ...],
    dtype: np.dtype = np.float32,
) -> np.ndarray:
    return np.loadtxt(filepath, delimiter=",", dtype=dtype).reshape(shape)


def write_common_header(fh, script_name: str) -> None:
    fh.write(get_generator_comment(script_name))


def write_wrapper_header(filepath: Path, script_name: str, filenames: list[str]) -> None:
    with filepath.open("w", encoding="utf-8") as fh:
        write_common_header(fh, script_name)
        for filename in filenames:
            fh.write(f'#include "{filename}"\n')
    format_generated_file(filepath)


def write_float_array_header(
    filepath: Path,
    script_name: str,
    symbol_name: str,
    values: np.ndarray,
    dtype_name: str,
) -> None:
    flat_values = values.reshape(-1)
    if dtype_name == "f32":
        datatype = "float32_t"
        formatter = format_float32
    else:
        datatype = "float16_t"
        formatter = format_float16

    with filepath.open("w", encoding="utf-8") as fh:
        write_common_header(fh, script_name)
        fh.write(f"const {datatype} {symbol_name}[{flat_values.size}] = {{\n")
        for index, value in enumerate(flat_values):
            suffix = "," if index + 1 < flat_values.size else ""
            fh.write(f"    {formatter(float(value))}{suffix}\n")
        fh.write("};\n")
    format_generated_file(filepath)
