// Generated by RefactoredTestGen/test.py using flatc version 23.5.26
// Interpreter from tflite_micro runtime version 0.dev20240224054047-gcfa4c91.
#pragma once
#include <stdint.h>

const int64_t lstm_1_s16_cell_gate_bias[11] =
    {20142, 23563, 15741, 25098, 29041, 25327, 12730, 19511, 21749, 13563, 31032};