// Generated by RefactoredTestGen/test.py using flatc version 23.5.26
// Interpreter from tflite_micro runtime version 0.dev20240224054047-gcfa4c91.
#pragma once
#define lstm_1_s16_time_major true
#define lstm_1_s16_batch_size 1
#define lstm_1_s16_time_steps 10
#define lstm_1_s16_input_size 22
#define lstm_1_s16_hidden_size 11
#define lstm_1_s16_cell_scale_power -9
#define lstm_1_s16_output_zero_point 0
#define lstm_1_s16_input_zero_point 0
#define lstm_1_s16_cell_clip 32767
#define lstm_1_s16_forget_to_cell_multiplier 1073741824
#define lstm_1_s16_forget_to_cell_shift -14
#define lstm_1_s16_input_to_cell_multiplier 1107260824
#define lstm_1_s16_input_to_cell_shift -20
#define lstm_1_s16_output_multiplier 1213629630
#define lstm_1_s16_output_shift -16
#define lstm_1_s16_output_gate_hidden_multiplier 1898861718
#define lstm_1_s16_output_gate_hidden_shift -11
#define lstm_1_s16_cell_gate_hidden_multiplier 1891079498
#define lstm_1_s16_cell_gate_hidden_shift -11
#define lstm_1_s16_forget_gate_hidden_multiplier 1103129707
#define lstm_1_s16_forget_gate_hidden_shift -11
#define lstm_1_s16_input_gate_hidden_multiplier 1470839610
#define lstm_1_s16_input_gate_hidden_shift -12
#define lstm_1_s16_output_gate_input_multiplier 1106912731
#define lstm_1_s16_output_gate_input_shift -8
#define lstm_1_s16_cell_gate_input_multiplier 1407915316
#define lstm_1_s16_cell_gate_input_shift -11
#define lstm_1_s16_forget_gate_input_multiplier 1606965412
#define lstm_1_s16_forget_gate_input_shift -9
#define lstm_1_s16_input_gate_input_multiplier 1177308497
#define lstm_1_s16_input_gate_input_shift -8
