// Generated by RefactoredTestGen/test.py using flatc version 23.5.26
// Interpreter from tflite_micro runtime version 0.dev20240224054047-gcfa4c91.
#pragma once
#include <stdint.h>

const int64_t lstm_1_s16_forget_gate_bias[11] = {8691, 24230, 5069, 6375, 13615, 17184, 3326, 27937, 5850, 1018, 15410};