// Generated by RefactoredTestGen/test.py using flatc version 23.5.26
// Interpreter from tflite_micro runtime version 0.dev20240224054047-gcfa4c91.
#pragma once
#include <stdint.h>

const int64_t lstm_1_s16_output_gate_bias[11] =
    {8300, 1579, 11812, 11224, 18423, 11748, 9932, 26717, 23831, 11737, 10113};