// Generated by generate_test_data.py using TFL version 2.9.1 as reference.
#pragma once
#include <stdint.h>

const int32_t kernel1x1_stride_x_y_1_biases[5] = {17076, -58409, -21502, -39745, -26634};
