// Generated by generate_test_data.py using TFL version 2.9.1 as reference.
#pragma once
#include <stdint.h>

const int8_t kernel1x1_stride_x_y_1_output_ref[40] = {
    70, -35, -75, -34, -76, 40, -43, -56, -33, -50, 66, -33, -88, -37, -66, 70, -29, -86, -51, -91,
    79, -31, -97, -44, -87, 82, -32, -98, -42, -89, 73, -42, -95, -46, -81, 70, -37, -86, -38, -69};
