// Generated by generate_test_data.py using TFL version 2.9.1 as reference.
#pragma once
#include <stdint.h>

const int32_t kernel1x1_stride_x_y_1_output_mult[5] = {1088380504, 1108169231, 1207112940, 1306056575, 2117394827};
