// Generated by generate_test_data.py using tensorflow version 2.10.0 (Keras version 2.10.0).
// Interpreter from tensorflow version 2.10.0 and revision v2.10.0-rc3-6-g359c3cdfc5f.
#pragma once
#include <stdint.h>

const int32_t kernel1x1_stride_x_y_1_output_mult[5] = {1088380504, 1108169231, 1207112940, 1306056575, 2117394827};
