// Generated by generate_test_data.py using tensorflow version 2.10.0 (Keras version 2.10.0).
// Interpreter from tensorflow version 2.10.0 and revision v2.10.0-rc3-6-g359c3cdfc5f.
#pragma once
#include <stdint.h>

const int8_t kernel1x1_stride_x_y_1_weights[25] = {50,   109,  127,  99, 74, -84, -102, 127, 0,   98,  -57,  -119, 75,
                                                   -115, -127, -108, 89, 4,  -50, -127, -77, -11, -83, -127, -96};
