// Generated by fully_connected_settings_flt.py using PyTorch version 2.10.0+cu128.
const float32_t fully_connected_2out_tail17_f32_output_ref_data[4] = {3.29120994f,
                                                                      1.72403085f,
                                                                      4.135993f,
                                                                      -1.38057745f};
