// Generated by generate_test_data.py using tensorflow version 2.10.0 (Keras version 2.10.0).
// Interpreter from tensorflow version 2.10.0 and revision v2.10.0-rc3-6-g359c3cdfc5f.
#pragma once
#include <stdint.h>

const int8_t svdf_int8_input_sequence[40] = {-23,  123,  104, 88,  -47, 92,  -14, -14, -90,  -113, -94, -46, 121, -125,
                                             -100, -59,  69,  19,  -80, 24,  86,  37,  8,    116,  113, -45, 116, 41,
                                             -1,   -103, 37,  103, 88,  -86, 28,  30,  -121, 4,    -83, -109};
