// Generated by generate_test_data.py using tensorflow version 2.10.0 (Keras version 2.10.0).
// Interpreter from tensorflow version 2.10.0 and revision v2.10.0-rc3-6-g359c3cdfc5f.
#pragma once
#include <stdint.h>

const int8_t svdf_int8_weights_time[24] = {30,  32,  -33, 59,  -53, -32,  -45, -12, -119, 87,  34,  -114,
                                           -92, -45, -90, 114, -68, -116, -8,  -10, 18,   -55, 100, 1};
