// Generated by generate_test_data.py using tensorflow version 2.10.0 (Keras version 2.10.0).
// Interpreter from tensorflow version 2.10.0 and revision upstream/v2.10.0-0-g359c3cdfc5f.
#pragma once
#include <stdint.h>

const int8_t conv_1_x_n_1_input[16] = {28, 6, -4, 114, -53, -123, -2, 78, -97, -7, -83, -109, -74, 35, 65, -50};
