// Generated by generate_test_data.py using tensorflow version 2.10.0 (Keras version 2.10.0).
// Interpreter from tensorflow version 2.10.0 and revision v2.10.0-rc3-6-g359c3cdfc5f.
#pragma once
#include <stdint.h>

const int8_t conv_1_x_n_1_output_ref[48] = {-62, -35, -127, -96, 43,  -63,  -39,  26, -50, -82, 47, -31,
                                            -12, -43, -91,  -79, -38, -100, -27,  32, -72, -49, 28, -127,
                                            -58, -31, -124, -73, 47,  -83,  -127, -4, -82, -64, 29, -81,
                                            -68, -9,  -113, -22, -77, -77,  -100, 23, -64, -59, 60, -5};
