// Generated by generate_test_data.py using tensorflow version 2.10.0 (Keras version 2.10.0).
// Interpreter from tensorflow version 2.10.0 and revision v2.10.0-rc3-6-g359c3cdfc5f.
#pragma once
#include <stdint.h>

const int8_t conv_1_x_n_1_weights[18] =
    {27, 85, -127, 26, -75, -106, 124, 29, 73, -36, 20, 127, 120, -19, -17, -121, 127, -48};
