// Generated by generate_test_data.py using tensorflow version 2.10.0 (Keras version 2.10.0).
// Interpreter from tensorflow version 2.10.0 and revision upstream/v2.10.0-0-g359c3cdfc5f.
#pragma once
#include <stdint.h>

const int8_t conv_1_x_n_1_weights[36] = {107, -25, -34, -55, 53,   98,   -127, 73,  89,   -84, -35, 54,
                                         32,  -74, -67, 25,  -127, -107, -76,  -96, -107, 62,  33,  19,
                                         56,  114, -61, 100, 73,   -40,  36,   74,  127,  -44, 83,  -47};
