// Generated by fully_connected_settings_flt.py using PyTorch version 2.10.0+cu128.
const float16_t fully_connected_medium_f16_biases_data[32] = {
    (float16_t)-0.391845703f, (float16_t)0.0704956055f,  (float16_t)0.28515625f,   (float16_t)0.109436035f,
    (float16_t)0.256347656f,  (float16_t)0.0816040039f,  (float16_t)0.277099609f,  (float16_t)-0.411132812f,
    (float16_t)-0.125732422f, (float16_t)0.00848388672f, (float16_t)-0.127929688f, (float16_t)-0.249511719f,
    (float16_t)0.0876464844f, (float16_t)0.0687866211f,  (float16_t)0.291748047f,  (float16_t)0.0352172852f,
    (float16_t)0.311279297f,  (float16_t)-0.267333984f,  (float16_t)0.0938720703f, (float16_t)0.341308594f,
    (float16_t)-0.219726562f, (float16_t)-0.099609375f,  (float16_t)-0.470703125f, (float16_t)0.269042969f,
    (float16_t)-0.135375977f, (float16_t)0.0728149414f,  (float16_t)-0.353271484f, (float16_t)-0.34375f,
    (float16_t)-0.172119141f, (float16_t)0.284667969f,   (float16_t)-0.465332031f, (float16_t)0.25f};
