// Generated by fully_connected_settings_flt.py using PyTorch version 2.10.0+cu128.
const float16_t fully_connected_medium_f16_output_ref_data[32] = {
    (float16_t)1.34863281f,  (float16_t)-0.749023438f, (float16_t)9.5625f,      (float16_t)-1.29980469f,
    (float16_t)-6.71484375f, (float16_t)4.6796875f,    (float16_t)3.08984375f,  (float16_t)-14.6640625f,
    (float16_t)-1.01660156f, (float16_t)3.13671875f,   (float16_t)2.42773438f,  (float16_t)-0.725585938f,
    (float16_t)11.890625f,   (float16_t)2.91992188f,   (float16_t)-1.24609375f, (float16_t)-11.8984375f,
    (float16_t)4.32421875f,  (float16_t)0.538574219f,  (float16_t)-4.578125f,   (float16_t)-1.59863281f,
    (float16_t)-13.3203125f, (float16_t)-2.30078125f,  (float16_t)14.3359375f,  (float16_t)2.05078125f,
    (float16_t)-3.96484375f, (float16_t)-3.2734375f,   (float16_t)-4.43359375f, (float16_t)-19.9375f,
    (float16_t)-1.48046875f, (float16_t)3.68359375f,   (float16_t)11.828125f,   (float16_t)-6.171875f};
