// Generated by generate_test_data.py using tensorflow version 2.11.0 (Keras version 2.11.0).
// Interpreter from tensorflow version 2.11.0 and revision v2.11.0-rc2-17-gd5b57ca93e5.
#pragma once
#include <stdint.h>

const int8_t conv_out_activation_input[36] = {125, 105, -111, -15, -68,  114, 28,  -72, 85,  54,  70,  -117,
                                              -26, 47,  77,   -24, -106, -28, 59,  33,  -77, -46, 101, 8,
                                              14,  -55, -63,  -73, 12,   120, -67, -93, 79,  33,  48,  -22};
