// Generated by generate_test_data.py using tensorflow version 2.10.0 (Keras version 2.10.0).
// Interpreter from tensorflow version 2.10.0 and revision v2.10.0-rc3-6-g359c3cdfc5f.
#pragma once
#include <stdint.h>

const int8_t conv_out_activation_input[18] =
    {23, -12, -1, -29, 63, -36, 83, -71, -26, 66, 56, -37, -6, -95, -18, 3, -23, 21};
