// Generated by generate_test_data.py using tensorflow version 2.11.0 (Keras version 2.11.0).
// Interpreter from tensorflow version 2.11.0 and revision v2.11.0-rc2-17-gd5b57ca93e5.
#pragma once
#include <stdint.h>

const int8_t conv_out_activation_output_ref[18] =
    {7, -61, 27, -61, 35, -46, 11, -39, 86, -46, 27, -61, -44, -61, -28, -61, -13, -61};
