// Generated by generate_test_data.py using tensorflow version 2.10.0 (Keras version 2.10.0).
// Interpreter from tensorflow version 2.10.0 and revision v2.10.0-rc3-6-g359c3cdfc5f.
#pragma once
#include <stdint.h>

const int8_t conv_out_activation_output_ref[18] =
    {74, 66, 33, 53, 89, 92, 36, 103, -61, 4, 48, 67, -9, 107, -19, 86, 22, 77};
