// Generated by generate_test_data.py using tensorflow version 2.11.0 (Keras version 2.11.0).
// Interpreter from tensorflow version 2.11.0 and revision v2.11.0-rc2-17-gd5b57ca93e5.
#pragma once
#include <stdint.h>

const int8_t conv_out_activation_weights[72] = {
    10,  -29, -33,  73,   -93, 42, -59,  64,   26, 69,  -20, -115, -118, 70,  127, 80,  16,  -19,
    -46, 58,  -49,  -58,  116, 36, 69,   80,   67, 121, 89,  -29,  50,   -81, 82,  -20, 76,  29,
    6,   -8,  -127, -14,  28,  93, -123, -45,  14, 46,  -60, 22,   -98,  43,  101, 56,  -52, -87,
    -68, -32, 77,   -108, 37,  99, 41,   -127, -3, 115, -70, -78,  75,   -96, 6,   40,  -95, 54};
