// Generated by generate_test_data.py using tensorflow version 2.10.0 (Keras version 2.10.0).
// Interpreter from tensorflow version 2.10.0 and revision v2.10.0-rc3-6-g359c3cdfc5f.
#pragma once
#include <stdint.h>

const int8_t conv_out_activation_weights[36] = {-4,  -65, -85, -9, -108, -106, -17,  17,  93,  -97, -127, 23,
                                                -81, 42,  -12, 0,  29,   40,   -90,  -74, -10, -42, 74,   -104,
                                                -58, 74,  17,  5,  -58,  123,  -127, 59,  -90, -5,  16,   -104};
