// Generated by conv_settings_flt.py using PyTorch version 2.10.0+cu128.
const float16_t conv_basic_f16_biases_data[10] = {(float16_t)-0.412841797f,
                                                  (float16_t)-0.366455078f,
                                                  (float16_t)0.0196075439f,
                                                  (float16_t)-0.110351562f,
                                                  (float16_t)0.0523986816f,
                                                  (float16_t)0.111022949f,
                                                  (float16_t)0.187011719f,
                                                  (float16_t)-0.484863281f,
                                                  (float16_t)0.0728149414f,
                                                  (float16_t)0.3203125f};
