// Generated by generate_test_data.py using flatc version 25.9.23
// Interpreter from tflite_micro runtime version 0.dev20260203175027-g88f8587.
#pragma once
#include <stdint.h>

const int8_t lstm_stateful_batch_major_multibatch_s16_cell_gate_input_weights[42] = {
    49, 34, 68,  -90, -112, -1, 22,   -86, -44, -96, 84,  73,  118, 23,  -40, 88,  -83, 85, -61, 70, -32,
    -4, -4, 109, -25, -77,  -9, -122, -84, 122, 44,  -15, -43, -60, -37, 64,  -85, 73,  43, 74,  23, 25};
