// Generated by generate_test_data.py using flatc version 25.9.23
// Interpreter from tflite_micro runtime version 0.dev20260203175027-g88f8587.
#pragma once
#include <stdint.h>

const int8_t lstm_stateful_batch_major_multibatch_s16_cell_gate_hidden_weights[49] = {
    -6,   -40, 107, -122, -109, -62, 103, 112, -125, 57,  -80, -126, -93, -77, 30, 2,   -32,
    30,   35,  37,  10,   45,   -3,  -96, 20,  31,   110, 121, -74,  -10, -82, 76, -63, 117,
    -111, 24,  -23, -81,  49,   102, -45, 97,  48,   -9,  -75, -90,  5,   88,  -50};
