// Generated by generate_test_data.py using flatc version 25.9.23
// Interpreter from tflite_micro runtime version 0.dev20260203175027-g88f8587.
#pragma once
#include <stdint.h>

const int64_t lstm_stateful_batch_major_multibatch_s16_forget_gate_bias[7] =
    {20637, 23729, 19724, 13194, 29244, 9521, 32113};
