// Generated by generate_test_data.py using flatc version 25.9.23
// Interpreter from tflite_micro runtime version 0.dev20260203175027-g88f8587.
#pragma once
#include <stdint.h>

const int8_t lstm_stateful_batch_major_multibatch_s16_forget_gate_input_weights[42] = {
    -57, -94, 41,  110, 49,   -128, 110, -120, 61,  -17,  26, -68, 121, -74, 76,   -29,  59,  -32, -67, 13,  14,
    67,  116, -31, 94,  -101, -114, 60,  120,  -18, -105, 6,  123, 97,  -95, -100, -108, -11, 116, 73,  -61, -92};
