// Generated by generate_test_data.py using flatc version 25.9.23
// Interpreter from tflite_micro runtime version 0.dev20260203175027-g88f8587.
#pragma once
#include <stdint.h>

const int8_t lstm_stateful_batch_major_multibatch_s16_forget_gate_hidden_weights[49] = {
    -96, 89, 37,   -113, -123, 81, -28, 111, -38, 88,  78,  -56,  113, -96, 44,   -85, -13,
    -41, 76, -126, 8,    -10,  48, -84, 96,  40,  -78, -40, -43,  49,  -94, -122, -15, 76,
    47,  41, -10,  -17,  -4,   33, 9,   -57, -24, -98, -23, -100, 112, -51, -74};
