// Generated by generate_test_data.py using flatc version 25.9.23
// Interpreter from tflite_micro runtime version 0.dev20260203175027-g88f8587.
#pragma once
#include <stdint.h>

const int8_t lstm_stateful_batch_major_multibatch_s16_input_gate_hidden_weights[49] = {
    81,  -28, -21, 121, 117, 24,  47, -1,  110, 76,  -71, -77, 66,  42,  45, 74,  90,
    56,  -92, -40, -25, -74, -55, -3, -65, 39,  22,  -10, 63,  123, 100, 56, -94, -123,
    -18, -91, 55,  -98, 8,   -44, 22, -71, -11, -60, 81,  45,  55,  119, 3};
