// Generated by generate_test_data.py using flatc version 25.9.23
// Interpreter from tflite_micro runtime version 0.dev20260203175027-g88f8587.
#pragma once
#include <stdint.h>

const int8_t lstm_stateful_batch_major_multibatch_s16_input_gate_input_weights[42] = {
    38, -47, -111, -26, 124, -69, -37, 116,  53, 5,  -106, 38,  77,  14, 35, 38, -53,  -44, 76,  -26, 17,
    49, -85, -120, 80,  58,  -56, -51, -126, 26, 17, -57,  -78, -74, 18, 57, 88, -121, -25, -40, -89, -3};
