// Generated by generate_test_data.py using flatc version 25.9.23
// Interpreter from tflite_micro runtime version 0.dev20260203175027-g88f8587.
#pragma once
#include <stdint.h>

const int16_t lstm_stateful_batch_major_multibatch_s16_input_tensor[24] = {
    28057, 25392, -13007, -4876, -9976, -24994, -29540, 16696, 12431, -17737, -20149, 5250,
    3699,  21061, -6754,  31374, 4217,  7014,   16679,  -4841, 12023, 24303,  26425,  -26243};
