// Generated by generate_test_data.py using flatc version 25.9.23
// Interpreter from tflite_micro runtime version 0.dev20260203175027-g88f8587.
#pragma once
#include <stdint.h>

const int8_t lstm_stateful_batch_major_multibatch_s16_output_gate_hidden_weights[49] = {
    -44, -33, -65, 37,  -118, 53,  61, -2,   -106, -110, 106, 90, -56, -19, 44, 6,    71,
    -43, -12, -47, 75,  -25,  -62, 18, -104, -29,  -33,  -83, 30, -91, 6,   -2, -120, 38,
    -96, 67,  87,  -49, -58,  -48, 29, -100, -71,  -85,  -14, 62, -24, 118, -38};
