// Generated by generate_test_data.py using flatc version 25.9.23
// Interpreter from tflite_micro runtime version 0.dev20260203175027-g88f8587.
#pragma once
#include <stdint.h>

const int8_t lstm_stateful_batch_major_multibatch_s16_output_gate_input_weights[42] = {
    -74, 30, -26, -97, 44, -26, -1, -54, 15, 91, 99, -32, -80, -28, -127, -22, 105, 55,  110, 113, 126,
    4,   8,  107, 113, 82, -5,  21, 15,  46, 64, 13, -94, -23, 4,   -102, 9,   -88, -30, 69,  -79, 71};
