// Generated by generate_test_data.py using flatc version 25.9.23
// Interpreter from tflite_micro runtime version 0.dev20260203175027-g88f8587.
#pragma once
#include <stdint.h>

const int16_t lstm_stateful_batch_major_multibatch_s16_output[28] = {
    191, -140, 117, -230, -470, 40,  -90, 203,  -123, -37, 29,   98,   11,   5,
    -89, -284, 239, 160,  -320, -51, 99,  -242, -313, 62,  -275, -292, -170, 53};
