// Generated by test_settings.py using tensorflow version 2.11.0 (Keras version 2.11.0).
// Interpreter from tflite_runtime version 2.14.0 and revision 0.6.0-147738-g1448daa62f0.
#pragma once
#include <stdint.h>

const int32_t transpose_conv_1_output_shift[3] = {-12, -12, -12};
