// Generated by test_settings.py using tensorflow version 2.14.0 (Keras version 2.14.0).
// Interpreter from tflite_runtime version 2.16.0dev20231108 and revision 0.6.0-155953-g2bcb825a248.
#pragma once
#define BASIC_2_INT4_OUT_CH 15
#define BASIC_2_INT4_IN_CH 5
#define BASIC_2_INT4_INPUT_W 15
#define BASIC_2_INT4_INPUT_H 15
#define BASIC_2_INT4_DST_SIZE 1815
#define BASIC_2_INT4_INPUT_SIZE 1125
#define BASIC_2_INT4_OUT_ACTIVATION_MIN -128
#define BASIC_2_INT4_OUT_ACTIVATION_MAX 127
#define BASIC_2_INT4_INPUT_BATCHES 1
#define BASIC_2_INT4_FILTER_X 5
#define BASIC_2_INT4_FILTER_Y 5
#define BASIC_2_INT4_STRIDE_X 1
#define BASIC_2_INT4_STRIDE_Y 1
#define BASIC_2_INT4_PAD_X 0
#define BASIC_2_INT4_PAD_Y 0
#define BASIC_2_INT4_OUTPUT_W 11
#define BASIC_2_INT4_OUTPUT_H 11
#define BASIC_2_INT4_INPUT_OFFSET 0
#define BASIC_2_INT4_OUTPUT_OFFSET 0
#define BASIC_2_INT4_DILATION_X 1
#define BASIC_2_INT4_DILATION_Y 1
