// Generated by generate_test_data.py using tensorflow version 2.10.0 (Keras version 2.10.0).
// Interpreter from tensorflow version 2.10.0 and revision v2.10.0-rc3-6-g359c3cdfc5f.
#pragma once
#include <stdint.h>

const int64_t fc_int16_slow_biases[11] =
    {4154170, 4149344, 4152773, 4159504, 4155440, 4152646, 4148963, 4160139, 4149090, 4149979, 4156837};
