// Generated by generate_test_data.py using tensorflow version 2.10.0 (Keras version 2.10.0).
// Interpreter from tensorflow version 2.10.0 and revision v2.10.0-rc3-6-g359c3cdfc5f.
#pragma once
#include <stdint.h>

const int16_t fc_int16_slow_output_ref[33] = {32762, 32762, 32762, 32762, 32762, 32762, 32762, 32762, 32762,
                                              32762, 32762, 32764, 32763, 32763, 32764, 32764, 32763, 32763,
                                              32764, 32763, 32763, 32764, 32763, 32763, 32763, 32763, 32763,
                                              32763, 32763, 32763, 32763, 32763, 32763};
