// Generated by generate_test_data.py using tensorflow version 2.17.0 (Keras version 3.5.0).
// Interpreter from tensorflow version 2.17.0 and revision v2.17.0-rc1-2-gad6d8cc177d.
#pragma once
#include <stdint.h>

const int8_t transpose_wchn_input_tensor[72] = {
    6,   -38, -61,  50,   -128, 102, 48,   -42,  9,   86,  71,   -63, -42,  118, -71,  18,  59,  113,
    -60, -72, 21,   -65,  57,   120, 42,   -114, -10, -53, 59,   19,  -60,  42,  -108, -16, 75,  -125,
    75,  57,  -102, 67,   27,   -51, -106, 117,  -24, 124, -101, 102, -117, -41, 36,   -20, -85, -48,
    -78, -81, -29,  -105, -80,  -35, -121, -64,  103, -3,  -78,  122, -122, 11,  -125, 14,  88,  85};
