// Generated by generate_test_data.py using tensorflow version 2.17.0 (Keras version 3.5.0).
// Interpreter from tensorflow version 2.17.0 and revision v2.17.0-rc1-2-gad6d8cc177d.
#pragma once
#include <stdint.h>

const int8_t transpose_wchn_output[72] = {
    6,    -60, 75,  -78,  48,  42,  -106, -121, -42,  -60, -117, -122, -38,  -72, 57,  -81,  -42, -114,
    117,  -64, 118, 42,   -41, 11,  -61,  21,   -102, -29, 9,    -10,  -24,  103, -71, -108, 36,  -125,
    50,   -65, 67,  -105, 86,  -53, 124,  -3,   18,   -16, -20,  14,   -128, 57,  27,  -80,  71,  59,
    -101, -78, 59,  75,   -85, 88,  102,  120,  -51,  -35, -63,  19,   102,  122, 113, -125, -48, 85};
