// Generated by pooling_settings_flt.py using PyTorch version 2.10.0+cu128.
const float32_t avgpooling_f32_2_input_tensor[9] = {-0.746911585f,
                                                    0.0804697201f,
                                                    2.93615198f,
                                                    4.92949867f,
                                                    6.02535439f,
                                                    5.67717457f,
                                                    1.08524644f,
                                                    4.17048693f,
                                                    8.64692497f};
