// Generated by pooling_settings_flt.py using PyTorch version 2.10.0+cu128.
const float32_t avgpooling_f32_2_output_ref[9] =
    {2.09129357f, 3.052912f, 4.30666351f, 1.75594461f, 3.42543697f, 5.75341749f, 3.00737262f, 5.09792042f, 6.0f};
