// Generated by test_settings.py using tensorflow version 2.15.0-dev20231004 (Keras version 2.15.0.dev2023092207).
// Interpreter from tflite_micro version 0.dev20231002060915-gec477d5c and revision None.
#pragma once
#include <stdint.h>

const int8_t fully_connected_int4_2_weights[14] = {193, 220, 79, 36, 224, 160, 229, 128, 211, 16, 142, 221, 109, 205};
