// Generated by fully_connected_settings_flt.py using PyTorch version 2.10.0+cu128.
const float32_t fully_connected_match_mve_0_f32_biases_data[9] = {-0.104332983f,
                                                                  -0.116652645f,
                                                                  0.6125018f,
                                                                  0.159252644f,
                                                                  -0.62134397f,
                                                                  -0.389548987f,
                                                                  -0.508505881f,
                                                                  -0.502078652f,
                                                                  -0.68410778f};
