// Generated by fully_connected_settings_flt.py using PyTorch version 2.10.0+cu128.
const float32_t fully_connected_match_mve_0_f32_output_ref_data[9] = {-1.59747005f,
                                                                      0.725607693f,
                                                                      8.57967186f,
                                                                      4.67774343f,
                                                                      -3.22920036f,
                                                                      0.155097991f,
                                                                      5.0174942f,
                                                                      5.19956541f,
                                                                      -3.82436037f};
