// Generated by depthwise_conv_settings_flt.py using PyTorch version 2.10.0+cu128.
#include "biases_data.h"
#include "config_data.h"
#include "input_data.h"
#include "output_ref_data.h"
#include "weights_data.h"
