// Generated by depthwise_conv_settings_flt.py using PyTorch version 2.10.0+cu128.
const float16_t depthwise_match_sub_block_f16_biases_data[9] = {(float16_t)-0.375f,
                                                                (float16_t)0.357177734f,
                                                                (float16_t)-0.463378906f,
                                                                (float16_t)-0.0497741699f,
                                                                (float16_t)0.0266876221f,
                                                                (float16_t)-0.145996094f,
                                                                (float16_t)0.466796875f,
                                                                (float16_t)-0.343017578f,
                                                                (float16_t)-0.412597656f};
