// Generated by depthwise_conv_settings_flt.py using PyTorch version 2.10.0+cu128.
const float16_t depthwise_match_sub_block_f16_weights_data[36] = {
    (float16_t)-0.474121094f,  (float16_t)-0.243652344f, (float16_t)0.376220703f,     (float16_t)0.116699219f,
    (float16_t)-0.464599609f,  (float16_t)0.490722656f,  (float16_t)0.260986328f,     (float16_t)-0.0271453857f,
    (float16_t)0.384521484f,   (float16_t)0.157592773f,  (float16_t)-0.481689453f,    (float16_t)0.0564575195f,
    (float16_t)0.00324058533f, (float16_t)0.126831055f,  (float16_t)0.171630859f,     (float16_t)0.383056641f,
    (float16_t)0.482421875f,   (float16_t)0.0545959473f, (float16_t)-0.000357866287f, (float16_t)0.232788086f,
    (float16_t)-0.390869141f,  (float16_t)0.682128906f,  (float16_t)0.403076172f,     (float16_t)0.568359375f,
    (float16_t)0.289794922f,   (float16_t)-0.120056152f, (float16_t)-0.116638184f,    (float16_t)0.234619141f,
    (float16_t)-0.439453125f,  (float16_t)-0.244140625f, (float16_t)0.578613281f,     (float16_t)0.141601562f,
    (float16_t)0.131469727f,   (float16_t)0.301513672f,  (float16_t)-0.520019531f,    (float16_t)0.288574219f};
