// Generated by depthwise_conv_settings_flt.py using PyTorch version 2.10.0+cu128.
const float16_t depthwise_basic_f16_biases_data[8] = {(float16_t)-0.194580078f,
                                                      (float16_t)-0.470214844f,
                                                      (float16_t)0.136962891f,
                                                      (float16_t)0.052520752f,
                                                      (float16_t)0.222412109f,
                                                      (float16_t)0.144042969f,
                                                      (float16_t)-0.0728149414f,
                                                      (float16_t)0.153930664f};
