var searchData=
[
  ['c_0',['c',['../group__genPubTypes.html#a3c6f6f6780d5503e1bc87fc432c3af69',1,'cmsis_nn_dims']]],
  ['cell_1',['cell',['../group__genPubTypes.html#ad52e92c89f8d8a059e92c09dc32e54d7',1,'cmsis_nn_lstm_clip_params']]],
  ['cell_5fgate_2',['cell_gate',['../group__genPubTypes.html#a1ea12183e484f0f5f225b21ad725d70f',1,'cmsis_nn_lstm_context']]],
  ['cell_5fgate_5fbias_3',['cell_gate_bias',['../group__genPubTypes.html#a48813ae66477c5eb6e6defddb4324fe8',1,'cmsis_nn_lstm_params']]],
  ['cell_5fstate_5fshift_4',['cell_state_shift',['../group__genPubTypes.html#ae586c01f707fa04979e4ec854460dbe3',1,'cmsis_nn_lstm_params']]],
  ['cell_5fto_5fforget_5fscaling_5',['cell_to_forget_scaling',['../group__genPubTypes.html#a6b4a4581049e1a39ebd26ed12307e2a4',1,'cmsis_nn_lstm_params']]],
  ['cell_5fto_5finput_5fscaling_6',['cell_to_input_scaling',['../group__genPubTypes.html#ae82c04d8afa61717a605e462e84e159a',1,'cmsis_nn_lstm_params']]],
  ['cell_5fto_5foutput_5fscaling_7',['cell_to_output_scaling',['../group__genPubTypes.html#a8cb86900d241b7c3eb2dc0df9119b282',1,'cmsis_nn_lstm_params']]],
  ['cell_5fvariance_8',['cell_variance',['../group__genPubTypes.html#ae96db03c795f5d8e70257a3b794e6263',1,'cmsis_nn_lstm_guard_params']]],
  ['cell_5fweight_9',['cell_weight',['../group__genPubTypes.html#ad6496daaebb61bc6a94efcbaf60bb195',1,'cmsis_nn_layer_norm']]],
  ['ch_5fin_5fblock_5fmve_10',['CH_IN_BLOCK_MVE',['../arm__nnsupportfunctions_8h.html#ace380daf8e374d9ab4aa50095d1b39b1',1,'arm_nnsupportfunctions.h']]],
  ['ch_5fmult_11',['ch_mult',['../group__genPubTypes.html#ae5ebf7e8da576d0475859ec74be90b55',1,'cmsis_nn_dw_conv_params']]],
  ['clamp_12',['CLAMP',['../arm__nnsupportfunctions_8h.html#abe05f0e80d965ae31dec16ba4063f48a',1,'arm_nnsupportfunctions.h']]],
  ['clip_13',['clip',['../group__genPubTypes.html#aa3fd35f1c383157b56d88055405be64a',1,'cmsis_nn_lstm_params']]],
  ['cmsis_20nn_20software_20library_14',['CMSIS NN Software Library',['../index.html',1,'']]],
  ['cmsis_5fnn_5factivation_15',['cmsis_nn_activation',['../group__genPubTypes.html#structcmsis__nn__activation',1,'']]],
  ['cmsis_5fnn_5fcontext_16',['cmsis_nn_context',['../group__genPubTypes.html#structcmsis__nn__context',1,'']]],
  ['cmsis_5fnn_5fconv_5fparams_17',['cmsis_nn_conv_params',['../group__genPubTypes.html#structcmsis__nn__conv__params',1,'']]],
  ['cmsis_5fnn_5fdims_18',['cmsis_nn_dims',['../group__genPubTypes.html#structcmsis__nn__dims',1,'']]],
  ['cmsis_5fnn_5fdw_5fconv_5fparams_19',['cmsis_nn_dw_conv_params',['../group__genPubTypes.html#structcmsis__nn__dw__conv__params',1,'']]],
  ['cmsis_5fnn_5ffc_5fparams_20',['cmsis_nn_fc_params',['../group__genPubTypes.html#structcmsis__nn__fc__params',1,'']]],
  ['cmsis_5fnn_5flayer_5fnorm_21',['cmsis_nn_layer_norm',['../group__genPubTypes.html#structcmsis__nn__layer__norm',1,'']]],
  ['cmsis_5fnn_5flstm_5fclip_5fparams_22',['cmsis_nn_lstm_clip_params',['../group__genPubTypes.html#structcmsis__nn__lstm__clip__params',1,'']]],
  ['cmsis_5fnn_5flstm_5fcontext_23',['cmsis_nn_lstm_context',['../group__genPubTypes.html#structcmsis__nn__lstm__context',1,'']]],
  ['cmsis_5fnn_5flstm_5fdims_24',['cmsis_nn_lstm_dims',['../group__genPubTypes.html#structcmsis__nn__lstm__dims',1,'']]],
  ['cmsis_5fnn_5flstm_5fguard_5fparams_25',['cmsis_nn_lstm_guard_params',['../group__genPubTypes.html#structcmsis__nn__lstm__guard__params',1,'']]],
  ['cmsis_5fnn_5flstm_5fparams_26',['cmsis_nn_lstm_params',['../group__genPubTypes.html#structcmsis__nn__lstm__params',1,'']]],
  ['cmsis_5fnn_5fper_5fchannel_5fquant_5fparams_27',['cmsis_nn_per_channel_quant_params',['../group__genPubTypes.html#structcmsis__nn__per__channel__quant__params',1,'']]],
  ['cmsis_5fnn_5fper_5ftensor_5fquant_5fparams_28',['cmsis_nn_per_tensor_quant_params',['../group__genPubTypes.html#structcmsis__nn__per__tensor__quant__params',1,'']]],
  ['cmsis_5fnn_5fpool_5fparams_29',['cmsis_nn_pool_params',['../group__genPubTypes.html#structcmsis__nn__pool__params',1,'']]],
  ['cmsis_5fnn_5fscaling_30',['cmsis_nn_scaling',['../group__genPubTypes.html#structcmsis__nn__scaling',1,'']]],
  ['cmsis_5fnn_5fsoftmax_5flut_5fs16_31',['cmsis_nn_softmax_lut_s16',['../group__genPubTypes.html#structcmsis__nn__softmax__lut__s16',1,'']]],
  ['cmsis_5fnn_5fsvdf_5fparams_32',['cmsis_nn_svdf_params',['../group__genPubTypes.html#structcmsis__nn__svdf__params',1,'']]],
  ['cmsis_5fnn_5ftile_33',['cmsis_nn_tile',['../group__genPubTypes.html#structcmsis__nn__tile',1,'']]],
  ['cmsis_5fnn_5ftranspose_5fconv_5fparams_34',['cmsis_nn_transpose_conv_params',['../group__genPubTypes.html#structcmsis__nn__transpose__conv__params',1,'']]],
  ['concatenation_20functions_35',['Concatenation Functions',['../group__Concatenation.html',1,'']]],
  ['convolution_36',['Convolution',['../group__supportConvolution.html',1,'']]],
  ['convolution_20functions_37',['Convolution Functions',['../group__NNConv.html',1,'']]]
];
