var searchData=
[
  ['c_0',['c',['../group__genPubTypes.html#a3c6f6f6780d5503e1bc87fc432c3af69',1,'cmsis_nn_dims']]],
  ['cell_5fclip_1',['cell_clip',['../group__genPubTypes.html#a4991bc5b842b96232566243c0bfd4c94',1,'cmsis_nn_lstm_params']]],
  ['cell_5fgate_2',['cell_gate',['../group__genPubTypes.html#acd208e3c48b975f358d9ad705c296f8a',1,'cmsis_nn_lstm_params']]],
  ['cell_5fscale_5fpower_3',['cell_scale_power',['../group__genPubTypes.html#a75abf1a91aca9e0407c861f01150f52a',1,'cmsis_nn_lstm_params']]],
  ['cell_5fstate_4',['cell_state',['../group__genPubTypes.html#a34cb41690c431bd9a3a8241edde8a22e',1,'cmsis_nn_lstm_context']]],
  ['ch_5fin_5fblock_5fmve_5',['CH_IN_BLOCK_MVE',['../arm__nnsupportfunctions_8h.html#ace380daf8e374d9ab4aa50095d1b39b1',1,'arm_nnsupportfunctions.h']]],
  ['ch_5fmult_6',['ch_mult',['../group__genPubTypes.html#ae5ebf7e8da576d0475859ec74be90b55',1,'cmsis_nn_dw_conv_params']]],
  ['clamp_7',['CLAMP',['../arm__nnsupportfunctions_8h.html#abe05f0e80d965ae31dec16ba4063f48a',1,'arm_nnsupportfunctions.h']]],
  ['cmsis_20nn_20software_20library_8',['CMSIS NN Software Library',['../index.html',1,'']]],
  ['cmsis_5fnn_5factivation_9',['cmsis_nn_activation',['../group__genPubTypes.html#structcmsis__nn__activation',1,'']]],
  ['cmsis_5fnn_5fcontext_10',['cmsis_nn_context',['../group__genPubTypes.html#structcmsis__nn__context',1,'']]],
  ['cmsis_5fnn_5fconv_5fparams_11',['cmsis_nn_conv_params',['../group__genPubTypes.html#structcmsis__nn__conv__params',1,'']]],
  ['cmsis_5fnn_5fdims_12',['cmsis_nn_dims',['../group__genPubTypes.html#structcmsis__nn__dims',1,'']]],
  ['cmsis_5fnn_5fdw_5fconv_5fparams_13',['cmsis_nn_dw_conv_params',['../group__genPubTypes.html#structcmsis__nn__dw__conv__params',1,'']]],
  ['cmsis_5fnn_5ffc_5fparams_14',['cmsis_nn_fc_params',['../group__genPubTypes.html#structcmsis__nn__fc__params',1,'']]],
  ['cmsis_5fnn_5flstm_5fcontext_15',['cmsis_nn_lstm_context',['../group__genPubTypes.html#structcmsis__nn__lstm__context',1,'']]],
  ['cmsis_5fnn_5flstm_5fdims_16',['cmsis_nn_lstm_dims',['../group__genPubTypes.html#structcmsis__nn__lstm__dims',1,'']]],
  ['cmsis_5fnn_5flstm_5fgate_17',['cmsis_nn_lstm_gate',['../group__genPubTypes.html#structcmsis__nn__lstm__gate',1,'']]],
  ['cmsis_5fnn_5flstm_5fparams_18',['cmsis_nn_lstm_params',['../group__genPubTypes.html#structcmsis__nn__lstm__params',1,'']]],
  ['cmsis_5fnn_5fper_5fchannel_5fquant_5fparams_19',['cmsis_nn_per_channel_quant_params',['../group__genPubTypes.html#structcmsis__nn__per__channel__quant__params',1,'']]],
  ['cmsis_5fnn_5fper_5ftensor_5fquant_5fparams_20',['cmsis_nn_per_tensor_quant_params',['../group__genPubTypes.html#structcmsis__nn__per__tensor__quant__params',1,'']]],
  ['cmsis_5fnn_5fpool_5fparams_21',['cmsis_nn_pool_params',['../group__genPubTypes.html#structcmsis__nn__pool__params',1,'']]],
  ['cmsis_5fnn_5fscaling_22',['cmsis_nn_scaling',['../group__genPubTypes.html#structcmsis__nn__scaling',1,'']]],
  ['cmsis_5fnn_5fsoftmax_5flut_5fs16_23',['cmsis_nn_softmax_lut_s16',['../group__genPubTypes.html#structcmsis__nn__softmax__lut__s16',1,'']]],
  ['cmsis_5fnn_5fsvdf_5fparams_24',['cmsis_nn_svdf_params',['../group__genPubTypes.html#structcmsis__nn__svdf__params',1,'']]],
  ['cmsis_5fnn_5ftile_25',['cmsis_nn_tile',['../group__genPubTypes.html#structcmsis__nn__tile',1,'']]],
  ['cmsis_5fnn_5ftranspose_5fconv_5fparams_26',['cmsis_nn_transpose_conv_params',['../group__genPubTypes.html#structcmsis__nn__transpose__conv__params',1,'']]],
  ['concatenation_20functions_27',['Concatenation Functions',['../group__Concatenation.html',1,'']]],
  ['convolution_28',['Convolution',['../group__supportConvolution.html',1,'']]],
  ['convolution_20functions_29',['Convolution Functions',['../group__NNConv.html',1,'']]]
];
