// Generated by batch_norm_settings_flt.py using PyTorch version 2.10.0+cu128.
const float32_t bn_basic_nhwc_f32_bias[6] =
    {0.0762719065f, 0.0362152457f, 0.0104769394f, -0.00966387242f, -0.0278761461f, -0.0459585339f};
