// Generated by depthwise_conv_settings_flt.py using PyTorch version 2.10.0+cu128.
const float16_t depthwise_2x5_opt_nhwc_chmult16_f16_input_data[42] = {
    (float16_t)0.192871094f,   (float16_t)-0.130371094f, (float16_t)0.836914062f,  (float16_t)-0.56640625f,
    (float16_t)0.863769531f,   (float16_t)0.0140838623f, (float16_t)0.829101562f,  (float16_t)-0.321289062f,
    (float16_t)-0.170654297f,  (float16_t)-0.549804688f, (float16_t)0.362304688f,  (float16_t)0.0971679688f,
    (float16_t)0.875488281f,   (float16_t)0.470703125f,  (float16_t)-0.985839844f, (float16_t)0.0336303711f,
    (float16_t)0.548339844f,   (float16_t)-0.75390625f,  (float16_t)0.836425781f,  (float16_t)0.575683594f,
    (float16_t)-0.0604858398f, (float16_t)0.888671875f,  (float16_t)0.674804688f,  (float16_t)-0.66015625f,
    (float16_t)0.218505859f,   (float16_t)0.439208984f,  (float16_t)0.236328125f,  (float16_t)-0.134399414f,
    (float16_t)-0.110656738f,  (float16_t)0.471679688f,  (float16_t)0.176879883f,  (float16_t)0.398925781f,
    (float16_t)0.771972656f,   (float16_t)-0.521972656f, (float16_t)0.978515625f,  (float16_t)-0.0848999023f,
    (float16_t)-0.0333251953f, (float16_t)-0.4375f,      (float16_t)-0.939453125f, (float16_t)-0.962402344f,
    (float16_t)0.839355469f,   (float16_t)-0.908203125f};
