// Generated by svdf_settings_flt.py using PyTorch version 2.10.0+cu128.
const float16_t svdf_small_f16_bias[6] = {(float16_t)0.191162109f,
                                          (float16_t)-0.105285645f,
                                          (float16_t)-0.11907959f,
                                          (float16_t)-0.0810546875f,
                                          (float16_t)0.0765380859f,
                                          (float16_t)0.0982055664f};
