// Generated by svdf_settings_flt.py using PyTorch version 2.10.0+cu128.
const float16_t svdf_small_f16_initial_state[48] = {
    (float16_t)0.0f, (float16_t)0.0f, (float16_t)0.0f, (float16_t)0.0f, (float16_t)0.0f, (float16_t)0.0f,
    (float16_t)0.0f, (float16_t)0.0f, (float16_t)0.0f, (float16_t)0.0f, (float16_t)0.0f, (float16_t)0.0f,
    (float16_t)0.0f, (float16_t)0.0f, (float16_t)0.0f, (float16_t)0.0f, (float16_t)0.0f, (float16_t)0.0f,
    (float16_t)0.0f, (float16_t)0.0f, (float16_t)0.0f, (float16_t)0.0f, (float16_t)0.0f, (float16_t)0.0f,
    (float16_t)0.0f, (float16_t)0.0f, (float16_t)0.0f, (float16_t)0.0f, (float16_t)0.0f, (float16_t)0.0f,
    (float16_t)0.0f, (float16_t)0.0f, (float16_t)0.0f, (float16_t)0.0f, (float16_t)0.0f, (float16_t)0.0f,
    (float16_t)0.0f, (float16_t)0.0f, (float16_t)0.0f, (float16_t)0.0f, (float16_t)0.0f, (float16_t)0.0f,
    (float16_t)0.0f, (float16_t)0.0f, (float16_t)0.0f, (float16_t)0.0f, (float16_t)0.0f, (float16_t)0.0f};
