// Generated by svdf_settings_flt.py using PyTorch version 2.10.0+cu128.
const float16_t svdf_small_f16_input_sequence[48] = {
    (float16_t)-0.711914062f,  (float16_t)-0.440185547f, (float16_t)-0.81640625f,   (float16_t)0.00646209717f,
    (float16_t)0.633300781f,   (float16_t)-1.08105469f,  (float16_t)-1.03710938f,   (float16_t)0.987792969f,
    (float16_t)-0.8359375f,    (float16_t)-0.806640625f, (float16_t)-1.37988281f,   (float16_t)0.551757812f,
    (float16_t)-0.941894531f,  (float16_t)1.40234375f,   (float16_t)-0.0493774414f, (float16_t)-0.546875f,
    (float16_t)1.42773438f,    (float16_t)0.0186309814f, (float16_t)1.34570312f,    (float16_t)0.853027344f,
    (float16_t)-0.862304688f,  (float16_t)-1.02539062f,  (float16_t)-0.891601562f,  (float16_t)-0.149047852f,
    (float16_t)1.11425781f,    (float16_t)1.16992188f,   (float16_t)0.402587891f,   (float16_t)0.442871094f,
    (float16_t)-1.17480469f,   (float16_t)-1.0390625f,   (float16_t)-0.823242188f,  (float16_t)-0.423583984f,
    (float16_t)-0.0833129883f, (float16_t)-0.375732422f, (float16_t)-1.23925781f,   (float16_t)-0.632324219f,
    (float16_t)1.26855469f,    (float16_t)-0.344726562f, (float16_t)0.184204102f,   (float16_t)0.153930664f,
    (float16_t)0.0788574219f,  (float16_t)-0.5625f,      (float16_t)-0.602050781f,  (float16_t)-0.323730469f,
    (float16_t)-0.078125f,     (float16_t)0.986328125f,  (float16_t)1.1796875f,     (float16_t)-0.305175781f};
