// Generated by svdf_settings_flt.py using PyTorch version 2.10.0+cu128.
const float16_t svdf_small_f16_output_ref[6] = {(float16_t)0.925292969f,
                                                (float16_t)-0.883300781f,
                                                (float16_t)0.302490234f,
                                                (float16_t)-0.490234375f,
                                                (float16_t)-0.383300781f,
                                                (float16_t)-0.0218811035f};
