// Generated by conv_settings_flt.py using PyTorch version 2.10.0+cu128.
const float16_t conv_match_1x1_stride_x_y_2_f16_biases_data[5] = {(float16_t)-0.44140625f,
                                                                  (float16_t)0.308837891f,
                                                                  (float16_t)0.486572266f,
                                                                  (float16_t)-0.199829102f,
                                                                  (float16_t)0.0531921387f};
