// Generated by conv_settings_flt.py using PyTorch version 2.10.0+cu128.
const float16_t conv_match_1x1_stride_x_y_2_f16_output_ref_data[40] = {
    (float16_t)0.525878906f,   (float16_t)0.941894531f,   (float16_t)-0.115966797f, (float16_t)-0.289794922f,
    (float16_t)0.291259766f,   (float16_t)-1.06933594f,   (float16_t)-1.03027344f,  (float16_t)0.600585938f,
    (float16_t)-0.202636719f,  (float16_t)0.220214844f,   (float16_t)-0.966796875f, (float16_t)-0.288574219f,
    (float16_t)0.724609375f,   (float16_t)0.310058594f,   (float16_t)0.0264434814f, (float16_t)-0.458251953f,
    (float16_t)-0.0889282227f, (float16_t)0.319335938f,   (float16_t)0.314941406f,  (float16_t)0.270019531f,
    (float16_t)0.28125f,       (float16_t)0.144042969f,   (float16_t)-0.431396484f, (float16_t)-0.0537414551f,
    (float16_t)0.802246094f,   (float16_t)-0.0825805664f, (float16_t)0.350097656f,  (float16_t)-0.0405883789f,
    (float16_t)0.392089844f,   (float16_t)0.516601562f,   (float16_t)-1.16894531f,  (float16_t)-0.0856323242f,
    (float16_t)1.67382812f,    (float16_t)-0.180541992f,  (float16_t)-1.03417969f,  (float16_t)0.0111923218f,
    (float16_t)-0.46875f,      (float16_t)0.72265625f,    (float16_t)0.221801758f,  (float16_t)-0.49609375f};
