// Generated by conv_settings_flt.py using PyTorch version 2.10.0+cu128.
const float16_t conv_match_1x1_stride_x_y_2_f16_weights_data[25] = {
    (float16_t)-0.366455078f, (float16_t)-0.558105469f, (float16_t)-0.736816406f, (float16_t)-0.559570312f,
    (float16_t)0.366943359f,  (float16_t)0.58203125f,   (float16_t)-0.398193359f, (float16_t)-0.622070312f,
    (float16_t)-0.646484375f, (float16_t)0.705566406f,  (float16_t)0.488769531f,  (float16_t)0.0489501953f,
    (float16_t)0.258056641f,  (float16_t)0.693847656f,  (float16_t)-0.323486328f, (float16_t)-0.15234375f,
    (float16_t)-0.5f,         (float16_t)0.609375f,     (float16_t)0.514648438f,  (float16_t)-0.307861328f,
    (float16_t)-0.396728516f, (float16_t)0.227539062f,  (float16_t)0.0682983398f, (float16_t)-0.570800781f,
    (float16_t)0.212646484f};
