// Generated by test_settings.py using tensorflow version 2.15.0 (Keras version 2.15.0).
// Interpreter from tensorflow version 2.15.0 and revision v2.15.0-rc1-8-g6887368d6d4.
#pragma once
#include <stdint.h>

const int32_t *transpose_conv_4_biases = NULL;
