// Generated by conv_settings_flt.py using PyTorch version 2.10.0+cu128.
const float16_t conv_k5_opt_f16_biases_data[12] = {(float16_t)0.370361328f,
                                                   (float16_t)-0.0276947021f,
                                                   (float16_t)-0.333740234f,
                                                   (float16_t)-0.143188477f,
                                                   (float16_t)-0.0529785156f,
                                                   (float16_t)0.00524139404f,
                                                   (float16_t)0.107666016f,
                                                   (float16_t)-0.155151367f,
                                                   (float16_t)0.0354003906f,
                                                   (float16_t)0.436279297f,
                                                   (float16_t)-0.195922852f,
                                                   (float16_t)0.226806641f};
