// Generated by generate_test_data.py using tensorflow version 2.10.0 (Keras version 2.10.0).
// Interpreter from tensorflow version 2.10.0 and revision v2.10.0-rc3-6-g359c3cdfc5f.
#pragma once
#include <stdint.h>

const int8_t conv_2x3_dilation_input[18] =
    {-40, -61, -31, -102, -9, 63, 54, 120, -32, 101, 107, -102, 95, -82, 111, -61, -30, 26};
