// Generated by generate_test_data.py using tensorflow version 2.10.0 (Keras version 2.10.0).
// Interpreter from tensorflow version 2.10.0 and revision v2.10.0-rc3-6-g359c3cdfc5f.
#pragma once
#include <stdint.h>

const int8_t conv_2x3_dilation_output_ref[18] =
    {-20, -61, -16, -61, 8, -61, 72, -61, -5, -61, 34, -61, 25, -61, 13, -61, 38, -56};
