// Generated by generate_test_data.py using TFL version 2.9.1 as reference.
#pragma once
#include <stdint.h>

const int32_t kernel1x1_stride_x_y_biases[15] =
    {-1265, -21781, 31090, 777, -21763, -26988, -6736, 12144, 20073, 28990, 29794, -27981, 3508, 30053, 28669};
