// Generated by generate_test_data.py using TFL version 2.9.1 as reference.
#pragma once
#include <stdint.h>

const int32_t kernel1x1_stride_x_y_output_mult[15] = {1512859040,
                                                      1335570865,
                                                      1477401423,
                                                      1477401423,
                                                      1477401423,
                                                      1489220628,
                                                      1477401423,
                                                      1512859040,
                                                      1430124600,
                                                      1465582217,
                                                      1477401423,
                                                      1477401423,
                                                      1418305395,
                                                      1477401423,
                                                      1441943806};
