// Generated by generate_test_data.py using tensorflow version 2.10.0 (Keras version 2.10.0).
// Interpreter from tensorflow version 2.10.0 and revision v2.10.0-rc3-6-g359c3cdfc5f.
#pragma once
#include <stdint.h>

const int32_t kernel1x1_stride_x_y_output_shift[15] =
    {-10, -10, -10, -10, -10, -10, -10, -10, -10, -10, -10, -10, -10, -10, -10};
