// Generated by softmax_settings_flt.py using PyTorch version 2.10.0+cu128.
const float16_t softmax_f16_input[10] = {(float16_t)1.0f,
                                         (float16_t)0.25f,
                                         (float16_t)-0.5f,
                                         (float16_t)2.0f,
                                         (float16_t)-1.25f,
                                         (float16_t)-2.0f,
                                         (float16_t)-0.125f,
                                         (float16_t)0.75f,
                                         (float16_t)3.0f,
                                         (float16_t)1.5f};
