// Generated by conv_settings_flt.py using PyTorch version 2.10.0+cu128.
const float16_t conv_match_3x3_dilation_5x5_input_f16_biases_data[2] = {(float16_t)-0.297119141f,
                                                                        (float16_t)-0.199584961f};
