// Generated by conv_settings_flt.py using PyTorch version 2.10.0+cu128.
const float16_t conv_match_3x3_dilation_5x5_input_f16_weights_data[36] = {
    (float16_t)-0.37109375f,   (float16_t)0.479980469f,   (float16_t)0.271728516f,   (float16_t)-0.637207031f,
    (float16_t)-0.730957031f,  (float16_t)-0.0499572754f, (float16_t)0.0319519043f,  (float16_t)0.105407715f,
    (float16_t)0.502441406f,   (float16_t)-0.483154297f,  (float16_t)0.0795288086f,  (float16_t)0.541992188f,
    (float16_t)-0.0484008789f, (float16_t)-0.191650391f,  (float16_t)-0.1171875f,    (float16_t)0.485107422f,
    (float16_t)0.281005859f,   (float16_t)0.4296875f,     (float16_t)0.4921875f,     (float16_t)0.578613281f,
    (float16_t)-0.634765625f,  (float16_t)-0.543457031f,  (float16_t)-0.266845703f,  (float16_t)-0.440185547f,
    (float16_t)-0.518066406f,  (float16_t)-0.551269531f,  (float16_t)-0.0376281738f, (float16_t)0.125732422f,
    (float16_t)0.741210938f,   (float16_t)0.469970703f,   (float16_t)0.240844727f,   (float16_t)0.2421875f,
    (float16_t)-0.470458984f,  (float16_t)0.0317077637f,  (float16_t)-0.184326172f,  (float16_t)0.168823242f};
