// Generated by conv_settings_flt.py using PyTorch version 2.10.0+cu128.
const float16_t conv_match_1xn_8_f16_biases_data[10] = {(float16_t)-0.399169922f,
                                                        (float16_t)-0.357910156f,
                                                        (float16_t)0.0983276367f,
                                                        (float16_t)-0.309814453f,
                                                        (float16_t)0.216796875f,
                                                        (float16_t)0.220825195f,
                                                        (float16_t)-0.415039062f,
                                                        (float16_t)0.0900878906f,
                                                        (float16_t)-0.283691406f,
                                                        (float16_t)0.209594727f};
