// Generated by test_settings.py using tensorflow version 2.11.0 (Keras version 2.11.0).
// Interpreter from tflite_runtime version 2.16.0 and revision 0.6.0-154906-gb2493fdf794.
#pragma once
#define AVGPOOLING_3_OUT_CH 2
#define AVGPOOLING_3_IN_CH 2
#define AVGPOOLING_3_INPUT_W 9
#define AVGPOOLING_3_INPUT_H 1
#define AVGPOOLING_3_DST_SIZE 20
#define AVGPOOLING_3_INPUT_SIZE 18
#define AVGPOOLING_3_OUT_ACTIVATION_MIN -128
#define AVGPOOLING_3_OUT_ACTIVATION_MAX 127
#define AVGPOOLING_3_INPUT_BATCHES 2
#define AVGPOOLING_3_FILTER_X 1
#define AVGPOOLING_3_FILTER_Y 1
#define AVGPOOLING_3_STRIDE_X 2
#define AVGPOOLING_3_STRIDE_Y 1
#define AVGPOOLING_3_PAD_X 0
#define AVGPOOLING_3_PAD_Y 0
#define AVGPOOLING_3_OUTPUT_W 5
#define AVGPOOLING_3_OUTPUT_H 1
