// Generated by test_settings.py using tensorflow version 2.11.0 (Keras version 2.11.0).
// Interpreter from tflite_runtime version 2.16.0 and revision 0.6.0-154906-gb2493fdf794.
#pragma once
#include <stdint.h>

const int8_t avgpooling_3_output_ref[20] = {-21, -36, 23,   44,  18, -91, 103, -100, -91, -79,
                                            -96, -22, -113, -84, 27, 103, -28, -48,  37,  -128};
