// Generated by batch_matmul_settings_flt.py using PyTorch version 2.10.0+cu128.
#include "config_data.h"
#include "lhs_input_tensor.h"
#include "lhs_transposed_tensor.h"
#include "output.h"
#include "rhs_input_tensor.h"
#include "rhs_transposed_tensor.h"
