// Generated by generate_test_data.py using tensorflow version 2.10.0 (Keras version 2.10.0).
// Interpreter from tensorflow version 2.10.0 and revision v2.10.0-rc3-6-g359c3cdfc5f.
#pragma once
#include <stdint.h>

const int64_t dw_int16xint8_fast_test_bias_biases[8] =
    {-795878, -5334291, 1236759, -5395949, 1406307, -3500813, 1515920, -1889120};
