// Generated by generate_test_data.py using tensorflow version 2.10.0 (Keras version 2.10.0).
// Interpreter from tensorflow version 2.10.0 and revision v2.10.0-rc3-6-g359c3cdfc5f.
#pragma once
#include <stdint.h>

const int32_t dw_int16xint8_fast_test_bias_output_mult[8] =
    {1569849899, 1183330628, 1432068229, 1089140565, 1216762566, 1610738992, 1561141528, 1090892326};
