// Generated by generate_test_data.py using tensorflow version 2.10.0 (Keras version 2.10.0).
// Interpreter from tensorflow version 2.10.0 and revision v2.10.0-rc3-6-g359c3cdfc5f.
#pragma once
#include <stdint.h>

const int8_t dw_int16xint8_fast_test_bias_weights[32] = {7,   -117, -110, -16, -102, -127, -3,   -19,  107, -1, -95,
                                                         127, 68,   -24,  122, -18,  -127, -127, -127, 12,  -3, -49,
                                                         -22, -127, 1,    15,  -90,  -97,  -127, 84,   127, -38};
