// Generated by test_settings.py using tensorflow version 2.11.0 (Keras version 2.11.0).
// Interpreter from tflite_runtime version 2.16.0 and revision 0.6.0-154906-gb2493fdf794.
#pragma once
#define AVGPOOLING_4_OUT_CH 2
#define AVGPOOLING_4_IN_CH 2
#define AVGPOOLING_4_INPUT_W 1
#define AVGPOOLING_4_INPUT_H 20
#define AVGPOOLING_4_DST_SIZE 42
#define AVGPOOLING_4_INPUT_SIZE 40
#define AVGPOOLING_4_OUT_ACTIVATION_MIN -128
#define AVGPOOLING_4_OUT_ACTIVATION_MAX 127
#define AVGPOOLING_4_INPUT_BATCHES 3
#define AVGPOOLING_4_FILTER_X 1
#define AVGPOOLING_4_FILTER_Y 3
#define AVGPOOLING_4_STRIDE_X 1
#define AVGPOOLING_4_STRIDE_Y 3
#define AVGPOOLING_4_PAD_X 0
#define AVGPOOLING_4_PAD_Y 0
#define AVGPOOLING_4_OUTPUT_W 1
#define AVGPOOLING_4_OUTPUT_H 7
