// Generated by test_settings.py using tensorflow version 2.11.0 (Keras version 2.11.0).
// Interpreter from tflite_runtime version 2.16.0 and revision 0.6.0-154906-gb2493fdf794.
#pragma once
#include <stdint.h>

const int8_t avgpooling_4_output_ref[42] = {-63, 51, 58,  -12, 17,  -19, -23, -11, -53, 22,  29, 51, 43,  -9,
                                            48,  3,  -30, 8,   -22, 34,  25,  17,  39,  -6,  56, -6, 91,  -21,
                                            2,   19, -39, 34,  -55, -51, 75,  -42, -56, -29, 54, 57, -84, 2};
