// Generated by test_settings.py using tensorflow version 2.14.0 (Keras version 2.14.0).
// Interpreter from tensorflow version 2.14.0 and revision v2.14.0-rc1-21-g4dacf3f368e.
#pragma once
#include <stdint.h>

const int8_t basic_int4_output_ref[20] = {-45,  127, -104, -51, -44, -24, 127, 5,   -41, 61,
                                          -128, 97,  15,   80,  1,   74,  8,   -76, -4,  19};
