// Generated by transpose_conv_settings_flt.py using PyTorch version 2.10.0+cu128.
const float16_t transpose_conv_basic_nhwc_f16_biases[6] = {(float16_t)0.220458984f,
                                                           (float16_t)-0.387939453f,
                                                           (float16_t)-0.273681641f,
                                                           (float16_t)0.242919922f,
                                                           (float16_t)-0.248657227f,
                                                           (float16_t)-0.158081055f};
