// Generated by pad_settings_flt.py using PyTorch version 2.10.0+cu128.
const float16_t pad_int8_2_f16_input_tensor[8] = {(float16_t)3.9609375f,
                                                  (float16_t)-3.25195312f,
                                                  (float16_t)3.578125f,
                                                  (float16_t)-3.20507812f,
                                                  (float16_t)-1.89550781f,
                                                  (float16_t)-1.41601562f,
                                                  (float16_t)1.59863281f,
                                                  (float16_t)3.94140625f};
