// Generated by conv_settings_flt.py using PyTorch version 2.10.0+cu128.
const float32_t conv_match_1x1_stride_x_y_2_f32_biases_data[5] = {-0.441401422f,
                                                                  0.308796972f,
                                                                  0.486553043f,
                                                                  -0.199850842f,
                                                                  0.0531912446f};
