// Generated by generate_test_data.py using tensorflow version 2.17.0 (Keras version 3.5.0).
// Interpreter from tensorflow version 2.17.0 and revision v2.17.0-rc1-2-gad6d8cc177d.
#pragma once
#include <stdint.h>

const int8_t transpose_nchw_input_tensor[72] = {
    94,  -100, 105,  -73, -25,  -68, 76, 117, 15,  -105, -103, 90,  95,   44,  37,  101,  -84, -36,
    19,  10,   -46,  27,  -123, 41,  60, 12,  93,  77,   14,   86,  -103, 29,  29,  -33,  76,  -90,
    -40, -57,  -104, -72, -116, -19, 90, 41,  -84, 13,   -121, -56, -15,  117, -68, -84,  -75, -115,
    -91, 5,    -42,  50,  106,  74,  21, 107, 80,  107,  -45,  -44, -9,   46,  -3,  -104, 2,   -84};
