// Generated by generate_test_data.py using tensorflow version 2.17.0 (Keras version 3.5.0).
// Interpreter from tensorflow version 2.17.0 and revision v2.17.0-rc1-2-gad6d8cc177d.
#pragma once
#include <stdint.h>

const int8_t transpose_nchw_output[72] = {
    94,  105,  -25,  76, 15,  -103, 95,   37,  -84, -100, -73, -68, 117, -105, 90,  44,  101,  -36,
    19,  -46,  -123, 60, 93,  14,   -103, 29,  76,  10,   27,  41,  12,  77,   86,  29,  -33,  -90,
    -40, -104, -116, 90, -84, -121, -15,  -68, -75, -57,  -72, -19, 41,  13,   -56, 117, -84,  -115,
    -91, -42,  106,  21, 80,  -45,  -9,   -3,  2,   5,    50,  74,  107, 107,  -44, 46,  -104, -84};
