// Generated by conv_settings_flt.py using PyTorch version 2.10.0+cu128.
const float32_t conv_match_stride2pad1_f32_weights_data[9] = {0.180838391f,
                                                              -0.614802361f,
                                                              0.486519039f,
                                                              0.0512407646f,
                                                              0.495086998f,
                                                              0.0370023325f,
                                                              -0.683992922f,
                                                              0.475909203f,
                                                              -0.528368413f};
