// Generated by generate_test_data.py using tensorflow version 2.17.0 (Keras version 3.5.0).
// Interpreter from tensorflow version 2.17.0 and revision v2.17.0-rc1-2-gad6d8cc177d.
#pragma once
#include <stdint.h>

const int8_t transpose_matrix_input_tensor[20] = {-92, -18, -103, 79,  -37,  -114, 95, -48, 127, -79,
                                                  -10, 14,  -121, -10, -116, -127, -9, 19,  -61, 82};
