// Generated by generate_test_data.py using tensorflow version 2.17.0 (Keras version 3.5.0).
// Interpreter from tensorflow version 2.17.0 and revision v2.17.0-rc1-2-gad6d8cc177d.
#pragma once
#include <stdint.h>

const int8_t transpose_matrix_output[20] = {-92,  -37, 127, -121, -9,  -18, -114, -79, -10,  19,
                                            -103, 95,  -10, -116, -61, 79,  -48,  14,  -127, 82};
