// Generated by generate_test_data.py using tensorflow version 2.10.0 (Keras version 2.10.0).
// Interpreter from tensorflow version 2.10.0 and revision v2.10.0-rc3-6-g359c3cdfc5f.
#pragma once
#include <stdint.h>

const int8_t conv_2x2_dilation_output_ref[72] = {
    -38, 93, -60, -18, -1, 97,  -61, 52,  18,  52,  -14, 92,  -61, 22,  -61, 94,  -61, 50,
    -37, 85, -61, 83,  57, 44,  -15, 107, -61, 35,  28,  107, -19, -16, 26,  107, -61, 74,
    11,  30, -61, 20,  12, 107, -23, 63,  8,   51,  42,  51,  -61, 85,  -61, 107, -61, 24,
    34,  81, -61, -2,  63, 89,  -1,  56,  -56, -24, -61, -61, -24, 106, -60, 107, -61, 92};
