// Generated by depthwise_conv_settings_flt.py using PyTorch version 2.10.0+cu128.
const float16_t depthwise_kernel_3x3_f16_biases_data[5] = {(float16_t)0.157592773f,
                                                           (float16_t)-0.4765625f,
                                                           (float16_t)-0.381835938f,
                                                           (float16_t)0.140991211f,
                                                           (float16_t)0.445068359f};
