// Generated by depthwise_conv_settings_flt.py using PyTorch version 2.10.0+cu128.
const float16_t depthwise_kernel_3x3_f16_weights_data[45] = {
    (float16_t)0.632324219f,   (float16_t)-0.150390625f, (float16_t)0.692382812f,  (float16_t)0.430908203f,
    (float16_t)-0.0573425293f, (float16_t)-0.694824219f, (float16_t)0.724121094f,  (float16_t)-0.448730469f,
    (float16_t)0.515136719f,   (float16_t)-0.707519531f, (float16_t)0.506347656f,  (float16_t)0.5f,
    (float16_t)0.738769531f,   (float16_t)-0.515136719f, (float16_t)0.513183594f,  (float16_t)0.241455078f,
    (float16_t)-0.286865234f,  (float16_t)0.697265625f,  (float16_t)0.100952148f,  (float16_t)0.3359375f,
    (float16_t)0.022064209f,   (float16_t)-0.332519531f, (float16_t)0.327880859f,  (float16_t)0.15234375f,
    (float16_t)0.594726562f,   (float16_t)-0.62890625f,  (float16_t)-0.445068359f, (float16_t)0.447021484f,
    (float16_t)-0.0328674316f, (float16_t)-0.196533203f, (float16_t)-0.304199219f, (float16_t)-0.68359375f,
    (float16_t)-0.522460938f,  (float16_t)0.289794922f,  (float16_t)0.577148438f,  (float16_t)0.732910156f,
    (float16_t)-0.146484375f,  (float16_t)-0.218017578f, (float16_t)0.0127944946f, (float16_t)-0.0609741211f,
    (float16_t)-0.416748047f,  (float16_t)-0.215209961f, (float16_t)-0.403320312f, (float16_t)0.0285797119f,
    (float16_t)0.502929688f};
