// Generated by conv_settings_flt.py using PyTorch version 2.10.0+cu128.
const float32_t conv_1x1_stride2_nhwc_f32_biases_data[13] = {-0.424446285f,
                                                             0.49512291f,
                                                             -0.214005142f,
                                                             -0.0149858408f,
                                                             0.23616913f,
                                                             -0.478109539f,
                                                             0.23161386f,
                                                             -0.00909191649f,
                                                             0.489786059f,
                                                             -0.427591681f,
                                                             0.162849128f,
                                                             0.401654154f,
                                                             -0.436546057f};
