// Generated by test_settings.py using tensorflow version 2.15.0 (Keras version 2.15.0).
// Interpreter from tflite_micro version 0.dev20231214171620-g47f77ab and revision None.
#pragma once
#include <stdint.h>

const int32_t lstm_1_cell_gate_bias[11] = {-16190, 6797, 24062, 29971, -22780, 17656, 14698, 1849, 4054, 14590, -20709};
