// Generated by test_settings.py using tensorflow version 2.15.0 (Keras version 2.15.0).
// Interpreter from tflite_micro version 0.dev20231214171620-g47f77ab and revision None.
#pragma once
#include <stdint.h>

const int32_t lstm_1_forget_gate_bias[11] =
    {-23170, -13466, -6110, 22504, -22652, 25549, -26211, -32267, 15774, -29318, 6943};
