// Generated by test_settings.py using tensorflow version 2.15.0 (Keras version 2.15.0).
// Interpreter from tflite_micro version 0.dev20231214171620-g47f77ab and revision None.
#pragma once
#include <stdint.h>

const int32_t lstm_1_input_to_input_eff_bias[11] =
    {-123034, -15592, 20415, -22377, 65527, -19069, 31697, -19220, 96526, 111007, 17534};
