// Generated by generate_test_data.py using tensorflow version 2.9.1 (Keras version 2.9.0).
// Interpreter from tflite_runtime version 2.11.0 and revision 0.6.0-135805-g25bfb32e73a.
#pragma once
#include <stdint.h>

const int8_t lstm_1_input[50] = {-107, 12, 109,  114, -74, -19, 66,  -13,  33, -86, -101, 103, -35, 94,   50,   100, 80,
                                 32,   -3, -118, 87,  87,  115, 113, 79,   73, 30,  -33,  118, -86, -119, -101, 17,  92,
                                 -71,  -1, -7,   -91, -40, -14, 2,   -105, 85, 2,   -127, -95, -29, 108,  13,   21};
