// Generated by test_settings.py using tensorflow version 2.15.0 (Keras version 2.15.0).
// Interpreter from tflite_micro version 0.dev20231214171620-g47f77ab and revision None.
#pragma once
#include <stdint.h>

const int32_t lstm_1_input_to_forget_eff_bias[11] =
    {19454, 742, -39262, 13544, -61308, 48333, 43165, -115211, -17250, -34822, 33823};
