// Generated by test_settings.py using tensorflow version 2.15.0 (Keras version 2.15.0).
// Interpreter from tflite_micro version 0.dev20231214171620-g47f77ab and revision None.
#pragma once
#include <stdint.h>

const int32_t lstm_1_input_gate_bias[11] = {-32410, -104, 21567, -21097, 12535, 259, 8401, 10604, 24974, 30367, -9986};
