// Generated by generate_test_data.py using tensorflow version 2.9.1 (Keras version 2.9.0).
// Interpreter from tflite_runtime version 2.11.0 and revision 0.6.0-135805-g25bfb32e73a.
#pragma once
#include <stdint.h>

const int8_t lstm_1_input_to_input_w[15] = {-38, -84, -21, -12, -93, -127, 22, 24, -116, -3, 4, -55, 97, -87, -41};
