// Generated by generate_test_data.py using tensorflow version 2.9.1 (Keras version 2.9.0).
// Interpreter from tflite_runtime version 2.11.0 and revision 0.6.0-135805-g25bfb32e73a.
#pragma once
#include <stdint.h>

const int8_t lstm_1_input_to_output_w[15] = {86, -107, -20, 43, 46, 42, -46, -69, -41, 26, -91, -6, -59, -89, -127};
