// Generated by test_settings.py using tensorflow version 2.15.0 (Keras version 2.15.0).
// Interpreter from tflite_micro version 0.dev20231214171620-g47f77ab and revision None.
#pragma once
#include <stdint.h>

const int32_t lstm_1_input_to_cell_eff_bias[11] =
    {-70974, 15629, 50174, -12269, -26876, 14328, 56938, -90951, 37206, 49150, 37019};
