// Generated by generate_test_data.py using tensorflow version 2.10.0 (Keras version 2.10.0).
// Interpreter from tflite_runtime version 2.11.0 and revision 0.6.0-134012-g31cfa135ac4.
#pragma once
#include <stdint.h>

const int32_t lstm_1_input_to_forget_eff_bias[11] =
    {-58523, -69423, 59764, -63035, -12625, -52357, 2463, 52593, -6703, -113488, 114652};
