// Generated by generate_test_data.py using tensorflow version 2.9.1 (Keras version 2.9.0).
// Interpreter from tflite_runtime version 2.11.0 and revision 0.6.0-135805-g25bfb32e73a.
#pragma once
#include <stdint.h>

const int8_t lstm_1_output_ref[30] = {-128, 92, 10, -128, 80, -62, -108, 127, 3,   -128, 4,   -36, -106, 92, 80,
                                      -128, 87, 65, -128, 50, 36,  -128, 25,  -81, -128, -67, 47,  -128, 1,  -28};
