// Generated by generate_test_data.py using tensorflow version 2.10.0 (Keras version 2.10.0).
// Interpreter from tflite_runtime version 2.11.0 and revision 0.6.0-134012-g31cfa135ac4.
#pragma once
#include <stdint.h>

const int32_t lstm_1_output_gate_bias[11] =
    {23870, 1732, 7691, -877, -23955, 30718, -22855, 11982, 28860, 27829, -31334};
