// Generated by test_settings.py using tensorflow version 2.15.0 (Keras version 2.15.0).
// Interpreter from tflite_micro version 0.dev20231214171620-g47f77ab and revision None.
#pragma once
#include <stdint.h>

const int32_t lstm_1_output_gate_bias[11] =
    {22266, 16773, 25291, -17527, -11578, 16072, 21528, 3001, -28336, 29661, 30876};
