// Generated by test_settings.py using tensorflow version 2.15.0 (Keras version 2.15.0).
// Interpreter from tflite_micro version 0.dev20231214171620-g47f77ab and revision None.
#pragma once
#include <stdint.h>

const int32_t lstm_1_recurrent_to_input_eff_bias[11] =
    {414, 437, -3772, 8211, -6992, -7429, -8441, -8694, 6164, 7199, 1679};
