// Generated by generate_test_data.py using tensorflow version 2.10.0 (Keras version 2.10.0).
// Interpreter from tflite_runtime version 2.11.0 and revision 0.6.0-134012-g31cfa135ac4.
#pragma once
#include <stdint.h>

const int32_t lstm_1_recurrent_to_output_eff_bias[11] =
    {-9900, 30954, -8778, -7920, 16236, -25410, 38412, 21582, -594, -20460, 15576};
