// Generated by test_settings.py using tensorflow version 2.15.0 (Keras version 2.15.0).
// Interpreter from tflite_micro version 0.dev20231214171620-g47f77ab and revision None.
#pragma once
#include <stdint.h>

const int32_t lstm_1_recurrent_to_output_eff_bias[11] =
    {5957, 2254, -368, -4968, -6785, 713, 2185, 2806, -5497, 6693, 230};
