// Generated by generate_test_data.py using tensorflow version 2.10.0 (Keras version 2.10.0).
// Interpreter from tflite_runtime version 2.11.0 and revision 0.6.0-134012-g31cfa135ac4.
#pragma once
#include <stdint.h>

const int32_t lstm_1_recurrent_to_cell_eff_bias[11] =
    {-36696, -9570, 29700, -792, 23364, -35970, 10032, 1518, 24156, 594, 18810};
