// Generated by generate_test_data.py using tensorflow version 2.10.0 (Keras version 2.10.0).
// Interpreter from tensorflow version 2.10.0 and revision v2.10.0-rc3-6-g359c3cdfc5f.
#pragma once
#include <stdint.h>

const int8_t dw_int16xint8_fast_spill_weights[45] = {-53,  57,  127,  39,   -127, 127,  31,   -54, -79, -23,  93,   -23,
                                                     -51,  23,  -121, -118, 59,   -27,  120,  109, -1,  -29,  -105, -90,
                                                     114,  -94, -41,  -8,   45,   -70,  -107, 93,  66,  -127, 120,  5,
                                                     -101, 73,  13,   -9,   -96,  -127, -69,  -96, -64};
