// Generated by generate_test_data.py using tensorflow version 2.12.0 (Keras version 2.12.0).
// Interpreter from tensorflow version 2.12.0 and revision v2.12.0-rc1-12-g0db597d0d75.
#pragma once
#include <stdint.h>

const int8_t kernel1x1_null_bias_input[48] = {-32, 112, -21, 103,  -108, 122,  37,  123, 79,   49,  79,   -31,
                                              5,   -46, -60, -119, 64,   110,  -98, -45, -108, 36,  -11,  121,
                                              121, -67, -75, -23,  36,   -104, 38,  30,  -105, 75,  -100, -107,
                                              59,  13,  -77, -76,  -19,  77,   33,  31,  -9,   -77, -82,  42};
