// Generated by generate_test_data.py using tensorflow version 2.12.0 (Keras version 2.12.0).
// Interpreter from tensorflow version 2.12.0 and revision v2.12.0-rc1-12-g0db597d0d75.
#pragma once
#include <stdint.h>

const int32_t kernel1x1_null_bias_output_shift[2] = {-9, -9};
