// Generated by generate_test_data.py using tensorflow version 2.12.0 (Keras version 2.12.0).
// Interpreter from tensorflow version 2.12.0 and revision v2.12.0-rc1-12-g0db597d0d75.
#include "biases_data.h"
#include "config_data.h"
#include "input_data.h"
#include "output_mult_data.h"
#include "output_ref_data.h"
#include "output_shift_data.h"
#include "weights_data.h"
