// Generated by generate_test_data.py using tensorflow version 2.12.0 (Keras version 2.12.0).
// Interpreter from tensorflow version 2.12.0 and revision v2.12.0-rc1-12-g0db597d0d75.
#pragma once
#include <stdint.h>

const int8_t kernel1x1_null_bias_weights[32] = {27,  -22,  80, -70,  113, -52, -110, -88, -127, -105, -59,
                                                -4,  48,   0,  -100, 26,  -38, 113,  64,  109,  -111, 127,
                                                -42, -121, 39, 4,    101, -11, 54,   -96, -97,  44};
