// Generated by generate_test_data.py using tensorflow version 2.10.0 (Keras version 2.10.0).
// Interpreter from tensorflow version 2.10.0 and revision upstream/v2.10.0-0-g359c3cdfc5f.
#pragma once
#include <stdint.h>

const int8_t conv_1_x_n_5_input[68] = {106,  76,  18,   -33,  -82, 2,    -37, 28,  24, 20,   5,    89,   -98, -109,
                                       66,   50,  -115, -106, 47,  99,   43,  77,  76, -29,  -127, -85,  -69, -80,
                                       -66,  109, 104,  97,   40,  -90,  -12, 112, 20, -126, 34,   -102, 13,  -62,
                                       63,   99,  -2,   1,    85,  100,  33,  65,  42, -2,   71,   -89,  -48, -4,
                                       -124, 59,  -116, 98,   -22, -106, -32, 49,  92, -38,  -24,  -92};
