// Generated by generate_test_data.py using tensorflow version 2.10.0 (Keras version 2.10.0).
// Interpreter from tensorflow version 2.10.0 and revision upstream/v2.10.0-0-g359c3cdfc5f.
#pragma once
#include <stdint.h>

const int8_t conv_1_x_n_5_weights[12] = {106, 23, 127, 96, 2, -11, -71, -1, -32, 73, 66, 34};
