// Generated by generate_test_data.py using tensorflow version 2.17.0 (Keras version 3.5.0).
// Interpreter from tensorflow version 2.17.0 and revision v2.17.0-rc1-2-gad6d8cc177d.
#pragma once
#include <stdint.h>

const int8_t transpose_3dim_input_tensor[60] = {
    -107, 66,   -61, -58, -96, -70, 36,  -42, -120, -102, -113, 79, 77,  -114, 4,    -88,  21,  -4,  28,  -38,
    -9,   73,   69,  -59, -13, -75, 68,  -39, -94,  -14,  -92,  -7, -61, -99,  29,   -116, 121, 22,  -82, 4,
    90,   -122, -26, -10, 15,  -36, -57, 76,  19,   -85,  -126, -6, 51,  -21,  -110, -128, 43,  -47, 121, -25};
