// Generated by generate_test_data.py using tensorflow version 2.17.0 (Keras version 3.5.0).
// Interpreter from tensorflow version 2.17.0 and revision v2.17.0-rc1-2-gad6d8cc177d.
#pragma once
#include <stdint.h>

const int8_t transpose_3dim_output[60] = {
    -107, -58, 36,  -102, 66,  -96,  -42, -113, -61, -70, -120, 79,  77,  -88, 28,   73,   -114, 21,  -38, 69,
    4,    -4,  -9,  -59,  -13, -39,  -92, -99,  -75, -94, -7,   29,  68,  -14, -61,  -116, 121,  4,   -26, -36,
    22,   90,  -10, -57,  -82, -122, 15,  76,   19,  -6,  -110, -47, -85, 51,  -128, 121,  -126, -21, 43,  -25};
