// Generated by generate_test_data.py using tensorflow version 2.10.0 (Keras version 2.10.0).
// Interpreter from tensorflow version 2.10.0 and revision v2.10.0-rc3-6-g359c3cdfc5f.
#pragma once
#include <stdint.h>

const int8_t depthwise_null_bias_1_input[40] = {-40, -34, 41,  14,  92,  -20, 123, -72, -14, 58,  -56, -52, -79, -8,
                                                -11, -66, -51, 73,  -55, -30, -23, 55,  -96, 59,  -46, 86,  46,  66,
                                                -88, -3,  -51, -82, -67, 105, 39,  -98, 96,  -26, 40,  32};
