// Generated by generate_test_data.py using tensorflow version 2.10.0 (Keras version 2.10.0).
// Interpreter from tensorflow version 2.10.0 and revision v2.10.0-rc3-6-g359c3cdfc5f.
#pragma once
#include <stdint.h>

const int8_t depthwise_null_bias_1_weights[64] = {
    -100, -15, -12,  -125, 61,   58,   12,   115,  127, -56,  -104, -72,  -117, 127, 127, -127,
    -103, 127, 36,   -113, 15,   -127, -17,  -127, -99, 127,  -30,  -110, -70,  -14, -68, -84,
    -84,  118, -109, -127, 100,  -7,   -127, 105,  13,  -109, 127,  127,  127,  7,   77,  89,
    -127, -64, 127,  -102, -127, 93,   -96,  80,   71,  -87,  -3,   -82,  -93,  -72, 77,  -75};
