// Generated by concatenation_settings_flt.py using PyTorch version 2.10.0+cu128.
#define CONCAT_C_NHWC_F16_INPUT_N 1
#define CONCAT_C_NHWC_F16_INPUT_H 8
#define CONCAT_C_NHWC_F16_INPUT_W 8
#define CONCAT_C_NHWC_F16_LHS_C 5
#define CONCAT_C_NHWC_F16_RHS_C 3
#define CONCAT_C_NHWC_F16_OUTPUT_C 8
#define CONCAT_C_NHWC_F16_SIZE 512
#define CONCAT_C_NHWC_F16_LAYOUT ARM_NN_LAYOUT_NHWC
