// Generated by lstm_settings_flt.py using PyTorch version 2.10.0+cu128.
const float16_t lstm_large_f16_cell_bias[24] = {
    (float16_t)-0.101196289f,  (float16_t)-0.0629272461f,  (float16_t)0.165771484f,   (float16_t)-0.245849609f,
    (float16_t)-0.308349609f,  (float16_t)-0.10369873f,    (float16_t)-0.186767578f,  (float16_t)-0.289306641f,
    (float16_t)0.13671875f,    (float16_t)0.124450684f,    (float16_t)-0.108764648f,  (float16_t)0.0615844727f,
    (float16_t)-0.159545898f,  (float16_t)0.0325012207f,   (float16_t)-0.0323181152f, (float16_t)0.0881958008f,
    (float16_t)0.157104492f,   (float16_t)-0.00375556946f, (float16_t)-0.115234375f,  (float16_t)-0.286865234f,
    (float16_t)-0.0873413086f, (float16_t)-0.126586914f,   (float16_t)0.237426758f,   (float16_t)0.0204315186f};
