// Generated by lstm_settings_flt.py using PyTorch version 2.10.0+cu128.
const float16_t lstm_large_f16_forget_bias[24] = {
    (float16_t)-0.399902344f,  (float16_t)0.369873047f,  (float16_t)0.306640625f,  (float16_t)0.275390625f,
    (float16_t)0.127563477f,   (float16_t)-0.082824707f, (float16_t)-0.185791016f, (float16_t)-0.217407227f,
    (float16_t)0.20300293f,    (float16_t)-0.176879883f, (float16_t)0.0105438232f, (float16_t)0.0916748047f,
    (float16_t)0.375976562f,   (float16_t)-0.129272461f, (float16_t)-0.143188477f, (float16_t)-0.2890625f,
    (float16_t)0.0292358398f,  (float16_t)0.0731811523f, (float16_t)-0.430175781f, (float16_t)0.0185546875f,
    (float16_t)-0.0469970703f, (float16_t)0.158203125f,  (float16_t)0.0910644531f, (float16_t)0.118774414f};
