// Generated by lstm_settings_flt.py using PyTorch version 2.10.0+cu128.
const float16_t lstm_large_f16_input_bias[24] = {
    (float16_t)-0.491699219f,   (float16_t)0.0233764648f,  (float16_t)-0.142211914f, (float16_t)0.195678711f,
    (float16_t)-0.00366210938f, (float16_t)-0.0117797852f, (float16_t)-0.013671875f, (float16_t)-0.19909668f,
    (float16_t)0.2109375f,      (float16_t)-0.313476562f,  (float16_t)-0.164428711f, (float16_t)0.193115234f,
    (float16_t)0.0548095703f,   (float16_t)-0.193237305f,  (float16_t)-0.215454102f, (float16_t)0.0483703613f,
    (float16_t)0.334472656f,    (float16_t)-0.36328125f,   (float16_t)-0.138671875f, (float16_t)-0.044128418f,
    (float16_t)0.414306641f,    (float16_t)0.0562133789f,  (float16_t)0.0679321289f, (float16_t)0.194091797f};
