// Generated by lstm_settings_flt.py using PyTorch version 2.10.0+cu128.
const float16_t lstm_large_f16_output_bias[24] = {
    (float16_t)0.177978516f,   (float16_t)0.0875854492f,   (float16_t)0.169189453f,   (float16_t)0.396240234f,
    (float16_t)0.00784301758f, (float16_t)0.0780639648f,   (float16_t)-0.156616211f,  (float16_t)-0.127563477f,
    (float16_t)-0.384277344f,  (float16_t)-0.00075340271f, (float16_t)-0.0427856445f, (float16_t)0.135742188f,
    (float16_t)-0.0346069336f, (float16_t)-0.252929688f,   (float16_t)0.2578125f,     (float16_t)0.0139846802f,
    (float16_t)-0.202880859f,  (float16_t)-0.180053711f,   (float16_t)0.163208008f,   (float16_t)-0.0137252808f,
    (float16_t)0.409667969f,   (float16_t)0.208984375f,    (float16_t)0.110290527f,   (float16_t)0.0103149414f};
