// Generated by generate_test_data.py using tensorflow version 2.10.0 (Keras version 2.10.0).
// Interpreter from tensorflow version 2.10.0 and revision v2.10.0-rc3-6-g359c3cdfc5f.
#pragma once
#include <stdint.h>

const int32_t dw_int16xint8_fast_stride_null_bias_output_mult[8] =
    {1259187472, 1484929796, 1730993539, 1755899937, 1090673129, 1591800876, 1789240575, 1354058059};
