// Generated by generate_test_data.py using tensorflow version 2.10.0 (Keras version 2.10.0).
// Interpreter from tensorflow version 2.10.0 and revision v2.10.0-rc3-6-g359c3cdfc5f.
#pragma once
#include <stdint.h>

const int8_t dw_int16xint8_fast_stride_null_bias_weights[32] = {
    -71, 127, -76,  -109, 6,  -127, 88, -6, 50,   -45, -78, 127, -72, -55, 127, 127,
    -95, -41, -127, -83,  73, -70,  48, -6, -127, -78, 125, -81, 127, 17,  44,  52};
