// Generated by depthwise_conv_settings_flt.py using PyTorch version 2.10.0+cu128.
const float16_t depthwise_match_out_activation_f16_biases_data[3] = {(float16_t)-0.394042969f,
                                                                     (float16_t)0.0171813965f,
                                                                     (float16_t)0.126464844f};
