// Generated by depthwise_conv_settings_flt.py using PyTorch version 2.10.0+cu128.
const float16_t depthwise_match_out_activation_f16_output_ref_data[6] = {(float16_t)-1.37792969f,
                                                                         (float16_t)-0.474853516f,
                                                                         (float16_t)0.841308594f,
                                                                         (float16_t)-1.3671875f,
                                                                         (float16_t)-0.433837891f,
                                                                         (float16_t)-0.456787109f};
