// Generated by depthwise_conv_settings_flt.py using PyTorch version 2.10.0+cu128.
const float16_t depthwise_match_out_activation_f16_weights_data[36] = {
    (float16_t)0.129638672f,   (float16_t)0.360107422f,   (float16_t)-0.638671875f,  (float16_t)-0.302978516f,
    (float16_t)0.584960938f,   (float16_t)0.309814453f,   (float16_t)0.345947266f,   (float16_t)-0.229370117f,
    (float16_t)0.502441406f,   (float16_t)-0.0346984863f, (float16_t)-0.387695312f,  (float16_t)0.618164062f,
    (float16_t)-0.315673828f,  (float16_t)-0.15637207f,   (float16_t)-0.0296173096f, (float16_t)-0.534179688f,
    (float16_t)-0.0115966797f, (float16_t)0.0524291992f,  (float16_t)0.731933594f,   (float16_t)0.712890625f,
    (float16_t)-0.538574219f,  (float16_t)0.219360352f,   (float16_t)-0.0311431885f, (float16_t)0.257568359f,
    (float16_t)0.0958862305f,  (float16_t)-0.338134766f,  (float16_t)0.267578125f,   (float16_t)0.628417969f,
    (float16_t)-0.467041016f,  (float16_t)0.353759766f,   (float16_t)0.565429688f,   (float16_t)-0.481445312f,
    (float16_t)0.186279297f,   (float16_t)-0.0726928711f, (float16_t)-0.0966796875f, (float16_t)0.0292663574f};
