// Generated by conv_settings_flt.py using PyTorch version 2.10.0+cu128.
const float16_t conv_match_2x2_dilation_5x5_input_f16_input_data[50] = {
    (float16_t)-0.182373047f,  (float16_t)-0.859863281f,  (float16_t)-0.237060547f, (float16_t)-0.7109375f,
    (float16_t)-0.145263672f,  (float16_t)-0.260986328f,  (float16_t)0.466308594f,  (float16_t)-0.244506836f,
    (float16_t)0.623535156f,   (float16_t)0.0370483398f,  (float16_t)0.326904297f,  (float16_t)0.0897827148f,
    (float16_t)-0.638183594f,  (float16_t)-0.58203125f,   (float16_t)-0.709472656f, (float16_t)0.241333008f,
    (float16_t)0.475341797f,   (float16_t)0.0068397522f,  (float16_t)0.0837402344f, (float16_t)0.207519531f,
    (float16_t)0.987304688f,   (float16_t)-0.154663086f,  (float16_t)0.453369141f,  (float16_t)-0.515136719f,
    (float16_t)-0.722167969f,  (float16_t)-0.366699219f,  (float16_t)-0.395019531f, (float16_t)-0.15246582f,
    (float16_t)-0.0135955811f, (float16_t)-0.497314453f,  (float16_t)0.834472656f,  (float16_t)0.295654297f,
    (float16_t)0.715820312f,   (float16_t)0.385009766f,   (float16_t)0.611816406f,  (float16_t)-0.374511719f,
    (float16_t)0.605957031f,   (float16_t)0.857910156f,   (float16_t)-0.703613281f, (float16_t)0.483642578f,
    (float16_t)0.635253906f,   (float16_t)0.7734375f,     (float16_t)0.812011719f,  (float16_t)0.99609375f,
    (float16_t)-0.726074219f,  (float16_t)0.257080078f,   (float16_t)-0.193969727f, (float16_t)-0.812011719f,
    (float16_t)-0.966308594f,  (float16_t)-0.00365638733f};
