// Generated by conv_settings_flt.py using PyTorch version 2.10.0+cu128.
const float16_t conv_match_2x2_dilation_5x5_input_f16_output_ref_data[50] = {
    (float16_t)-1.58105469f,    (float16_t)1.06054688f,    (float16_t)-0.901855469f, (float16_t)0.887207031f,
    (float16_t)0.354248047f,    (float16_t)-0.318847656f,  (float16_t)0.0877685547f, (float16_t)-0.17578125f,
    (float16_t)-0.93359375f,    (float16_t)-0.459716797f,  (float16_t)-1.1796875f,   (float16_t)-0.942871094f,
    (float16_t)0.573242188f,    (float16_t)0.202880859f,   (float16_t)-0.571289062f, (float16_t)0.938964844f,
    (float16_t)-0.459228516f,   (float16_t)-0.7890625f,    (float16_t)0.333496094f,  (float16_t)-0.138305664f,
    (float16_t)-1.3984375f,     (float16_t)-0.0801391602f, (float16_t)-1.48339844f,  (float16_t)-1.22753906f,
    (float16_t)0.10369873f,     (float16_t)-0.240112305f,  (float16_t)-0.763671875f, (float16_t)-0.28515625f,
    (float16_t)-0.321777344f,   (float16_t)-0.676269531f,  (float16_t)-0.703125f,    (float16_t)-0.0346069336f,
    (float16_t)-0.00333023071f, (float16_t)-1.93554688f,   (float16_t)0.227539062f,  (float16_t)0.0508422852f,
    (float16_t)-1.25390625f,    (float16_t)-1.17382812f,   (float16_t)-0.337402344f, (float16_t)-0.907714844f,
    (float16_t)-1.8203125f,     (float16_t)-0.266357422f,  (float16_t)-1.73046875f,  (float16_t)-0.546386719f,
    (float16_t)-0.438720703f,   (float16_t)0.846679688f,   (float16_t)0.063659668f,  (float16_t)0.970214844f,
    (float16_t)-0.616699219f,   (float16_t)-0.555664062f};
