// Generated by conv_settings_flt.py using PyTorch version 2.10.0+cu128.
const float16_t conv_match_2x2_dilation_5x5_input_f16_weights_data[36] = {
    (float16_t)0.141235352f,   (float16_t)0.127319336f,  (float16_t)-0.622558594f, (float16_t)0.234863281f,
    (float16_t)0.00730895996f, (float16_t)0.507324219f,  (float16_t)0.160522461f,  (float16_t)-0.16027832f,
    (float16_t)-0.231445312f,  (float16_t)-0.328125f,    (float16_t)0.313720703f,  (float16_t)0.30078125f,
    (float16_t)0.315429688f,   (float16_t)-0.196899414f, (float16_t)-0.734863281f, (float16_t)0.448486328f,
    (float16_t)0.411621094f,   (float16_t)0.715820312f,  (float16_t)0.536621094f,  (float16_t)0.165649414f,
    (float16_t)0.0269622803f,  (float16_t)0.649902344f,  (float16_t)-0.707519531f, (float16_t)-0.478271484f,
    (float16_t)-0.102783203f,  (float16_t)0.630371094f,  (float16_t)-0.198852539f, (float16_t)-0.682617188f,
    (float16_t)-0.181152344f,  (float16_t)-0.548828125f, (float16_t)0.465087891f,  (float16_t)-0.299072266f,
    (float16_t)0.158935547f,   (float16_t)-0.568359375f, (float16_t)-0.597167969f, (float16_t)0.525390625f};
