// Generated by depthwise_conv_settings_flt.py using PyTorch version 2.10.0+cu128.
const float32_t depthwise_k3_1d_opt_nhwc_f32_biases_data[8] = {-0.136435211f,
                                                               0.154553384f,
                                                               -0.068371132f,
                                                               0.0939170346f,
                                                               -0.0619552918f,
                                                               -0.444835246f,
                                                               0.348479062f,
                                                               -0.178226918f};
