// Generated by generate_test_data.py using tensorflow version 2.10.0 (Keras version 2.10.0).
// Interpreter from tensorflow version 2.10.0 and revision v2.10.0-rc3-6-g359c3cdfc5f.
#pragma once
#include <stdint.h>

const int64_t fully_connected_int16_big_biases[11] =
    {-3933832, 2210749, -2763436, -3803788, -3901321, -3251101, 2893480, -3446167, -2438326, 3966343, -617709};
