// Generated by generate_test_data.py using tensorflow version 2.10.0 (Keras version 2.10.0).
// Interpreter from tensorflow version 2.10.0 and revision v2.10.0-rc3-6-g359c3cdfc5f.
#pragma once
#include <stdint.h>

const int8_t kernel1x1_stride_x_y_2_output_ref[40] = {
    114, -43, -42, 53,   127, 34, -25, 81, -41, 127, -125, 107, 125, -41, 127, -87, 22,  -5,  25,  68,
    -46, 2,   127, -121, 127, 66, 118, 21, 64,  127, 89,   -39, 10,  39,  127, 40,  119, -28, 105, 127};
