// Generated by generate_test_data.py using TFL version 2.9.1 as reference.
#pragma once
#include <stdint.h>

const int32_t kernel1x1_stride_x_y_2_output_mult[5] = {1701915958, 2071897646, 1331934271, 1646418726, 1720415036};
