// Generated by generate_test_data.py using tensorflow version 2.10.0 (Keras version 2.10.0).
// Interpreter from tensorflow version 2.10.0 and revision v2.10.0-rc3-6-g359c3cdfc5f.
#pragma once
#include <stdint.h>

const int8_t kernel1x1_stride_x_y_2_weights[25] = {-127, 26, -26, 48, 29, -2,  -26,  -23,  70,  -127, 99,  -79, -127,
                                                   97,   81, -90, 49, 61, -44, -127, -127, -70, -66,  124, 10};
