// Generated by pad_settings_flt.py using PyTorch version 2.10.0+cu128.
const float32_t pad_int8_1_f32_input_tensor[8] =
    {-2.14788055f, 2.17099571f, -3.4749589f, 0.665352285f, 2.15102077f, 0.742655993f, 2.1601727f, -1.57520151f};
