// Generated by generate_test_data.py using TFL version 2.9.1 as reference.
#pragma once
#include <stdint.h>

const int32_t kernel1x1_stride_x_output_mult[5] = {1366985121, 1534860499, 1366985121, 1354994029, 1390967305};
