// Generated by generate_test_data.py using tensorflow version 2.10.0 (Keras version 2.10.0).
// Interpreter from tensorflow version 2.10.0 and revision v2.10.0-rc3-6-g359c3cdfc5f.
#pragma once
#include <stdint.h>

const int8_t kernel1x1_stride_x_weights[45] = {-39, -115, -96, 104,  -127, 57,   64,   -2,   20,  -127, 118, -99,
                                               50,  -109, -49, -109, 81,   39,   39,   33,   -78, -99,  127, 84,
                                               43,  -33,  -74, 90,   -102, -105, -127, 108,  -12, 93,   64,  22,
                                               -12, 30,   126, 26,   -50,  -42,  -97,  -127, 2};
