// Generated by fully_connected_settings_flt.py using PyTorch version 2.10.0+cu128.
const float32_t fully_connected_match_fc_per_ch_f32_output_ref_data[22] = {
    4.29727077f,  13.0467911f,   4.23057604f,  -2.69571877f, -7.58362103f, 10.6991224f,  -4.78073597f, 4.6182375f,
    -4.28369808f, -13.713129f,   13.4946442f,  5.12015486f,  -5.57234335f, -7.40514183f, -4.83683872f, 7.4765687f,
    6.64471579f,  -0.534159303f, -6.08563328f, 4.60722065f,  -4.92709637f, 10.7864532f};
