// Generated by activation_settings_flt.py using PyTorch version 2.10.0+cu128.
const float16_t activation_f16_input[9] = {(float16_t)-5.0f,
                                           (float16_t)-3.0f,
                                           (float16_t)-1.25f,
                                           (float16_t)-0.0999755859f,
                                           (float16_t)0.0f,
                                           (float16_t)0.5f,
                                           (float16_t)1.5f,
                                           (float16_t)3.0f,
                                           (float16_t)6.0f};
