// Generated by activation_settings_flt.py using PyTorch version 2.10.0+cu128.
const float16_t activation_f16_output_ref_sigmoid[9] = {(float16_t)0.006690979f,
                                                        (float16_t)0.0474243164f,
                                                        (float16_t)0.22265625f,
                                                        (float16_t)0.475097656f,
                                                        (float16_t)0.5f,
                                                        (float16_t)0.622558594f,
                                                        (float16_t)0.817382812f,
                                                        (float16_t)0.952636719f,
                                                        (float16_t)0.997558594f};
