// Generated by activation_settings_flt.py using PyTorch version 2.10.0+cu128.
const float16_t activation_f16_output_ref_leaky_relu[9] = {(float16_t)-0.625f,
                                                           (float16_t)-0.375f,
                                                           (float16_t)-0.15625f,
                                                           (float16_t)-0.0124969482f,
                                                           (float16_t)0.0f,
                                                           (float16_t)0.5f,
                                                           (float16_t)1.5f,
                                                           (float16_t)3.0f,
                                                           (float16_t)6.0f};
