// Generated by activation_settings_flt.py using PyTorch version 2.10.0+cu128.
const float16_t activation_f16_output_ref_hardswish[9] = {(float16_t)-0.0f,
                                                          (float16_t)-0.0f,
                                                          (float16_t)-0.364501953f,
                                                          (float16_t)-0.0483398438f,
                                                          (float16_t)0.0f,
                                                          (float16_t)0.291748047f,
                                                          (float16_t)1.125f,
                                                          (float16_t)3.0f,
                                                          (float16_t)6.0f};
