// Generated by activation_settings_flt.py using PyTorch version 2.10.0+cu128.
const float16_t activation_f16_output_ref_tanh[9] = {(float16_t)-1.0f,
                                                     (float16_t)-0.995117188f,
                                                     (float16_t)-0.848144531f,
                                                     (float16_t)-0.0996704102f,
                                                     (float16_t)0.0f,
                                                     (float16_t)0.462158203f,
                                                     (float16_t)0.905273438f,
                                                     (float16_t)0.995117188f,
                                                     (float16_t)1.0f};
