// Generated by conv_settings_flt.py using PyTorch version 2.10.0+cu128.
const float16_t conv_1x1_stride2_nhwc_f16_biases_data[13] = {(float16_t)-0.424560547f,
                                                             (float16_t)0.495117188f,
                                                             (float16_t)-0.213989258f,
                                                             (float16_t)-0.0149841309f,
                                                             (float16_t)0.236206055f,
                                                             (float16_t)-0.478027344f,
                                                             (float16_t)0.231567383f,
                                                             (float16_t)-0.00909423828f,
                                                             (float16_t)0.489746094f,
                                                             (float16_t)-0.427490234f,
                                                             (float16_t)0.162841797f,
                                                             (float16_t)0.401611328f,
                                                             (float16_t)-0.436523438f};
