// Generated by conv_settings_flt.py using PyTorch version 2.10.0+cu128.
const float16_t conv_match_1xn_2_f16_biases_data[3] = {(float16_t)-0.106994629f,
                                                       (float16_t)-0.0610656738f,
                                                       (float16_t)0.0238647461f};
