// Generated by fully_connected_settings_flt.py using PyTorch version 2.10.0+cu128.
const float16_t fully_connected_match_fc_per_ch_f16_biases_data[22] = {
    (float16_t)-0.181518555f,  (float16_t)0.15637207f,    (float16_t)-0.473144531f, (float16_t)-0.103149414f,
    (float16_t)0.422607422f,   (float16_t)0.493652344f,   (float16_t)-0.225585938f, (float16_t)-0.273925781f,
    (float16_t)0.128417969f,   (float16_t)-0.430419922f,  (float16_t)-0.406738281f, (float16_t)0.226806641f,
    (float16_t)0.408447266f,   (float16_t)-0.0538330078f, (float16_t)-0.467773438f, (float16_t)-0.474365234f,
    (float16_t)-0.306640625f,  (float16_t)0.235351562f,   (float16_t)0.188232422f,  (float16_t)0.0259094238f,
    (float16_t)-0.0170440674f, (float16_t)-0.371826172f};
