// Generated by fully_connected_settings_flt.py using PyTorch version 2.10.0+cu128.
const float16_t fully_connected_match_fc_per_ch_f16_output_ref_data[22] = {
    (float16_t)3.74023438f,   (float16_t)0.337158203f, (float16_t)1.82226562f, (float16_t)7.2265625f,
    (float16_t)0.9375f,       (float16_t)-5.7890625f,  (float16_t)-5.8359375f, (float16_t)2.56835938f,
    (float16_t)-12.4453125f,  (float16_t)0.195800781f, (float16_t)-6.6328125f, (float16_t)3.09179688f,
    (float16_t)-5.70703125f,  (float16_t)-13.84375f,   (float16_t)1.76269531f, (float16_t)0.00709533691f,
    (float16_t)-1.58007812f,  (float16_t)6.6328125f,   (float16_t)3.82226562f, (float16_t)-1.09472656f,
    (float16_t)-0.697265625f, (float16_t)4.078125f};
