// Generated by generate_test_data.py using tensorflow version 2.10.0 (Keras version 2.10.0).
// Interpreter from tensorflow version 2.10.0 and revision v2.10.0-rc3-6-g359c3cdfc5f.
#pragma once
#include <stdint.h>

const int8_t conv_1_x_n_2_input[32] = {103, -12, 82, -63, -29, -125, 117, 126, -40, -58, -34, 61, -37, -97, -21, 63,
                                       -44, 44,  49, 30,  -1,  62,   2,   125, 38,  118, 81,  85, -90, -23, -22, -33};
