// Generated by generate_test_data.py using tensorflow version 2.10.0 (Keras version 2.10.0).
// Interpreter from tensorflow version 2.10.0 and revision v2.10.0-rc3-6-g359c3cdfc5f.
#pragma once
#include <stdint.h>

const int8_t conv_1_x_n_2_weights[80] = {
    48,  -104, -93, -32,  127,  -30, 68,  -42, -106, -104, 43,   -51,  115,  38,  104,  0,   -52,  5,   118, 127,
    43,  -14,  -85, -119, 18,   -58, -94, 34,  80,   115,  5,    61,   17,   127, -107, 20,  34,   -16, -89, 11,
    -34, -39,  -55, 122,  -121, 11,  26,  101, 97,   25,   3,    -23,  -127, -35, 66,   -57, -100, 37,  -78, 55,
    7,   65,   -86, -47,  8,    120, 80,  0,   -29,  -124, -109, -102, -85,  115, -127, -71, -54,  -73, -10, -89};
