// Generated by depthwise_conv_settings_flt.py using PyTorch version 2.10.0+cu128.
const float16_t depthwise_basic_smallc_nhwc_f16_biases_data[6] = {(float16_t)-0.0908203125f,
                                                                  (float16_t)-0.169189453f,
                                                                  (float16_t)0.184326172f,
                                                                  (float16_t)0.268798828f,
                                                                  (float16_t)0.106872559f,
                                                                  (float16_t)0.459960938f};
