// Generated by depthwise_conv_settings_flt.py using PyTorch version 2.10.0+cu128.
const float16_t depthwise_basic_smallc_nhwc_f16_weights_data[54] = {
    (float16_t)-0.108276367f, (float16_t)-0.597167969f, (float16_t)0.580078125f,   (float16_t)0.419921875f,
    (float16_t)0.241088867f,  (float16_t)-0.325439453f, (float16_t)-0.434082031f,  (float16_t)0.385009766f,
    (float16_t)-0.708984375f, (float16_t)-0.294677734f, (float16_t)-0.724609375f,  (float16_t)-0.21875f,
    (float16_t)0.404541016f,  (float16_t)-0.716796875f, (float16_t)-0.174682617f,  (float16_t)-0.606933594f,
    (float16_t)0.076965332f,  (float16_t)-0.623046875f, (float16_t)0.0640869141f,  (float16_t)0.181396484f,
    (float16_t)-0.470214844f, (float16_t)0.591796875f,  (float16_t)0.0643920898f,  (float16_t)0.11114502f,
    (float16_t)0.302978516f,  (float16_t)0.608886719f,  (float16_t)0.554199219f,   (float16_t)-0.254882812f,
    (float16_t)-0.474609375f, (float16_t)-0.698730469f, (float16_t)-0.0495605469f, (float16_t)0.312011719f,
    (float16_t)0.337890625f,  (float16_t)0.502441406f,  (float16_t)-0.638671875f,  (float16_t)-0.260009766f,
    (float16_t)0.574707031f,  (float16_t)-0.144042969f, (float16_t)0.0850830078f,  (float16_t)0.0856323242f,
    (float16_t)0.134521484f,  (float16_t)-0.300292969f, (float16_t)-0.602050781f,  (float16_t)-0.34765625f,
    (float16_t)-0.574707031f, (float16_t)0.286132812f,  (float16_t)-0.333984375f,  (float16_t)0.239379883f,
    (float16_t)0.0339050293f, (float16_t)0.504394531f,  (float16_t)0.561523438f,   (float16_t)-0.241333008f,
    (float16_t)-0.584472656f, (float16_t)0.125366211f};
