// Generated by conv_settings_flt.py using PyTorch version 2.10.0+cu128.
const float32_t conv_k3_opt_f32_biases_data[12] = {0.183923975f,
                                                   0.431868553f,
                                                   -0.246395811f,
                                                   -0.304440081f,
                                                   -0.108465716f,
                                                   0.498667091f,
                                                   0.332763344f,
                                                   0.234872952f,
                                                   -0.354654133f,
                                                   0.0284294281f,
                                                   -0.490387261f,
                                                   -0.479224324f};
