// Generated by add_mul_settings_flt.py using PyTorch version 2.10.0+cu128.
#define MUL_F32_DST_SIZE 160
#define MUL_F32_OUT_ACTIVATION_MIN -10.0f
#define MUL_F32_OUT_ACTIVATION_MAX 10.0f
#define MUL_F32_INPUT1_OFFSET 0
#define MUL_F32_INPUT2_OFFSET 0
#define MUL_F32_OUTPUT_MULT 0
#define MUL_F32_OUTPUT_SHIFT 0
#define MUL_F32_OUTPUT_OFFSET 0
