// Generated by conv_settings_flt.py using PyTorch version 2.10.0+cu128.
const float16_t conv_k3_opt_f16_biases_data[12] = {(float16_t)0.183959961f,
                                                   (float16_t)0.431884766f,
                                                   (float16_t)-0.246337891f,
                                                   (float16_t)-0.304443359f,
                                                   (float16_t)-0.108459473f,
                                                   (float16_t)0.498779297f,
                                                   (float16_t)0.332763672f,
                                                   (float16_t)0.234863281f,
                                                   (float16_t)-0.354736328f,
                                                   (float16_t)0.028427124f,
                                                   (float16_t)-0.490478516f,
                                                   (float16_t)-0.479248047f};
