// Generated by conv_settings_flt.py using PyTorch version 2.10.0+cu128.
const float16_t conv_match_3x2_dilation_f16_weights_data[36] = {
    (float16_t)0.437011719f,   (float16_t)-0.33984375f,  (float16_t)0.0352478027f, (float16_t)-0.548339844f,
    (float16_t)0.633300781f,   (float16_t)0.674316406f,  (float16_t)0.687988281f,  (float16_t)-0.584960938f,
    (float16_t)0.150634766f,   (float16_t)0.333007812f,  (float16_t)-0.468994141f, (float16_t)0.198608398f,
    (float16_t)-0.427490234f,  (float16_t)0.431884766f,  (float16_t)0.131469727f,  (float16_t)0.397705078f,
    (float16_t)-0.0729980469f, (float16_t)0.269775391f,  (float16_t)0.65625f,      (float16_t)0.23034668f,
    (float16_t)-0.0434265137f, (float16_t)0.448242188f,  (float16_t)-0.591308594f, (float16_t)0.618652344f,
    (float16_t)-0.425537109f,  (float16_t)0.73828125f,   (float16_t)0.701660156f,  (float16_t)-0.262939453f,
    (float16_t)0.498291016f,   (float16_t)-0.218505859f, (float16_t)0.0222625732f, (float16_t)0.258544922f,
    (float16_t)-0.0269775391f, (float16_t)0.289794922f,  (float16_t)0.374023438f,  (float16_t)0.729980469f};
