// Generated by test_settings.py using tensorflow version 2.15.0 (Keras version 2.15.0).
// Interpreter from tensorflow version 2.15.0 and revision v2.15.0-2-g0b15fdfcb3f.
#pragma once
#include <stdint.h>

const int64_t requantize_s64_biases[8] = {2718092, 2556575, 646371, 1427241, 2010306, 3766647, 1886211, 1482898};
