// Generated by generate_test_data.py using tensorflow version 2.10.0 (Keras version 2.10.0).
// Interpreter from tensorflow version 2.10.0 and revision v2.10.0-rc3-6-g359c3cdfc5f.
#pragma once
#include <stdint.h>

const int16_t requantize_s64_input[12] = {82, 66, -30, -105, 95, 74, 124, 93, -25, 93, 57, -32};
