// Generated by generate_test_data.py using tensorflow version 2.10.0 (Keras version 2.10.0).
// Interpreter from tensorflow version 2.10.0 and revision v2.10.0-rc3-6-g359c3cdfc5f.
#pragma once
#include <stdint.h>

const int8_t requantize_s64_weights[16] = {-23, 101, 3, -55, -120, 127, -120, 6, 103, 103, -95, 60, 102, 9, -60, -90};
