// Generated by generate_test_data.py using tensorflow version 2.10.0 (Keras version 2.10.0).
// Interpreter from tensorflow version 2.10.0 and revision upstream/v2.10.0-0-g359c3cdfc5f.
#pragma once
#include <stdint.h>

const int8_t requantize_s64_weights[16] =
    {-95, -110, -39, 99, -127, 73, -58, 108, 101, 127, -17, -89, 24, -99, -34, 87};
