// Generated by generate_test_data.py using tensorflow version 2.10.0 (Keras version 2.10.0).
// Interpreter from tensorflow version 2.10.0 and revision v2.10.0-rc3-6-g359c3cdfc5f.
#pragma once
#include <stdint.h>

const int32_t depthwise_2_output_mult[9] =
    {1133287388, 1161155097, 1123998152, 1151865861, 1096130373, 1133287388, 1179733569, 1189022806, 1114708915};
