// Generated by fully_connected_settings_flt.py using PyTorch version 2.10.0+cu128.
const float32_t fully_connected_match_basic_f32_biases_data[6] =
    {0.433437347f, -0.451486766f, 0.603065312f, 0.284521729f, 0.470644712f, 0.351996928f};
