// Generated by generate_test_data.py using tensorflow version 2.10.0 (Keras version 2.10.0).
// Interpreter from tensorflow version 2.10.0 and revision upstream/v2.10.0-0-g359c3cdfc5f.
#pragma once
#include <stdint.h>

const int8_t int16xint8_dilation_1_weights[16] =
    {-6, -48, 127, -18, -44, 110, 20, 59, 127, 104, 45, -106, 116, -125, 90, 127};
