// Generated by generate_test_data.py using tensorflow version 2.10.0 (Keras version 2.10.0).
// Interpreter from tensorflow version 2.10.0 and revision v2.10.0-rc3-6-g359c3cdfc5f.
#pragma once
#include <stdint.h>

const int8_t int16xint8_dilation_1_weights[16] =
    {-127, -37, 74, 1, -85, 102, -110, 65, -77, 127, 110, 124, 17, -10, 110, -110};
