// Generated by test_settings.py using tensorflow version 2.14.0 (Keras version 2.14.0).
// Interpreter from tensorflow version 2.14.0 and revision v2.14.0-rc1-21-g4dacf3f368e.
#pragma once
#include <stdint.h>

const int32_t int16xint8_spill2_output_mult[9] =
    {1231320420, 1228194292, 1228950954, 1231269879, 1231112138, 1229528901, 1230557932, 1230167876, 1229640034};
