// Generated by generate_test_data.py using tensorflow version 2.10.0 (Keras version 2.10.0).
// Interpreter from tensorflow version 2.10.0 and revision upstream/v2.10.0-0-g359c3cdfc5f.
#pragma once
#include <stdint.h>

const int32_t int16xint8_dilation_3_output_mult[4] = {1329225195, 1440392595, 1414304507, 1407575743};
