// Generated by activation_settings_flt.py using PyTorch version 2.10.0+cu128.
const float32_t activation_f32_output_ref_leaky_relu[9] =
    {-0.625f, -0.375f, -0.15625f, -0.0125000002f, 0.0f, 0.5f, 1.5f, 3.0f, 6.0f};
