// Generated by activation_settings_flt.py using PyTorch version 2.10.0+cu128.
const float32_t activation_f32_output_ref_sigmoid[9] = {0.00669285096f,
                                                        0.0474258736f,
                                                        0.222700134f,
                                                        0.475020796f,
                                                        0.5f,
                                                        0.622459352f,
                                                        0.817574441f,
                                                        0.952574134f,
                                                        0.997527421f};
