// Generated by activation_settings_flt.py using PyTorch version 2.10.0+cu128.
const float32_t activation_f32_output_ref_tanh[9] = {-0.999909222f,
                                                     -0.995054781f,
                                                     -0.848283648f,
                                                     -0.0996679962f,
                                                     0.0f,
                                                     0.462117165f,
                                                     0.905148268f,
                                                     0.995054781f,
                                                     0.999987721f};
