// Generated by activation_settings_flt.py using PyTorch version 2.10.0+cu128.
const float32_t activation_f32_output_ref_hardswish[9] =
    {-0.0f, -0.0f, -0.364583343f, -0.0483333357f, 0.0f, 0.291666657f, 1.125f, 3.0f, 6.0f};
