// Generated by activation_settings_flt.py using PyTorch version 2.10.0+cu128.
#include "config_data.h"
#include "input_data.h"
#include "output_ref_hardswish_data.h"
#include "output_ref_leaky_relu_data.h"
#include "output_ref_sigmoid_data.h"
#include "output_ref_tanh_data.h"
