// Generated by generate_test_data.py using tensorflow version 2.10.0 (Keras version 2.10.0).
// Interpreter from tensorflow version 2.10.0 and revision v2.10.0-rc3-6-g359c3cdfc5f.
#pragma once
#include <stdint.h>

const int8_t fully_connected_out_activation_input[10] = {-11, 119, -74, 109, -34, 59, 96, 2, -115, 55};
