// Generated by generate_test_data.py using tensorflow version 2.10.0 (Keras version 2.10.0).
// Interpreter from tensorflow version 2.10.0 and revision v2.10.0-rc3-6-g359c3cdfc5f.
#pragma once
#include <stdint.h>

const int8_t fully_connected_out_activation_weights[40] = {
    -96, -9,  -64, -4, -105, -92, 77, 90, 15,  109, -121, 84, 78,   107, 48, -55, 10, 29,   47,   -120,
    -1,  -55, 14,  98, 36,   51,  0,  43, -29, 7,   87,   98, -106, 109, 40, -66, 30, -127, -125, -124};
