// Generated by generate_test_data.py using tensorflow version 2.10.0 (Keras version 2.10.0).
// Interpreter from tensorflow version 2.10.0 and revision v2.10.0-rc3-6-g359c3cdfc5f.
#pragma once
#include <stdint.h>

const int8_t depthwise_mult_batches_output_ref[36] = {6,   21,  57,  -6,  16,  61, 5,   -29, 98, -5,  0,  42,
                                                      -97, -31, 21,  -8,  -26, 26, 44,  25,  56, 2,   7,  54,
                                                      5,   -7,  127, -10, -11, 35, -79, -56, 15, -32, -1, 38};
