// Generated by generate_test_data.py using tensorflow version 2.10.0 (Keras version 2.10.0).
// Interpreter from tensorflow version 2.10.0 and revision v2.10.0-rc3-6-g359c3cdfc5f.
#pragma once
#include <stdint.h>

const int8_t depthwise_mult_batches_weights[24] = {-21, -127, -59, -127, -113, 74,  -121, 12,  88, -101, -4, -111,
                                                   59,  85,   81,  97,   49,   127, 38,   -31, 61, 126,  -4, 49};
