// Generated by generate_test_data.py using tensorflow version 2.9.1 (Keras version 2.9.0).
// Interpreter from tflite_runtime version 2.11.0 and revision 0.6.0-135805-g25bfb32e73a.
#pragma once
#include <stdint.h>

const int8_t lstm_2_input_to_input_w[30] = {21,  41,   -37,  -34, -110, -64,  117,  11,  -40, -28,
                                            127, 102,  -107, -75, 42,   -85,  -33,  -49, -52, 125,
                                            -85, -125, -37,  -8,  -103, -116, -117, -53, 17,  -38};
