// Generated by generate_test_data.py using tensorflow version 2.10.0 (Keras version 2.10.0).
// Interpreter from tflite_runtime version 2.11.0 and revision 0.6.0-134012-g31cfa135ac4.
#pragma once
#include <stdint.h>

const int32_t lstm_2_input_to_cell_eff_bias[7] = {-24495, 6800, -29846, 4212, -18843, -18518, -34196};
