// Generated by generate_test_data.py using tensorflow version 2.10.0 (Keras version 2.10.0).
// Interpreter from tflite_runtime version 2.11.0 and revision 0.6.0-134012-g31cfa135ac4.
#pragma once
#include <stdint.h>

const int8_t lstm_2_input_to_cell_w[42] = {-37,  -62, 88,  15, -84, 31,  14,   -46, 97,  33,  86,  -70, -112, -75,
                                           -45,  -13, -22, 18, 26,  -10, -117, -82, -45, 67,  106, 60,  -127, -33,
                                           -118, -78, -90, 51, 10,  -23, 43,   52,  23,  -64, 79,  75,  -121, -7};
