// Generated by generate_test_data.py using tensorflow version 2.9.1 (Keras version 2.9.0).
// Interpreter from tflite_runtime version 2.11.0 and revision 0.6.0-135805-g25bfb32e73a.
#pragma once
#include <stdint.h>

const int8_t lstm_2_input_to_output_w[30] = {-100, -31, -40, -80, 35,  106, 17, -113, -45,  8,
                                             103,  -4,  114, -62, -22, 15,  99, 45,   -127, 22,
                                             -111, -69, -80, -85, 26,  56,  58, 85,   -55,  -124};
