// Generated by generate_test_data.py using tensorflow version 2.9.1 (Keras version 2.9.0).
// Interpreter from tflite_runtime version 2.11.0 and revision 0.6.0-135805-g25bfb32e73a.
#pragma once
#include <stdint.h>

const int8_t lstm_2_input_to_cell_w[30] = {119, 24,  21,  70, -4,   126, 124, 127, 78,  2,   -9, 96, 39,  -27, 108,
                                           -30, -56, -79, 18, -102, 127, 66,  75,  -97, -87, 48, 95, 101, -31, -50};
