// Generated by generate_test_data.py using tensorflow version 2.10.0 (Keras version 2.10.0).
// Interpreter from tflite_runtime version 2.11.0 and revision 0.6.0-134012-g31cfa135ac4.
#pragma once
#include <stdint.h>

const int8_t lstm_2_input_to_input_w[42] = {92,   7,    -36, 85,   13,   32, -115, 84, -64, 124, 86,  -83, 6,    127,
                                            -106, -116, -80, -100, -124, -2, 46,   54, -56, -74, -20, 83,  -113, -59,
                                            36,   87,   -86, -31,  -30,  5,  122,  91, -73, 96,  11,  -7,  101,  -77};
