// Generated by generate_test_data.py using tensorflow version 2.10.0 (Keras version 2.10.0).
// Interpreter from tflite_runtime version 2.11.0 and revision 0.6.0-134012-g31cfa135ac4.
#pragma once
#include <stdint.h>

const int32_t lstm_2_input_to_output_eff_bias[7] = {-23260, -64953, 21616, 44956, -55885, -8659, -2372};
