// Generated by generate_test_data.py using tensorflow version 2.9.1 (Keras version 2.9.0).
// Interpreter from tflite_runtime version 2.11.0 and revision 0.6.0-135805-g25bfb32e73a.
#pragma once
#include <stdint.h>

const int8_t lstm_2_input_to_forget_w[30] = {20,  -31, -21, 43, 22, -103, -36, 76, -56, -20, -37,  -10, -72, -127, -2,
                                             -37, 10,  5,   11, 88, -78,  37,  40, -59, -51, -117, -90, 57,  65,   -81};
