// Generated by generate_test_data.py using tensorflow version 2.10.0 (Keras version 2.10.0).
// Interpreter from tflite_runtime version 2.11.0 and revision 0.6.0-134012-g31cfa135ac4.
#pragma once
#include <stdint.h>

const int8_t lstm_2_input_to_forget_w[42] = {127,  -100, -44,  35, -24, -24, -26,  27,  -21, -44, 116, 40,  -43, 70,
                                             -101, -126, 78,   13, -31, -40, 121,  -67, 108, 77,  -56, 93,  10,  74,
                                             56,   30,   -104, 47, -14, 60,  -120, -97, 19,  -63, 84,  111, -53, 53};
