// Generated by generate_test_data.py using tensorflow version 2.10.0 (Keras version 2.10.0).
// Interpreter from tflite_runtime version 2.11.0 and revision 0.6.0-134012-g31cfa135ac4.
#pragma once
#include <stdint.h>

const int8_t lstm_2_input_to_output_w[42] = {-13,  -107, 95, -90, 57,   -71, -122, -38,  -121, -44, -68, -69, 109, -62,
                                             126,  -53,  43, -26, -101, 123, 50,   82,   -46,  39,  -81, 41,  -58, -52,
                                             -101, 40,   13, -45, -15,  -90, 19,   -127, -6,   -21, -38, 14,  25,  -44};
