// Generated by generate_test_data.py using tensorflow version 2.10.0 (Keras version 2.10.0).
// Interpreter from tflite_runtime version 2.11.0 and revision 0.6.0-134012-g31cfa135ac4.
#pragma once
#include <stdint.h>

const int32_t lstm_2_input_to_forget_eff_bias[7] = {-19136, 14836, 19173, 16790, 12029, -6452, 14645};
