// Generated by generate_test_data.py using tensorflow version 2.10.0 (Keras version 2.10.0).
// Interpreter from tflite_runtime version 2.11.0 and revision 0.6.0-134012-g31cfa135ac4.
#pragma once
#include <stdint.h>

const int32_t lstm_2_output_gate_bias[7] = {-6748, -5817, 4080, 26140, -28877, 22701, 6588};
