// Generated by generate_test_data.py using tensorflow version 2.9.1 (Keras version 2.9.0).
// Interpreter from tflite_runtime version 2.11.0 and revision 0.6.0-135805-g25bfb32e73a.
#pragma once
#include <stdint.h>

const int8_t lstm_2_recurrent_input_to_forget_w[25] = {11,  40,   37,   54,  -13,  73,  -26, -33, 22,  127, -69, 72, 95,
                                                       -15, -106, -106, -94, -106, 109, 81,  40,  -29, 93,  -79, 22};
