// Generated by generate_test_data.py using tensorflow version 2.10.0 (Keras version 2.10.0).
// Interpreter from tflite_runtime version 2.11.0 and revision 0.6.0-134012-g31cfa135ac4.
#pragma once
#include <stdint.h>

const int8_t lstm_2_recurrent_input_to_cell_w[49] = {111, -117, 121, -81, -85, -44, -107, 118,  83,  51,  69,  16,  110,
                                                     60,  -36,  114, -55, -87, -60, -115, -8,   -98, -91, -45, -94, -10,
                                                     49,  -127, 17,  112, 126, -21, 86,   -80,  82,  44,  90,  -20, -38,
                                                     55,  -67,  39,  125, 104, 80,  102,  -110, -4,  -5};
