// Generated by generate_test_data.py using tensorflow version 2.9.1 (Keras version 2.9.0).
// Interpreter from tflite_runtime version 2.11.0 and revision 0.6.0-135805-g25bfb32e73a.
#pragma once
#include <stdint.h>

const int8_t lstm_2_recurrent_input_to_output_w[25] = {
    -68, -94, -121, 75, -2, 36, 58, 110, 38, 55, -40, 19, -63, -1, -127, 9, 3, -117, 108, -122, 71, -105, -25, 108, -2};
