// Generated by generate_test_data.py using tensorflow version 2.9.1 (Keras version 2.9.0).
// Interpreter from tflite_runtime version 2.11.0 and revision 0.6.0-135805-g25bfb32e73a.
#pragma once
#include <stdint.h>

const int32_t lstm_2_recurrent_to_forget_eff_bias[5] = {12126, 15322, -2162, -10904, 4418};
