// Generated by generate_test_data.py using tensorflow version 2.10.0 (Keras version 2.10.0).
// Interpreter from tflite_runtime version 2.11.0 and revision 0.6.0-134012-g31cfa135ac4.
#pragma once
#include <stdint.h>

const int8_t lstm_2_recurrent_input_to_input_w[49] = {
    -41,  46,   -126, -116, -34, -18, -107, -105, -6,   -68, 56,  36, -2,  113, 76,   -65, 67,
    -123, -125, 74,   92,   31,  116, -108, 114,  -123, -60, -59, 29, -23, 4,   -116, 114, -94,
    -79,  79,   -13,  -70,  -99, -17, 67,   120,  127,  41,  -71, 59, 80,  53,  -111};
