// Generated by generate_test_data.py using tensorflow version 2.10.0 (Keras version 2.10.0).
// Interpreter from tflite_runtime version 2.11.0 and revision 0.6.0-134012-g31cfa135ac4.
#pragma once
#include <stdint.h>

const int8_t lstm_2_recurrent_input_to_output_w[49] = {
    -38, 81,  -44,  -57, 126,  -127, 50,  -3,  54,  71,  74,  -51, -9,  -3,  -122, 51, -26,
    92,  -18, -124, -91, 73,   -68,  109, -33, 24,  -55, -48, 124, -83, 12,  -113, 68, 23,
    32,  88,  -115, 113, -109, 28,   61,  -37, -31, -62, -83, 74,  73,  -23, -123};
