// Generated by generate_test_data.py using tensorflow version 2.9.1 (Keras version 2.9.0).
// Interpreter from tflite_runtime version 2.11.0 and revision 0.6.0-135805-g25bfb32e73a.
#pragma once
#include <stdint.h>

const int8_t lstm_2_recurrent_input_to_input_w[25] = {-91, -6, -84, -90, -25, 110, 51, 95,  -93, 86, -96, 37, -52,
                                                      12,  41, 33,  1,   114, -71, 71, 127, 112, -8, 85,  -99};
