// Generated by generate_test_data.py using tensorflow version 2.10.0 (Keras version 2.10.0).
// Interpreter from tflite_runtime version 2.11.0 and revision 0.6.0-134012-g31cfa135ac4.
#pragma once
#include <stdint.h>

const int8_t lstm_2_recurrent_input_to_forget_w[49] = {
    46,  72, -126, -19,  -98, -127, -83, 6,    74,  110, 109, 69,   -82, 71,  100, 84,  -37,
    -88, 60, -86,  -111, 14,  -64,  -95, 41,   87,  -27, -67, -110, 59,  -66, 88,  -62, 61,
    121, 60, -52,  -17,  113, -102, 53,  -103, 127, -56, -57, 45,   37,  125, 32};
