// Generated by depthwise_conv_settings_flt.py using PyTorch version 2.10.0+cu128.
const float32_t depthwise_kernel_2x2_f32_biases_data[4] = {0.23972787f, -0.100074098f, 0.461551815f, -0.111373886f};
