// Generated by generate_test_data.py using tensorflow version 2.10.0 (Keras version 2.10.0).
// Interpreter from tensorflow version 2.10.0 and revision v2.10.0-rc3-6-g359c3cdfc5f.
#pragma once
#include <stdint.h>

const int8_t dw_int16xint8_fast_null_bias_weights[32] = {-37, -32, 63,  13,  -123, 125,  85,  122, -127, -44, 54,
                                                         72,  56,  127, 51,  127,  -127, 86,  127, -127, 122, -111,
                                                         -91, -22, 8,   127, 48,   -25,  127, -47, 127,  -112};
