// Generated by batch_norm_settings_flt.py using PyTorch version 2.10.0+cu128.
const float32_t bn_op_nhwc_f32_scale[7] =
    {1.13135958f, 1.06143749f, 1.02240932f, 0.999994993f, 0.987537265f, 0.981491745f, 0.979792655f};
