// Generated by conv_settings_flt.py using PyTorch version 2.10.0+cu128.
const float32_t conv_match_1x1_stride_x_f32_biases_data[5] = {0.303631485f,
                                                              -0.0841947123f,
                                                              -0.291997075f,
                                                              0.243136406f,
                                                              0.109799214f};
