// Generated by generate_test_data.py using tensorflow version 2.10.0 (Keras version 2.10.0).
// Interpreter from tensorflow version 2.10.0 and revision v2.10.0-rc3-6-g359c3cdfc5f.
#pragma once
#include <stdint.h>

const int8_t basic_input[40] = {-9,  -38, 76,  -40, 99,  60, 64,  52,  47,  -43, 72, 28,  -82, 61,
                                -63, 48,  -21, -47, 74,  29, -28, 8,   -38, 13,  33, -45, 59,  -25,
                                -8,  -50, 107, 81,  -77, 43, -82, 125, 83,  23,  17, 15};
