// Generated by generate_test_data.py using tensorflow version 2.10.0 (Keras version 2.10.0).
// Interpreter from tensorflow version 2.10.0 and revision v2.10.0-rc3-6-g359c3cdfc5f.
#pragma once
#include <stdint.h>

const int8_t basic_output_ref[20] = {127, -128, 63,  -128, -128, 127, 127, 127, -41, 127,
                                     -17, 127,  127, 127,  -128, 127, 127, 127, 127, 127};
