// Generated by pooling_settings_flt.py using PyTorch version 2.10.0+cu128.
const float16_t maxpooling_match_3_f16_output_ref[10] = {(float16_t)-4.94921875f,
                                                         (float16_t)-3.2421875f,
                                                         (float16_t)1.98632812f,
                                                         (float16_t)-5.5703125f,
                                                         (float16_t)-1.77734375f,
                                                         (float16_t)3.51953125f,
                                                         (float16_t)-1.08007812f,
                                                         (float16_t)5.4375f,
                                                         (float16_t)5.35546875f,
                                                         (float16_t)-3.57226562f};
