// Generated by lstm_settings_flt.py using PyTorch version 2.10.0+cu128.
const float16_t lstm_match_one_time_step_f16_cell_hidden_weights[9] = {(float16_t)-0.0135269165f,
                                                                       (float16_t)-0.260986328f,
                                                                       (float16_t)0.175170898f,
                                                                       (float16_t)-0.254638672f,
                                                                       (float16_t)0.283447266f,
                                                                       (float16_t)0.217529297f,
                                                                       (float16_t)-0.335693359f,
                                                                       (float16_t)0.0269622803f,
                                                                       (float16_t)0.179931641f};
