// Generated by lstm_settings_flt.py using PyTorch version 2.10.0+cu128.
const float16_t lstm_match_one_time_step_f16_cell_bias[3] = {(float16_t)-0.161865234f,
                                                             (float16_t)0.173095703f,
                                                             (float16_t)0.300048828f};
