// Generated by lstm_settings_flt.py using PyTorch version 2.10.0+cu128.
const float16_t lstm_match_one_time_step_f16_cell_input_weights[66] = {
    (float16_t)-0.284179688f,  (float16_t)-0.0414123535f, (float16_t)0.164672852f,   (float16_t)0.0824584961f,
    (float16_t)-0.14453125f,   (float16_t)0.0772705078f,  (float16_t)-0.229736328f,  (float16_t)0.278564453f,
    (float16_t)-0.0107040405f, (float16_t)0.171386719f,   (float16_t)0.0498962402f,  (float16_t)0.303466797f,
    (float16_t)0.0231933594f,  (float16_t)0.107910156f,   (float16_t)-0.334960938f,  (float16_t)-0.0807495117f,
    (float16_t)-0.256591797f,  (float16_t)0.217651367f,   (float16_t)-0.233642578f,  (float16_t)-0.0421142578f,
    (float16_t)0.250976562f,   (float16_t)-0.194824219f,  (float16_t)-0.0370178223f, (float16_t)-0.2578125f,
    (float16_t)0.182373047f,   (float16_t)0.135986328f,   (float16_t)0.0908813477f,  (float16_t)0.221069336f,
    (float16_t)0.208618164f,   (float16_t)0.065246582f,   (float16_t)-0.123352051f,  (float16_t)0.00511932373f,
    (float16_t)-0.195556641f,  (float16_t)-0.279785156f,  (float16_t)-0.155639648f,  (float16_t)0.257324219f,
    (float16_t)0.192504883f,   (float16_t)-0.142578125f,  (float16_t)-0.346679688f,  (float16_t)0.227294922f,
    (float16_t)-0.216796875f,  (float16_t)0.192260742f,   (float16_t)-0.254394531f,  (float16_t)0.0650634766f,
    (float16_t)0.0477905273f,  (float16_t)-0.24621582f,   (float16_t)-0.250244141f,  (float16_t)-0.230834961f,
    (float16_t)0.272705078f,   (float16_t)0.295654297f,   (float16_t)-0.0692138672f, (float16_t)0.184692383f,
    (float16_t)-0.141967773f,  (float16_t)0.148071289f,   (float16_t)-0.298095703f,  (float16_t)-0.325927734f,
    (float16_t)0.244384766f,   (float16_t)-0.254150391f,  (float16_t)-0.0966796875f, (float16_t)0.281982422f,
    (float16_t)-0.0726318359f, (float16_t)-0.0352172852f, (float16_t)0.162841797f,   (float16_t)0.026473999f,
    (float16_t)-0.193481445f,  (float16_t)0.238525391f};
