// Generated by lstm_settings_flt.py using PyTorch version 2.10.0+cu128.
const float16_t lstm_match_one_time_step_f16_forget_input_weights[66] = {
    (float16_t)-0.337890625f,  (float16_t)0.0718994141f,  (float16_t)0.148193359f,   (float16_t)0.302490234f,
    (float16_t)0.165893555f,   (float16_t)-0.159057617f,  (float16_t)-0.118286133f,  (float16_t)-0.338867188f,
    (float16_t)0.0102539062f,  (float16_t)-0.230224609f,  (float16_t)0.0189819336f,  (float16_t)-0.0634155273f,
    (float16_t)0.216430664f,   (float16_t)-0.128417969f,  (float16_t)0.166625977f,   (float16_t)0.0665283203f,
    (float16_t)0.205688477f,   (float16_t)-0.322265625f,  (float16_t)-0.131347656f,  (float16_t)0.309570312f,
    (float16_t)-0.145385742f,  (float16_t)0.0204467773f,  (float16_t)0.181518555f,   (float16_t)-0.120910645f,
    (float16_t)-0.338623047f,  (float16_t)0.233764648f,   (float16_t)-0.223144531f,  (float16_t)0.338623047f,
    (float16_t)-0.109985352f,  (float16_t)-0.147460938f,  (float16_t)-0.229858398f,  (float16_t)0.298828125f,
    (float16_t)-0.0421142578f, (float16_t)-0.0100631714f, (float16_t)-0.0713500977f, (float16_t)-0.0272979736f,
    (float16_t)-0.0256347656f, (float16_t)0.344726562f,   (float16_t)-0.162353516f,  (float16_t)-0.269042969f,
    (float16_t)0.136108398f,   (float16_t)-0.16003418f,   (float16_t)0.227294922f,   (float16_t)-0.217285156f,
    (float16_t)0.126586914f,   (float16_t)0.344238281f,   (float16_t)-0.114257812f,  (float16_t)0.104064941f,
    (float16_t)0.150512695f,   (float16_t)-0.310302734f,  (float16_t)-0.0546569824f, (float16_t)0.138549805f,
    (float16_t)0.221923828f,   (float16_t)-0.292236328f,  (float16_t)0.155273438f,   (float16_t)-0.0363769531f,
    (float16_t)-0.147705078f,  (float16_t)-0.17578125f,   (float16_t)0.0673828125f,  (float16_t)-0.228637695f,
    (float16_t)0.101135254f,   (float16_t)0.211547852f,   (float16_t)-0.0162811279f, (float16_t)-0.333984375f,
    (float16_t)-0.0935058594f, (float16_t)0.0319824219f};
