// Generated by lstm_settings_flt.py using PyTorch version 2.10.0+cu128.
const float16_t lstm_match_one_time_step_f16_forget_bias[3] = {(float16_t)0.0811157227f,
                                                               (float16_t)0.169189453f,
                                                               (float16_t)-0.260253906f};
