// Generated by lstm_settings_flt.py using PyTorch version 2.10.0+cu128.
const float16_t lstm_match_one_time_step_f16_forget_hidden_weights[9] = {(float16_t)0.346679688f,
                                                                         (float16_t)-0.220092773f,
                                                                         (float16_t)0.265136719f,
                                                                         (float16_t)-0.160644531f,
                                                                         (float16_t)0.0973510742f,
                                                                         (float16_t)-0.242553711f,
                                                                         (float16_t)0.275634766f,
                                                                         (float16_t)0.00457000732f,
                                                                         (float16_t)-0.242797852f};
