// Generated by lstm_settings_flt.py using PyTorch version 2.10.0+cu128.
const float16_t lstm_match_one_time_step_f16_input[66] = {
    (float16_t)-0.752929688f,  (float16_t)-0.612792969f, (float16_t)-0.472900391f,  (float16_t)0.886230469f,
    (float16_t)-0.104003906f,  (float16_t)0.0447998047f, (float16_t)-0.276611328f,  (float16_t)-0.357666016f,
    (float16_t)-0.747558594f,  (float16_t)-0.849609375f, (float16_t)0.37890625f,    (float16_t)0.731445312f,
    (float16_t)0.860839844f,   (float16_t)0.571289062f,  (float16_t)-0.0513000488f, (float16_t)0.5546875f,
    (float16_t)0.983398438f,   (float16_t)-0.297363281f, (float16_t)0.657714844f,   (float16_t)-0.982421875f,
    (float16_t)0.637695312f,   (float16_t)-0.140258789f, (float16_t)-0.294189453f,  (float16_t)0.0637207031f,
    (float16_t)-0.492431641f,  (float16_t)-0.355957031f, (float16_t)-0.5f,          (float16_t)0.261474609f,
    (float16_t)-0.546875f,     (float16_t)-0.120300293f, (float16_t)0.251953125f,   (float16_t)0.572265625f,
    (float16_t)0.708007812f,   (float16_t)-0.733886719f, (float16_t)-0.24597168f,   (float16_t)0.0244140625f,
    (float16_t)-0.755371094f,  (float16_t)0.221191406f,  (float16_t)-0.750488281f,  (float16_t)0.816894531f,
    (float16_t)0.8125f,        (float16_t)0.488037109f,  (float16_t)-0.942382812f,  (float16_t)0.589355469f,
    (float16_t)-0.0822753906f, (float16_t)0.763671875f,  (float16_t)-0.670410156f,  (float16_t)0.323486328f,
    (float16_t)0.0723266602f,  (float16_t)0.0940551758f, (float16_t)-0.513671875f,  (float16_t)-0.960449219f,
    (float16_t)0.875488281f,   (float16_t)0.0104522705f, (float16_t)0.598632812f,   (float16_t)-0.0704345703f,
    (float16_t)-0.0592041016f, (float16_t)0.583984375f,  (float16_t)0.21862793f,    (float16_t)-0.66796875f,
    (float16_t)-0.795898438f,  (float16_t)-0.787109375f, (float16_t)-0.444824219f,  (float16_t)0.75390625f,
    (float16_t)-0.354003906f,  (float16_t)0.190917969f};
