// Generated by lstm_settings_flt.py using PyTorch version 2.10.0+cu128.
const float16_t lstm_match_one_time_step_f16_input_input_weights[66] = {
    (float16_t)-0.210571289f,  (float16_t)0.0914306641f,  (float16_t)0.0500488281f,   (float16_t)0.05859375f,
    (float16_t)0.127441406f,   (float16_t)0.297119141f,   (float16_t)-0.266845703f,   (float16_t)-0.150756836f,
    (float16_t)0.309814453f,   (float16_t)0.335693359f,   (float16_t)-0.00262451172f, (float16_t)-0.0230560303f,
    (float16_t)-0.144165039f,  (float16_t)0.283203125f,   (float16_t)-0.254394531f,   (float16_t)-0.119384766f,
    (float16_t)-0.0467834473f, (float16_t)0.168945312f,   (float16_t)-0.0523071289f,  (float16_t)0.108520508f,
    (float16_t)-0.339111328f,  (float16_t)-0.190307617f,  (float16_t)-0.216308594f,   (float16_t)0.346191406f,
    (float16_t)0.0673828125f,  (float16_t)-0.173339844f,  (float16_t)-0.335205078f,   (float16_t)0.227050781f,
    (float16_t)-0.117492676f,  (float16_t)-0.150390625f,  (float16_t)0.0703735352f,   (float16_t)-0.284667969f,
    (float16_t)-0.147705078f,  (float16_t)-0.0813598633f, (float16_t)0.111328125f,    (float16_t)0.303222656f,
    (float16_t)-0.221923828f,  (float16_t)0.0752563477f,  (float16_t)0.0475158691f,   (float16_t)-0.272460938f,
    (float16_t)0.17956543f,    (float16_t)0.347412109f,   (float16_t)-0.289550781f,   (float16_t)-0.0728759766f,
    (float16_t)-0.142456055f,  (float16_t)-0.267822266f,  (float16_t)-0.328125f,      (float16_t)0.270263672f,
    (float16_t)-0.195922852f,  (float16_t)-0.208618164f,  (float16_t)-0.233886719f,   (float16_t)-0.127075195f,
    (float16_t)0.224731445f,   (float16_t)0.0536193848f,  (float16_t)-0.0345153809f,  (float16_t)0.0215148926f,
    (float16_t)0.286376953f,   (float16_t)0.0218963623f,  (float16_t)-0.197387695f,   (float16_t)0.107543945f,
    (float16_t)-0.0321960449f, (float16_t)0.00939178467f, (float16_t)0.240722656f,    (float16_t)-0.205932617f,
    (float16_t)-0.0925292969f, (float16_t)0.170166016f};
