// Generated by lstm_settings_flt.py using PyTorch version 2.10.0+cu128.
const float16_t lstm_match_one_time_step_f16_input_hidden_weights[9] = {(float16_t)-0.0262145996f,
                                                                        (float16_t)0.184204102f,
                                                                        (float16_t)-0.239746094f,
                                                                        (float16_t)-0.267089844f,
                                                                        (float16_t)0.229858398f,
                                                                        (float16_t)0.0948486328f,
                                                                        (float16_t)-0.141967773f,
                                                                        (float16_t)-0.116333008f,
                                                                        (float16_t)-0.166748047f};
