// Generated by lstm_settings_flt.py using PyTorch version 2.10.0+cu128.
const float16_t lstm_match_one_time_step_f16_input_bias[3] = {(float16_t)-0.20690918f,
                                                              (float16_t)-0.0510253906f,
                                                              (float16_t)0.224121094f};
