// Generated by lstm_settings_flt.py using PyTorch version 2.10.0+cu128.
const float16_t lstm_match_one_time_step_f16_output_ref[9] = {(float16_t)-0.00536346436f,
                                                              (float16_t)-0.190185547f,
                                                              (float16_t)-0.00748825073f,
                                                              (float16_t)-0.0299072266f,
                                                              (float16_t)0.135864258f,
                                                              (float16_t)0.298095703f,
                                                              (float16_t)-0.125488281f,
                                                              (float16_t)0.0417785645f,
                                                              (float16_t)-0.16027832f};
