// Generated by lstm_settings_flt.py using PyTorch version 2.10.0+cu128.
const float16_t lstm_match_one_time_step_f16_output_hidden_weights[9] = {(float16_t)-0.160888672f,
                                                                         (float16_t)0.265380859f,
                                                                         (float16_t)-0.254150391f,
                                                                         (float16_t)0.193725586f,
                                                                         (float16_t)-0.0642089844f,
                                                                         (float16_t)-0.138916016f,
                                                                         (float16_t)-0.00296020508f,
                                                                         (float16_t)-0.0197296143f,
                                                                         (float16_t)0.153930664f};
