// Generated by lstm_settings_flt.py using PyTorch version 2.10.0+cu128.
const float16_t lstm_match_one_time_step_f16_output_bias[3] = {(float16_t)0.253662109f,
                                                               (float16_t)-0.137817383f,
                                                               (float16_t)0.33984375f};
