// Generated by lstm_settings_flt.py using PyTorch version 2.10.0+cu128.
const float16_t lstm_match_one_time_step_f16_output_input_weights[66] = {
    (float16_t)0.16418457f,    (float16_t)-0.203735352f,  (float16_t)-0.102355957f,  (float16_t)-0.348876953f,
    (float16_t)0.234375f,      (float16_t)0.0653076172f,  (float16_t)0.0556335449f,  (float16_t)0.234741211f,
    (float16_t)0.205078125f,   (float16_t)-0.200805664f,  (float16_t)0.290283203f,   (float16_t)-0.095703125f,
    (float16_t)0.262695312f,   (float16_t)0.202758789f,   (float16_t)-0.228881836f,  (float16_t)0.288085938f,
    (float16_t)-0.269287109f,  (float16_t)-0.0679931641f, (float16_t)0.338623047f,   (float16_t)-0.145751953f,
    (float16_t)0.0109558105f,  (float16_t)0.13659668f,    (float16_t)0.268798828f,   (float16_t)-0.0139389038f,
    (float16_t)0.194824219f,   (float16_t)0.0233612061f,  (float16_t)-0.293701172f,  (float16_t)0.142700195f,
    (float16_t)-0.198608398f,  (float16_t)0.343017578f,   (float16_t)-0.279785156f,  (float16_t)0.191772461f,
    (float16_t)-0.249023438f,  (float16_t)0.228515625f,   (float16_t)0.0250091553f,  (float16_t)0.0435791016f,
    (float16_t)-0.200561523f,  (float16_t)0.214599609f,   (float16_t)0.0475769043f,  (float16_t)-0.158081055f,
    (float16_t)0.341796875f,   (float16_t)-0.248535156f,  (float16_t)-0.22265625f,   (float16_t)-0.106018066f,
    (float16_t)0.0841064453f,  (float16_t)0.182006836f,   (float16_t)-0.261230469f,  (float16_t)-0.200195312f,
    (float16_t)-0.115661621f,  (float16_t)0.296142578f,   (float16_t)-0.0693969727f, (float16_t)0.022354126f,
    (float16_t)0.00247383118f, (float16_t)0.0883789062f,  (float16_t)-0.0323791504f, (float16_t)0.208618164f,
    (float16_t)0.132446289f,   (float16_t)0.227661133f,   (float16_t)0.173828125f,   (float16_t)-0.338867188f,
    (float16_t)0.210571289f,   (float16_t)-0.280517578f,  (float16_t)0.324951172f,   (float16_t)-0.00135421753f,
    (float16_t)-0.223999023f,  (float16_t)-0.200073242f};
