// Generated by concatenation_settings_flt.py using PyTorch version 2.10.0+cu128.
#define CONCAT_C_F32_INPUT_N 1
#define CONCAT_C_F32_INPUT_H 8
#define CONCAT_C_F32_INPUT_W 8
#define CONCAT_C_F32_LHS_C 5
#define CONCAT_C_F32_RHS_C 3
#define CONCAT_C_F32_OUTPUT_C 8
#define CONCAT_C_F32_SIZE 512
#define CONCAT_C_F32_LAYOUT ARM_NN_LAYOUT_NHWC
