// Generated by conv_settings_flt.py using PyTorch version 2.10.0+cu128.
const float32_t conv_match_1x1_basic_f32_biases_data[7] =
    {-0.102267995f, -0.425354481f, 0.0492131747f, -0.123081155f, 0.0641790107f, -0.09203659f, -0.278269589f};
