// Generated by generate_test_data.py using tensorflow version 2.10.0 (Keras version 2.10.0).
// Interpreter from tensorflow version 2.10.0 and revision v2.10.0-rc3-6-g359c3cdfc5f.
#pragma once
#define CONV_8_OUT_CH 64
#define CONV_8_IN_CH 64
#define CONV_8_INPUT_W 5
#define CONV_8_INPUT_H 25
#define CONV_8_DST_SIZE 8000
#define CONV_8_FILTER_X 1
#define CONV_8_FILTER_Y 1
#define CONV_8_FILTER_W 1
#define CONV_8_FILTER_H 1
#define CONV_8_STRIDE_X 1
#define CONV_8_STRIDE_Y 1
#define CONV_8_STRIDE_W 1
#define CONV_8_STRIDE_H 1
#define CONV_8_PAD_X 0
#define CONV_8_PAD_Y 0
#define CONV_8_PAD_W 0
#define CONV_8_PAD_H 0
#define CONV_8_OUTPUT_W 5
#define CONV_8_OUTPUT_H 25
#define CONV_8_INPUT_OFFSET 128
#define CONV_8_INPUT_SIZE 8000
#define CONV_8_OUT_ACTIVATION_MIN -128
#define CONV_8_OUT_ACTIVATION_MAX 127
#define CONV_8_INPUT_BATCHES 1
#define CONV_8_OUTPUT_OFFSET -128
#define CONV_8_DILATION_X 1
#define CONV_8_DILATION_Y 1
#define CONV_8_DILATION_W 1
#define CONV_8_DILATION_H 1
