// Generated by generate_test_data.py using tensorflow version 2.10.0 (Keras version 2.10.0).
// Interpreter from tensorflow version 2.10.0 and revision v2.10.0-rc3-6-g359c3cdfc5f.
#pragma once
#define CONV_0_OUT_CH 64
#define CONV_0_IN_CH 1
#define CONV_0_INPUT_W 10
#define CONV_0_INPUT_H 49
#define CONV_0_DST_SIZE 8000
#define CONV_0_FILTER_X 4
#define CONV_0_FILTER_Y 10
#define CONV_0_FILTER_W 4
#define CONV_0_FILTER_H 10
#define CONV_0_STRIDE_X 2
#define CONV_0_STRIDE_Y 2
#define CONV_0_STRIDE_W 2
#define CONV_0_STRIDE_H 2
#define CONV_0_PAD_X 1
#define CONV_0_PAD_Y 4
#define CONV_0_PAD_W 1
#define CONV_0_PAD_H 4
#define CONV_0_OUTPUT_W 5
#define CONV_0_OUTPUT_H 25
#define CONV_0_INPUT_OFFSET -100
#define CONV_0_INPUT_SIZE 490
#define CONV_0_OUT_ACTIVATION_MIN -128
#define CONV_0_OUT_ACTIVATION_MAX 127
#define CONV_0_INPUT_BATCHES 1
#define CONV_0_OUTPUT_OFFSET -128
#define CONV_0_DILATION_X 1
#define CONV_0_DILATION_Y 1
#define CONV_0_DILATION_W 1
#define CONV_0_DILATION_H 1
