// Generated by generate_test_data.py using tensorflow version 2.10.0 (Keras version 2.10.0).
// Interpreter from tensorflow version 2.10.0 and revision v2.10.0-rc3-6-g359c3cdfc5f.
#pragma once
#define DW_CONV_5_OUT_CH 64
#define DW_CONV_5_IN_CH 64
#define DW_CONV_5_INPUT_W 5
#define DW_CONV_5_INPUT_H 25
#define DW_CONV_5_DST_SIZE 8000
#define DW_CONV_5_FILTER_X 3
#define DW_CONV_5_FILTER_Y 3
#define DW_CONV_5_FILTER_W 3
#define DW_CONV_5_FILTER_H 3
#define DW_CONV_5_STRIDE_X 1
#define DW_CONV_5_STRIDE_Y 1
#define DW_CONV_5_STRIDE_W 1
#define DW_CONV_5_STRIDE_H 1
#define DW_CONV_5_PAD_X 1
#define DW_CONV_5_PAD_Y 1
#define DW_CONV_5_PAD_W 1
#define DW_CONV_5_PAD_H 1
#define DW_CONV_5_OUTPUT_W 5
#define DW_CONV_5_OUTPUT_H 25
#define DW_CONV_5_INPUT_OFFSET 128
#define DW_CONV_5_INPUT_SIZE 8000
#define DW_CONV_5_OUT_ACTIVATION_MIN -128
#define DW_CONV_5_OUT_ACTIVATION_MAX 127
#define DW_CONV_5_INPUT_BATCHES 1
#define DW_CONV_5_OUTPUT_OFFSET -128
#define DW_CONV_5_DILATION_X 1
#define DW_CONV_5_DILATION_Y 1
#define DW_CONV_5_DILATION_W 1
#define DW_CONV_5_DILATION_H 1
#define DW_CONV_5_ACCUMULATION_DEPTH 8000
