// Generated by generate_test_data.py using tensorflow version 2.10.0 (Keras version 2.10.0).
// Interpreter from tensorflow version 2.10.0 and revision v2.10.0-rc3-6-g359c3cdfc5f.
#pragma once
#include <stdint.h>

const int32_t ds_cnn_s_layer_12_fully_connected_bias[12] = {93, 131, -99, -72, 175, -19, 2, -77, -6, -51, -3, 22};
