// Generated by generate_test_data.py using tensorflow version 2.10.0 (Keras version 2.10.0).
// Interpreter from tensorflow version 2.10.0 and revision v2.10.0-rc3-6-g359c3cdfc5f.
#pragma once
#define SOFTMAX_13_OUT_CH 64
#define SOFTMAX_13_IN_CH 12
#define SOFTMAX_13_INPUT_W 12
#define SOFTMAX_13_INPUT_H 1
#define SOFTMAX_13_DST_SIZE 768
#define SOFTMAX_13_NUM_ROWS 1
#define SOFTMAX_13_ROW_SIZE 12
#define SOFTMAX_13_MULT 1881344896
#define SOFTMAX_13_SHIFT 24
#define SOFTMAX_13_DIFF_MIN -124
