// Generated by depthwise_conv_settings_flt.py using PyTorch version 2.10.0+cu128.
const float16_t depthwise_kernel_2x2_f16_biases_data[4] = {(float16_t)0.239746094f,
                                                           (float16_t)-0.100097656f,
                                                           (float16_t)0.461669922f,
                                                           (float16_t)-0.11138916f};
