// Generated by fully_connected_settings_flt.py using PyTorch version 2.10.0+cu128.
const float32_t fully_connected_match_mve_1_f32_biases_data[4] = {0.485140294f,
                                                                  -0.339216888f,
                                                                  0.715892017f,
                                                                  0.60747987f};
