// Generated by fully_connected_settings_flt.py using PyTorch version 2.10.0+cu128.
const float32_t fully_connected_match_mve_1_f32_input_data[20] = {
    -1.15106368f, -1.85897899f, 0.647217512f,  -1.60712028f,  -1.25007951f,  1.32596564f,  -0.854087532f,
    1.26931882f,  -1.01968491f, -0.138275132f, -0.768471181f, 1.32637835f,   -1.69400918f, 1.46766198f,
    1.22015655f,  1.07978451f,  1.75532126f,   -0.559055209f, -0.245186582f, 0.353682101f};
