// Generated by fully_connected_settings_flt.py using PyTorch version 2.10.0+cu128.
const float32_t fully_connected_match_mve_1_f32_output_ref_data[4] = {-2.03344059f,
                                                                      -6.53915358f,
                                                                      -0.130610645f,
                                                                      4.46209192f};
