// Generated by conv_settings_flt.py using PyTorch version 2.10.0+cu128.
const float16_t conv_match_2x2_dilation_f16_weights_data[36] = {
    (float16_t)-0.693847656f, (float16_t)0.565917969f,    (float16_t)-0.272705078f,  (float16_t)0.105712891f,
    (float16_t)0.455810547f,  (float16_t)0.0195770264f,   (float16_t)-0.0917358398f, (float16_t)0.327148438f,
    (float16_t)0.056854248f,  (float16_t)0.218383789f,    (float16_t)-0.712890625f,  (float16_t)-0.0975952148f,
    (float16_t)0.725097656f,  (float16_t)-0.561035156f,   (float16_t)-0.420898438f,  (float16_t)0.0367736816f,
    (float16_t)0.335693359f,  (float16_t)-0.0668334961f,  (float16_t)0.408203125f,   (float16_t)0.606933594f,
    (float16_t)0.437988281f,  (float16_t)-0.00477218628f, (float16_t)-0.520019531f,  (float16_t)-0.217529297f,
    (float16_t)0.644042969f,  (float16_t)-0.302490234f,   (float16_t)0.146972656f,   (float16_t)0.611816406f,
    (float16_t)0.638671875f,  (float16_t)0.101135254f,    (float16_t)-0.420410156f,  (float16_t)-0.477539062f,
    (float16_t)0.188232422f,  (float16_t)0.387939453f,    (float16_t)-0.239257812f,  (float16_t)-0.0489807129f};
