// Generated by generate_test_data.py using tensorflow version 2.10.0 (Keras version 2.10.0).
// Interpreter from tensorflow version 2.10.0 and revision v2.10.0-rc3-6-g359c3cdfc5f.
#pragma once
#include <stdint.h>

const int8_t fully_connected_null_bias_0_input[66] = {
    -118, -10, -64, -86, 91,  -114, -29, -73, 89,  42, 22,  37,  56, 71,  45, 43,   35, 37, 48,  38,   34,  -49,
    -117, 85,  33,  -78, -90, 83,   -10, 53,  21,  39, -14, 31,  58, 28,  14, -120, 11, 54, -21, -7,   -83, 69,
    -90,  19,  39,  87,  -45, 116,  -42, -4,  -35, 4,  48,  -54, 94, -47, 23, 4,    62, 74, 39,  -121, -60, -83};
