// Generated by depthwise_conv_settings_flt.py using PyTorch version 2.10.0+cu128.
const float16_t depthwise_match_stride2pad1_f16_input_data[49] = {
    (float16_t)-0.379882812f, (float16_t)0.971191406f,  (float16_t)-0.471923828f,  (float16_t)-0.00421142578f,
    (float16_t)0.357177734f,  (float16_t)-0.322265625f, (float16_t)-0.658691406f,  (float16_t)-0.871582031f,
    (float16_t)-0.804199219f, (float16_t)0.348388672f,  (float16_t)-0.785644531f,  (float16_t)0.922851562f,
    (float16_t)-0.258789062f, (float16_t)0.509765625f,  (float16_t)0.398925781f,   (float16_t)-0.471923828f,
    (float16_t)-0.818847656f, (float16_t)-0.131835938f, (float16_t)-0.786132812f,  (float16_t)0.0885009766f,
    (float16_t)0.903320312f,  (float16_t)-0.455566406f, (float16_t)-0.450195312f,  (float16_t)-0.969726562f,
    (float16_t)-0.908203125f, (float16_t)-0.119995117f, (float16_t)-0.0972900391f, (float16_t)0.522949219f,
    (float16_t)0.931152344f,  (float16_t)-0.634765625f, (float16_t)-0.660644531f,  (float16_t)0.38671875f,
    (float16_t)-0.554199219f, (float16_t)-0.297851562f, (float16_t)-0.978515625f,  (float16_t)0.740722656f,
    (float16_t)-0.605957031f, (float16_t)0.265136719f,  (float16_t)-0.647460938f,  (float16_t)0.682128906f,
    (float16_t)-0.806152344f, (float16_t)-0.917480469f, (float16_t)-0.647460938f,  (float16_t)-0.681152344f,
    (float16_t)-0.637207031f, (float16_t)-0.923828125f, (float16_t)-0.18371582f,   (float16_t)-0.0879516602f,
    (float16_t)0.642578125f};
