// Generated by depthwise_conv_settings_flt.py using PyTorch version 2.10.0+cu128.
const float16_t depthwise_match_stride2pad1_f16_weights_data[9] = {(float16_t)-0.0761108398f,
                                                                   (float16_t)-0.250976562f,
                                                                   (float16_t)-0.653320312f,
                                                                   (float16_t)-0.371337891f,
                                                                   (float16_t)-0.310791016f,
                                                                   (float16_t)-0.326416016f,
                                                                   (float16_t)0.141601562f,
                                                                   (float16_t)0.580078125f,
                                                                   (float16_t)0.184570312f};
