// Generated by test_settings.py using tensorflow version 2.14.0 (Keras version 2.14.0).
// Interpreter from tflite_runtime version 2.16.0dev20231108 and revision 0.6.0-155953-g2bcb825a248.
#include "biases_data.h"
#include "config_data.h"
#include "input_data.h"
#include "output_mult_data.h"
#include "output_ref_data.h"
#include "output_shift_data.h"
#include "weights_data.h"
