// Generated by test_settings.py using tensorflow version 2.15.0-dev20231004 (Keras version 2.15.0.dev2023092207).
// Interpreter from tflite_micro version 0.dev20231002060915-gec477d5c and revision None.
#pragma once
#include <stdint.h>

const int8_t fully_connected_int4_6_weights[27] = {153, 216, 186, 83,  173, 140, 59, 197, 191, 213, 218, 65,  18, 187,
                                                   185, 109, 233, 160, 94,  86,  72, 91,  222, 30,  192, 198, 181};
