// Generated by batch_norm_settings_flt.py using PyTorch version 2.10.0+cu128.
#define BN_OP_NHWC_F16_INPUT_N 1
#define BN_OP_NHWC_F16_INPUT_H 5
#define BN_OP_NHWC_F16_INPUT_W 6
#define BN_OP_NHWC_F16_INPUT_C 7
#define BN_OP_NHWC_F16_SIZE 210
#define BN_OP_NHWC_F16_LAYOUT ARM_NN_LAYOUT_NHWC
