// Generated by batch_norm_settings_flt.py using PyTorch version 2.10.0+cu128.
const float16_t bn_op_nhwc_f16_scale[7] = {(float16_t)1.13183594f,
                                           (float16_t)1.06152344f,
                                           (float16_t)1.02246094f,
                                           (float16_t)1.0f,
                                           (float16_t)0.987304688f,
                                           (float16_t)0.981445312f,
                                           (float16_t)0.979980469f};
