// Generated by batch_norm_settings_flt.py using PyTorch version 2.10.0+cu128.
#include "bias_data.h"
#include "config_data.h"
#include "input_data.h"
#include "output_ref_data.h"
#include "scale_data.h"
