// Generated by lstm_settings_flt.py using PyTorch version 2.10.0+cu128.
const float16_t lstm_match_2_f16_cell_hidden_weights[49] = {
    (float16_t)0.100891113f,    (float16_t)0.305419922f,    (float16_t)-0.281005859f,  (float16_t)-0.192382812f,
    (float16_t)0.262939453f,    (float16_t)-0.177368164f,   (float16_t)0.256347656f,   (float16_t)-0.258300781f,
    (float16_t)0.00282287598f,  (float16_t)-0.00845336914f, (float16_t)-0.222045898f,  (float16_t)-0.305419922f,
    (float16_t)-0.13269043f,    (float16_t)-0.30078125f,    (float16_t)-0.138671875f,  (float16_t)-0.129394531f,
    (float16_t)0.0817871094f,   (float16_t)0.107055664f,    (float16_t)0.197998047f,   (float16_t)0.0692138672f,
    (float16_t)0.0534362793f,   (float16_t)0.2421875f,      (float16_t)0.00617599487f, (float16_t)-0.338623047f,
    (float16_t)0.166748047f,    (float16_t)-0.0500183105f,  (float16_t)0.0518493652f,  (float16_t)0.196655273f,
    (float16_t)-0.0952758789f,  (float16_t)0.0541687012f,   (float16_t)0.0113983154f,  (float16_t)-0.101074219f,
    (float16_t)-0.244506836f,   (float16_t)-0.094909668f,   (float16_t)0.268554688f,   (float16_t)0.229736328f,
    (float16_t)-0.00652694702f, (float16_t)0.123474121f,    (float16_t)0.30859375f,    (float16_t)-0.0423583984f,
    (float16_t)0.0980224609f,   (float16_t)-0.254394531f,   (float16_t)0.167480469f,   (float16_t)0.138671875f,
    (float16_t)-0.191772461f,   (float16_t)0.150024414f,    (float16_t)-0.109313965f,  (float16_t)-0.249389648f,
    (float16_t)0.306152344f};
