// Generated by lstm_settings_flt.py using PyTorch version 2.10.0+cu128.
const float16_t lstm_match_2_f16_cell_bias[7] = {(float16_t)-0.174072266f,
                                                 (float16_t)-0.0944824219f,
                                                 (float16_t)-0.063293457f,
                                                 (float16_t)0.0126190186f,
                                                 (float16_t)-0.0639648438f,
                                                 (float16_t)0.135742188f,
                                                 (float16_t)-0.186767578f};
