// Generated by lstm_settings_flt.py using PyTorch version 2.10.0+cu128.
const float16_t lstm_match_2_f16_cell_input_weights[42] = {
    (float16_t)-0.250732422f,  (float16_t)-0.159301758f,    (float16_t)0.337402344f,   (float16_t)-0.279541016f,
    (float16_t)0.309814453f,   (float16_t)-0.000255584717f, (float16_t)-0.175537109f,  (float16_t)0.249145508f,
    (float16_t)-0.0268859863f, (float16_t)-0.265380859f,    (float16_t)-0.24230957f,   (float16_t)0.2578125f,
    (float16_t)-0.0124435425f, (float16_t)-0.176513672f,    (float16_t)0.176025391f,   (float16_t)-0.0114364624f,
    (float16_t)0.286132812f,   (float16_t)-0.0189208984f,   (float16_t)0.270263672f,   (float16_t)0.289550781f,
    (float16_t)-0.271728516f,  (float16_t)0.219360352f,     (float16_t)-0.242797852f,  (float16_t)0.174072266f,
    (float16_t)0.109191895f,   (float16_t)-0.291992188f,    (float16_t)0.253417969f,   (float16_t)-0.0689697266f,
    (float16_t)-0.247924805f,  (float16_t)-0.326416016f,    (float16_t)0.108581543f,   (float16_t)0.285644531f,
    (float16_t)-0.0656738281f, (float16_t)-0.16015625f,     (float16_t)-0.155639648f,  (float16_t)0.0718383789f,
    (float16_t)0.106079102f,   (float16_t)0.130981445f,     (float16_t)-0.0779418945f, (float16_t)0.044921875f,
    (float16_t)-0.22253418f,   (float16_t)0.105712891f};
