// Generated by lstm_settings_flt.py using PyTorch version 2.10.0+cu128.
const float16_t lstm_match_2_f16_forget_bias[7] = {(float16_t)-0.0372924805f,
                                                   (float16_t)0.12512207f,
                                                   (float16_t)0.0423278809f,
                                                   (float16_t)0.178222656f,
                                                   (float16_t)-0.0850830078f,
                                                   (float16_t)0.06640625f,
                                                   (float16_t)-0.260986328f};
