// Generated by lstm_settings_flt.py using PyTorch version 2.10.0+cu128.
const float16_t lstm_match_2_f16_forget_input_weights[42] = {
    (float16_t)0.245239258f,   (float16_t)0.348632812f,    (float16_t)-0.216064453f,   (float16_t)-0.0448303223f,
    (float16_t)0.346679688f,   (float16_t)0.131103516f,    (float16_t)0.140258789f,    (float16_t)0.0531616211f,
    (float16_t)0.319580078f,   (float16_t)-0.220947266f,   (float16_t)-0.325927734f,   (float16_t)0.136230469f,
    (float16_t)-0.23059082f,   (float16_t)-0.0791015625f,  (float16_t)-0.161865234f,   (float16_t)0.135375977f,
    (float16_t)0.0316467285f,  (float16_t)-0.145385742f,   (float16_t)0.245117188f,    (float16_t)0.0848999023f,
    (float16_t)0.174072266f,   (float16_t)0.000767230988f, (float16_t)-0.00543212891f, (float16_t)0.0244140625f,
    (float16_t)-0.276367188f,  (float16_t)-0.261962891f,   (float16_t)-0.159423828f,   (float16_t)0.00127315521f,
    (float16_t)0.0957641602f,  (float16_t)-0.148193359f,   (float16_t)0.128051758f,    (float16_t)-0.240234375f,
    (float16_t)0.00688934326f, (float16_t)0.290527344f,    (float16_t)-0.19543457f,    (float16_t)0.173461914f,
    (float16_t)0.248046875f,   (float16_t)0.2109375f,      (float16_t)-0.0618591309f,  (float16_t)0.280517578f,
    (float16_t)0.0614929199f,  (float16_t)-0.0643310547f};
