// Generated by lstm_settings_flt.py using PyTorch version 2.10.0+cu128.
const float16_t lstm_match_2_f16_forget_hidden_weights[49] = {
    (float16_t)0.208129883f,   (float16_t)0.147949219f,   (float16_t)-0.0701904297f, (float16_t)-0.0249633789f,
    (float16_t)-0.243164062f,  (float16_t)-0.0626831055f, (float16_t)0.220336914f,   (float16_t)0.0952758789f,
    (float16_t)-0.0321960449f, (float16_t)-0.0843505859f, (float16_t)-0.204589844f,  (float16_t)0.177246094f,
    (float16_t)0.346679688f,   (float16_t)-0.110351562f,  (float16_t)-0.202636719f,  (float16_t)0.153320312f,
    (float16_t)0.252929688f,   (float16_t)0.333740234f,   (float16_t)-0.035736084f,  (float16_t)0.228271484f,
    (float16_t)-0.114501953f,  (float16_t)-0.0118713379f, (float16_t)0.205322266f,   (float16_t)-0.316162109f,
    (float16_t)-0.260009766f,  (float16_t)0.121887207f,   (float16_t)-0.120605469f,  (float16_t)-0.0426940918f,
    (float16_t)0.22644043f,    (float16_t)0.150024414f,   (float16_t)0.139892578f,   (float16_t)0.143554688f,
    (float16_t)-0.276855469f,  (float16_t)0.0947265625f,  (float16_t)-0.2578125f,    (float16_t)-0.322998047f,
    (float16_t)0.0505065918f,  (float16_t)0.303466797f,   (float16_t)0.0883178711f,  (float16_t)-0.329833984f,
    (float16_t)-0.0255737305f, (float16_t)0.310546875f,   (float16_t)0.0415649414f,  (float16_t)0.104492188f,
    (float16_t)-0.152099609f,  (float16_t)0.233764648f,   (float16_t)0.291259766f,   (float16_t)-0.0859985352f,
    (float16_t)0.223510742f};
