// Generated by lstm_settings_flt.py using PyTorch version 2.10.0+cu128.
const float16_t lstm_match_2_f16_input_hidden_weights[49] = {
    (float16_t)0.0449829102f,  (float16_t)0.214111328f,    (float16_t)0.095703125f,  (float16_t)0.0418395996f,
    (float16_t)0.141967773f,   (float16_t)-0.0362243652f,  (float16_t)0.262207031f,  (float16_t)0.21081543f,
    (float16_t)0.105834961f,   (float16_t)0.0177459717f,   (float16_t)-0.220703125f, (float16_t)0.127929688f,
    (float16_t)-0.0234222412f, (float16_t)-0.258789062f,   (float16_t)0.314941406f,  (float16_t)-0.0735473633f,
    (float16_t)-0.146972656f,  (float16_t)0.0916748047f,   (float16_t)0.325683594f,  (float16_t)0.0866088867f,
    (float16_t)0.340332031f,   (float16_t)-0.0894165039f,  (float16_t)-0.269775391f, (float16_t)-0.0618286133f,
    (float16_t)0.00428771973f, (float16_t)0.235229492f,    (float16_t)-0.281982422f, (float16_t)0.228027344f,
    (float16_t)0.276123047f,   (float16_t)0.246948242f,    (float16_t)0.197021484f,  (float16_t)0.324462891f,
    (float16_t)0.141723633f,   (float16_t)-0.00226020813f, (float16_t)0.138671875f,  (float16_t)-0.189819336f,
    (float16_t)-0.135253906f,  (float16_t)0.0954589844f,   (float16_t)0.307861328f,  (float16_t)-0.00335121155f,
    (float16_t)0.224365234f,   (float16_t)0.203369141f,    (float16_t)0.317138672f,  (float16_t)0.0264434814f,
    (float16_t)-0.0715332031f, (float16_t)0.322021484f,    (float16_t)0.0247039795f, (float16_t)-0.196655273f,
    (float16_t)0.286621094f};
