// Generated by lstm_settings_flt.py using PyTorch version 2.10.0+cu128.
const float16_t lstm_match_2_f16_input[54] = {
    (float16_t)-0.626953125f, (float16_t)0.267089844f,  (float16_t)0.22644043f,   (float16_t)0.12878418f,
    (float16_t)-0.500488281f, (float16_t)0.924804688f,  (float16_t)0.766113281f,  (float16_t)0.743652344f,
    (float16_t)0.887207031f,  (float16_t)0.946777344f,  (float16_t)-0.772460938f, (float16_t)-0.0578613281f,
    (float16_t)-0.314208984f, (float16_t)-0.798339844f, (float16_t)0.586425781f,  (float16_t)0.614257812f,
    (float16_t)0.475341797f,  (float16_t)0.577148438f,  (float16_t)0.332275391f,  (float16_t)0.595214844f,
    (float16_t)-0.254150391f, (float16_t)0.658203125f,  (float16_t)0.621582031f,  (float16_t)-0.672851562f,
    (float16_t)0.292724609f,  (float16_t)-0.884765625f, (float16_t)0.302734375f,  (float16_t)-0.030960083f,
    (float16_t)-0.146240234f, (float16_t)0.246459961f,  (float16_t)0.69921875f,   (float16_t)0.0455322266f,
    (float16_t)-0.480957031f, (float16_t)0.973144531f,  (float16_t)-0.629394531f, (float16_t)-0.837402344f,
    (float16_t)0.486572266f,  (float16_t)0.624511719f,  (float16_t)-0.895996094f, (float16_t)-0.28515625f,
    (float16_t)0.0674438477f, (float16_t)-0.8359375f,   (float16_t)0.584472656f,  (float16_t)-0.681152344f,
    (float16_t)0.516113281f,  (float16_t)0.528320312f,  (float16_t)0.194458008f,  (float16_t)-0.705078125f,
    (float16_t)0.587402344f,  (float16_t)0.741210938f,  (float16_t)-0.142822266f, (float16_t)0.734863281f,
    (float16_t)-0.755859375f, (float16_t)-0.388671875f};
