// Generated by lstm_settings_flt.py using PyTorch version 2.10.0+cu128.
const float16_t lstm_match_2_f16_input_input_weights[42] = {
    (float16_t)-0.224243164f, (float16_t)0.0532226562f,  (float16_t)0.295654297f,    (float16_t)0.294189453f,
    (float16_t)-0.24597168f,  (float16_t)0.336181641f,   (float16_t)-0.193237305f,   (float16_t)0.0163269043f,
    (float16_t)-0.237182617f, (float16_t)0.194946289f,   (float16_t)-0.00817871094f, (float16_t)0.267822266f,
    (float16_t)0.0272369385f, (float16_t)-0.12322998f,   (float16_t)-0.083190918f,   (float16_t)-0.345458984f,
    (float16_t)0.0485534668f, (float16_t)-0.0685424805f, (float16_t)-0.190795898f,   (float16_t)0.0842895508f,
    (float16_t)-0.202514648f, (float16_t)-0.167114258f,  (float16_t)-0.243774414f,   (float16_t)0.177734375f,
    (float16_t)-0.273925781f, (float16_t)0.325683594f,   (float16_t)0.196533203f,    (float16_t)0.210693359f,
    (float16_t)0.220092773f,  (float16_t)-0.0480651855f, (float16_t)0.241088867f,    (float16_t)0.18359375f,
    (float16_t)0.185668945f,  (float16_t)0.145507812f,   (float16_t)-0.285644531f,   (float16_t)0.323974609f,
    (float16_t)-0.322265625f, (float16_t)-0.228759766f,  (float16_t)-0.14465332f,    (float16_t)0.227783203f,
    (float16_t)0.0760498047f, (float16_t)-0.161987305f};
