// Generated by lstm_settings_flt.py using PyTorch version 2.10.0+cu128.
const float16_t lstm_match_2_f16_input_bias[7] = {(float16_t)0.0979614258f,
                                                  (float16_t)-0.264648438f,
                                                  (float16_t)-0.049407959f,
                                                  (float16_t)0.0936889648f,
                                                  (float16_t)0.350585938f,
                                                  (float16_t)0.0824584961f,
                                                  (float16_t)-0.0574035645f};
