// Generated by lstm_settings_flt.py using PyTorch version 2.10.0+cu128.
const float16_t lstm_match_2_f16_output_bias[7] = {(float16_t)0.118225098f,
                                                   (float16_t)0.0978393555f,
                                                   (float16_t)-0.313232422f,
                                                   (float16_t)-0.0643310547f,
                                                   (float16_t)-0.387207031f,
                                                   (float16_t)-0.166625977f,
                                                   (float16_t)-0.0728759766f};
