// Generated by lstm_settings_flt.py using PyTorch version 2.10.0+cu128.
const float16_t lstm_match_2_f16_output_ref[63] = {
    (float16_t)-0.0714111328f, (float16_t)0.115356445f,   (float16_t)-0.0303497314f,  (float16_t)0.0558166504f,
    (float16_t)-0.0610046387f, (float16_t)0.0756225586f,  (float16_t)-0.00440216064f, (float16_t)-0.201049805f,
    (float16_t)0.0395202637f,  (float16_t)-0.0634155273f, (float16_t)0.178344727f,    (float16_t)0.0209960938f,
    (float16_t)0.165283203f,   (float16_t)0.0259094238f,  (float16_t)-0.0527648926f,  (float16_t)-0.0641479492f,
    (float16_t)0.0320739746f,  (float16_t)0.00717926025f, (float16_t)-0.00469970703f, (float16_t)0.0198669434f,
    (float16_t)-0.0897216797f, (float16_t)-0.116394043f,  (float16_t)-0.10949707f,    (float16_t)0.0165252686f,
    (float16_t)0.0425415039f,  (float16_t)-0.0871582031f, (float16_t)0.0472717285f,   (float16_t)-0.114257812f,
    (float16_t)-0.108947754f,  (float16_t)-0.110778809f,  (float16_t)0.0326538086f,   (float16_t)-0.0276794434f,
    (float16_t)0.00807952881f, (float16_t)0.0110321045f,  (float16_t)-0.115966797f,   (float16_t)-0.245849609f,
    (float16_t)-0.159423828f,  (float16_t)-0.0492858887f, (float16_t)0.105712891f,    (float16_t)0.0645751953f,
    (float16_t)0.0487976074f,  (float16_t)-0.0753173828f, (float16_t)-0.205566406f,   (float16_t)-0.0930175781f,
    (float16_t)-0.0836791992f, (float16_t)0.126953125f,   (float16_t)-0.0249633789f,  (float16_t)0.101928711f,
    (float16_t)-0.0779418945f, (float16_t)-0.147216797f,  (float16_t)-0.125366211f,   (float16_t)0.0139770508f,
    (float16_t)0.028717041f,   (float16_t)0.0767211914f,  (float16_t)0.0140838623f,   (float16_t)-0.141479492f,
    (float16_t)-0.264648438f,  (float16_t)-0.110839844f,  (float16_t)-0.0655517578f,  (float16_t)0.190795898f,
    (float16_t)0.0292358398f,  (float16_t)0.135009766f,   (float16_t)-0.0641479492f};
