// Generated by lstm_settings_flt.py using PyTorch version 2.10.0+cu128.
const float16_t lstm_match_2_f16_output_input_weights[42] = {
    (float16_t)-0.185424805f,   (float16_t)-0.282714844f,  (float16_t)-0.282470703f,  (float16_t)0.226806641f,
    (float16_t)-0.158569336f,   (float16_t)0.236816406f,   (float16_t)-0.0174560547f, (float16_t)-0.0335998535f,
    (float16_t)-0.341552734f,   (float16_t)0.0586547852f,  (float16_t)-0.312011719f,  (float16_t)0.183227539f,
    (float16_t)0.344726562f,    (float16_t)-0.131958008f,  (float16_t)-0.224243164f,  (float16_t)0.273193359f,
    (float16_t)0.220703125f,    (float16_t)-0.0961303711f, (float16_t)0.0162353516f,  (float16_t)0.157470703f,
    (float16_t)-0.00168991089f, (float16_t)0.16394043f,    (float16_t)-0.255126953f,  (float16_t)0.0664672852f,
    (float16_t)0.310302734f,    (float16_t)0.255615234f,   (float16_t)-0.313964844f,  (float16_t)-0.214233398f,
    (float16_t)-0.159179688f,   (float16_t)-0.336669922f,  (float16_t)-0.331542969f,  (float16_t)0.339599609f,
    (float16_t)-0.0583190918f,  (float16_t)0.312744141f,   (float16_t)0.0219573975f,  (float16_t)-0.170654297f,
    (float16_t)0.220214844f,    (float16_t)0.0136642456f,  (float16_t)0.189697266f,   (float16_t)-0.127319336f,
    (float16_t)-0.0314331055f,  (float16_t)-0.060546875f};
