// Generated by lstm_settings_flt.py using PyTorch version 2.10.0+cu128.
const float16_t lstm_match_2_f16_output_hidden_weights[49] = {
    (float16_t)-0.250488281f,   (float16_t)-0.0325927734f, (float16_t)0.125732422f,    (float16_t)-0.0267486572f,
    (float16_t)-0.32421875f,    (float16_t)0.19921875f,    (float16_t)-0.231079102f,   (float16_t)0.254882812f,
    (float16_t)-0.0101928711f,  (float16_t)0.104370117f,   (float16_t)0.116821289f,    (float16_t)-0.193237305f,
    (float16_t)0.00773239136f,  (float16_t)0.0861206055f,  (float16_t)-0.138427734f,   (float16_t)-0.333251953f,
    (float16_t)-0.142089844f,   (float16_t)0.0442199707f,  (float16_t)-0.339599609f,   (float16_t)0.295410156f,
    (float16_t)-0.173461914f,   (float16_t)-0.282714844f,  (float16_t)0.00760650635f,  (float16_t)-0.0523681641f,
    (float16_t)-0.0017118454f,  (float16_t)-0.101318359f,  (float16_t)-0.129638672f,   (float16_t)-0.197753906f,
    (float16_t)0.029296875f,    (float16_t)0.319091797f,   (float16_t)0.185913086f,    (float16_t)-0.188476562f,
    (float16_t)-0.00373649597f, (float16_t)-0.075012207f,  (float16_t)0.0883789062f,   (float16_t)0.346923828f,
    (float16_t)0.120361328f,    (float16_t)-0.319824219f,  (float16_t)-0.00319480896f, (float16_t)-0.293457031f,
    (float16_t)-0.288330078f,   (float16_t)-0.0888671875f, (float16_t)-0.288818359f,   (float16_t)0.171020508f,
    (float16_t)-0.31640625f,    (float16_t)-0.287841797f,  (float16_t)0.0220336914f,   (float16_t)-0.00840759277f,
    (float16_t)0.00494003296f};
