// Generated by pooling_settings_flt.py using PyTorch version 2.10.0+cu128.
const float16_t avgpooling_match_2_f16_input_tensor[60] = {
    (float16_t)1.83203125f,   (float16_t)0.349365234f,  (float16_t)-0.268310547f, (float16_t)-1.0625f,
    (float16_t)3.2109375f,    (float16_t)-0.943847656f, (float16_t)0.107910156f,  (float16_t)-4.3359375f,
    (float16_t)-2.63671875f,  (float16_t)-1.66601562f,  (float16_t)3.703125f,     (float16_t)3.11328125f,
    (float16_t)0.153442383f,  (float16_t)-4.703125f,    (float16_t)-5.828125f,    (float16_t)3.67382812f,
    (float16_t)4.40234375f,   (float16_t)0.0573120117f, (float16_t)-1.76367188f,  (float16_t)-2.35742188f,
    (float16_t)-2.09570312f,  (float16_t)1.08007812f,   (float16_t)0.0273742676f, (float16_t)-4.640625f,
    (float16_t)2.80273438f,   (float16_t)3.1796875f,    (float16_t)3.30273438f,   (float16_t)1.32519531f,
    (float16_t)-3.94921875f,  (float16_t)3.29101562f,   (float16_t)0.418701172f,  (float16_t)-4.8046875f,
    (float16_t)-2.140625f,    (float16_t)-0.382080078f, (float16_t)-1.09863281f,  (float16_t)-4.546875f,
    (float16_t)2.32617188f,   (float16_t)5.0234375f,    (float16_t)0.0540771484f, (float16_t)3.84765625f,
    (float16_t)-1.93847656f,  (float16_t)-0.755371094f, (float16_t)4.203125f,     (float16_t)-1.18066406f,
    (float16_t)4.97265625f,   (float16_t)4.59375f,      (float16_t)0.353027344f,  (float16_t)-4.71484375f,
    (float16_t)-0.506347656f, (float16_t)-4.4375f,      (float16_t)-5.60546875f,  (float16_t)5.67578125f,
    (float16_t)5.296875f,     (float16_t)2.09765625f,   (float16_t)-1.78027344f,  (float16_t)-2.0625f,
    (float16_t)-5.765625f,    (float16_t)-1.60351562f,  (float16_t)-2.72851562f,  (float16_t)-0.369140625f};
