// Generated by pooling_settings_flt.py using PyTorch version 2.10.0+cu128.
const float16_t avgpooling_match_2_f16_output_ref[60] = {
    (float16_t)0.444335938f,   (float16_t)0.228637695f,  (float16_t)-2.30273438f,  (float16_t)-1.84960938f,
    (float16_t)0.772460938f,   (float16_t)1.53027344f,   (float16_t)1.19042969f,   (float16_t)-1.48339844f,
    (float16_t)-2.80078125f,   (float16_t)-1.42675781f,  (float16_t)2.14453125f,   (float16_t)2.54101562f,
    (float16_t)-1.375f,        (float16_t)-3.03515625f,  (float16_t)-3.28320312f,  (float16_t)1.75976562f,
    (float16_t)2.86523438f,    (float16_t)0.0794067383f, (float16_t)-3.703125f,    (float16_t)-1.79394531f,
    (float16_t)1.5859375f,     (float16_t)2.92773438f,   (float16_t)0.469970703f,  (float16_t)-3.45117188f,
    (float16_t)1.24511719f,    (float16_t)0.500488281f,  (float16_t)-0.141357422f, (float16_t)-0.262695312f,
    (float16_t)-2.9921875f,    (float16_t)1.66503906f,   (float16_t)-0.316162109f, (float16_t)0.273925781f,
    (float16_t)1.40332031f,    (float16_t)-1.42578125f,  (float16_t)2.01367188f,   (float16_t)-2.02148438f,
    (float16_t)-1.078125f,     (float16_t)2.36132812f,   (float16_t)-0.502929688f, (float16_t)2.57421875f,
    (float16_t)-0.630371094f,  (float16_t)0.641113281f,  (float16_t)1.50390625f,   (float16_t)-0.543945312f,
    (float16_t)1.4609375f,     (float16_t)-0.983398438f, (float16_t)1.7578125f,    (float16_t)1.59472656f,
    (float16_t)0.13684082f,    (float16_t)-0.415283203f, (float16_t)-1.02539062f,  (float16_t)0.0876464844f,
    (float16_t)-0.340087891f,  (float16_t)-0.379150391f, (float16_t)-2.1953125f,   (float16_t)-3.8359375f,
    (float16_t)-0.0450744629f, (float16_t)1.84667969f,   (float16_t)-0.315429688f, (float16_t)-1.07421875f};
