// Generated by conv_settings_flt.py using PyTorch version 2.10.0+cu128.
const float16_t conv_match_conv_5_f16_output_ref_data[32] = {
    (float16_t)6.59765625f,  (float16_t)2.375f,       (float16_t)-0.378417969f, (float16_t)7.1640625f,
    (float16_t)0.460693359f, (float16_t)6.515625f,    (float16_t)-4.52734375f,  (float16_t)0.622070312f,
    (float16_t)-8.4375f,     (float16_t)-3.83203125f, (float16_t)-10.1484375f,  (float16_t)-0.588378906f,
    (float16_t)-3.96289062f, (float16_t)-7.73828125f, (float16_t)7.58203125f,   (float16_t)-2.2578125f,
    (float16_t)3.50585938f,  (float16_t)-1.05078125f, (float16_t)-3.96289062f,  (float16_t)2.29101562f,
    (float16_t)2.66015625f,  (float16_t)2.16015625f,  (float16_t)3.41210938f,   (float16_t)-10.46875f,
    (float16_t)-5.98828125f, (float16_t)2.43164062f,  (float16_t)3.796875f,     (float16_t)3.08984375f,
    (float16_t)-0.70703125f, (float16_t)8.0f,         (float16_t)0.890625f,     (float16_t)-7.05078125f};
