// Generated by test_settings.py using tensorflow version 2.14.0 (Keras version 2.14.0).
// Interpreter from tflite_runtime version 2.16.0 and revision 0.6.0-154906-gb2493fdf794.
#pragma once
#include <stdint.h>

const int32_t transpose_conv_3_output_mult[5] = {2011473654, 2012718049, 1968745198, 1898573321, 1883479978};
