// Generated by generate_test_data.py using tensorflow version 2.10.0 (Keras version 2.10.0).
// Interpreter from tensorflow version 2.10.0 and revision v2.10.0-rc3-6-g359c3cdfc5f.
#pragma once
#include <stdint.h>

const int8_t conv_5_output_ref[32] = {-88, -6,  -88, -88, -88, 127, -88, -88, 127, -88, -88, 127, -88, 127, -88, -88,
                                      127, 127, -88, 127, 127, -88, -88, -88, 4,   127, 127, -88, -88, -88, -88, 127};
