// Generated by conv_settings_flt.py using PyTorch version 2.10.0+cu128.
const float32_t conv_kernel_2x2_f32_biases_data[5] = {-0.0123699661f,
                                                      -0.122685298f,
                                                      -0.391565561f,
                                                      0.495593011f,
                                                      -0.170338348f};
