// Generated by generate_test_data.py using tensorflow version 2.10.0 (Keras version 2.10.0).
// Interpreter from tensorflow version 2.10.0 and revision v2.10.0-rc3-6-g359c3cdfc5f.
#pragma once
#include <stdint.h>

const int8_t conv_2_input[36] = {49, -29, 25, -87, 101, 108, 68, -24, -98, 11,  92,  120, -26, -114, 23, 40, -35, -18,
                                 13, -13, 70, 27,  95,  -74, 80, 106, 117, -63, -95, -71, -20, 47,   32, 62, 10,  -96};
