// Generated by conv_settings_flt.py using PyTorch version 2.10.0+cu128.
const float16_t conv_match_out_activation_f16_input_data[36] = {
    (float16_t)-2.34375f,     (float16_t)-7.3203125f,  (float16_t)-6.515625f,    (float16_t)5.78515625f,
    (float16_t)-5.15234375f,  (float16_t)-3.13867188f, (float16_t)-4.8359375f,   (float16_t)-3.5859375f,
    (float16_t)-0.104492188f, (float16_t)-1.35546875f, (float16_t)-1.88671875f,  (float16_t)-0.715332031f,
    (float16_t)5.72265625f,   (float16_t)6.04296875f,  (float16_t)0.422851562f,  (float16_t)6.86328125f,
    (float16_t)-0.351806641f, (float16_t)0.859375f,    (float16_t)-7.1875f,      (float16_t)0.170043945f,
    (float16_t)7.375f,        (float16_t)3.81054688f,  (float16_t)-1.62011719f,  (float16_t)6.38671875f,
    (float16_t)-3.16210938f,  (float16_t)4.0625f,      (float16_t)0.0533447266f, (float16_t)-1.62695312f,
    (float16_t)-5.0f,         (float16_t)5.5078125f,   (float16_t)2.28710938f,   (float16_t)-2.53320312f,
    (float16_t)-3.25195312f,  (float16_t)-3.24804688f, (float16_t)-6.89453125f,  (float16_t)-7.91015625f};
