// Generated by batch_matmul_settings_flt.py using PyTorch version 2.10.0+cu128.
const float16_t batch_matmul_2_f16_rhs_transposed_tensor[35] = {
    (float16_t)0.943847656f,  (float16_t)0.418212891f, (float16_t)-1.51367188f,  (float16_t)1.78515625f,
    (float16_t)-1.21289062f,  (float16_t)1.55957031f,  (float16_t)0.297607422f,  (float16_t)0.44921875f,
    (float16_t)-1.03027344f,  (float16_t)0.384521484f, (float16_t)0.0836791992f, (float16_t)-1.6796875f,
    (float16_t)0.371582031f,  (float16_t)-1.5625f,     (float16_t)-1.05371094f,  (float16_t)1.98144531f,
    (float16_t)0.335693359f,  (float16_t)-1.61035156f, (float16_t)0.383056641f,  (float16_t)1.96191406f,
    (float16_t)0.870605469f,  (float16_t)-1.74511719f, (float16_t)-1.29785156f,  (float16_t)1.49609375f,
    (float16_t)0.200683594f,  (float16_t)1.23828125f,  (float16_t)-1.23535156f,  (float16_t)-0.844238281f,
    (float16_t)0.778320312f,  (float16_t)0.852050781f, (float16_t)-0.876953125f, (float16_t)-0.387695312f,
    (float16_t)-0.834472656f, (float16_t)1.16699219f,  (float16_t)-1.75878906f};
