// Generated by generate_test_data.py using tensorflow version 2.10.0 (Keras version 2.10.0).
// Interpreter from tensorflow version 2.10.0 and revision v2.10.0-rc3-6-g359c3cdfc5f.
#pragma once
#include <stdint.h>

const int64_t dw_int16xint8_biases[8] = {3864101, -2174812, -4273364, -1538703, 2379869, 1637715, 842417, 3285024};
