// Generated by generate_test_data.py using tensorflow version 2.10.0 (Keras version 2.10.0).
// Interpreter from tensorflow version 2.10.0 and revision v2.10.0-rc3-6-g359c3cdfc5f.
#pragma once
#include <stdint.h>

const int32_t dw_int16xint8_output_mult[8] =
    {1814563076, 1795978464, 1686052907, 1782534381, 1817839397, 1745817143, 1660576855, 1657639441};
