// Generated by lstm_settings_flt.py using PyTorch version 2.10.0+cu128.
const float16_t lstm_match_1_f16_cell_bias[11] = {(float16_t)-0.139648438f,
                                                  (float16_t)-0.419189453f,
                                                  (float16_t)-0.267333984f,
                                                  (float16_t)0.0981445312f,
                                                  (float16_t)-0.105773926f,
                                                  (float16_t)0.395263672f,
                                                  (float16_t)-0.0853271484f,
                                                  (float16_t)0.240966797f,
                                                  (float16_t)0.134277344f,
                                                  (float16_t)-0.223754883f,
                                                  (float16_t)-0.321777344f};
