// Generated by lstm_settings_flt.py using PyTorch version 2.10.0+cu128.
const float16_t lstm_match_1_f16_forget_bias[11] = {(float16_t)0.091796875f,
                                                    (float16_t)-0.110839844f,
                                                    (float16_t)-0.212646484f,
                                                    (float16_t)-0.107055664f,
                                                    (float16_t)-0.391357422f,
                                                    (float16_t)0.284912109f,
                                                    (float16_t)0.272705078f,
                                                    (float16_t)-0.0389709473f,
                                                    (float16_t)0.475097656f,
                                                    (float16_t)0.0444946289f,
                                                    (float16_t)0.0791015625f};
