// Generated by lstm_settings_flt.py using PyTorch version 2.10.0+cu128.
const float16_t lstm_match_1_f16_input_bias[11] = {(float16_t)0.311523438f,
                                                   (float16_t)-0.145019531f,
                                                   (float16_t)0.183837891f,
                                                   (float16_t)-0.062286377f,
                                                   (float16_t)0.15222168f,
                                                   (float16_t)-0.402099609f,
                                                   (float16_t)0.312011719f,
                                                   (float16_t)0.302490234f,
                                                   (float16_t)-0.100402832f,
                                                   (float16_t)0.0778808594f,
                                                   (float16_t)0.0491638184f};
