// Generated by lstm_settings_flt.py using PyTorch version 2.10.0+cu128.
const float16_t lstm_match_1_f16_output_bias[11] = {(float16_t)0.0905151367f,
                                                    (float16_t)-0.193237305f,
                                                    (float16_t)-0.0345458984f,
                                                    (float16_t)0.43359375f,
                                                    (float16_t)-0.0293121338f,
                                                    (float16_t)-0.10559082f,
                                                    (float16_t)0.265869141f,
                                                    (float16_t)-0.06640625f,
                                                    (float16_t)-0.232543945f,
                                                    (float16_t)-0.0215454102f,
                                                    (float16_t)-0.132202148f};
