// Generated by generate_test_data.py using tensorflow version 2.10.0 (Keras version 2.10.0).
// Interpreter from tensorflow version 2.10.0 and revision v2.10.0-rc3-6-g359c3cdfc5f.
#pragma once
#include <stdint.h>

const int64_t dw_int16xint8_fast_stride_biases[8] =
    {3857514, 5638784, 8961266, -2293409, 4619095, 103948, -4048063, -6682};
