// Generated by generate_test_data.py using tensorflow version 2.10.0 (Keras version 2.10.0).
// Interpreter from tensorflow version 2.10.0 and revision v2.10.0-rc3-6-g359c3cdfc5f.
#pragma once
#include <stdint.h>

const int8_t dw_int16xint8_fast_stride_weights[32] = {127,  -127, 127,  -102, -70, -83,  10, 123, -98, 83, -49,
                                                      -106, 127,  -119, -4,   127, 67,   54, -10, 124, 2,  102,
                                                      -127, 56,   86,   93,   58,  -127, 99, 127, 52,  -67};
