// Generated by fully_connected_settings_flt.py using PyTorch version 2.10.0+cu128.
const float16_t fully_connected_match_mve_1_f16_biases_data[4] = {(float16_t)-0.545410156f,
                                                                  (float16_t)-0.536621094f,
                                                                  (float16_t)-0.59375f,
                                                                  (float16_t)-0.182617188f};
