// Generated by fully_connected_settings_flt.py using PyTorch version 2.10.0+cu128.
const float16_t fully_connected_match_mve_1_f16_input_data[20] = {
    (float16_t)-0.640136719f, (float16_t)1.1015625f,    (float16_t)-0.826660156f,  (float16_t)-1.12695312f,
    (float16_t)-0.966796875f, (float16_t)1.62207031f,   (float16_t)0.989746094f,   (float16_t)-1.92578125f,
    (float16_t)1.04394531f,   (float16_t)1.50488281f,   (float16_t)-0.0126266479f, (float16_t)1.41113281f,
    (float16_t)-1.57617188f,  (float16_t)-0.165405273f, (float16_t)1.58398438f,    (float16_t)0.482666016f,
    (float16_t)0.891601562f,  (float16_t)-0.895019531f, (float16_t)-0.813964844f,  (float16_t)-0.627929688f};
