// Generated by fully_connected_settings_flt.py using PyTorch version 2.10.0+cu128.
const float16_t fully_connected_match_mve_1_f16_output_ref_data[4] = {(float16_t)1.5234375f,
                                                                      (float16_t)3.13085938f,
                                                                      (float16_t)1.0f,
                                                                      (float16_t)5.28515625f};
