// Generated by generate_test_data.py using tensorflow version 2.10.0 (Keras version 2.10.0).
// Interpreter from tensorflow version 2.10.0 and revision v2.10.0-rc3-6-g359c3cdfc5f.
#pragma once
#include <stdint.h>

const int8_t conv_4_output_ref[36] = {127, -69, -31, 37,  -77,  21,  91,  79,  -3,  51,  69,   86,
                                      45,  37,  88,  127, -103, -61, 82,  -83, 15,  127, -54,  -76,
                                      -9,  18,  63,  127, -47,  99,  104, -35, -48, 117, -109, -10};
