// Generated by generate_test_data.py using tensorflow version 2.10.0 (Keras version 2.10.0).
// Interpreter from tensorflow version 2.10.0 and revision v2.10.0-rc3-6-g359c3cdfc5f.
#pragma once
#include <stdint.h>

const int8_t conv_4_weights[54] = {-127, -23, 88,   -26, 14,   39,  -79, -53,  -94, -97,  105,  17,  -119, 115,
                                   74,   81,  44,   59,  -117, 118, 70,  59,   -26, -126, -101, -30, 127,  -1,
                                   103,  58,  -85,  -92, -73,  -72, -81, -115, 16,  -13,  -76,  95,  -19,  -105,
                                   -81,  14,  -104, 59,  13,   14,  30,  -110, 11,  -68,  -82,  127};
