// Generated by generate_test_data.py using tensorflow version 2.17.0 (Keras version 3.5.0).
// Interpreter from tensorflow version 2.17.0 and revision v2.17.0-rc1-2-gad6d8cc177d.
#pragma once
#include <stdint.h>

const int8_t transpose_3dim2_output[60] = {
    -9,   25,   111, -6,  -94, 94,  127, -126, -15, -50, -102, 83,  -89, 56,  73, 37,  80,   16,   -68, -110,
    -112, -111, -3,  -33, 102, 64,  125, 4,    42,  10,  88,   -21, 80,  70,  53, -55, 31,   32,   -41, -73,
    15,   51,   33,  31,  77,  -28, -9,  -117, -63, -6,  -95,  -55, 28,  -40, 96, -13, -107, -105, 88,  -20};
