// Generated by generate_test_data.py using tensorflow version 2.10.0 (Keras version 2.10.0).
// Interpreter from tensorflow version 2.10.0 and revision v2.10.0-rc3-6-g359c3cdfc5f.
#pragma once
#include <stdint.h>

const int8_t stride2pad1_input[49] = {27,   70,  -117, 45,   99,   100,  107, -24, 5,   75,  106,  -19, -70,
                                      -123, 30,  55,   24,   -49,  71,   36,  -35, -46, -96, -102, -15, -127,
                                      121,  37,  -37,  -10,  -115, 82,   53,  -60, -74, 38,  -109, 4,   53,
                                      -95,  120, 5,    -122, -71,  -117, 6,   39,  61,  88};
