// Generated by generate_test_data.py using tensorflow version 2.10.0 (Keras version 2.10.0).
// Interpreter from tensorflow version 2.10.0 and revision v2.10.0-rc3-6-g359c3cdfc5f.
#pragma once
#include <stdint.h>

const int8_t stride2pad1_output_ref[16] = {-42, 3, -11, -112, -42, -38, -8, -29, -26, -19, -72, 31, -73, -68, -47, -41};
