// Generated by ds_cnn_s_body_settings_flt.py using PyTorch version 2.10.0+cu128.
const float32_t ds_cnn_s_body_f32_fc_biases_data[12] = {-0.0290437583f,
                                                        -0.00316095375f,
                                                        0.022950083f,
                                                        0.00551534025f,
                                                        0.0250060037f,
                                                        -0.0442860201f,
                                                        0.0367247313f,
                                                        0.0375697464f,
                                                        0.0320638902f,
                                                        0.0360117666f,
                                                        0.0263689999f,
                                                        0.00165376649f};
