// Generated by ds_cnn_s_body_settings_flt.py using PyTorch version 2.10.0+cu128.
const float32_t ds_cnn_s_body_f32_output_ref_data[12] = {0.0775370002f,
                                                         0.0812419951f,
                                                         0.0840318874f,
                                                         0.0835080817f,
                                                         0.0865597203f,
                                                         0.079363212f,
                                                         0.0885824189f,
                                                         0.0869727209f,
                                                         0.0872648433f,
                                                         0.0823692083f,
                                                         0.0815939382f,
                                                         0.0809749439f};
