// Generated by generate_test_data.py using tensorflow version 2.10.0 (Keras version 2.10.0).
// Interpreter from tensorflow version 2.10.0 and revision v2.10.0-rc3-6-g359c3cdfc5f.
#pragma once
#include <stdint.h>

const int8_t conv_3x2_dilation_input[18] =
    {9, -66, 120, -126, 118, -52, 9, -8, 120, 38, 31, -107, -36, -81, -128, -14, 105, -30};
