// Generated by generate_test_data.py using tensorflow version 2.10.0 (Keras version 2.10.0).
// Interpreter from tensorflow version 2.10.0 and revision v2.10.0-rc3-6-g359c3cdfc5f.
#pragma once
#include <stdint.h>

const int8_t conv_3x2_dilation_output_ref[18] =
    {107, 72, 107, 17, 107, 107, 107, -17, 107, -22, 107, 40, 74, 44, -61, -10, -2, 57};
