// Generated by conv_settings_flt.py using PyTorch version 2.10.0+cu128.
const float16_t conv_match_1xn_1_f16_biases_data[3] = {(float16_t)-0.00494003296f,
                                                       (float16_t)0.149414062f,
                                                       (float16_t)-0.0446472168f};
