// Generated by conv_settings_flt.py using PyTorch version 2.10.0+cu128.
const float16_t conv_match_1xn_1_f16_output_ref_data[12] = {(float16_t)0.584472656f,
                                                            (float16_t)-1.04199219f,
                                                            (float16_t)0.259033203f,
                                                            (float16_t)-1.3515625f,
                                                            (float16_t)-0.613769531f,
                                                            (float16_t)0.114562988f,
                                                            (float16_t)0.402832031f,
                                                            (float16_t)0.319824219f,
                                                            (float16_t)0.587890625f,
                                                            (float16_t)1.48828125f,
                                                            (float16_t)0.475830078f,
                                                            (float16_t)0.235717773f};
