// Generated by conv_settings_flt.py using PyTorch version 2.10.0+cu128.
const float16_t conv_match_1xn_1_f16_weights_data[36] = {
    (float16_t)0.635742188f,   (float16_t)0.483398438f,  (float16_t)0.278564453f,   (float16_t)-0.432617188f,
    (float16_t)-0.708007812f,  (float16_t)0.544921875f,  (float16_t)-0.1796875f,    (float16_t)-0.0590820312f,
    (float16_t)0.749023438f,   (float16_t)-0.113586426f, (float16_t)-0.724609375f,  (float16_t)0.317138672f,
    (float16_t)0.133056641f,   (float16_t)0.126953125f,  (float16_t)0.0525512695f,  (float16_t)0.581054688f,
    (float16_t)0.719238281f,   (float16_t)0.702636719f,  (float16_t)0.00292015076f, (float16_t)-0.0622558594f,
    (float16_t)-0.0631103516f, (float16_t)-0.435302734f, (float16_t)0.744628906f,   (float16_t)-0.650390625f,
    (float16_t)-0.362060547f,  (float16_t)0.204833984f,  (float16_t)-0.193725586f,  (float16_t)-0.71484375f,
    (float16_t)0.0934448242f,  (float16_t)-0.218505859f, (float16_t)-0.119384766f,  (float16_t)0.0661621094f,
    (float16_t)0.234619141f,   (float16_t)0.241943359f,  (float16_t)-0.58984375f,   (float16_t)0.353027344f};
