// Generated by svdf_settings_flt.py using PyTorch version 2.10.0+cu128.
const float16_t svdf_match_1_f16_bias[12] = {(float16_t)-0.0167388916f,
                                             (float16_t)-0.224609375f,
                                             (float16_t)0.173095703f,
                                             (float16_t)0.0245666504f,
                                             (float16_t)-0.197875977f,
                                             (float16_t)-0.187744141f,
                                             (float16_t)0.175048828f,
                                             (float16_t)-0.168212891f,
                                             (float16_t)-0.237548828f,
                                             (float16_t)0.0484313965f,
                                             (float16_t)-0.185546875f,
                                             (float16_t)0.188720703f};
