// Generated by svdf_settings_flt.py using PyTorch version 2.10.0+cu128.
const float16_t svdf_match_1_f16_input_sequence[60] = {
    (float16_t)-0.101013184f, (float16_t)-0.598144531f, (float16_t)-0.188354492f, (float16_t)-0.404296875f,
    (float16_t)-0.442382812f, (float16_t)1.00097656f,   (float16_t)-0.816894531f, (float16_t)0.84765625f,
    (float16_t)-0.849121094f, (float16_t)-1.2890625f,   (float16_t)0.171264648f,  (float16_t)-1.20800781f,
    (float16_t)-1.4296875f,   (float16_t)-0.712890625f, (float16_t)0.423339844f,  (float16_t)0.0405273438f,
    (float16_t)0.283203125f,  (float16_t)-1.45117188f,  (float16_t)1.42675781f,   (float16_t)1.2109375f,
    (float16_t)-0.131225586f, (float16_t)0.336669922f,  (float16_t)-0.336669922f, (float16_t)0.799316406f,
    (float16_t)-0.176879883f, (float16_t)-1.12988281f,  (float16_t)0.901855469f,  (float16_t)1.18457031f,
    (float16_t)-1.40527344f,  (float16_t)0.688476562f,  (float16_t)-0.372070312f, (float16_t)0.240112305f,
    (float16_t)-1.47753906f,  (float16_t)-0.414794922f, (float16_t)0.190917969f,  (float16_t)0.0121231079f,
    (float16_t)-1.29980469f,  (float16_t)1.00292969f,   (float16_t)-0.857421875f, (float16_t)-0.41015625f,
    (float16_t)-0.119506836f, (float16_t)1.23730469f,   (float16_t)-0.214233398f, (float16_t)-1.15527344f,
    (float16_t)-0.193603516f, (float16_t)1.05761719f,   (float16_t)0.293945312f,  (float16_t)-0.981933594f,
    (float16_t)-0.779785156f, (float16_t)0.898925781f,  (float16_t)-0.343505859f, (float16_t)0.671386719f,
    (float16_t)-0.411865234f, (float16_t)1.39746094f,   (float16_t)-0.986328125f, (float16_t)1.046875f,
    (float16_t)-1.47070312f,  (float16_t)0.435791016f,  (float16_t)0.895019531f,  (float16_t)-0.797363281f};
