// Generated by svdf_settings_flt.py using PyTorch version 2.10.0+cu128.
const float16_t svdf_match_1_f16_output_ref[12] = {(float16_t)-0.0107421875f,
                                                   (float16_t)0.140380859f,
                                                   (float16_t)-0.0532836914f,
                                                   (float16_t)-0.0414428711f,
                                                   (float16_t)-0.0414733887f,
                                                   (float16_t)-0.191162109f,
                                                   (float16_t)0.768066406f,
                                                   (float16_t)-0.392822266f,
                                                   (float16_t)-0.62890625f,
                                                   (float16_t)0.0573425293f,
                                                   (float16_t)0.0954589844f,
                                                   (float16_t)0.124633789f};
