// Generated by svdf_settings_flt.py using PyTorch version 2.10.0+cu128.
const float16_t svdf_match_1_f16_weights_time[24] = {
    (float16_t)-0.107299805f, (float16_t)0.276611328f,   (float16_t)-0.492431641f,  (float16_t)0.0102920532f,
    (float16_t)0.414794922f,  (float16_t)0.209350586f,   (float16_t)0.0830078125f,  (float16_t)0.0336914062f,
    (float16_t)0.487548828f,  (float16_t)-0.171386719f,  (float16_t)0.10949707f,    (float16_t)-0.247192383f,
    (float16_t)-0.280273438f, (float16_t)-0.3125f,       (float16_t)0.481445312f,   (float16_t)0.442626953f,
    (float16_t)0.344726562f,  (float16_t)0.111206055f,   (float16_t)-0.0256500244f, (float16_t)-0.0748291016f,
    (float16_t)0.234619141f,  (float16_t)-0.0682373047f, (float16_t)-0.0597839355f, (float16_t)-0.123840332f};
