// Generated by conv_settings_flt.py using PyTorch version 2.10.0+cu128.
const float16_t conv_match_basic_f16_input_data[40] = {
    (float16_t)-0.783691406f, (float16_t)-0.0888671875f, (float16_t)0.941894531f,  (float16_t)-0.019241333f,
    (float16_t)-0.333984375f, (float16_t)0.089050293f,   (float16_t)-0.729980469f, (float16_t)0.0271911621f,
    (float16_t)0.58203125f,   (float16_t)-0.134155273f,  (float16_t)0.145385742f,  (float16_t)-0.833007812f,
    (float16_t)0.646484375f,  (float16_t)-0.228027344f,  (float16_t)-0.700683594f, (float16_t)0.794921875f,
    (float16_t)-0.693847656f, (float16_t)-0.794433594f,  (float16_t)-0.670410156f, (float16_t)0.184204102f,
    (float16_t)0.38671875f,   (float16_t)0.210205078f,   (float16_t)0.104003906f,  (float16_t)-0.244750977f,
    (float16_t)-0.330078125f, (float16_t)0.235961914f,   (float16_t)-0.219604492f, (float16_t)-0.358154297f,
    (float16_t)0.826171875f,  (float16_t)0.319824219f,   (float16_t)0.194824219f,  (float16_t)0.440429688f,
    (float16_t)-0.328613281f, (float16_t)-0.776855469f,  (float16_t)0.0719604492f, (float16_t)0.956054688f,
    (float16_t)-0.336669922f, (float16_t)-0.387451172f,  (float16_t)-0.701660156f, (float16_t)-0.885253906f};
