// Generated by conv_settings_flt.py using PyTorch version 2.10.0+cu128.
const float16_t conv_match_basic_f16_output_ref_data[20] = {
    (float16_t)-0.00499343872f, (float16_t)-0.224975586f, (float16_t)0.308837891f,   (float16_t)0.536621094f,
    (float16_t)-0.476318359f,   (float16_t)-0.690429688f, (float16_t)0.00262069702f, (float16_t)-0.419921875f,
    (float16_t)0.41015625f,     (float16_t)-0.475585938f, (float16_t)-1.53027344f,   (float16_t)-1.11816406f,
    (float16_t)-0.494140625f,   (float16_t)0.429931641f,  (float16_t)1.04785156f,    (float16_t)0.0798339844f,
    (float16_t)-0.815429688f,   (float16_t)-0.209838867f, (float16_t)0.323730469f,   (float16_t)1.61328125f};
