// Generated by conv_settings_flt.py using PyTorch version 2.10.0+cu128.
const float16_t conv_match_basic_f16_weights_data[8] = {(float16_t)-0.441894531f,
                                                        (float16_t)-0.397705078f,
                                                        (float16_t)0.734863281f,
                                                        (float16_t)0.155883789f,
                                                        (float16_t)-0.0211334229f,
                                                        (float16_t)-0.0182495117f,
                                                        (float16_t)-0.618164062f,
                                                        (float16_t)-0.665527344f};
