// Generated by pooling_settings_flt.py using PyTorch version 2.10.0+cu128.
const float16_t maxpooling_match_2_f16_input_tensor[60] = {
    (float16_t)5.94921875f,  (float16_t)4.41015625f,  (float16_t)-2.7265625f,   (float16_t)-1.00292969f,
    (float16_t)-1.95898438f, (float16_t)-2.76171875f, (float16_t)-3.29882812f,  (float16_t)3.0234375f,
    (float16_t)-4.44140625f, (float16_t)-3.76757812f, (float16_t)-0.802734375f, (float16_t)2.09765625f,
    (float16_t)-3.453125f,   (float16_t)-2.66601562f, (float16_t)-3.40039062f,  (float16_t)4.625f,
    (float16_t)-2.90039062f, (float16_t)3.1328125f,   (float16_t)-0.965820312f, (float16_t)-5.2578125f,
    (float16_t)5.8203125f,   (float16_t)-4.1171875f,  (float16_t)2.23828125f,   (float16_t)0.94921875f,
    (float16_t)-4.74609375f, (float16_t)-3.18945312f, (float16_t)-0.023651123f, (float16_t)-4.65625f,
    (float16_t)-0.37109375f, (float16_t)-1.89453125f, (float16_t)2.8125f,       (float16_t)-2.11132812f,
    (float16_t)-3.37304688f, (float16_t)5.65234375f,  (float16_t)3.29882812f,   (float16_t)-1.16796875f,
    (float16_t)4.56640625f,  (float16_t)3.33203125f,  (float16_t)5.33984375f,   (float16_t)-2.19726562f,
    (float16_t)-2.26953125f, (float16_t)4.78125f,     (float16_t)1.68457031f,   (float16_t)-2.04882812f,
    (float16_t)-4.6015625f,  (float16_t)4.61328125f,  (float16_t)-2.296875f,    (float16_t)1.23828125f,
    (float16_t)-5.0859375f,  (float16_t)1.92773438f,  (float16_t)-5.2734375f,   (float16_t)3.91601562f,
    (float16_t)4.3125f,      (float16_t)3.23828125f,  (float16_t)-3.5078125f,   (float16_t)-4.3671875f,
    (float16_t)3.07421875f,  (float16_t)-3.20117188f, (float16_t)5.55859375f,   (float16_t)-4.1015625f};
