// Generated by fully_connected_settings_flt.py using PyTorch version 2.10.0+cu128.
const float16_t fully_connected_small_f16_input_data[64] = {
    (float16_t)-1.40625f,       (float16_t)0.12512207f,   (float16_t)0.473388672f,  (float16_t)-0.332519531f,
    (float16_t)-1.35839844f,    (float16_t)1.59082031f,   (float16_t)0.880859375f,  (float16_t)0.932617188f,
    (float16_t)-0.290771484f,   (float16_t)1.68554688f,   (float16_t)-0.790039062f, (float16_t)-1.53125f,
    (float16_t)-0.731933594f,   (float16_t)1.90722656f,   (float16_t)-1.3828125f,   (float16_t)-1.01660156f,
    (float16_t)-1.30957031f,    (float16_t)0.750976562f,  (float16_t)-1.29296875f,  (float16_t)-0.278076172f,
    (float16_t)0.0905761719f,   (float16_t)-1.55859375f,  (float16_t)-1.62890625f,  (float16_t)-1.09179688f,
    (float16_t)-0.00682449341f, (float16_t)-0.142578125f, (float16_t)1.95410156f,   (float16_t)-1.02148438f,
    (float16_t)-0.0483093262f,  (float16_t)1.32226562f,   (float16_t)-0.712890625f, (float16_t)1.05371094f,
    (float16_t)-0.982910156f,   (float16_t)0.294189453f,  (float16_t)-1.64746094f,  (float16_t)0.389648438f,
    (float16_t)1.23339844f,     (float16_t)-1.52832031f,  (float16_t)-1.36328125f,  (float16_t)1.80761719f,
    (float16_t)-1.64648438f,    (float16_t)0.798339844f,  (float16_t)1.22167969f,   (float16_t)-1.44726562f,
    (float16_t)-0.344238281f,   (float16_t)1.63574219f,   (float16_t)1.14648438f,   (float16_t)-1.06640625f,
    (float16_t)-0.859863281f,   (float16_t)0.560546875f,  (float16_t)-0.767578125f, (float16_t)1.12792969f,
    (float16_t)-1.80664062f,    (float16_t)-1.87109375f,  (float16_t)-0.87109375f,  (float16_t)1.88183594f,
    (float16_t)-0.838867188f,   (float16_t)-1.88964844f,  (float16_t)0.916015625f,  (float16_t)1.11621094f,
    (float16_t)1.24023438f,     (float16_t)1.90234375f,   (float16_t)0.0223693848f, (float16_t)1.91210938f};
