// Generated by generate_test_data.py using tensorflow version 2.10.0 (Keras version 2.10.0).
// Interpreter from tensorflow version 2.10.0 and revision v2.10.0-rc3-6-g359c3cdfc5f.
#pragma once
#define DW_CONV_9_OUT_CH 276
#define DW_CONV_9_IN_CH 276
#define DW_CONV_9_INPUT_W 5
#define DW_CONV_9_INPUT_H 13
#define DW_CONV_9_DST_SIZE 17940
#define DW_CONV_9_FILTER_X 3
#define DW_CONV_9_FILTER_Y 3
#define DW_CONV_9_FILTER_W 3
#define DW_CONV_9_FILTER_H 3
#define DW_CONV_9_STRIDE_X 1
#define DW_CONV_9_STRIDE_Y 1
#define DW_CONV_9_STRIDE_W 1
#define DW_CONV_9_STRIDE_H 1
#define DW_CONV_9_PAD_X 1
#define DW_CONV_9_PAD_Y 1
#define DW_CONV_9_PAD_W 1
#define DW_CONV_9_PAD_H 1
#define DW_CONV_9_OUTPUT_W 5
#define DW_CONV_9_OUTPUT_H 13
#define DW_CONV_9_INPUT_OFFSET 128
#define DW_CONV_9_INPUT_SIZE 17940
#define DW_CONV_9_OUT_ACTIVATION_MIN -128
#define DW_CONV_9_OUT_ACTIVATION_MAX 127
#define DW_CONV_9_INPUT_BATCHES 1
#define DW_CONV_9_OUTPUT_OFFSET -128
#define DW_CONV_9_DILATION_X 1
#define DW_CONV_9_DILATION_Y 1
#define DW_CONV_9_DILATION_W 1
#define DW_CONV_9_DILATION_H 1
#define DW_CONV_9_ACCUMULATION_DEPTH 17940
