// Generated by generate_test_data.py using tensorflow version 2.10.0 (Keras version 2.10.0).
// Interpreter from tensorflow version 2.10.0 and revision v2.10.0-rc3-6-g359c3cdfc5f.
#pragma once
#define DW_CONV_1_OUT_CH 276
#define DW_CONV_1_IN_CH 276
#define DW_CONV_1_INPUT_W 10
#define DW_CONV_1_INPUT_H 25
#define DW_CONV_1_DST_SIZE 17940
#define DW_CONV_1_FILTER_X 3
#define DW_CONV_1_FILTER_Y 3
#define DW_CONV_1_FILTER_W 3
#define DW_CONV_1_FILTER_H 3
#define DW_CONV_1_STRIDE_X 2
#define DW_CONV_1_STRIDE_Y 2
#define DW_CONV_1_STRIDE_W 2
#define DW_CONV_1_STRIDE_H 2
#define DW_CONV_1_PAD_X 0
#define DW_CONV_1_PAD_Y 1
#define DW_CONV_1_PAD_W 0
#define DW_CONV_1_PAD_H 1
#define DW_CONV_1_OUTPUT_W 5
#define DW_CONV_1_OUTPUT_H 13
#define DW_CONV_1_INPUT_OFFSET 128
#define DW_CONV_1_INPUT_SIZE 69000
#define DW_CONV_1_OUT_ACTIVATION_MIN -128
#define DW_CONV_1_OUT_ACTIVATION_MAX 127
#define DW_CONV_1_INPUT_BATCHES 1
#define DW_CONV_1_OUTPUT_OFFSET -128
#define DW_CONV_1_DILATION_X 1
#define DW_CONV_1_DILATION_Y 1
#define DW_CONV_1_DILATION_W 1
#define DW_CONV_1_DILATION_H 1
#define DW_CONV_1_ACCUMULATION_DEPTH 69000
