// Generated by generate_test_data.py using tensorflow version 2.10.0 (Keras version 2.10.0).
// Interpreter from tensorflow version 2.10.0 and revision v2.10.0-rc3-6-g359c3cdfc5f.
#pragma once
#define SOFTMAX_14_OUT_CH 276
#define SOFTMAX_14_IN_CH 12
#define SOFTMAX_14_INPUT_W 12
#define SOFTMAX_14_INPUT_H 1
#define SOFTMAX_14_DST_SIZE 3312
#define SOFTMAX_14_NUM_ROWS 1
#define SOFTMAX_14_ROW_SIZE 12
#define SOFTMAX_14_MULT 1103896789
#define SOFTMAX_14_SHIFT 25
#define SOFTMAX_14_DIFF_MIN -62
