// Generated by batch_norm_settings_flt.py using PyTorch version 2.10.0+cu128.
#define BN_BASIC_F32_INPUT_N 1
#define BN_BASIC_F32_INPUT_H 8
#define BN_BASIC_F32_INPUT_W 8
#define BN_BASIC_F32_INPUT_C 6
#define BN_BASIC_F32_SIZE 384
#define BN_BASIC_F32_LAYOUT ARM_NN_LAYOUT_NHWC
