// Generated by batch_norm_settings_flt.py using PyTorch version 2.10.0+cu128.
const float32_t bn_basic_f32_scale[6] =
    {1.13135958f, 1.05179369f, 1.01192331f, 0.991596699f, 0.982301235f, 0.979792655f};
