// Generated by depthwise_conv_settings_flt.py using PyTorch version 2.10.0+cu128.
const float16_t depthwise_match_dilation_f16_input_data[49] = {
    (float16_t)-0.828125f,     (float16_t)0.850097656f,   (float16_t)-0.0319213867f, (float16_t)-0.820800781f,
    (float16_t)-0.251708984f,  (float16_t)0.0287017822f,  (float16_t)-0.908691406f,  (float16_t)0.991699219f,
    (float16_t)0.5703125f,     (float16_t)-0.945800781f,  (float16_t)0.740234375f,   (float16_t)-0.328857422f,
    (float16_t)0.480224609f,   (float16_t)0.98046875f,    (float16_t)0.050994873f,   (float16_t)0.890625f,
    (float16_t)0.526367188f,   (float16_t)0.965820312f,   (float16_t)-0.899414062f,  (float16_t)-0.268066406f,
    (float16_t)0.335693359f,   (float16_t)-0.529296875f,  (float16_t)0.797851562f,   (float16_t)0.991210938f,
    (float16_t)-0.0313720703f, (float16_t)0.787109375f,   (float16_t)0.881835938f,   (float16_t)0.939941406f,
    (float16_t)0.459228516f,   (float16_t)0.751464844f,   (float16_t)0.520996094f,   (float16_t)-0.380371094f,
    (float16_t)0.709960938f,   (float16_t)-0.168701172f,  (float16_t)0.247314453f,   (float16_t)0.667480469f,
    (float16_t)-0.12298584f,   (float16_t)0.797363281f,   (float16_t)-0.303466797f,  (float16_t)-0.538085938f,
    (float16_t)0.320556641f,   (float16_t)-0.952148438f,  (float16_t)0.501953125f,   (float16_t)-0.385986328f,
    (float16_t)0.850097656f,   (float16_t)-0.0701904297f, (float16_t)0.922363281f,   (float16_t)-0.00805664062f,
    (float16_t)-0.330810547f};
