// Generated by depthwise_conv_settings_flt.py using PyTorch version 2.10.0+cu128.
const float16_t depthwise_match_dilation_f16_output_ref_data[49] = {
    (float16_t)-0.0762939453f, (float16_t)-0.40234375f,  (float16_t)1.26953125f,    (float16_t)0.353271484f,
    (float16_t)-0.547851562f,  (float16_t)0.599121094f,  (float16_t)0.389160156f,   (float16_t)-1.05957031f,
    (float16_t)0.481201172f,   (float16_t)-0.562988281f, (float16_t)-0.702636719f,  (float16_t)0.856933594f,
    (float16_t)-0.105529785f,  (float16_t)0.619628906f,  (float16_t)-0.216186523f,  (float16_t)1.52050781f,
    (float16_t)-0.449462891f,  (float16_t)-0.716308594f, (float16_t)0.693359375f,   (float16_t)-0.861816406f,
    (float16_t)0.361328125f,   (float16_t)1.19921875f,   (float16_t)-0.233276367f,  (float16_t)1.31054688f,
    (float16_t)-0.433837891f,  (float16_t)-1.14746094f,  (float16_t)0.451171875f,   (float16_t)-0.78515625f,
    (float16_t)-0.497314453f,  (float16_t)-0.570800781f, (float16_t)0.572753906f,   (float16_t)0.368652344f,
    (float16_t)-0.0267333984f, (float16_t)0.525390625f,  (float16_t)-0.583007812f,  (float16_t)-0.738769531f,
    (float16_t)0.345214844f,   (float16_t)-0.9140625f,   (float16_t)-0.0933837891f, (float16_t)-0.565429688f,
    (float16_t)0.526367188f,   (float16_t)1.15722656f,   (float16_t)-0.0164794922f, (float16_t)0.652832031f,
    (float16_t)-0.331054688f,  (float16_t)0.528808594f,  (float16_t)-0.416503906f,  (float16_t)-0.0679931641f,
    (float16_t)-0.138061523f};
