// Generated by depthwise_conv_settings_flt.py using PyTorch version 2.10.0+cu128.
const float16_t depthwise_match_dilation_f16_weights_data[9] = {(float16_t)0.314697266f,
                                                                (float16_t)0.372558594f,
                                                                (float16_t)-0.673339844f,
                                                                (float16_t)-0.625f,
                                                                (float16_t)-0.161010742f,
                                                                (float16_t)0.205444336f,
                                                                (float16_t)0.138183594f,
                                                                (float16_t)0.418701172f,
                                                                (float16_t)-0.558105469f};
