// Generated by transpose_conv_settings_flt.py using PyTorch version 2.10.0+cu128.
const float32_t transpose_conv_basic_nhwc_f32_biases[6] =
    {-0.274051696f, 0.4390634f, -0.261632621f, 0.173772573f, 0.0213841889f, -0.331626803f};
