// Generated by transpose_conv_settings_flt.py using PyTorch version 2.10.0+cu128.
const float16_t transpose_conv_basic_f16_biases[6] = {(float16_t)0.0219116211f,
                                                      (float16_t)-0.37890625f,
                                                      (float16_t)-0.328857422f,
                                                      (float16_t)0.124145508f,
                                                      (float16_t)0.415771484f,
                                                      (float16_t)0.317871094f};
