// Generated by transpose_settings_flt.py using PyTorch version 2.10.0+cu128.
const float16_t transpose_matrix_small_f16_output_ref[8] = {(float16_t)-3.23046875f,
                                                            (float16_t)1.43164062f,
                                                            (float16_t)2.15039062f,
                                                            (float16_t)1.55761719f,
                                                            (float16_t)-0.00286102295f,
                                                            (float16_t)-3.94335938f,
                                                            (float16_t)3.29296875f,
                                                            (float16_t)2.74023438f};
