// Generated by lstm_settings_flt.py using PyTorch version 2.10.0+cu128.
const float16_t lstm_small_f16_cell_bias[8] = {(float16_t)-0.0487365723f,
                                               (float16_t)-0.0910644531f,
                                               (float16_t)-0.394775391f,
                                               (float16_t)-0.0764770508f,
                                               (float16_t)0.0546264648f,
                                               (float16_t)0.0361633301f,
                                               (float16_t)-0.0302124023f,
                                               (float16_t)0.228271484f};
