// Generated by lstm_settings_flt.py using PyTorch version 2.10.0+cu128.
const float16_t lstm_small_f16_cell_input_weights[64] = {
    (float16_t)0.216918945f,   (float16_t)-0.237548828f,  (float16_t)-0.158569336f,  (float16_t)-0.298828125f,
    (float16_t)-0.251708984f,  (float16_t)0.187866211f,   (float16_t)0.203735352f,   (float16_t)0.0927124023f,
    (float16_t)-0.0956420898f, (float16_t)-0.0697631836f, (float16_t)0.016784668f,   (float16_t)0.163208008f,
    (float16_t)-0.275878906f,  (float16_t)-0.24230957f,   (float16_t)0.217163086f,   (float16_t)0.104003906f,
    (float16_t)-0.279541016f,  (float16_t)-0.142822266f,  (float16_t)0.0341491699f,  (float16_t)0.172485352f,
    (float16_t)-0.0606689453f, (float16_t)-0.227416992f,  (float16_t)-0.0838012695f, (float16_t)-0.0322265625f,
    (float16_t)0.159912109f,   (float16_t)-0.114990234f,  (float16_t)0.145629883f,   (float16_t)0.29296875f,
    (float16_t)0.256835938f,   (float16_t)0.238647461f,   (float16_t)0.164428711f,   (float16_t)-0.1171875f,
    (float16_t)-0.270751953f,  (float16_t)-0.223510742f,  (float16_t)-0.247680664f,  (float16_t)0.0207519531f,
    (float16_t)-0.155395508f,  (float16_t)-0.0699462891f, (float16_t)-0.0986938477f, (float16_t)-0.0861816406f,
    (float16_t)0.217407227f,   (float16_t)-0.0349731445f, (float16_t)0.310302734f,   (float16_t)0.0221862793f,
    (float16_t)-0.251953125f,  (float16_t)0.341796875f,   (float16_t)0.051940918f,   (float16_t)0.198364258f,
    (float16_t)0.0863647461f,  (float16_t)0.323730469f,   (float16_t)-0.209106445f,  (float16_t)0.216186523f,
    (float16_t)-0.127319336f,  (float16_t)-0.288330078f,  (float16_t)0.297119141f,   (float16_t)0.249267578f,
    (float16_t)-0.136352539f,  (float16_t)0.198730469f,   (float16_t)-0.026260376f,  (float16_t)-0.246459961f,
    (float16_t)0.0504455566f,  (float16_t)-0.0513305664f, (float16_t)0.039276123f,   (float16_t)0.302734375f};
