// Generated by lstm_settings_flt.py using PyTorch version 2.10.0+cu128.
const float16_t lstm_small_f16_cell_hidden_weights[64] = {
    (float16_t)0.290527344f,   (float16_t)0.128417969f,    (float16_t)-0.0911865234f, (float16_t)-0.289550781f,
    (float16_t)-0.0681152344f, (float16_t)-0.00616455078f, (float16_t)0.12487793f,    (float16_t)-0.0201416016f,
    (float16_t)0.0878295898f,  (float16_t)0.194335938f,    (float16_t)-0.249023438f,  (float16_t)0.045715332f,
    (float16_t)0.0548400879f,  (float16_t)-0.177124023f,   (float16_t)0.329101562f,   (float16_t)-0.150024414f,
    (float16_t)-0.0914916992f, (float16_t)-0.296142578f,   (float16_t)0.0925292969f,  (float16_t)0.130615234f,
    (float16_t)0.142944336f,   (float16_t)-0.155639648f,   (float16_t)-0.0198822021f, (float16_t)0.0856933594f,
    (float16_t)-0.149414062f,  (float16_t)0.338623047f,    (float16_t)0.0554504395f,  (float16_t)-0.221313477f,
    (float16_t)0.0447998047f,  (float16_t)-0.157836914f,   (float16_t)-0.149047852f,  (float16_t)-0.215454102f,
    (float16_t)-0.332275391f,  (float16_t)0.333007812f,    (float16_t)0.061126709f,   (float16_t)0.275634766f,
    (float16_t)0.342529297f,   (float16_t)-0.198364258f,   (float16_t)0.226074219f,   (float16_t)-0.0545349121f,
    (float16_t)-0.204345703f,  (float16_t)-0.0500488281f,  (float16_t)-0.0438537598f, (float16_t)-0.209228516f,
    (float16_t)0.268554688f,   (float16_t)0.071472168f,    (float16_t)0.348876953f,   (float16_t)0.276611328f,
    (float16_t)0.312011719f,   (float16_t)0.269775391f,    (float16_t)0.302734375f,   (float16_t)-0.286865234f,
    (float16_t)0.338867188f,   (float16_t)0.106933594f,    (float16_t)-0.0841064453f, (float16_t)0.0244903564f,
    (float16_t)-0.194091797f,  (float16_t)0.305908203f,    (float16_t)0.0658569336f,  (float16_t)0.223022461f,
    (float16_t)-0.322265625f,  (float16_t)-0.0276184082f,  (float16_t)0.126464844f,   (float16_t)0.204711914f};
