// Generated by lstm_settings_flt.py using PyTorch version 2.10.0+cu128.
const float16_t lstm_small_f16_forget_bias[8] = {(float16_t)-0.0795288086f,
                                                 (float16_t)-0.0579833984f,
                                                 (float16_t)0.0495300293f,
                                                 (float16_t)-0.145263672f,
                                                 (float16_t)-0.272705078f,
                                                 (float16_t)0.341796875f,
                                                 (float16_t)0.218383789f,
                                                 (float16_t)-0.202026367f};
