// Generated by lstm_settings_flt.py using PyTorch version 2.10.0+cu128.
const float16_t lstm_small_f16_forget_input_weights[64] = {
    (float16_t)-0.0891723633f,  (float16_t)0.260742188f,   (float16_t)0.34765625f,    (float16_t)0.311523438f,
    (float16_t)0.138916016f,    (float16_t)0.17175293f,    (float16_t)0.225341797f,   (float16_t)-0.164672852f,
    (float16_t)0.314208984f,    (float16_t)-0.344238281f,  (float16_t)0.0911865234f,  (float16_t)0.330566406f,
    (float16_t)0.181030273f,    (float16_t)0.0856933594f,  (float16_t)-0.305419922f,  (float16_t)-0.267822266f,
    (float16_t)0.338867188f,    (float16_t)0.118530273f,   (float16_t)-0.261230469f,  (float16_t)0.110534668f,
    (float16_t)0.0765991211f,   (float16_t)-0.0986328125f, (float16_t)-0.159301758f,  (float16_t)0.176269531f,
    (float16_t)-0.132202148f,   (float16_t)-0.119812012f,  (float16_t)-0.251953125f,  (float16_t)-0.344726562f,
    (float16_t)-0.311523438f,   (float16_t)-0.113891602f,  (float16_t)-0.217529297f,  (float16_t)0.00786590576f,
    (float16_t)0.0458374023f,   (float16_t)0.257324219f,   (float16_t)-0.170654297f,  (float16_t)-0.0642089844f,
    (float16_t)-0.0733642578f,  (float16_t)0.0055770874f,  (float16_t)-0.315917969f,  (float16_t)-0.22277832f,
    (float16_t)-0.345214844f,   (float16_t)0.0532531738f,  (float16_t)-0.0172119141f, (float16_t)-0.134521484f,
    (float16_t)-0.174560547f,   (float16_t)0.333251953f,   (float16_t)0.106384277f,   (float16_t)-0.0262145996f,
    (float16_t)0.277099609f,    (float16_t)0.067565918f,   (float16_t)0.318847656f,   (float16_t)0.329101562f,
    (float16_t)-0.262695312f,   (float16_t)-0.159179688f,  (float16_t)-0.270263672f,  (float16_t)-0.325683594f,
    (float16_t)-0.157714844f,   (float16_t)-0.0145339966f, (float16_t)-0.24621582f,   (float16_t)-0.295410156f,
    (float16_t)-0.00290107727f, (float16_t)-0.222167969f,  (float16_t)0.00917053223f, (float16_t)0.0212249756f};
