// Generated by lstm_settings_flt.py using PyTorch version 2.10.0+cu128.
const float16_t lstm_small_f16_forget_hidden_weights[64] = {
    (float16_t)0.281738281f,   (float16_t)-0.318847656f,   (float16_t)-0.0020198822f, (float16_t)0.153320312f,
    (float16_t)0.102050781f,   (float16_t)-0.241943359f,   (float16_t)0.138305664f,   (float16_t)0.199829102f,
    (float16_t)-0.301757812f,  (float16_t)0.237060547f,    (float16_t)-0.0135574341f, (float16_t)0.201782227f,
    (float16_t)-0.0119552612f, (float16_t)0.218139648f,    (float16_t)-0.161132812f,  (float16_t)0.119018555f,
    (float16_t)0.203613281f,   (float16_t)0.0124511719f,   (float16_t)-0.228027344f,  (float16_t)-0.0715942383f,
    (float16_t)0.155029297f,   (float16_t)-0.00715637207f, (float16_t)0.293701172f,   (float16_t)0.037689209f,
    (float16_t)0.0335388184f,  (float16_t)-0.256103516f,   (float16_t)-0.128173828f,  (float16_t)-0.264892578f,
    (float16_t)0.0910644531f,  (float16_t)0.110046387f,    (float16_t)0.0904541016f,  (float16_t)0.0941772461f,
    (float16_t)0.133911133f,   (float16_t)0.0817871094f,   (float16_t)0.237304688f,   (float16_t)-0.217407227f,
    (float16_t)-0.319580078f,  (float16_t)0.0280914307f,   (float16_t)0.0767211914f,  (float16_t)-0.0779418945f,
    (float16_t)-0.239257812f,  (float16_t)-0.240234375f,   (float16_t)0.194702148f,   (float16_t)-0.0513916016f,
    (float16_t)-0.173217773f,  (float16_t)0.0122833252f,   (float16_t)0.0906982422f,  (float16_t)-0.0631713867f,
    (float16_t)-0.217163086f,  (float16_t)-0.0726318359f,  (float16_t)-0.0368041992f, (float16_t)-0.255615234f,
    (float16_t)0.343994141f,   (float16_t)-0.157104492f,   (float16_t)-0.170043945f,  (float16_t)-0.262451172f,
    (float16_t)0.331298828f,   (float16_t)0.337646484f,    (float16_t)-0.140991211f,  (float16_t)-0.0269927979f,
    (float16_t)0.319824219f,   (float16_t)-0.250976562f,   (float16_t)0.140136719f,   (float16_t)0.143188477f};
