// Generated by lstm_settings_flt.py using PyTorch version 2.10.0+cu128.
const float16_t lstm_small_f16_input_bias[8] = {(float16_t)0.0895385742f,
                                                (float16_t)0.083984375f,
                                                (float16_t)0.262939453f,
                                                (float16_t)0.177856445f,
                                                (float16_t)0.129150391f,
                                                (float16_t)0.154785156f,
                                                (float16_t)0.0285339355f,
                                                (float16_t)-0.0446472168f};
