// Generated by lstm_settings_flt.py using PyTorch version 2.10.0+cu128.
const float16_t lstm_small_f16_input_input_weights[64] = {
    (float16_t)-0.309326172f,  (float16_t)-0.199584961f,   (float16_t)-0.312988281f, (float16_t)0.255859375f,
    (float16_t)-0.0811157227f, (float16_t)0.272949219f,    (float16_t)0.0961303711f, (float16_t)0.172119141f,
    (float16_t)0.241333008f,   (float16_t)0.291259766f,    (float16_t)0.173583984f,  (float16_t)0.340087891f,
    (float16_t)0.1640625f,     (float16_t)0.274658203f,    (float16_t)0.346191406f,  (float16_t)0.177368164f,
    (float16_t)-0.141357422f,  (float16_t)0.296875f,       (float16_t)-0.122192383f, (float16_t)0.300292969f,
    (float16_t)0.222167969f,   (float16_t)-0.00863647461f, (float16_t)0.179931641f,  (float16_t)-0.332519531f,
    (float16_t)0.275878906f,   (float16_t)-0.184936523f,   (float16_t)-0.157836914f, (float16_t)-0.291748047f,
    (float16_t)-0.0627441406f, (float16_t)0.0651855469f,   (float16_t)0.16003418f,   (float16_t)-0.048034668f,
    (float16_t)-0.324951172f,  (float16_t)0.0400390625f,   (float16_t)-0.311035156f, (float16_t)0.181640625f,
    (float16_t)-0.340087891f,  (float16_t)0.0674438477f,   (float16_t)-0.137939453f, (float16_t)-0.231079102f,
    (float16_t)0.150878906f,   (float16_t)-0.0199127197f,  (float16_t)0.240478516f,  (float16_t)-0.278564453f,
    (float16_t)-0.141479492f,  (float16_t)0.309814453f,    (float16_t)0.220092773f,  (float16_t)0.183959961f,
    (float16_t)-0.260498047f,  (float16_t)0.0690917969f,   (float16_t)0.0403137207f, (float16_t)0.0170135498f,
    (float16_t)0.0406494141f,  (float16_t)-0.246704102f,   (float16_t)-0.107055664f, (float16_t)0.299804688f,
    (float16_t)-0.345458984f,  (float16_t)-0.26171875f,    (float16_t)0.174072266f,  (float16_t)0.241821289f,
    (float16_t)-0.174316406f,  (float16_t)-0.223754883f,   (float16_t)0.263183594f,  (float16_t)-0.0869140625f};
