// Generated by lstm_settings_flt.py using PyTorch version 2.10.0+cu128.
const float16_t lstm_small_f16_input_hidden_weights[64] = {
    (float16_t)-0.109313965f,   (float16_t)0.123352051f,   (float16_t)0.143188477f,   (float16_t)0.335449219f,
    (float16_t)-0.00802612305f, (float16_t)-0.340576172f,  (float16_t)0.13293457f,    (float16_t)0.0806884766f,
    (float16_t)-0.00448226929f, (float16_t)-0.24206543f,   (float16_t)0.222412109f,   (float16_t)0.0454406738f,
    (float16_t)-0.311035156f,   (float16_t)-0.348144531f,  (float16_t)-0.245727539f,  (float16_t)-0.30859375f,
    (float16_t)0.229858398f,    (float16_t)0.0765380859f,  (float16_t)-0.104064941f,  (float16_t)-0.168579102f,
    (float16_t)0.0257415771f,   (float16_t)0.22277832f,    (float16_t)0.105163574f,   (float16_t)0.278076172f,
    (float16_t)0.181152344f,    (float16_t)-0.30078125f,   (float16_t)0.232421875f,   (float16_t)0.0411682129f,
    (float16_t)0.249389648f,    (float16_t)-0.0360412598f, (float16_t)0.232543945f,   (float16_t)0.327392578f,
    (float16_t)0.078125f,       (float16_t)0.147094727f,   (float16_t)0.345214844f,   (float16_t)-0.274414062f,
    (float16_t)-0.0609741211f,  (float16_t)0.210327148f,   (float16_t)-0.0475158691f, (float16_t)-0.061706543f,
    (float16_t)0.247314453f,    (float16_t)0.141723633f,   (float16_t)0.249755859f,   (float16_t)0.134643555f,
    (float16_t)-0.153930664f,   (float16_t)-0.0790405273f, (float16_t)-0.230957031f,  (float16_t)0.181152344f,
    (float16_t)0.0996704102f,   (float16_t)-0.16809082f,   (float16_t)0.318359375f,   (float16_t)-0.245239258f,
    (float16_t)0.262939453f,    (float16_t)-0.260742188f,  (float16_t)-0.298583984f,  (float16_t)-0.347412109f,
    (float16_t)-0.251464844f,   (float16_t)-0.291748047f,  (float16_t)0.263183594f,   (float16_t)-0.0919189453f,
    (float16_t)0.251220703f,    (float16_t)0.269287109f,   (float16_t)0.273925781f,   (float16_t)0.346923828f};
