// Generated by lstm_settings_flt.py using PyTorch version 2.10.0+cu128.
const float16_t lstm_small_f16_output_bias[8] = {(float16_t)0.338867188f,
                                                 (float16_t)-0.389648438f,
                                                 (float16_t)0.177490234f,
                                                 (float16_t)0.0235900879f,
                                                 (float16_t)0.0848999023f,
                                                 (float16_t)0.0776367188f,
                                                 (float16_t)-0.0282440186f,
                                                 (float16_t)-0.255859375f};
