// Generated by lstm_settings_flt.py using PyTorch version 2.10.0+cu128.
const float16_t lstm_small_f16_output_hidden_weights[64] = {
    (float16_t)0.0729980469f, (float16_t)-0.0253448486f, (float16_t)-0.228515625f,   (float16_t)-0.0780639648f,
    (float16_t)0.284179688f,  (float16_t)-0.0880737305f, (float16_t)-0.264160156f,   (float16_t)0.10144043f,
    (float16_t)-0.343017578f, (float16_t)0.300537109f,   (float16_t)-0.14050293f,    (float16_t)-0.116577148f,
    (float16_t)-0.302001953f, (float16_t)-0.273193359f,  (float16_t)-0.348144531f,   (float16_t)0.316650391f,
    (float16_t)0.254150391f,  (float16_t)0.0787353516f,  (float16_t)0.0133056641f,   (float16_t)-0.0645751953f,
    (float16_t)-0.106811523f, (float16_t)-0.0645141602f, (float16_t)0.0206298828f,   (float16_t)0.165161133f,
    (float16_t)-0.304199219f, (float16_t)0.216674805f,   (float16_t)0.114868164f,    (float16_t)0.256347656f,
    (float16_t)-0.171630859f, (float16_t)-0.0432434082f, (float16_t)-0.329833984f,   (float16_t)-0.227416992f,
    (float16_t)-0.118530273f, (float16_t)0.301025391f,   (float16_t)0.0915527344f,   (float16_t)0.0113143921f,
    (float16_t)-0.101013184f, (float16_t)-0.0587768555f, (float16_t)-0.219848633f,   (float16_t)-0.152832031f,
    (float16_t)0.110656738f,  (float16_t)0.312744141f,   (float16_t)-0.326416016f,   (float16_t)-0.208984375f,
    (float16_t)0.274414062f,  (float16_t)0.12878418f,    (float16_t)-0.00820922852f, (float16_t)-0.262695312f,
    (float16_t)0.013458252f,  (float16_t)0.221313477f,   (float16_t)-0.0838623047f,  (float16_t)0.212890625f,
    (float16_t)0.0903930664f, (float16_t)0.0279693604f,  (float16_t)-0.284667969f,   (float16_t)0.161499023f,
    (float16_t)0.0635986328f, (float16_t)-0.341308594f,  (float16_t)0.282226562f,    (float16_t)0.234008789f,
    (float16_t)-0.242553711f, (float16_t)0.121276855f,   (float16_t)0.268554688f,    (float16_t)0.242431641f};
