// Generated by lstm_settings_flt.py using PyTorch version 2.10.0+cu128.
const float16_t lstm_small_f16_output_input_weights[64] = {
    (float16_t)-0.305175781f, (float16_t)0.145507812f,   (float16_t)0.318847656f,   (float16_t)0.0354614258f,
    (float16_t)0.240844727f,  (float16_t)-0.19519043f,   (float16_t)-0.172363281f,  (float16_t)-0.237548828f,
    (float16_t)0.247924805f,  (float16_t)-0.329833984f,  (float16_t)0.229003906f,   (float16_t)-0.237915039f,
    (float16_t)0.063293457f,  (float16_t)0.0273742676f,  (float16_t)0.144042969f,   (float16_t)0.325683594f,
    (float16_t)0.0483703613f, (float16_t)0.0289459229f,  (float16_t)0.203979492f,   (float16_t)-0.186767578f,
    (float16_t)-0.301757812f, (float16_t)-0.0739746094f, (float16_t)0.0226593018f,  (float16_t)0.0690917969f,
    (float16_t)-0.2578125f,   (float16_t)-0.281494141f,  (float16_t)0.306884766f,   (float16_t)-0.0936279297f,
    (float16_t)0.044921875f,  (float16_t)-0.294921875f,  (float16_t)0.120605469f,   (float16_t)-0.125366211f,
    (float16_t)0.334716797f,  (float16_t)0.0243835449f,  (float16_t)0.317382812f,   (float16_t)-0.326904297f,
    (float16_t)-0.316894531f, (float16_t)-0.230712891f,  (float16_t)0.0910644531f,  (float16_t)-0.322021484f,
    (float16_t)0.250732422f,  (float16_t)-0.104003906f,  (float16_t)-0.108337402f,  (float16_t)-0.0790405273f,
    (float16_t)0.266601562f,  (float16_t)-0.0975341797f, (float16_t)-0.0347595215f, (float16_t)0.14050293f,
    (float16_t)0.0905151367f, (float16_t)0.315917969f,   (float16_t)-0.151245117f,  (float16_t)-0.0626831055f,
    (float16_t)-0.226074219f, (float16_t)-0.229858398f,  (float16_t)0.0315551758f,  (float16_t)0.306152344f,
    (float16_t)0.151245117f,  (float16_t)-0.231323242f,  (float16_t)0.205688477f,   (float16_t)-0.219238281f,
    (float16_t)0.148681641f,  (float16_t)0.192138672f,   (float16_t)-0.179443359f,  (float16_t)0.0850219727f};
