// Generated by conv_settings_flt.py using PyTorch version 2.10.0+cu128.
const float16_t conv_match_conv_4_f16_biases_data[3] = {(float16_t)-0.434570312f,
                                                        (float16_t)0.0111694336f,
                                                        (float16_t)-0.11920166f};
