// Generated by conv_settings_flt.py using PyTorch version 2.10.0+cu128.
const float16_t conv_match_conv_4_f16_output_ref_data[36] = {
    (float16_t)-0.290283203f, (float16_t)1.1015625f,    (float16_t)0.364990234f,  (float16_t)-0.339599609f,
    (float16_t)-1.47949219f,  (float16_t)-1.50976562f,  (float16_t)-0.431152344f, (float16_t)-0.66796875f,
    (float16_t)-1.30371094f,  (float16_t)-1.48242188f,  (float16_t)0.296386719f,  (float16_t)0.631347656f,
    (float16_t)-0.246826172f, (float16_t)-0.556152344f, (float16_t)2.3046875f,    (float16_t)1.05761719f,
    (float16_t)-0.784667969f, (float16_t)-1.67285156f,  (float16_t)-0.295654297f, (float16_t)-0.373046875f,
    (float16_t)3.93554688f,   (float16_t)-1.40332031f,  (float16_t)0.6875f,       (float16_t)1.91113281f,
    (float16_t)-0.214477539f, (float16_t)0.4453125f,    (float16_t)-1.76953125f,  (float16_t)-1.20703125f,
    (float16_t)-0.503417969f, (float16_t)-0.240600586f, (float16_t)-0.494628906f, (float16_t)-0.15234375f,
    (float16_t)1.87890625f,   (float16_t)-2.48242188f,  (float16_t)-0.421386719f, (float16_t)-0.907226562f};
