// Generated by conv_settings_flt.py using PyTorch version 2.10.0+cu128.
const float16_t conv_match_conv_4_f16_weights_data[54] = {
    (float16_t)-0.187988281f,  (float16_t)-0.124023438f, (float16_t)0.274902344f,  (float16_t)0.238525391f,
    (float16_t)-0.637695312f,  (float16_t)0.547851562f,  (float16_t)-0.561035156f, (float16_t)-0.415039062f,
    (float16_t)-0.665527344f,  (float16_t)-0.665527344f, (float16_t)-0.41796875f,  (float16_t)-0.693847656f,
    (float16_t)0.629394531f,   (float16_t)-0.643554688f, (float16_t)-0.420898438f, (float16_t)-0.390136719f,
    (float16_t)0.108520508f,   (float16_t)0.612792969f,  (float16_t)0.477294922f,  (float16_t)-0.432128906f,
    (float16_t)-0.322998047f,  (float16_t)-0.697265625f, (float16_t)0.363769531f,  (float16_t)-0.0137863159f,
    (float16_t)-0.173461914f,  (float16_t)0.146972656f,  (float16_t)-0.158935547f, (float16_t)-0.384033203f,
    (float16_t)-0.0868530273f, (float16_t)-0.219116211f, (float16_t)-0.311035156f, (float16_t)0.556152344f,
    (float16_t)0.0446166992f,  (float16_t)-0.298828125f, (float16_t)0.642089844f,  (float16_t)-0.17175293f,
    (float16_t)0.670898438f,   (float16_t)-0.268066406f, (float16_t)0.713378906f,  (float16_t)0.53515625f,
    (float16_t)0.463867188f,   (float16_t)0.5f,          (float16_t)0.288574219f,  (float16_t)0.0639648438f,
    (float16_t)-0.196044922f,  (float16_t)0.158081055f,  (float16_t)-0.347900391f, (float16_t)-0.236206055f,
    (float16_t)0.0267333984f,  (float16_t)-0.682128906f, (float16_t)0.746582031f,  (float16_t)0.677734375f,
    (float16_t)0.236816406f,   (float16_t)-0.250976562f};
