// Generated by fully_connected_settings_flt.py using PyTorch version 2.10.0+cu128.
const float16_t fully_connected_2out_tail17_f16_biases_data[2] = {(float16_t)0.448730469f, (float16_t)-0.380859375f};
