// Generated by fully_connected_settings_flt.py using PyTorch version 2.10.0+cu128.
const float16_t fully_connected_2out_tail17_f16_output_ref_data[4] = {(float16_t)2.56835938f,
                                                                      (float16_t)-2.39648438f,
                                                                      (float16_t)-5.9375f,
                                                                      (float16_t)-0.566894531f};
