// Generated by fully_connected_settings_flt.py using PyTorch version 2.10.0+cu128.
const float16_t fully_connected_2out_tail17_f16_weights_data[34] = {
    (float16_t)0.743164062f,   (float16_t)-1.48046875f,  (float16_t)0.186157227f,  (float16_t)-1.24316406f,
    (float16_t)-0.0759277344f, (float16_t)-0.780273438f, (float16_t)-0.743164062f, (float16_t)0.313720703f,
    (float16_t)1.11230469f,    (float16_t)-0.459472656f, (float16_t)0.168823242f,  (float16_t)-0.207397461f,
    (float16_t)-1.44140625f,   (float16_t)-0.499267578f, (float16_t)0.12310791f,   (float16_t)-1.35449219f,
    (float16_t)-1.453125f,     (float16_t)1.109375f,     (float16_t)-1.0625f,      (float16_t)-1.39746094f,
    (float16_t)-0.143920898f,  (float16_t)0.272460938f,  (float16_t)-1.28027344f,  (float16_t)-0.879882812f,
    (float16_t)-1.39746094f,   (float16_t)0.883300781f,  (float16_t)0.037689209f,  (float16_t)0.157104492f,
    (float16_t)0.116333008f,   (float16_t)0.906738281f,  (float16_t)-0.777832031f, (float16_t)-1.00097656f,
    (float16_t)-0.651855469f,  (float16_t)-1.12304688f};
